import {describe,expect,it} from "vitest";
import {classifySpecificRole,interpretExperience,SPECIFIC_ROLE_TAXONOMY} from "./provider-normalization";
describe("provider-neutral normalization",()=>{
  it.each([["Data Analyst","data-analyst"],["BI Analyst","business-intelligence-analyst"],["Business Analyst","business-analyst"],["Financial Analyst","financial-analyst"],["Investment Analyst","investment-analyst"],["Consulting Analyst","consulting-analyst"],["Operations Analyst","operations-analyst"],["Data Scientist","data-scientist"],["Data Engineer","data-engineer"],["Analytics Engineer","analytics-engineer"],["Software Engineer","software-engineer"],["AI/ML Engineer","ai-ml-engineer"],["Project Coordinator","project-coordinator"],["Project Manager","project-manager"],["Program Analyst","program-analyst"],["Associate Data Engineer","data-engineer"]])("maps %s exactly",(title,id)=>{const result=classifySpecificRole(title);expect(result.specificRoleId).toBe(id);expect(result.roleFamilyId).toBe(SPECIFIC_ROLE_TAXONOMY[id as keyof typeof SPECIFIC_ROLE_TAXONOMY]);});
  it("never cross-classifies similar roles",()=>{expect(classifySpecificRole("Data Engineer").specificRoleId).not.toBe("data-analyst");expect(classifySpecificRole("Financial Analyst").specificRoleId).not.toBe("consulting-analyst");});
  it.each(["Database Analyst","Analyst","Data Engineering Consultant"])("fails closed for %s",(title)=>expect(classifySpecificRole(title).specificRoleId).toBeNull());
  it("keeps recipient leadership separate from the desired base role",()=>expect(classifySpecificRole("Director of Data Engineering")).toMatchObject({specificRoleId:"data-engineer",roleFamilyId:"data-analytics"}));
  it("uses the conservative lower bound",()=>{expect(interpretExperience([{kind:"range",minimum:5,maximum:8,sourceField:"range"}]).minimumSupportedYears).toBe(5);expect(interpretExperience([{kind:"range",minimum:0,maximum:10,sourceField:"range"}]).minimumSupportedYears).toBe(0);});
  it("preserves approximate uncertainty and conflicts",()=>{expect(interpretExperience([{kind:"approximate",years:6,sourceField:"total"}])).toMatchObject({minimumSupportedYears:5,maximumSupportedYears:7,kind:"inferred",reviewState:"review-required"});expect(interpretExperience([{kind:"exact",years:5,sourceField:"a"},{kind:"exact",years:8,sourceField:"b"}]).explanationCodes).toContain("experience-evidence-conflict");});
  it("merges overlapping employment periods without double counting",()=>{const result=interpretExperience([{kind:"employment-history",sourceField:"employment_history",referenceDate:"2026-01-01",periods:[{startDate:"2020-01-01",endDate:"2024-01-01"},{startDate:"2022-01-01",endDate:"2025-01-01"}]}]);expect(result.minimumSupportedYears).toBeGreaterThanOrEqual(4.99);expect(result.minimumSupportedYears).toBeLessThan(5.1);expect(result).toMatchObject({kind:"inferred",confidence:"medium",reviewState:"accepted"});});
  it("fails incomplete and contradictory employment evidence closed",()=>{expect(interpretExperience([{kind:"employment-history",sourceField:"history",referenceDate:"2026-01-01",periods:[{endDate:"2025-01-01"}]}]).explanationCodes).toContain("employment-history-incomplete");expect(interpretExperience([{kind:"employment-history",sourceField:"history",referenceDate:"2026-01-01",periods:[{startDate:"2020-01-01",endDate:"2025-01-01"}]},{kind:"exact",years:9,sourceField:"stated"}]).explanationCodes).toContain("experience-evidence-conflict");});
});
