import { describe, expect, it } from "vitest";
import { classifyRecipientFunction, mapFunctionTargetRoleAffinities, scoreRecipientRelevance } from "./recipient-function";

const corpus = [
  ["Senior Software Engineer","software-engineering"],["Staff Software Engineer","software-engineering"],["Principal Software Engineer","software-engineering"],["Engineering Manager","software-engineering"],["Director of Engineering","software-engineering"],
  ["Solutions Architect","technical-infrastructure"],["Cloud Solution Architect","technical-infrastructure"],["Senior Cloud Solution Architect, AI and Apps","technical-infrastructure"],["Infrastructure Engineer","technical-infrastructure"],["Network Engineer","technical-infrastructure"],
  ["Machine Learning Engineer","ai-ml"],["Applied Scientist","ai-ml"],["AI Engineer","ai-ml"],["Director of AI","ai-ml"],["Artificial Intelligence Lead","ai-ml"],
  ["Data Engineer","data-analytics"],["Senior Data Engineer","data-analytics"],["Analytics Engineer","data-analytics"],["Data Analyst","data-analytics"],["Senior Data Analyst","data-analytics"],["Business Intelligence Analyst","data-analytics"],["Analytics Manager","data-analytics"],["Director of Data","data-analytics"],["Director of Analytics","data-analytics"],["Data Scientist","data-analytics"],
  ["Analytics Program Manager","project-program"],["Technical Program Manager","project-program"],["Senior Program Manager","project-program"],["Program Director","project-program"],["Director of Program Management","project-program"],["Project Manager","project-program"],["Project Coordinator","project-program"],["Program Analyst","project-program"],
  ["Operations Manager","operations"],["Business Operations Manager","operations"],["Operations Analyst","operations"],["Strategy Manager","business-strategy"],["Corporate Strategy Manager","business-strategy"],
  ["Management Consultant","consulting"],["Senior Consultant","consulting"],["Engagement Manager","consulting"],
  ["Financial Analyst","finance"],["Senior Financial Analyst","finance"],["Director of Finance","finance"],["Finance Manager","finance"],
  ["Investment Analyst","investing"],["Investment Associate","investing"],["Portfolio Manager","investing"],["Quantitative Analyst","investing"],
  ["Commodities Analyst","commodities-energy"],["Energy Trader","commodities-energy"],["Power Markets Analyst","commodities-energy"],["Commodity Trader","commodities-energy"],["Aerospace Engineer","defense-aerospace"],["Defense Analyst","defense-aerospace"],
  ["Product Manager","product"],["Director of Product Management","product"],
  ["Talent Acquisition Director","unrelated"],["Senior Executive Recruiter","unrelated"],["Senior Technical Recruiter","unrelated"],["Senior Brand & Social Strategy Lead","unrelated"],
  ["Marketing Analytics & Data Manager","data-analytics"],["Security Analyst II","technical-infrastructure"],["Security Engineer","technical-infrastructure"],["Cloud Security Architect","technical-infrastructure"],["Corporate Security Manager","unrelated"],
  ["Director Digital & App Innovation","product"],["Digital Product Manager","product"],["Product Innovation Director","product"],["Director Digital Transformation","unknown"],["Director Digital Transformation, Data & Analytics","data-analytics"],["Director Digital Transformation, Supply Chain","unknown"],["SSE","unknown"],
  ["Global Digital & AI Transformation Lead","ai-ml"],["Lead Product Manager, AI Platforms & Infrastructure","product"],
  ["Account Executive","unrelated"],["Sales Development Representative","unrelated"],["Recruiter","unrelated"],["Human Resources Manager","unrelated"],["Marketing Manager","unrelated"],["Attorney","unrelated"],["Nurse","unrelated"],["Executive Assistant","unrelated"],["Student","unrelated"],["Intern","unrelated"],["Chief Executive Officer","unrelated"],
] as const;

describe("recipient-function-v2",()=>{
  it("classifies a materially varied sanitized corpus deterministically",()=>{expect(corpus.length).toBeGreaterThanOrEqual(50);for(const [title,primary] of corpus){const first=classifyRecipientFunction(title),second=classifyRecipientFunction(title);expect(first,title).toEqual(second);expect(first.primaryFunction,title).toBe(primary);}});
  it("preserves analytics plus project/program while making the role-bearing phrase primary",()=>{const result=classifyRecipientFunction("Analytics Program Manager");expect(result).toMatchObject({primaryFunction:"project-program",secondaryFunctions:expect.arrayContaining(["data-analytics"]),reviewState:"accepted",classifierVersion:"recipient-function-v2"});expect(result.evidence.map((item)=>item.phrase)).toEqual(expect.arrayContaining(["program manager","analytics"]));});
  it("anchors affinities to infrastructure even when AI is secondary",()=>{const result=classifyRecipientFunction("Senior Cloud Solution Architect, AI and Apps"),affinities=mapFunctionTargetRoleAffinities(result);expect(result).toMatchObject({primaryFunction:"technical-infrastructure",secondaryFunctions:expect.arrayContaining(["ai-ml"])});expect(affinities[0]).toMatchObject({sourceFunction:"technical-infrastructure",sourcePriority:"primary",relevance:"moderate"});expect(affinities.find((item)=>item.sourceFunction==="ai-ml")).toMatchObject({sourcePriority:"secondary",score:expect.any(Number)});});
  it("keeps director seniority out of the AI function",()=>expect(classifyRecipientFunction("Director of AI")).toMatchObject({primaryFunction:"ai-ml",secondaryFunctions:[]}));
  it("uses token boundaries and leaves unsupported titles unknown",()=>{expect(classifyRecipientFunction("Database Administrator").primaryFunction).toBe("unknown");expect(classifyRecipientFunction("General Manager").reviewState).toBe("review-required");});
  it("handles recruiting, brand, security, innovation, and ambiguous transformation conservatively",()=>{expect(classifyRecipientFunction("Talent Acquisition Director")).toMatchObject({primaryFunction:"unrelated",reviewState:"review-required"});expect(classifyRecipientFunction("Senior Brand & Social Strategy Lead").primaryFunction).toBe("unrelated");expect(classifyRecipientFunction("Security Analyst II")).toMatchObject({primaryFunction:"technical-infrastructure",reviewState:"accepted"});expect(classifyRecipientFunction("Corporate Security Manager").primaryFunction).toBe("unrelated");expect(classifyRecipientFunction("Director Digital & App Innovation").primaryFunction).toBe("product");expect(classifyRecipientFunction("Director Digital Transformation").primaryFunction).toBe("unknown");expect(classifyRecipientFunction("Director Digital Transformation, Data & Analytics").primaryFunction).toBe("data-analytics");expect(classifyRecipientFunction("Director Digital Transformation, Supply Chain").primaryFunction).toBe("unknown");expect(classifyRecipientFunction("SSE").primaryFunction).toBe("unknown");});
  it("preserves marketing context while avoiding unsupported analytics-engineering affinity",()=>{const classification=classifyRecipientFunction("Marketing Analytics & Data Manager"),affinities=mapFunctionTargetRoleAffinities(classification);expect(classification).toMatchObject({primaryFunction:"data-analytics",explanationCodes:expect.arrayContaining(["marketing-context-preserved"])});expect(affinities[0]).toMatchObject({targetRoleId:"data-analyst",relevance:"strong"});expect(affinities.find((item)=>item.targetRoleId==="analytics-engineer")).toMatchObject({relevance:"moderate"});});
  it("keeps product primary and gives secondary AI only bounded influence",()=>{const classification=classifyRecipientFunction("Lead Product Manager, AI Platforms & Infrastructure"),affinities=mapFunctionTargetRoleAffinities(classification),score=scoreRecipientRelevance(classification,null);expect(classification).toMatchObject({primaryFunction:"product",secondaryFunctions:expect.arrayContaining(["ai-ml"])});expect(affinities[0]).toMatchObject({sourceFunction:"product",sourcePriority:"primary"});expect(score.explanationCodes).toContain("secondary-function-bonus:3");});
  it("treats generic AI leadership as career-path relevance rather than occupational engineering evidence",()=>{const classification=classifyRecipientFunction("Director of AI"),affinity=mapFunctionTargetRoleAffinities(classification)[0];expect(affinity).toMatchObject({targetRoleId:"ai-ml-engineer",relevance:"moderate",score:75,evidence:expect.arrayContaining(["recipient-function:ai-ml:primary:career-path"])});});
  it("maps functions to explainable target-role affinities and adds a precise-role bonus",()=>{const classification=classifyRecipientFunction("Senior Software Engineer"),affinities=mapFunctionTargetRoleAffinities(classification);expect(affinities[0]).toMatchObject({targetRoleId:"software-engineer",relevance:"strong",mappingVersion:"function-role-relevance-v2"});expect(scoreRecipientRelevance(classification,"software-engineer")).toMatchObject({score:100,version:"recipient-relevance-v2",explanationCodes:expect.arrayContaining(["precise-target-role-bonus"])});});
  it("uses phrase boundaries for security and innovation evidence",()=>{expect(classifyRecipientFunction("Security Deposit Analyst").primaryFunction).toBe("unknown");expect(classifyRecipientFunction("Digitally Innovative Director").primaryFunction).toBe("unknown");expect(classifyRecipientFunction("Recruiterly Engineer").primaryFunction).toBe("unknown");});
});
