import type { SpecificRoleId } from "./provider-normalization";

export const RECIPIENT_FUNCTION_VERSION = "recipient-function-v2" as const;
export type RecipientFunctionVersion="recipient-function-v1"|typeof RECIPIENT_FUNCTION_VERSION;
export const FUNCTION_RELEVANCE_VERSION = "function-role-relevance-v2" as const;
export type FunctionRelevanceVersion="function-role-relevance-v1"|typeof FUNCTION_RELEVANCE_VERSION;
export const RECIPIENT_FUNCTIONS = ["data-analytics","software-engineering","ai-ml","technical-infrastructure","product","project-program","operations","consulting","finance","investing","commodities-energy","defense-aerospace","business-strategy","other-approved-relevant-function","unrelated","unknown"] as const;
export type RecipientFunctionId = typeof RECIPIENT_FUNCTIONS[number];
export interface FunctionEvidence { functionId:RecipientFunctionId; phrase:string; source:"normalized-title"|"industry-corroboration"; strength:"strong"|"supporting"; }
export interface RecipientFunctionClassification { primaryFunction:RecipientFunctionId; secondaryFunctions:RecipientFunctionId[]; evidence:FunctionEvidence[]; confidence:"high"|"medium"|"low"; reviewState:"accepted"|"review-required"; explanationCodes:string[]; classifierVersion:RecipientFunctionVersion; }
export interface TargetRoleAffinity { targetRoleId:SpecificRoleId; relevance:"strong"|"moderate"; score:number; evidence:string[]; mappingVersion:FunctionRelevanceVersion; sourceFunction?:RecipientFunctionId; sourcePriority?:"primary"|"secondary"; }

type Rule={phrase:string;functionId:RecipientFunctionId;rank:number;strength:"strong"|"supporting"};
const rules:Rule[]=[
  ["cloud solution architect","technical-infrastructure",100,"strong"],["solutions architect","technical-infrastructure",100,"strong"],["solution architect","technical-infrastructure",100,"strong"],["cloud architect","technical-infrastructure",100,"strong"],["infrastructure engineer","technical-infrastructure",100,"strong"],["systems engineer","technical-infrastructure",95,"strong"],["network engineer","technical-infrastructure",95,"strong"],
  ["machine learning engineer","ai-ml",110,"strong"],["applied scientist","ai-ml",105,"strong"],["ai engineer","ai-ml",105,"strong"],["artificial intelligence","ai-ml",100,"strong"],["machine learning","ai-ml",100,"strong"],["ai","ai-ml",80,"supporting"],["data scientist","data-analytics",105,"strong"],["business intelligence","data-analytics",105,"strong"],["analytics engineer","data-analytics",105,"strong"],["data engineer","data-analytics",100,"strong"],["data analyst","data-analytics",100,"strong"],["analytics","data-analytics",80,"supporting"],["data","data-analytics",70,"supporting"],
  ["software engineer","software-engineering",105,"strong"],["engineering manager","software-engineering",100,"strong"],["director of engineering","software-engineering",100,"strong"],["software development","software-engineering",95,"strong"],
  ["technical program manager","project-program",110,"strong"],["program manager","project-program",105,"strong"],["program director","project-program",105,"strong"],["program leader","project-program",105,"strong"],["program management","project-program",100,"strong"],["project manager","project-program",105,"strong"],["project coordinator","project-program",95,"strong"],["program analyst","project-program",95,"strong"],
  ["security analyst","technical-infrastructure",105,"strong"],["cybersecurity analyst","technical-infrastructure",110,"strong"],["security engineer","technical-infrastructure",110,"strong"],["cloud security","technical-infrastructure",110,"strong"],["information security","technical-infrastructure",105,"strong"],["application security","technical-infrastructure",110,"strong"],["security architect","technical-infrastructure",110,"strong"],
  ["business operations","operations",105,"strong"],["operations manager","operations",100,"strong"],["operations analyst","operations",100,"strong"],["product manager","product",100,"strong"],["product management","product",95,"strong"],
  ["app innovation","product",105,"strong"],["application innovation","product",105,"strong"],["digital product","product",105,"strong"],["digital products","product",105,"strong"],["product innovation","product",105,"strong"],
  ["management consultant","consulting",105,"strong"],["senior consultant","consulting",100,"strong"],["engagement manager","consulting",100,"strong"],["consultant","consulting",85,"supporting"],
  ["financial analyst","finance",105,"strong"],["director of finance","finance",105,"strong"],["finance manager","finance",100,"strong"],["corporate finance","finance",100,"strong"],["investment analyst","investing",105,"strong"],["investment associate","investing",105,"strong"],["portfolio manager","investing",100,"strong"],["quantitative analyst","investing",100,"strong"],
  ["commodities analyst","commodities-energy",105,"strong"],["energy trader","commodities-energy",105,"strong"],["power markets","commodities-energy",100,"strong"],["commodity trader","commodities-energy",100,"strong"],["aerospace engineer","defense-aerospace",105,"strong"],["defense analyst","defense-aerospace",100,"strong"],
  ["strategy manager","business-strategy",105,"strong"],["business strategy","business-strategy",100,"strong"],["corporate strategy","business-strategy",100,"strong"],
  ["account executive","unrelated",110,"strong"],["sales development representative","unrelated",110,"strong"],["talent acquisition","unrelated",115,"strong"],["executive recruiting","unrelated",115,"strong"],["technical recruiting","unrelated",115,"strong"],["recruiting","unrelated",110,"strong"],["recruiter","unrelated",110,"strong"],["brand and social","unrelated",115,"strong"],["brand strategy","unrelated",110,"strong"],["social strategy","unrelated",110,"strong"],["corporate security","unrelated",115,"strong"],["physical security","unrelated",115,"strong"],["human resources","unrelated",105,"strong"],["marketing manager","unrelated",105,"strong"],["attorney","unrelated",105,"strong"],["nurse","unrelated",105,"strong"],["executive assistant","unrelated",105,"strong"],["student","unrelated",105,"strong"],["intern","unrelated",120,"strong"],["chief executive officer","unrelated",120,"strong"],
].map(([phrase,functionId,rank,strength])=>({phrase:phrase as string,functionId:functionId as RecipientFunctionId,rank:rank as number,strength:strength as "strong"|"supporting"}));
const precedence:RecipientFunctionId[]=["project-program","technical-infrastructure","software-engineering","ai-ml","data-analytics","product","operations","consulting","finance","investing","commodities-energy","defense-aerospace","business-strategy","other-approved-relevant-function","unrelated","unknown"];
const normalized=(title:string)=>title.toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ");
const phraseMatch=(title:string,phrase:string)=>` ${title} `.includes(` ${phrase} `);

export function classifyRecipientFunction(title:string,industry?:string):RecipientFunctionClassification{
  const value=normalized(title),matches=rules.filter((rule)=>phraseMatch(value,rule.phrase));
  const strongest=new Map<RecipientFunctionId,Rule>();for(const match of matches){const prior=strongest.get(match.functionId);if(!prior||match.rank>prior.rank||match.rank===prior.rank&&match.phrase.length>prior.phrase.length)strongest.set(match.functionId,match);}
  if(!strongest.size)return{primaryFunction:"unknown",secondaryFunctions:[],evidence:[],confidence:"low",reviewState:"review-required",explanationCodes:["recipient-function-unknown"],classifierVersion:RECIPIENT_FUNCTION_VERSION};
  const approved=[...strongest.values()].filter((item)=>item.functionId!=="unrelated"),unrelated=strongest.has("unrelated");
  if(!approved.length)return{primaryFunction:"unrelated",secondaryFunctions:[],evidence:[...strongest.values()].map((item)=>({functionId:item.functionId,phrase:item.phrase,source:"normalized-title",strength:item.strength})),confidence:"high",reviewState:"review-required",explanationCodes:["recipient-function-unrelated"],classifierVersion:RECIPIENT_FUNCTION_VERSION};
  approved.sort((a,b)=>b.rank-a.rank||precedence.indexOf(a.functionId)-precedence.indexOf(b.functionId)||a.phrase.localeCompare(b.phrase));const primary=approved[0].functionId,secondary=[...new Set(approved.slice(1).map((item)=>item.functionId))];
  const evidence:FunctionEvidence[]=[...strongest.values()].map((item)=>({functionId:item.functionId,phrase:item.phrase,source:"normalized-title",strength:item.strength}));if(industry&&industry!=="unknown")evidence.push({functionId:primary,phrase:normalized(industry),source:"industry-corroboration",strength:"supporting"});
  const contextCodes=value.includes("marketing")&&primary==="data-analytics"?["marketing-context-preserved"]:[];
  return{primaryFunction:primary,secondaryFunctions:secondary,evidence,confidence:approved[0].strength==="strong"?"high":"medium",reviewState:unrelated?"review-required":"accepted",explanationCodes:[`recipient-function-primary:${primary}`,...secondary.map((item)=>`recipient-function-secondary:${item}`),...contextCodes,...(unrelated?["recipient-function-contradictory"]:[])],classifierVersion:RECIPIENT_FUNCTION_VERSION};
}

const affinities:Partial<Record<RecipientFunctionId,Array<[SpecificRoleId,"strong"|"moderate",number]>>>={
  "data-analytics":[["data-analyst","strong",95],["business-intelligence-analyst","strong",90],["data-engineer","moderate",75],["data-scientist","moderate",75],["analytics-engineer","moderate",70]],
  "software-engineering":[["software-engineer","strong",100],["ai-ml-engineer","moderate",70]],"ai-ml":[["ai-ml-engineer","moderate",75],["data-scientist","moderate",70],["software-engineer","moderate",65]],
  "technical-infrastructure":[["software-engineer","moderate",75],["data-engineer","moderate",70],["ai-ml-engineer","moderate",65]],"project-program":[["project-manager","strong",100],["program-analyst","strong",90],["operations-analyst","moderate",70],["data-analyst","moderate",60]],
  operations:[["operations-analyst","strong",100],["business-analyst","moderate",80],["project-manager","moderate",70]],consulting:[["consulting-analyst","strong",100],["business-analyst","moderate",80]],finance:[["financial-analyst","strong",100],["investment-analyst","moderate",75]],investing:[["investment-analyst","strong",100],["financial-analyst","moderate",80]],"commodities-energy":[["commodities-analyst","strong",100],["financial-analyst","moderate",65]],"business-strategy":[["business-analyst","strong",90],["consulting-analyst","moderate",80]],product:[["software-engineer","moderate",65],["project-manager","moderate",65]],"defense-aerospace":[["software-engineer","moderate",65],["operations-analyst","moderate",60]],
};
const evidencePromotions:Partial<Record<string,SpecificRoleId>>={"analytics engineer":"analytics-engineer","data engineer":"data-engineer","data scientist":"data-scientist","business intelligence":"business-intelligence-analyst","machine learning engineer":"ai-ml-engineer","ai engineer":"ai-ml-engineer"};
export function mapFunctionTargetRoleAffinities(classification:RecipientFunctionClassification):TargetRoleAffinity[]{
  const merged=new Map<SpecificRoleId,TargetRoleAffinity>();
  for(const [index,functionId] of [classification.primaryFunction,...classification.secondaryFunctions].entries())for(const [targetRoleId,baseRelevance,baseScore] of affinities[functionId]??[]){
    const priority=index===0?"primary":"secondary" as const,promotion=classification.evidence.some((item)=>item.functionId===functionId&&item.strength==="strong"&&evidencePromotions[item.phrase]===targetRoleId),relevance=promotion?"strong":baseRelevance,unbounded=promotion?100:baseScore,score=priority==="primary"?unbounded:Math.min(unbounded,65),evidence=`recipient-function:${functionId}:${priority}${promotion?":occupational-phrase":":career-path"}`,prior=merged.get(targetRoleId);
    if(!prior||prior.sourcePriority==="secondary"&&priority==="primary"||prior.sourcePriority===priority&&score>prior.score)merged.set(targetRoleId,{targetRoleId,relevance,score,evidence:[evidence],mappingVersion:FUNCTION_RELEVANCE_VERSION,sourceFunction:functionId,sourcePriority:priority});else if(!prior.evidence.includes(evidence))prior.evidence.push(evidence);
  }
  return[...merged.values()].sort((a,b)=>(a.sourcePriority==="primary"?0:1)-(b.sourcePriority==="primary"?0:1)||b.score-a.score||a.targetRoleId.localeCompare(b.targetRoleId));
}

export const RECIPIENT_RELEVANCE_SCORE_VERSION="recipient-relevance-v2" as const;
export type RecipientRelevanceVersion="recipient-relevance-v1"|typeof RECIPIENT_RELEVANCE_SCORE_VERSION;
export function scoreRecipientRelevance(classification:RecipientFunctionClassification,roleId:string|null):{score:number;version:typeof RECIPIENT_RELEVANCE_SCORE_VERSION;explanationCodes:string[]}{const mapped=mapFunctionTargetRoleAffinities(classification),primary=mapped.find((item)=>item.sourcePriority!=="secondary"),secondary=mapped.find((item)=>item.sourcePriority==="secondary"),base=primary?.score??0,secondaryBonus=secondary?Math.min(5,Math.round(secondary.score*.05)):0,exact=roleId&&mapped.some((item)=>item.targetRoleId===roleId)?10:0;return{score:Math.min(100,base+secondaryBonus+exact),version:RECIPIENT_RELEVANCE_SCORE_VERSION,explanationCodes:[...classification.explanationCodes,`primary-function-relevance:${base}`,...secondaryBonus?[`secondary-function-bonus:${secondaryBonus}`]:[],...exact?["precise-target-role-bonus"]:[]]};}
