import {createHash} from "node:crypto";
import type {ApprovedEmailDraftSnapshot,GmailDraftOperation} from "@/application/email-drafts";
import type {ImportedCandidateSnapshot} from "@/application/ingestion";

export interface CommandCenterDraftReview {
  candidateId:string;recipient:string;recipientEmail:string;company:string;title:string;primaryFunction:string;secondaryFunctions:ImportedCandidateSnapshot["recipientFunction"]["secondaryFunctions"];persona:string;experience:number;industry:string;location:string;score:number;lane:string;templateVariant:string;qualification:"qualified";whySelected:string;subject:string;body:string;wordCount:number;factIds:string[];catalogVersion:string;snapshotId:string;operation:GmailDraftOperation|null;blockedReason:string|null;
}
export interface GmailDraftReadinessInput {featureEnabled:boolean;connected:boolean;scopeValid:boolean;providerConfigured:boolean;credentialAvailable:boolean;credentialScopeValid:boolean;accountPinned:boolean;}
export interface GmailDraftReadiness {available:boolean;reason:string|null;}
export const commandCenterSnapshotId=(input:{candidateId:string;subject:string;body:string;catalogVersion:string})=>`command-center:${createHash("sha256").update(JSON.stringify(input)).digest("hex")}`;
export const selectReviewableDrafts=(items:readonly CommandCenterDraftReview[],maximum=5)=>items.filter((item)=>item.blockedReason===null).slice(0,maximum);
export function approvedSnapshot(review:CommandCenterDraftReview,now:Date):ApprovedEmailDraftSnapshot{return{snapshotId:review.snapshotId,recipientProfessionalEmail:review.recipientEmail,recipientDisplayName:review.recipient,subject:review.subject,body:review.body,planningSnapshotId:`daily-command-center:${review.candidateId}`,templateCatalogVersion:review.catalogVersion,evidenceIds:review.factIds,approvedAt:now.toISOString()};}
export function gmailDraftReadiness(input:GmailDraftReadinessInput):GmailDraftReadiness{
  const reason=!input.featureEnabled?"gmail-feature-disabled":!input.connected?"gmail-connection-invalid":!input.scopeValid?"gmail-scope-invalid":!input.providerConfigured?"gmail-oauth-configuration-missing":!input.credentialAvailable?"gmail-credential-unavailable":!input.credentialScopeValid?"gmail-credential-scope-invalid":!input.accountPinned?"gmail-account-unpinned":null;
  return{available:reason===null,reason};
}
export const humanDraftError=(code:string):string=>({"suppressed":"This contact is suppressed and cannot be contacted.","opted-out":"This contact opted out and cannot be contacted.","previous-contact":"This person was already contacted.","company-cooldown":"Someone at this company was contacted recently.","gmail-feature-disabled":"Gmail draft creation is unavailable because the local Gmail draft feature is disabled.","gmail-connection-invalid":"Gmail draft creation is unavailable because Gmail is not connected.","gmail-scope-invalid":"Gmail draft creation is unavailable because the saved connection does not have only the required compose scope.","gmail-oauth-configuration-missing":"Gmail draft creation is unavailable because the local OAuth configuration is incomplete.","gmail-credential-unavailable":"Gmail draft creation is unavailable because its Keychain credential could not be loaded.","gmail-credential-scope-invalid":"Gmail draft creation is unavailable because the Keychain credential does not have only the required compose scope.","gmail-account-unpinned":"Gmail draft creation is unavailable because the approved Gmail account is not pinned consistently.","draft-not-approved":"Approve this exact draft before creating it in Gmail."}[code]??"This action could not be completed safely.");
