import {createHash} from "node:crypto";
import {assertFiveBucketEnabled,fiveBucketEnabled,verifiedBucketEvidence} from "@/domain/recipient-buckets";
import type {ApprovedEmailDraftSnapshot,GmailDraftOperation} from "@/application/email-drafts";
import type {ImportedCandidateSnapshot} from "@/application/ingestion";
import {assertDylanVoice} from "@/domain/drafting/voice";
import {hasResumeAttachmentClaim,type ResumeAttachmentSnapshot} from "@/application/resumes";

export interface CommandCenterDraftReview {
  recipientBucket?:import("@/domain/recipient-buckets").RecipientBucketClassification|null;
  classificationChange?:{previous:import("@/domain/recipient-buckets").RecipientBucketClassification|null;current:import("@/domain/recipient-buckets").RecipientBucketClassification;decisionRequired:true};
  bucketLabel?:string;bucketReviewState?:string;bucketReviewReason?:string|null;bucketEvidenceReferences?:string[];bucketClassifierVersion?:string|null;
  resumeSelection?:{resumeId:string|null;decisionRequired:boolean;source:"configured-default"|"explicit"|"none"|"unavailable"};
  outreachIntent?:import("@/domain/drafting/outreach-intent").IntentSelection;
  outreachTrack:"professional"|"recruiter";candidateId:string;recipient:string;recipientEmail:string;company:string;companyId:string;title:string;primaryFunction:string;secondaryFunctions:ImportedCandidateSnapshot["recipientFunction"]["secondaryFunctions"];persona:string;experience:number;industry:string;location:string;score:number;lane:string;templateVariant:string;qualification:"qualified";whySelected:string;subject:string;body:string;wordCount:number;factIds:string[];catalogVersion:string;snapshotId:string;operation:GmailDraftOperation|null;blockedReason:string|null;recruiterType?:string;recruitingDomain?:string;technicalRecruiting?:boolean;earlyCareerRecruiting?:boolean;
}
export interface GmailDraftReadinessInput {featureEnabled:boolean;connected:boolean;scopeValid:boolean;providerConfigured:boolean;credentialAvailable:boolean;credentialScopeValid:boolean;accountPinned:boolean;}
export interface GmailDraftReadiness {available:boolean;reason:string|null;}
export const commandCenterSnapshotId=(input:{candidateId:string;subject:string;body:string;catalogVersion:string})=>`command-center:${createHash("sha256").update(JSON.stringify(input)).digest("hex")}`;
export function prepareEditedDraft(review:CommandCenterDraftReview,input:{subject:string;body:string}):CommandCenterDraftReview{
  const subject=input.subject.trim(),body=input.body.trim();
  assertDylanVoice(subject,body,{semanticAsks:Boolean(review.recipientBucket)});
  return{...review,subject,body,wordCount:body.split(/\s+/).length,snapshotId:commandCenterSnapshotId({candidateId:review.candidateId,subject,body,catalogVersion:review.catalogVersion}),operation:null};
}
export const selectReviewableDrafts=(items:readonly CommandCenterDraftReview[],maximum=5)=>items.filter((item)=>item.blockedReason===null).slice(0,maximum);
export function approvedSnapshot(review:CommandCenterDraftReview,now:Date,resumeAttachment?:ResumeAttachmentSnapshot,resumeDecision?:string):ApprovedEmailDraftSnapshot{
  if(review.classificationChange?.decisionRequired)throw new Error("bucket-correction-copy-review-required");
  if(fiveBucketEnabled()&&review.resumeSelection&&review.outreachTrack==="recruiter"&&!resumeAttachment&&resumeDecision!=="continue-without-attachment")throw new Error("recruiter-resume-decision-required");
  if(review.recipientBucket){
    assertFiveBucketEnabled();
    if(review.recipientBucket.reviewState!=="accepted"||!review.recipientBucket.bucket)throw new Error("recipient-bucket-review-required");
    if(review.blockedReason)throw new Error(review.blockedReason);
    if(review.outreachTrack==="recruiter"&&!resumeAttachment&&resumeDecision!=="continue-without-attachment")throw new Error("recruiter-resume-decision-required");
    if(!resumeAttachment&&hasResumeAttachmentClaim(review.body))throw new Error("resume-copy-mismatch");
    if(/\[[^\]]+\]/.test(review.subject+"\n"+review.body))throw new Error("draft-placeholder-unresolved");
    if(/current student|I(?:\'m| am) a student|found you on LinkedIn|previously (?:a |worked as a )?product manager/i.test(review.body))throw new Error("draft-unsupported-claim");
    if(!/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(review.recipientEmail))throw new Error("draft-recipient-invalid");
    if(/your role leading /i.test(review.body)&&!verifiedBucketEvidence(review.recipientBucket.evidence,"functional-leadership")&&!verifiedBucketEvidence(review.recipientBucket.evidence,"division-leadership"))throw new Error("draft-unsupported-leadership-claim");
    assertDylanVoice(review.subject,review.body,{semanticAsks:true});
  }
  const bucketCatalog=review.recipientBucket?`${review.catalogVersion}|bucket:${JSON.stringify(review.recipientBucket)}`:review.catalogVersion;
  const snapshotId=resumeAttachment?commandCenterSnapshotId({candidateId:review.candidateId,subject:review.subject,body:review.body,catalogVersion:`${bucketCatalog}|resume:${resumeAttachment.resumeId}:${resumeAttachment.sha256}:${resumeAttachment.filename}`}):review.recipientBucket?commandCenterSnapshotId({candidateId:review.candidateId,subject:review.subject,body:review.body,catalogVersion:bucketCatalog}):review.snapshotId;return{...review.recipientBucket?{recipientBucket:structuredClone(review.recipientBucket)}:{},...review.outreachIntent?{outreachIntent:review.outreachIntent}:{},snapshotId,recipientProfessionalEmail:review.recipientEmail,recipientDisplayName:review.recipient,subject:review.subject,body:review.body,planningSnapshotId:`daily-command-center:${review.candidateId}`,templateCatalogVersion:review.catalogVersion,evidenceIds:review.factIds,approvedAt:now.toISOString(),outreachTrack:review.outreachTrack,candidateId:review.candidateId,companyId:review.companyId,companyDisplayName:review.company,professionalTitle:review.title,...resumeAttachment?{resumeAttachment}:{}};}
export function mutableDraftBlockReason(input:{suppressed:boolean;optedOut:boolean;previousContact:boolean;companyCooldown:boolean;existingGmailDraft:boolean}):string|null{return input.suppressed?"suppressed":input.optedOut?"opted-out":input.previousContact?"previous-contact":input.companyCooldown?"company-cooldown":input.existingGmailDraft?"existing-gmail-draft":null;}
export function gmailDraftReadiness(input:GmailDraftReadinessInput):GmailDraftReadiness{
  const reason=!input.featureEnabled?"gmail-feature-disabled":!input.connected?"gmail-connection-invalid":!input.scopeValid?"gmail-scope-invalid":!input.providerConfigured?"gmail-oauth-configuration-missing":!input.credentialAvailable?"gmail-credential-unavailable":!input.credentialScopeValid?"gmail-credential-scope-invalid":!input.accountPinned?"gmail-account-unpinned":null;
  return{available:reason===null,reason};
}
export function gmailSendBlockReason(review:CommandCenterDraftReview,readiness:GmailDraftReadiness):string|null{
  if(review.operation?.sendState==="sent")return null;
  if(review.operation?.sendState==="sending"||review.operation?.sendState==="send-status-uncertain")return "gmail-send-reconciliation-required";
  if(review.operation?.state!=="gmail-draft-created"||!review.operation.gmailDraftId)return "gmail-send-draft-unavailable";
  if(review.blockedReason&&review.blockedReason!=="existing-gmail-draft")return review.blockedReason;
  return readiness.reason;
}
export const humanDraftError=(code:string):string=>({"bucket-correction-copy-review-required":"Review the corrected bucket and explicitly keep your edits or regenerate this unapproved message.","recipient-bucket-review-required":"Review the recipient bucket evidence before approval or externalization.","five-bucket-disabled":"The five-bucket feature is disabled for new actions.","recruiter-resume-decision-required":"Choose an active resume or explicitly continue without an attachment.","resume-copy-mismatch":"Remove the attachment claim for review or select an active resume.","suppressed":"This contact is suppressed and cannot be contacted.","opted-out":"This contact opted out and cannot be contacted.","previous-contact":"This person was already contacted.","company-cooldown":"Someone at this company was contacted recently.","existing-gmail-draft":"A Gmail draft already exists for this exact approved message.","gmail-feature-disabled":"Gmail draft creation is unavailable because the local Gmail draft feature is disabled.","gmail-connection-invalid":"Gmail draft creation is unavailable because Gmail is not connected.","gmail-scope-invalid":"Gmail draft creation is unavailable because the saved connection does not have only the required compose scope.","gmail-oauth-configuration-missing":"Gmail draft creation is unavailable because the local OAuth configuration is incomplete.","gmail-credential-unavailable":"Gmail draft creation is unavailable because its Keychain credential could not be loaded.","gmail-credential-scope-invalid":"Gmail draft creation is unavailable because the Keychain credential does not have only the required compose scope.","gmail-account-unpinned":"Gmail draft creation is unavailable because the approved Gmail account is not pinned consistently.","draft-not-approved":"Approve this exact draft before creating it in Gmail."}[code]??"This action could not be completed safely.");
export const humanSendError=(code:string):string=>({"gmail-send-draft-unavailable":"Only an approved, NetworkPilot-created Gmail draft can be sent.","gmail-send-reconciliation-required":"A send attempt started, but NetworkPilot did not record a final Gmail result. Do not retry this message until its status is reconciled in Gmail.","gmail-feature-disabled":"Sending is unavailable because the local Gmail feature is disabled.","gmail-connection-invalid":"Sending is unavailable because Gmail is not connected.","gmail-scope-invalid":"Sending is unavailable because the saved connection does not have only the required compose scope.","gmail-oauth-configuration-missing":"Sending is unavailable because the local OAuth configuration is incomplete.","gmail-credential-unavailable":"Sending is unavailable because its Keychain credential could not be loaded.","gmail-credential-scope-invalid":"Sending is unavailable because the Keychain credential does not have only the required compose scope.","gmail-account-unpinned":"Sending is unavailable because the approved Gmail account is not pinned consistently.","gmail-authentication-failed":"Gmail rejected the saved authorization. Reconnect Gmail before trying a different message.","gmail-authorization-failed":"Gmail did not authorize this send. No retry was attempted.","gmail-request-invalid":"Gmail rejected the prepared draft request. No retry was attempted.","gmail-draft-not-found":"Gmail could not find this immutable draft. No email was sent by NetworkPilot.","gmail-rate-limited":"Gmail rate-limited the send request. Its result must be reconciled before any retry.","gmail-provider-transient":"Gmail returned a temporary provider error. Its result must be reconciled before any retry.","gmail-timeout":"Gmail did not return a certain send result. Do not retry this message until its status is reconciled.","gmail-response-malformed":"Gmail returned an unreadable send result. Do not retry this message until its status is reconciled.","gmail-transport-failure":"NetworkPilot lost certainty while contacting Gmail. Do not retry this message until its status is reconciled.","gmail-account-ambiguous":"Sending is unavailable because the approved Gmail account cannot be verified."}[code]??humanDraftError(code));
export const humanEditError=(code:string):string=>({"dylan-voice-em-dash-prohibited":"Use a comma, colon, or full stop instead of an em dash.","dylan-voice-generic-phrase-prohibited":"Revise the generic outreach phrase before approving.","dylan-voice-subject-invalid":"Use a short, plain subject without emoji or ending punctuation.","dylan-voice-word-count-invalid":"Keep this message concise enough for a thoughtful introduction.","dylan-voice-cta-count-invalid":"Include one clear primary invitation; it does not need a question mark.","recipient-bucket-review-required":"Review and resolve the recipient-bucket evidence before approval.","recruiter-resume-decision-required":"Choose an active resume or explicitly continue without an attachment.","resume-copy-mismatch":"The message says a resume is attached, but no attachment is selected. Review and correct the copy or select a resume.","draft-placeholder-unresolved":"Replace every bracketed placeholder with reviewed evidence before approval.","draft-unsupported-claim":"Remove or correct the unsupported claim before approval.","draft-recipient-invalid":"The reviewed professional email address is not valid for approval."}[code]??"The edited message does not meet the outreach quality checks yet.");
