import {describe,expect,it} from "vitest";
import {gmailSendBlockReason,humanSendError,type CommandCenterDraftReview,type GmailDraftReadiness} from ".";

const ready:GmailDraftReadiness={available:true,reason:null};
const review=(blockedReason:string|null=null):CommandCenterDraftReview=>({outreachTrack:"professional",candidateId:"candidate",recipient:"A*** R.",recipientEmail:"fixture@example.invalid",company:"Fictional Co",companyId:"fictional-co",title:"Engineer",primaryFunction:"engineering",secondaryFunctions:[],persona:"experienced",experience:7,industry:"Technology",location:"Boston",score:91,lane:"engineering",templateVariant:"direct",qualification:"qualified",whySelected:"Relevant experience.",subject:"A question",body:"Fixture body",wordCount:75,factIds:[],catalogVersion:"catalog-v4-dylan-voice-v1",snapshotId:"snapshot",blockedReason,operation:{operationId:"operation",snapshot:{} as never,provider:"gmail",state:"gmail-draft-created",gmailDraftId:"draft",gmailMessageId:"message",attemptStartedAt:null,completedAt:null,errorCategory:null,adapterVersion:"fixture",outreachTrack:"professional",sendState:"not-sent",sentAt:null,gmailSentMessageId:null}});

describe("Gmail send gates",()=>{
  it("allows only a created, not-yet-sent draft with every mutable and runtime gate clear",()=>{expect(gmailSendBlockReason(review("existing-gmail-draft"),ready)).toBeNull();});
  it.each(["suppressed","opted-out","previous-contact","company-cooldown"])("blocks the mutable %s gate",(reason)=>{expect(gmailSendBlockReason(review(reason),ready)).toBe(reason);});
  it("blocks missing drafts and runtime readiness failures",()=>{expect(gmailSendBlockReason({...review(),operation:null},ready)).toBe("gmail-send-draft-unavailable");expect(gmailSendBlockReason(review(),{available:false,reason:"gmail-scope-invalid"})).toBe("gmail-scope-invalid");});
  it("requires reconciliation for in-flight or uncertain sends",()=>{for(const sendState of ["sending","send-status-uncertain"] as const)expect(gmailSendBlockReason({...review(),operation:{...review().operation!,sendState}},ready)).toBe("gmail-send-reconciliation-required");});
  it.each(["gmail-feature-disabled","gmail-connection-invalid","gmail-scope-invalid","gmail-oauth-configuration-missing","gmail-credential-unavailable","gmail-credential-scope-invalid","gmail-account-unpinned"])("blocks the %s runtime gate with an operator-safe explanation",(reason)=>{expect(gmailSendBlockReason(review(),{available:false,reason})).toBe(reason);expect(humanSendError(reason)).toMatch(/unavailable|not connected|does not have/);});
  it.each(["suppressed","opted-out","previous-contact","company-cooldown","gmail-send-draft-unavailable","gmail-send-reconciliation-required","gmail-authentication-failed","gmail-authorization-failed","gmail-request-invalid","gmail-draft-not-found","gmail-rate-limited","gmail-provider-transient","gmail-timeout","gmail-response-malformed","gmail-transport-failure","gmail-account-ambiguous"])("provides a human-readable %s failure without exposing an internal code",(reason)=>{const message=humanSendError(reason);expect(message).not.toBe(reason);expect(message.length).toBeGreaterThan(20);});
  it("does not self-block the first send because approval, planning, and the Gmail draft exist",()=>{const firstSend=review("existing-gmail-draft");expect(firstSend.operation?.sendState).toBe("not-sent");expect(gmailSendBlockReason(firstSend,ready)).toBeNull();});
});
