import { describe, expect, it } from "vitest";
import { mapApolloPerson } from "@/infrastructure/providers/apollo";
import { APOLLO_PEOPLE } from "@/infrastructure/providers/apollo/fixtures";
import { SqliteSimulationRepository } from "@/infrastructure/sqlite/database";
import { seedFictionalData } from "@/infrastructure/sqlite/seed";
import { TARGET_COMPANIES } from "@/domain/targeting";
import { importCandidateBatch } from "./import-candidates";

const observedTitles=[
  ["observed-software","Senior Software Engineer"],["observed-analytics-program","Analytics Program Manager"],["observed-cloud-ai","Senior Cloud Solution Architect, AI and Apps"],["observed-ai-director","Director of AI"],
] as const;

describe("recipient functions in provider-neutral ingestion",()=>{
  it("lets supported function relevance replace exact-role dependence without bypassing other gates",()=>{const repository=new SqliteSimulationRepository(":memory:");repository.migrate();seedFictionalData(repository);const records=observedTitles.map(([id,title])=>({...mapApolloPerson({...APOLLO_PEOPLE.senior,id,title},{stage:"enrichment",retrievedAt:"2026-09-09T12:00:00Z",datasetClassification:"provider-shaped-fixture"}),simulationAlias:{strategyCompanyId:"microsoft",reviewed:true,note:"Sanitized fixture alias."}}));importCandidateBatch(repository,repository.listTargetCompanies(),{batchId:"recipient-function-observations",adapterId:"apollo",adapterVersion:"fixture",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"recipient-function-observations-v1",records});const candidates=Object.fromEntries(repository.listImportedCandidates().filter((item)=>item.batchId==="recipient-function-observations").map((item)=>[item.source.providerRecordId,item]));expect(candidates["observed-software"]).toMatchObject({classification:{specificRoleId:"software-engineer"},recipientFunction:{primaryFunction:"software-engineering"},personaId:"senior-ic",state:"eligible"});expect(candidates["observed-analytics-program"]).toMatchObject({classification:{specificRoleId:null},recipientFunction:{primaryFunction:"project-program",secondaryFunctions:expect.arrayContaining(["data-analytics"])},personaId:"team-manager",state:"eligible"});expect(candidates["observed-cloud-ai"]).toMatchObject({classification:{specificRoleId:null},recipientFunction:{primaryFunction:"technical-infrastructure",secondaryFunctions:expect.arrayContaining(["ai-ml"])},personaId:"senior-ic",state:"eligible"});expect(candidates["observed-ai-director"]).toMatchObject({classification:{specificRoleId:null},recipientFunction:{primaryFunction:"ai-ml"},personaId:"functional-director",state:"eligible"});for(const candidate of Object.values(candidates))expect(candidate.gateFailures).not.toContain("role-title-unknown");repository.close();});

  it("keeps unknown and unrelated functions in review even with otherwise valid evidence",()=>{const repository=new SqliteSimulationRepository(":memory:");repository.migrate();const records=[["unknown-title","General Manager"],["unrelated-title","Account Executive"]].map(([id,title])=>({...mapApolloPerson({...APOLLO_PEOPLE.senior,id,title},{stage:"enrichment",retrievedAt:"2026-09-09T12:00:00Z",datasetClassification:"provider-shaped-fixture"}),simulationAlias:{strategyCompanyId:"microsoft",reviewed:true,note:"Sanitized fixture alias."}}));importCandidateBatch(repository,TARGET_COMPANIES,{batchId:"recipient-function-negative",adapterId:"apollo",adapterVersion:"fixture",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"recipient-function-negative-v1",records});const candidates=repository.listImportedCandidates();expect(candidates.find((item)=>item.source.providerRecordId==="unknown-title")).toMatchObject({state:"review-required",gateFailures:expect.arrayContaining(["recipient-function-unknown"])});expect(candidates.find((item)=>item.source.providerRecordId==="unrelated-title")).toMatchObject({state:"review-required",gateFailures:expect.arrayContaining(["recipient-function-unrelated"])});repository.close();});
});
