import {describe,expect,it} from "vitest";
import {importCandidateBatch} from ".";
import type {CandidateSourceRecord} from "@/domain/candidates";
import {TARGET_COMPANIES} from "@/domain/targeting";
import {SqliteSimulationRepository} from "@/infrastructure/sqlite/database";

const source=(id:string,title:string,employer:string,options:{providerId?:string;domain?:string}={}):CandidateSourceRecord=>({sourceProviderId:"apollo",providerRecordId:id,datasetClassification:"authorized-provider",person:{firstName:"Fixture",lastName:"Recruiter"},currentTitle:title,currentOrganization:{name:employer,...options},location:"United States",industrySignals:[],experienceEvidence:[{kind:"exact",years:7,sourceField:"fixture"}],email:{address:`${id}@example.invalid`,verificationStatus:"verified"},sourceTimestamps:{retrievedAt:"2026-09-19T12:00:00.000Z"},fieldProvenance:{},consent:{suppressed:false,optedOut:false},sourceFingerprint:`fixture-${id}-fingerprint`,providerMetadata:{adapterVersion:"fixture",responseMappingVersion:"fixture",requestContractVersion:"fixture",importArchitectureVersion:"fixture",matchConfidence:"high"}});
const importRecords=(records:CandidateSourceRecord[])=>{const repository=new SqliteSimulationRepository(":memory:");repository.migrate();importCandidateBatch(repository,TARGET_COMPANIES,{batchId:`recruiter-evidence-${records[0]!.providerRecordId}`,adapterId:"apollo",adapterVersion:"fixture",datasetClassification:"authorized-provider",sourceFingerprint:`recruiter-evidence-batch-${records[0]!.providerRecordId}`,records,authorizedProviderAccess:{enabled:true,providerId:"apollo"}},new Date("2026-09-19T12:00:00.000Z"));return repository;};

describe("internal recruiter employer evidence",()=>{
  it.each(["Technical Recruiter","Engineering Recruiter","Campus Recruiter","Product Recruiter","Early Career Recruiter"])("qualifies a legitimate internal %s without industry metadata",(title)=>{const id=title.toLowerCase().replaceAll(" ","-"),repository=importRecords([source(id,title,`Legitimate ${title} Employer`,{providerId:`org-${id}`})]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"eligible",outreachTrack:"recruiter",strategyCompanyMatch:{method:"discovered-provider"},recruiterClassification:{accepted:true,internalStatus:"internal"}});expect(repository.listImportedCandidates()[0]?.gateFailures).not.toContain("company-industry-unsupported");}finally{repository.close();}});
  it.each([["agency","Technical Recruiter","Example Staffing",{providerId:"org-agency"},"recruiter-agency-employer"],["clinical","Clinical Recruiter","Regional Health",{providerId:"org-clinical"},"recruiter-title-excluded"],["warehouse","Warehouse Recruiter","Distribution Group",{providerId:"org-warehouse"},"recruiter-title-excluded"],["sales","Sales Recruiter","Software Company",{providerId:"org-sales"},"recruiter-title-excluded"],["ambiguous","Technical Recruiter","Unknown",{},"recruiter-company-identity-unverifiable"]] as const)("rejects unsafe recruiter case %s",(id,title,employer,identity,reason)=>{const repository=importRecords([source(id,title,employer,identity)]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"rejected",gateFailures:expect.arrayContaining([reason])});}finally{repository.close();}});
  it("accepts a valid employer domain when provider employer ID is absent",()=>{const repository=importRecords([source("domain-backed","Technology Recruiter","Regional Software",{domain:"regional-software.example"})]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"eligible",recruiterClassification:{accepted:true}});}finally{repository.close();}});
});
