import {migrateTestDatabase} from "@/infrastructure/sqlite/test-migrations";
import {describe,expect,it} from "vitest";
import {importCandidateBatch} from ".";
import type {CandidateSourceRecord} from "@/domain/candidates";
import {TARGET_COMPANIES} from "@/domain/targeting";
import {SqliteSimulationRepository} from "@/infrastructure/sqlite/database";

const source=(id:string,title:string,employer:string,options:{providerId?:string;domain?:string}={},industrySignals:string[]=[]):CandidateSourceRecord=>({sourceProviderId:"apollo",providerRecordId:id,datasetClassification:"authorized-provider",person:{firstName:"Fixture",lastName:"Recruiter"},currentTitle:title,currentOrganization:{name:employer,...options},location:"United States",industrySignals,experienceEvidence:[{kind:"exact",years:7,sourceField:"fixture"}],email:{address:`${id}@example.invalid`,verificationStatus:"verified"},sourceTimestamps:{retrievedAt:"2026-09-19T12:00:00.000Z"},fieldProvenance:{},consent:{suppressed:false,optedOut:false},sourceFingerprint:`fixture-${id}-fingerprint`,providerMetadata:{adapterVersion:"fixture",responseMappingVersion:"fixture",requestContractVersion:"fixture",importArchitectureVersion:"fixture",matchConfidence:"high"}});
const importRecords=(records:CandidateSourceRecord[],strategyCompanyDomains:Record<string,string>={})=>{const repository=new SqliteSimulationRepository(":memory:");migrateTestDatabase(repository);importCandidateBatch(repository,TARGET_COMPANIES,{batchId:`recruiter-evidence-${records[0]!.providerRecordId}`,adapterId:"apollo",adapterVersion:"fixture",datasetClassification:"authorized-provider",sourceFingerprint:`recruiter-evidence-batch-${records[0]!.providerRecordId}`,records,strategyCompanyDomains,authorizedProviderAccess:{enabled:true,providerId:"apollo"}},new Date("2026-09-19T12:00:00.000Z"));return repository;};

describe("internal recruiter employer evidence",()=>{
  it.each(["Technical Recruiter","Engineering Recruiter","Campus Recruiter","Product Recruiter","Early Career Recruiter"])("keeps provider-only %s supply review-required without employer trust",(title)=>{const id=title.toLowerCase().replaceAll(" ","-"),repository=importRecords([source(id,title,`Legitimate ${title} Employer`,{providerId:`org-${id}`})]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"review-required",outreachTrack:"recruiter",strategyCompanyMatch:{method:"discovered-provider"},employerTrust:{state:"unverified"},recruiterClassification:{accepted:false,internalStatus:"ambiguous"},gateFailures:expect.arrayContaining(["company-trust-unverified"])});expect(repository.listImportedCandidates()[0]?.gateFailures).not.toContain("company-industry-unsupported");}finally{repository.close();}});
  it.each([["agency","Technical Recruiter","Example Staffing",{providerId:"org-agency"},"recruiter-agency-employer"],["clinical","Clinical Recruiter","Regional Health",{providerId:"org-clinical"},"recruiter-title-excluded"],["warehouse","Warehouse Recruiter","Distribution Group",{providerId:"org-warehouse"},"recruiter-title-excluded"],["sales","Sales Recruiter","Software Company",{providerId:"org-sales"},"recruiter-title-excluded"],["ambiguous","Technical Recruiter","Unknown",{},"recruiter-company-identity-unverifiable"]] as const)("rejects unsafe recruiter case %s",(id,title,employer,identity,reason)=>{const repository=importRecords([source(id,title,employer,identity)]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"rejected",gateFailures:expect.arrayContaining([reason])});}finally{repository.close();}});
  it.each(["northwindrpogroup.com","northwindrpopartners.com","northwindrpofirm.com","northwindrpoagency.com","northwindrposearch.com","northwindrpooutsourcing.com","northwindrpoproviders.com","northwindrpoexperts.com","northwindemploymentagencies.com","http://northwindstaffing.com"])("hard-rejects clear recruiter agency domain %s",(domain)=>{const id=`agency-domain-${domain.replace(/[^a-z0-9]+/gi,"-")}`,repository=importRecords([source(id,"Technical Recruiter","Northwind Technology",{providerId:`org-${id}`,domain},["Software"])]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"rejected",strategyCompanyMatch:null});expect(repository.listImportedCandidates()[0]?.gateFailures).toEqual(expect.arrayContaining([expect.stringMatching(/^(?:company-agency|recruiter-agency-employer)$/)]));}finally{repository.close();}});
  it.each(["northwindstaffers.com","northwindrecruit.com","northwindtalentsolution.com","stafford.com","staffordsoftware.com","staffordshire.co.uk","staffwise.com","researchfirm.com","researchfirmware.com","replacementservices.com","displacementgroup.com","misplacementpartners.com","unemploymentagency.com","nonhumanresources.com","understaffing.com","nonrecruiter.com","northwind_staffing.com","garbage","northwindѕtaffing.com","xn--northwindtaffing-0vn.com","münchen.example"])("keeps ambiguous recruiter domain %s reviewable",(domain)=>{const id=`ambiguous-domain-${domain.replace(/[^a-z0-9]+/gi,"-")}`,repository=importRecords([source(id,"Technical Recruiter","Stafford Software",{providerId:`org-${id}`,domain},["Software"])]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"review-required",strategyCompanyMatch:null,recruiterClassification:{accepted:false,internalStatus:"ambiguous"},gateFailures:expect.arrayContaining(["recruiter-company-domain-ambiguous","recruiter-employer-ambiguous","company-unreviewed"])});expect(repository.listImportedCandidates()[0]?.gateFailures).not.toEqual(expect.arrayContaining(["company-agency","recruiter-agency-employer"]));}finally{repository.close();}});
  it("keeps an ambiguous domain review-required even when the employer is already known",()=>{const repository=importRecords([source("known-company-ambiguous","Technical Recruiter","Microsoft",{providerId:"org-microsoft",domain:"staffordsoftware.com"},["Software"])],{microsoft:"staffordsoftware.com"});try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"review-required",strategyCompanyMatch:{canonicalName:"Microsoft",method:"domain"},recruiterClassification:{accepted:false,internalStatus:"ambiguous"},gateFailures:expect.arrayContaining(["recruiter-company-domain-ambiguous","recruiter-employer-ambiguous"])});expect(repository.listImportedCandidates()[0]?.gateFailures).not.toContain("company-unreviewed");}finally{repository.close();}});
  it("rejects a clear agency domain even when the employer is already known",()=>{const repository=importRecords([source("known-company-agency","Technical Recruiter","Microsoft",{providerId:"org-microsoft",domain:"northwindstaffing.com"},["Software"])],{microsoft:"northwindstaffing.com"});try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"rejected",strategyCompanyMatch:{canonicalName:"Microsoft",method:"domain"},recruiterClassification:{accepted:false},gateFailures:expect.arrayContaining(["recruiter-agency-employer"])});}finally{repository.close();}});
  it("preserves ambiguous raw-domain evidence after the adapter omits malformed identity",()=>{const record=source("normalized-malformed-domain","Technical Recruiter","Stafford Software",{providerId:"org-normalized-malformed"},["Software"]);record.responsibilityEvidence=[{id:"apollo:normalized-malformed-domain:internal-recruiting:1",kind:"internal-recruiting",value:"ambiguous",sourceReference:"apollo.person.organization.id",sourceReferences:["apollo.person.organization.id","apollo.person.organization.primary_domain","apollo.person.organization.industry"],observedAt:"2026-09-19T12:00:00.000Z",verified:false}];const repository=importRecords([record]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"review-required",strategyCompanyMatch:{method:"discovered-provider"},recruiterClassification:{accepted:false,internalStatus:"ambiguous"},gateFailures:expect.arrayContaining(["recruiter-company-domain-ambiguous","recruiter-employer-ambiguous"])});}finally{repository.close();}});
  it("still rejects an ambiguous-domain recruiter when an independent hard gate fails",()=>{const record=source("ambiguous-unverified","Technical Recruiter","Stafford Software",{providerId:"org-ambiguous-unverified",domain:"staffordsoftware.com"},["Software"]);record.email.verificationStatus="unverified";const repository=importRecords([record]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"rejected",gateFailures:expect.arrayContaining(["recruiter-company-domain-ambiguous","email-unverified"])});}finally{repository.close();}});
  it("keeps a neutral provider domain supporting-only when provider employer ID is absent",()=>{const repository=importRecords([source("domain-backed","Technology Recruiter","Regional Software",{domain:"regional-software.example"})]);try{expect(repository.listImportedCandidates()[0]).toMatchObject({state:"review-required",employerTrust:{state:"unverified"},recruiterClassification:{accepted:false},gateFailures:expect.arrayContaining(["company-trust-unverified"])});}finally{repository.close();}});
});
