import {CONTACT_IMPACTING_EVENT_TYPES} from "@/domain/outreach";
import {prepareControlledRealCampaign} from "@/application/providers/prepare-controlled-real-campaign";
import {approvedSnapshot,commandCenterSnapshotId,type CommandCenterDraftReview} from "@/application/command-center-drafts";
import {approveForGmailDraft,createApprovedGmailDraft,GMAIL_COMPOSE_SCOPE} from "@/application/email-drafts";
import {SqliteSimulationRepository} from "./database";
import {resolveManualOutreachDatabaseSelection} from "./manual-outreach-operator";
import {DeterministicPlainTextMimeBuilder,FetchGmailTransport,FetchGoogleOAuthTransport,GmailDraftAdapter,GMAIL_ADAPTER_VERSION,GoogleOAuthSession,MacOsKeychainGoogleTokenStore,readGmailConfig} from "@/infrastructure/providers/gmail";

const redactedEmail=(value:string|null)=>value?`${value[0]}***@${value.split("@")[1]}`:"not connected";
export function loadCommandCenterDraftReviews():{items:CommandCenterDraftReview[];gmail:{connected:boolean;account:string;scopeValid:boolean;featureEnabled:boolean}}{
 const selection=resolveManualOutreachDatabaseSelection(),repository=new SqliteSimulationRepository(selection.path);try{const candidates=repository.listImportedCandidates(),preview=prepareControlledRealCampaign(candidates,{target:20}),events=repository.listOutreachEvents(),contacted=new Set(events.filter(e=>CONTACT_IMPACTING_EVENT_TYPES.has(e.type)).map(e=>e.prospectId)),cooldownStart=Date.now()-7*86400000,cooldown=new Set(events.filter(e=>CONTACT_IMPACTING_EVENT_TYPES.has(e.type)&&e.type!=="operator-reported-hard-bounce"&&e.occurredAt.getTime()>=cooldownStart).map(e=>e.companyId)),candidateByPlan=new Map(candidates.map(c=>[`authorized:${c.source.providerRecordId}`,c]));const items=preview.drafts.map(d=>{const c=candidateByPlan.get(d.snapshot.prospectId);if(!c||!c.strategyCompanyMatch)return null;const snapshotId=commandCenterSnapshotId({candidateId:c.id,subject:d.draft.subject,body:d.draft.body,catalogVersion:d.draft.templateCatalogVersion});const current=repository.listProspects().find(p=>p.id===c.id),blockedReason=c.source.consent.suppressed||current?.suppressed?"suppressed":c.source.consent.optedOut||current?.optedOut?"opted-out":contacted.has(c.id)||contacted.has(d.snapshot.prospectId)?"previous-contact":cooldown.has(c.strategyCompanyMatch.companyId)?"company-cooldown":null;return{candidateId:c.id,recipient:d.redactedName,recipientEmail:c.source.email.address,company:d.company,title:d.sourceTitle,primaryFunction:d.recipientFunction??"unknown",secondaryFunctions:c.recipientFunction.secondaryFunctions,persona:d.persona,experience:d.yearsExperience,industry:d.snapshot.industry,location:d.geography,score:d.targetingScore,lane:d.lane,templateVariant:d.templateVariant,qualification:"qualified" as const,whySelected:d.whySelected,subject:d.draft.subject,body:d.draft.body,wordCount:d.wordCount,factIds:d.draft.referencedFactIds,catalogVersion:d.draft.templateCatalogVersion,snapshotId,operation:repository.findGmailDraftOperation(snapshotId),blockedReason};}).filter((v):v is CommandCenterDraftReview=>Boolean(v)).slice(0,5);const metadata=repository.getGmailConnectionMetadata(),config=readGmailConfig(process.env),scopeValid=metadata?.grantedScopes.length===1&&metadata.grantedScopes[0]===GMAIL_COMPOSE_SCOPE;return{items,gmail:{connected:metadata?.state==="connected"&&Boolean(metadata.accountEmail),account:redactedEmail(metadata?.accountEmail??null),scopeValid,featureEnabled:config.enabled}};}finally{repository.close();}}
export function approveCommandCenterDraft(snapshotId:string){const view=loadCommandCenterDraftReviews(),review=view.items.find(i=>i.snapshotId===snapshotId);if(!review)throw new Error("draft-unavailable");if(review.blockedReason)throw new Error(review.blockedReason);const repository=new SqliteSimulationRepository(resolveManualOutreachDatabaseSelection().path);try{repository.migrate();return approveForGmailDraft(repository,approvedSnapshot(review,new Date()),GMAIL_ADAPTER_VERSION);}finally{repository.close();}}
export async function createCommandCenterGmailDraft(snapshotId:string){const view=loadCommandCenterDraftReviews(),review=view.items.find(i=>i.snapshotId===snapshotId);if(!review)throw new Error("draft-unavailable");if(review.blockedReason)throw new Error(review.blockedReason);if(!view.gmail.featureEnabled)throw new Error("gmail-feature-disabled");if(!view.gmail.connected)throw new Error("gmail-connection-invalid");if(!view.gmail.scopeValid)throw new Error("gmail-scope-invalid");const repository=new SqliteSimulationRepository(resolveManualOutreachDatabaseSelection().path);try{repository.migrate();if(!repository.findGmailDraftOperation(snapshotId))throw new Error("draft-not-approved");const config=readGmailConfig(process.env),session=new GoogleOAuthSession(config,new FetchGoogleOAuthTransport(),new MacOsKeychainGoogleTokenStore(),()=>new Date(),repository),adapter=new GmailDraftAdapter(config,new FetchGmailTransport(),session);return await createApprovedGmailDraft({snapshotId,repository,creator:adapter,mime:new DeterministicPlainTextMimeBuilder(),now:()=>new Date()});}finally{repository.close();}}
