import Database from "better-sqlite3";
import {existsSync} from "node:fs";
import {resolve} from "node:path";
import {CONTACT_IMPACTING_EVENT_TYPES} from "@/domain/outreach";
import {renderRecruiterDraft} from "@/domain/recruiters";
import {prepareControlledRealCampaign} from "@/application/providers/prepare-controlled-real-campaign";
import {approvedSnapshot,commandCenterSnapshotId,gmailDraftReadiness,gmailSendBlockReason,mutableDraftBlockReason,type CommandCenterDraftReview,type GmailDraftReadiness} from "@/application/command-center-drafts";
import {approveForGmailDraft,createApprovedGmailDraft,sendApprovedGmailDraft,GMAIL_COMPOSE_SCOPE,type ApprovedEmailDraftSnapshot} from "@/application/email-drafts";
import {confirmOperatorManualSend} from "@/application/manual-outreach";
import type {ImportedCandidateSnapshot} from "@/application/ingestion";
import {SqliteSimulationRepository} from "./database";
import {resolveManualOutreachDatabaseSelection} from "./manual-outreach-operator";
import {RECRUITER_OPERATIONAL_DATABASE} from "./daily-command-center";
import {DeterministicPlainTextMimeBuilder,FetchGmailTransport,FetchGoogleOAuthTransport,GmailDraftAdapter,GMAIL_ADAPTER_VERSION,GoogleOAuthSession,MacOsKeychainGoogleTokenStore,readGmailConfig} from "@/infrastructure/providers/gmail";
import {localCampaignDate} from "@/application/daily-refresh";

const redactedEmail=(value:string|null)=>value?`${value[0]}***@${value.split("@")[1]}`:"not connected";
const redactedName=(candidate:ImportedCandidateSnapshot)=>`${candidate.source.person.firstName[0]??"?"}***${candidate.source.person.lastName?` ${candidate.source.person.lastName[0]}.`:""}`;
const reasonFor=(candidate:ImportedCandidateSnapshot,companyId:string,operation:CommandCenterDraftReview["operation"],contacted:Set<string>,cooldown:Set<string>,suppressed:Set<string>)=>mutableDraftBlockReason({suppressed:candidate.source.consent.suppressed||suppressed.has(candidate.id),optedOut:candidate.source.consent.optedOut,previousContact:contacted.has(candidate.id)||contacted.has(`authorized:${candidate.source.providerRecordId}`),companyCooldown:cooldown.has(companyId),existingGmailDraft:operation?.state==="gmail-draft-created"});
function operationForCandidate(repository:SqliteSimulationRepository,candidateId:string,generatedSnapshotId:string){const generated=repository.findGmailDraftOperation(generatedSnapshotId);if(generated)return generated;const rows=repository.native.prepare("SELECT draft_snapshot_id,approved_snapshot_json FROM gmail_draft_operations").all() as Array<{draft_snapshot_id:string;approved_snapshot_json:string}>;for(const row of rows){const snapshot=JSON.parse(row.approved_snapshot_json) as ApprovedEmailDraftSnapshot;if(snapshot.candidateId===candidateId)return repository.findGmailDraftOperation(row.draft_snapshot_id);}return null;}
function candidateIdsWithOperations(repository:SqliteSimulationRepository){return new Set((repository.native.prepare("SELECT approved_snapshot_json FROM gmail_draft_operations").all() as Array<{approved_snapshot_json:string}>).map((row)=>(JSON.parse(row.approved_snapshot_json) as ApprovedEmailDraftSnapshot).candidateId).filter((id):id is string=>Boolean(id)));}

export async function loadCommandCenterDraftReviews():Promise<{items:CommandCenterDraftReview[];gmail:{connected:boolean;account:string;scopeValid:boolean;featureEnabled:boolean;providerConfigured:boolean;credentialAvailable:boolean;credentialScopeValid:boolean;accountPinned:boolean;readiness:GmailDraftReadiness}}>{
  const selection=resolveManualOutreachDatabaseSelection(),repository=new SqliteSimulationRepository(selection.path);
  try{
    const allCandidates=repository.listImportedCandidates(),hasRefreshTable=Boolean(repository.native.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='daily_refresh_runs'").get()),refreshRow=hasRefreshTable?repository.native.prepare("SELECT result_json FROM daily_refresh_runs WHERE campaign_date=? ORDER BY generation DESC LIMIT 1").get(localCampaignDate(new Date())) as {result_json:string}|undefined:undefined,refreshIds=new Set(refreshRow?(JSON.parse(refreshRow.result_json) as {candidateIds:string[]}).candidateIds:[]),latestIds=refreshIds.size?refreshIds:new Set((repository.native.prepare("SELECT id FROM imported_candidates WHERE date(updated_at_utc)=(SELECT date(MAX(updated_at_utc)) FROM imported_candidates WHERE batch_id LIKE 'operational-enrichment-%')").all() as Array<{id:string}>).map((row)=>row.id));
    const events=repository.listOutreachEvents(),contacted=new Set(events.filter((event)=>CONTACT_IMPACTING_EVENT_TYPES.has(event.type)).map((event)=>event.prospectId)),cooldownStart=Date.now()-7*86400000,cooldown=new Set(events.filter((event)=>CONTACT_IMPACTING_EVENT_TYPES.has(event.type)&&event.type!=="operator-reported-hard-bounce"&&event.occurredAt.getTime()>=cooldownStart).map((event)=>event.companyId)),suppressed=new Set((repository.native.prepare("SELECT candidate_id FROM candidate_suppression_entries").all() as Array<{candidate_id:string}>).map((row)=>row.candidate_id)),operationCandidateIds=candidateIdsWithOperations(repository);
    const professionalCandidates=allCandidates.filter((candidate)=>latestIds.has(candidate.id)&&candidate.outreachTrack!=="recruiter"),preview=prepareControlledRealCampaign(professionalCandidates,{target:20}),candidateByPlan=new Map(professionalCandidates.map((candidate)=>[`authorized:${candidate.source.providerRecordId}`,candidate]));
    const professionalItems=preview.drafts.map((draft):CommandCenterDraftReview|null=>{const candidate=candidateByPlan.get(draft.snapshot.prospectId);if(!candidate?.strategyCompanyMatch)return null;const generatedSnapshotId=commandCenterSnapshotId({candidateId:candidate.id,subject:draft.draft.subject,body:draft.draft.body,catalogVersion:draft.draft.templateCatalogVersion}),operation=operationForCandidate(repository,candidate.id,generatedSnapshotId),snapshotId=operation?.snapshot.snapshotId??generatedSnapshotId,current=repository.listProspects().find((prospect)=>prospect.id===candidate.id),blockedReason=reasonFor({...candidate,source:{...candidate.source,consent:{...candidate.source.consent,suppressed:candidate.source.consent.suppressed||Boolean(current?.suppressed),optedOut:candidate.source.consent.optedOut||Boolean(current?.optedOut)}}},candidate.strategyCompanyMatch.companyId,operation,contacted,cooldown,suppressed);return{outreachTrack:"professional",candidateId:candidate.id,recipient:operation?.snapshot.recipientDisplayName??draft.redactedName,recipientEmail:operation?.snapshot.recipientProfessionalEmail??candidate.source.email.address,company:operation?.snapshot.companyDisplayName??draft.company,companyId:operation?.snapshot.companyId??candidate.strategyCompanyMatch.companyId,title:operation?.snapshot.professionalTitle??draft.sourceTitle,primaryFunction:draft.recipientFunction??"unknown",secondaryFunctions:candidate.recipientFunction.secondaryFunctions,persona:draft.persona,experience:draft.yearsExperience,industry:draft.snapshot.industry,location:draft.geography,score:draft.targetingScore,lane:draft.lane,templateVariant:draft.templateVariant,qualification:"qualified",whySelected:draft.whySelected,subject:operation?.snapshot.subject??draft.draft.subject,body:operation?.snapshot.body??draft.draft.body,wordCount:(operation?.snapshot.body??draft.draft.body).trim().split(/\s+/).length,factIds:[...(operation?.snapshot.evidenceIds??draft.draft.referencedFactIds)],catalogVersion:operation?.snapshot.templateCatalogVersion??draft.draft.templateCatalogVersion,snapshotId,operation,blockedReason} satisfies CommandCenterDraftReview;}).filter((item):item is CommandCenterDraftReview=>Boolean(item)).filter((item)=>item.blockedReason===null||Boolean(item.operation)).slice(0,10);
    const professionalCompanies=new Set(professionalItems.map((item)=>item.company)),recruiterItems:CommandCenterDraftReview[]=[];
    const recruiterPath=resolve(/*turbopackIgnore: true*/ process.cwd(),RECRUITER_OPERATIONAL_DATABASE);
    if(existsSync(/*turbopackIgnore: true*/ recruiterPath)){
      const recruiterDatabase=new Database(recruiterPath,{readonly:true,fileMustExist:true});
      try{
        const candidates=(recruiterDatabase.prepare("SELECT normalized_snapshot_json FROM imported_candidates ORDER BY updated_at_utc DESC").all() as Array<{normalized_snapshot_json:string}>).map((row)=>JSON.parse(row.normalized_snapshot_json) as ImportedCandidateSnapshot).filter((candidate)=>candidate.outreachTrack==="recruiter"&&candidate.recruiterClassification?.accepted&&((candidate.state==="eligible"&&candidate.source.email.verificationStatus==="verified"&&candidate.gateFailures.length===0&&(!refreshIds.size||refreshIds.has(candidate.id)))||operationCandidateIds.has(candidate.id))).sort((a,b)=>(b.recruiterClassification?.score??0)-(a.recruiterClassification?.score??0)||a.id.localeCompare(b.id));
        const companies=new Set<string>();
        for(const candidate of candidates){const companyId=candidate.strategyCompanyMatch?.companyId,classification=candidate.recruiterClassification;if(!companyId||!classification||(professionalCompanies.has(candidate.source.currentOrganization.name)&&!operationCandidateIds.has(candidate.id))||(companies.has(candidate.source.currentOrganization.name)&&!operationCandidateIds.has(candidate.id)))continue;const draft=renderRecruiterDraft({firstName:candidate.source.person.firstName,company:candidate.source.currentOrganization.name,title:candidate.source.currentTitle,classification}),generatedSnapshotId=commandCenterSnapshotId({candidateId:candidate.id,subject:draft.subject,body:draft.body,catalogVersion:draft.catalogVersion}),operation=operationForCandidate(repository,candidate.id,generatedSnapshotId),snapshotId=operation?.snapshot.snapshotId??generatedSnapshotId,blockedReason=reasonFor(candidate,companyId,operation,contacted,cooldown,suppressed);if(blockedReason&&!operation)continue;recruiterItems.push({outreachTrack:"recruiter",candidateId:candidate.id,recipient:operation?.snapshot.recipientDisplayName??redactedName(candidate),recipientEmail:operation?.snapshot.recipientProfessionalEmail??candidate.source.email.address,company:operation?.snapshot.companyDisplayName??candidate.source.currentOrganization.name,companyId:operation?.snapshot.companyId??companyId,title:operation?.snapshot.professionalTitle??candidate.source.currentTitle,primaryFunction:"recruiting",secondaryFunctions:[],persona:classification.recruiterType,experience:candidate.experience.minimumSupportedYears??0,industry:candidate.source.industrySignals[0]??"unclassified",location:candidate.source.location,score:classification.score,lane:"recruiter",templateVariant:draft.variant,qualification:"qualified",whySelected:classification.earlyCareerRelevance&&classification.technicalRelevance?"Internal early-career technology recruiter at a reviewed target company.":classification.technicalRelevance?"Internal technical recruiter at a reviewed target company.":classification.earlyCareerRelevance?"Internal early-career recruiter at a reviewed target company.":"Internal recruiter at a reviewed target company.",subject:operation?.snapshot.subject??draft.subject,body:operation?.snapshot.body??draft.body,wordCount:(operation?.snapshot.body??draft.body).trim().split(/\s+/).length,factIds:[...(operation?.snapshot.evidenceIds??draft.referencedEvidence)],catalogVersion:operation?.snapshot.templateCatalogVersion??draft.catalogVersion,snapshotId,operation,blockedReason,recruiterType:classification.recruiterType,recruitingDomain:classification.recruitingDomain,technicalRecruiting:classification.technicalRelevance,earlyCareerRecruiting:classification.earlyCareerRelevance});companies.add(candidate.source.currentOrganization.name);if(recruiterItems.length===5)break;}
      }finally{recruiterDatabase.close();}
    }
    const metadata=repository.getGmailConnectionMetadata(),config=readGmailConfig(process.env),connected=metadata?.state==="connected"&&Boolean(metadata.accountEmail),scopeValid=metadata?.grantedScopes.length===1&&metadata.grantedScopes[0]===GMAIL_COMPOSE_SCOPE,providerConfigured=Boolean(config.clientId&&config.redirectUri),tokens=await new MacOsKeychainGoogleTokenStore().load().catch(()=>null),credentialAvailable=Boolean(tokens),credentialScopeValid=tokens?.grantedScopes.length===1&&tokens.grantedScopes[0]===GMAIL_COMPOSE_SCOPE,accountPinned=Boolean(tokens?.accountEmail&&metadata?.accountEmail&&tokens.accountEmail===metadata.accountEmail),input={featureEnabled:config.enabled,connected,scopeValid,providerConfigured,credentialAvailable,credentialScopeValid,accountPinned};
    return{items:[...professionalItems,...recruiterItems],gmail:{account:redactedEmail(metadata?.accountEmail??null),...input,readiness:gmailDraftReadiness(input)}};
  }finally{repository.close();}
}

export async function approveCommandCenterDraft(snapshotId:string){const view=await loadCommandCenterDraftReviews(),review=view.items.find((item)=>item.snapshotId===snapshotId);if(!review)throw new Error("draft-unavailable");if(review.blockedReason)throw new Error(review.blockedReason);const repository=new SqliteSimulationRepository(resolveManualOutreachDatabaseSelection().path);try{repository.migrate();return approveForGmailDraft(repository,approvedSnapshot(review,new Date()),GMAIL_ADAPTER_VERSION,review.outreachTrack);}finally{repository.close();}}
export async function createCommandCenterGmailDraft(snapshotId:string){const view=await loadCommandCenterDraftReviews(),review=view.items.find((item)=>item.snapshotId===snapshotId);if(!review)throw new Error("draft-unavailable");if(review.blockedReason&&review.blockedReason!=="existing-gmail-draft")throw new Error(review.blockedReason);if(view.gmail.readiness.reason)throw new Error(view.gmail.readiness.reason);const repository=new SqliteSimulationRepository(resolveManualOutreachDatabaseSelection().path);try{repository.migrate();if(!repository.findGmailDraftOperation(snapshotId))throw new Error("draft-not-approved");const config=readGmailConfig(process.env),session=new GoogleOAuthSession(config,new FetchGoogleOAuthTransport(),new MacOsKeychainGoogleTokenStore(),()=>new Date(),repository),adapter=new GmailDraftAdapter(config,new FetchGmailTransport(),session);return await createApprovedGmailDraft({snapshotId,repository,creator:adapter,mime:new DeterministicPlainTextMimeBuilder(),now:()=>new Date()});}finally{repository.close();}}
export async function sendAndRecordCommandCenterDraft(input:{snapshotId:string;repository:SqliteSimulationRepository;sender:import("@/application/email-drafts").GmailDraftSender;now:()=>Date}){const existing=input.repository.findGmailDraftOperation(input.snapshotId),sent=existing?.sendState==="sent"?existing:await sendApprovedGmailDraft(input),sentAt=new Date(sent.sentAt??input.now().toISOString());confirmOperatorManualSend({snapshotId:input.snapshotId,effectiveSentAt:sentAt,now:()=>sentAt,repository:input.repository,confirmationSource:"networkpilot-gmail-send"});return input.repository.findGmailDraftOperation(input.snapshotId)!;}
export async function sendCommandCenterGmailDraft(snapshotId:string){const repository=new SqliteSimulationRepository(resolveManualOutreachDatabaseSelection().path);try{repository.migrate();const existing=repository.findGmailDraftOperation(snapshotId);if(existing?.sendState==="sent")return sendAndRecordCommandCenterDraft({snapshotId,repository,sender:{sendDraft:async()=>{throw new Error("gmail-send-idempotency-violation");}},now:()=>new Date()});const view=await loadCommandCenterDraftReviews(),review=view.items.find((item)=>item.snapshotId===snapshotId);if(!review)throw new Error("draft-unavailable");const blocked=gmailSendBlockReason(review,view.gmail.readiness);if(blocked)throw new Error(blocked);const config=readGmailConfig(process.env),session=new GoogleOAuthSession(config,new FetchGoogleOAuthTransport(),new MacOsKeychainGoogleTokenStore(),()=>new Date(),repository),adapter=new GmailDraftAdapter(config,new FetchGmailTransport(),session);return sendAndRecordCommandCenterDraft({snapshotId,repository,sender:adapter,now:()=>new Date()});}finally{repository.close();}}
