import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {describe,expect,it} from "vitest";
import {migrateTestDatabase} from "./test-migrations";
import {SqliteSimulationRepository} from "./database";
import {importCandidateBatch,type ImportedCandidateSnapshot} from "@/application/ingestion";
import {reviewCompanyTrust,type ReviewCompanyTrustCommand} from "@/application/company-trust";
import {planRecruiterCandidates} from "@/domain/recruiters";
import type {CandidateSourceRecord} from "@/domain/candidates";
import {seedTargetCompanyRegistry} from "./seed";
import {approveForGmailDraft,type ApprovedEmailDraftSnapshot} from "@/application/email-drafts";

const at=new Date("2026-09-30T12:00:00.000Z");
const source=(id:string,name:string,identity:{domain?:string;providerId?:string},title="Technical Recruiter",provider="apollo"):CandidateSourceRecord=>({sourceProviderId:provider,providerRecordId:id,datasetClassification:"authorized-provider",person:{firstName:"Fixture",lastName:"Recruiter"},currentTitle:title,currentOrganization:{name,...identity},location:"United States",industrySignals:["Software"],experienceEvidence:[{kind:"exact",years:7,sourceField:"fixture"}],email:{address:`${id}@example.invalid`,verificationStatus:"verified"},sourceTimestamps:{retrievedAt:at.toISOString()},fieldProvenance:{},consent:{suppressed:false,optedOut:false},sourceFingerprint:`company-trust-${provider}-${id}-fingerprint`,providerMetadata:{adapterVersion:"fixture",responseMappingVersion:"fixture",requestContractVersion:"fixture",importArchitectureVersion:"fixture",matchConfidence:"high"}});
const repository=()=>{const value=new SqliteSimulationRepository(":memory:");migrateTestDatabase(value);return value;};
const add=(repo:SqliteSimulationRepository,record:CandidateSourceRecord,domains:Record<string,string>={})=>{importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:`trust-batch-${record.sourceProviderId}-${record.providerRecordId}`,adapterId:record.sourceProviderId,adapterVersion:"fixture",datasetClassification:"authorized-provider",sourceFingerprint:`trust-batch-${record.sourceProviderId}-${record.providerRecordId}-fingerprint`,records:[record],strategyCompanyDomains:domains,authorizedProviderAccess:{enabled:true,providerId:record.sourceProviderId}},at);return repo.findImportedCandidate(record.sourceProviderId,record.providerRecordId)!;};
const identity=(candidate:ImportedCandidateSnapshot)=>({employerDomain:candidate.source.currentOrganization.domain,providerNamespace:candidate.source.sourceProviderId,providerEmployerId:candidate.source.currentOrganization.providerId});
const command=(candidate:ImportedCandidateSnapshot,resultingTrustState:"unverified"|"trusted-operating"|"disallowed-recruiting-service",expectedVersion:number,commandId:string,when=new Date(at.getTime()+expectedVersion*1000)):ReviewCompanyTrustCommand=>({commandId,companyId:candidate.strategyCompanyMatch!.companyId,identity:identity(candidate),expectedVersion,resultingTrustState,reason:`Reviewed ${resultingTrustState}`,reviewerActor:"local-operator",sourceReference:"operator://company-review/fixture",at:when});
const review=(repo:SqliteSimulationRepository,candidate:ImportedCandidateSnapshot,resultingTrustState:"unverified"|"trusted-operating"|"disallowed-recruiting-service",expectedVersion:number,commandId:string,when?:Date)=>reviewCompanyTrust(repo,command(candidate,resultingTrustState,expectedVersion,commandId,when));

describe("audited company trust persistence",()=>{
  it("derives current trust from audit and creates no discovery default row",()=>{const repo=repository();try{const first=add(repo,source("provider-one","Ordinary Software",{domain:"ordinary.example",providerId:"org-one"}));expect(first).toMatchObject({state:"review-required",employerTrust:{state:"unverified",sourceKind:"provider-discovery-default"}});expect(repo.native.prepare("SELECT COUNT(*) count FROM company_trust_audit").get()).toEqual({count:0});expect(repo.native.prepare("SELECT COUNT(*) count FROM company_trust_current").get()).toEqual({count:0});review(repo,first,"trusted-operating",0,"trust-command-one");expect(repo.findCompanyTrustRecord(first.strategyCompanyMatch!.companyId)).toMatchObject({trustState:"trusted-operating",version:1,providerNamespace:"apollo",providerEmployerId:"org-one",reviewedDomain:"ordinary.example"});expect(repo.findImportedCandidate("apollo","provider-one")).toMatchObject({state:"eligible",employerTrust:{state:"trusted-operating",sourceKind:"audited-human-review",version:1}});expect(planRecruiterCandidates(repo.listImportedCandidates(),new Set(),new Set())).toHaveLength(1);}finally{repo.close();}});

  it("reuses only the exact reviewed provider fingerprint and fails closed on drift",()=>{const repo=repository();try{const first=add(repo,source("identity-one","Acme Systems",{domain:"acme.example",providerId:"org-acme"}));review(repo,first,"trusted-operating",0,"identity-trust-one");expect(add(repo,source("identity-exact","Acme Systems",{domain:"acme.example",providerId:"org-acme"}))).toMatchObject({state:"eligible",employerTrust:{state:"trusted-operating"}});expect(add(repo,source("identity-domain","Acme Systems",{domain:"acme.example",providerId:"org-other"}))).toMatchObject({state:"review-required",employerTrust:{state:"unverified"}});expect(add(repo,source("identity-namespace","Acme Systems",{domain:"acme.example",providerId:"org-acme"},"Technical Recruiter","other-provider"))).toMatchObject({state:"review-required",employerTrust:{state:"unverified"}});expect(add(repo,source("identity-drift","Acme Systems",{domain:"changed.example",providerId:"org-acme"}))).toMatchObject({state:"review-required",employerTrust:{state:"unverified"}});}finally{repo.close();}});

  it("keeps names, similar domains, and parent-looking entities outside trust reuse",()=>{const repo=repository();try{const fallback=add(repo,source("fallback-one","Example Holdings",{domain:"example.com"}));review(repo,fallback,"trusted-operating",0,"fallback-trust-one");expect(add(repo,source("fallback-exact","Renamed Entity",{domain:"example.com"}))).toMatchObject({state:"eligible",employerTrust:{state:"trusted-operating"}});for(const [id,name,domain] of [["similar","Example Holdings","examplejobs.com"],["same-name","Example Holdings","unrelated.com"],["subsidiary","Example Holdings Subsidiary","subsidiary.example.com"]])expect(add(repo,source(id,name,{domain}))).toMatchObject({state:"review-required",employerTrust:{state:"unverified"}});expect(add(repo,source("missing","Example Holdings",{}))).toMatchObject({employerTrust:{state:"unverified",identityVerified:false}});}finally{repo.close();}});

  it("supports disallow and later corrections while preserving every audit event",()=>{const repo=repository();try{const candidate=add(repo,source("correction-one","Correction Software",{domain:"correction.example"}));review(repo,candidate,"trusted-operating",0,"correction-command-one");review(repo,candidate,"disallowed-recruiting-service",1,"correction-command-two");expect(repo.findImportedCandidate("apollo","correction-one")).toMatchObject({state:"rejected",employerTrust:{state:"disallowed-recruiting-service"},gateFailures:expect.arrayContaining(["company-trust-disallowed"])});review(repo,candidate,"trusted-operating",2,"correction-command-three");expect(repo.findImportedCandidate("apollo","correction-one")).toMatchObject({state:"eligible",employerTrust:{state:"trusted-operating",version:3}});expect(repo.native.prepare("SELECT previous_trust_state previous,resulting_trust_state result,resulting_version version FROM company_trust_audit WHERE company_identity_key=? ORDER BY resulting_version").all(candidate.strategyCompanyMatch!.companyId)).toEqual([{previous:"unverified",result:"trusted-operating",version:1},{previous:"trusted-operating",result:"disallowed-recruiting-service",version:2},{previous:"disallowed-recruiting-service",result:"trusted-operating",version:3}]);}finally{repo.close();}});

  it("enforces append-only, version-chain, and read-only-current invariants in SQLite",()=>{const repo=repository();try{const candidate=add(repo,source("sql-one","SQL Software",{domain:"sql.example"}));review(repo,candidate,"trusted-operating",0,"sql-command-one");expect(()=>repo.native.prepare("UPDATE company_trust_audit SET reason='rewritten'").run()).toThrow("company-trust-audit-append-only");expect(()=>repo.native.prepare("DELETE FROM company_trust_audit").run()).toThrow("company-trust-audit-append-only");expect(()=>repo.native.prepare("UPDATE company_trust_current SET trust_state='unverified'").run()).toThrow();expect(()=>repo.native.prepare("INSERT INTO company_trust_current(company_identity_key,trust_state) VALUES('forged','trusted-operating')").run()).toThrow();expect(()=>repo.native.prepare("INSERT INTO company_trust_audit SELECT 'duplicate-version',company_identity_key,provider_namespace,provider_employer_id,reviewed_domain,previous_trust_state,resulting_trust_state,reviewer_actor,occurred_at_utc,reason,source_kind,source_reference,'duplicate-version-command',command_fingerprint,resulting_version FROM company_trust_audit LIMIT 1").run()).toThrow();expect(()=>repo.native.prepare("INSERT INTO company_trust_audit SELECT 'bad-chain',company_identity_key,provider_namespace,provider_employer_id,reviewed_domain,'disallowed-recruiting-service','unverified',reviewer_actor,occurred_at_utc,reason,source_kind,source_reference,'bad-chain-command',command_fingerprint,2 FROM company_trust_audit LIMIT 1").run()).toThrow("company-trust-audit-previous-state");}finally{repo.close();}});

  it("fingerprints the complete command including timestamp",()=>{const repo=repository();try{const candidate=add(repo,source("replay-one","Replay Software",{domain:"replay.example"})),firstCommand=command(candidate,"trusted-operating",0,"replay-command-one");const result=reviewCompanyTrust(repo,firstCommand),replay=reviewCompanyTrust(repo,firstCommand);expect(replay).toMatchObject({replayed:true,event:{id:result.event.id}});expect(()=>reviewCompanyTrust(repo,{...firstCommand,at:new Date(at.getTime()+1)})).toThrow("company-trust-command-conflict");expect(()=>reviewCompanyTrust(repo,{...firstCommand,reason:"Different payload"})).toThrow("company-trust-command-conflict");expect(()=>review(repo,candidate,"disallowed-recruiting-service",0,"stale-command-one")).toThrow("company-trust-stale-version");}finally{repo.close();}});

  it("serializes expected-version commands across independent connections",()=>{const directory=mkdtempSync(join(tmpdir(),"networkpilot-trust-concurrency-")),path=join(directory,"operational.sqlite"),seed=new SqliteSimulationRepository(path);try{migrateTestDatabase(seed);const candidate=add(seed,source("concurrent-one","Concurrent Software",{domain:"concurrent.example"}));seed.close();const first=new SqliteSimulationRepository(path),second=new SqliteSimulationRepository(path);try{review(first,candidate,"trusted-operating",0,"concurrent-command-a");expect(()=>review(second,candidate,"disallowed-recruiting-service",0,"concurrent-command-b")).toThrow("company-trust-stale-version");expect(second.native.prepare("SELECT COUNT(*) count FROM company_trust_audit").get()).toEqual({count:1});expect(second.findCompanyTrustRecord(candidate.strategyCompanyMatch!.companyId)).toMatchObject({trustState:"trusted-operating",version:1});review(second,candidate,"disallowed-recruiting-service",1,"concurrent-command-c");expect(first.findCompanyTrustRecord(candidate.strategyCompanyMatch!.companyId)).toMatchObject({trustState:"disallowed-recruiting-service",version:2});}finally{first.close();second.close();}}finally{if(seed.native.open)seed.close();rmSync(directory,{recursive:true,force:true});}});

  it("does not rewrite candidate imports, Gmail snapshots, or outreach history",()=>{const repo=repository();try{const candidate=add(repo,source("history-one","History Software",{domain:"history.example"})),companyId=candidate.strategyCompanyMatch!.companyId,snapshot:ApprovedEmailDraftSnapshot={snapshotId:"history-approved-snapshot",recipientProfessionalEmail:"history@example.invalid",recipientDisplayName:"Fixture Recruiter",subject:"Historical subject",body:"Historical approved body",planningSnapshotId:`daily-command-center:${candidate.id}`,templateCatalogVersion:"historical-fixture",evidenceIds:[],approvedAt:at.toISOString(),outreachTrack:"recruiter",candidateId:candidate.id,companyId,companyDisplayName:"History Software",professionalTitle:"Technical Recruiter"};const operation=approveForGmailDraft(repo,snapshot,"fixture");repo.createManualOutreach({id:"history-outreach",draftSnapshotId:snapshot.snapshotId,gmailOperationId:operation.operationId,candidateId:candidate.id,companyId,identitySource:"imported-candidate",confirmationSource:"operator",confirmedAt:at.toISOString(),effectiveSentAt:at.toISOString(),outcome:"awaiting-response",operationVersion:"fixture",createdAt:at.toISOString(),updatedAt:at.toISOString(),outreachTrack:"recruiter"});const before=JSON.stringify({candidate:repo.native.prepare("SELECT * FROM imported_candidates WHERE id=?").get(candidate.id),gmail:repo.native.prepare("SELECT * FROM gmail_draft_operations WHERE operation_id=?").get(operation.operationId),outreach:repo.native.prepare("SELECT * FROM manual_outreach_records WHERE id='history-outreach'").get(),audit:repo.native.prepare("SELECT * FROM manual_outreach_audit WHERE manual_outreach_id='history-outreach'").all()});review(repo,candidate,"trusted-operating",0,"history-trust-one");const after=JSON.stringify({candidate:repo.native.prepare("SELECT * FROM imported_candidates WHERE id=?").get(candidate.id),gmail:repo.native.prepare("SELECT * FROM gmail_draft_operations WHERE operation_id=?").get(operation.operationId),outreach:repo.native.prepare("SELECT * FROM manual_outreach_records WHERE id='history-outreach'").get(),audit:repo.native.prepare("SELECT * FROM manual_outreach_audit WHERE manual_outreach_id='history-outreach'").all()});expect(after).toBe(before);}finally{repo.close();}});

  it("preserves curated exact ID+domain trust and rejects target membership alone",()=>{const repo=repository();try{seedTargetCompanyRegistry(repo);const curated=add(repo,source("curated-domain","Microsoft",{domain:"microsoft.com",providerId:"apollo-microsoft"}),{microsoft:"microsoft.com"});expect(curated).toMatchObject({state:"eligible",strategyCompanyMatch:{companyId:"microsoft",method:"domain"},employerTrust:{state:"trusted-operating",sourceKind:"authoritative-curated-registry"}});const disallow=reviewCompanyTrust(repo,{...command(curated,"disallowed-recruiting-service",0,"curated-disallow-one"),identity:{employerDomain:"microsoft.com"}});expect(disallow.event.previousTrustState).toBe("trusted-operating");expect(repo.resolveCompanyTrust({companyId:"microsoft",employerDomain:"microsoft.com"})).toMatchObject({state:"disallowed-recruiting-service",sourceKind:"audited-human-review"});repo.native.prepare("INSERT INTO target_companies(id,canonical_name,industry_id,company_tier,enabled,recognition_score,career_upside_score,technical_interest_score,geographic_relevance_json,rationale,provenance,last_reviewed_date,operator_notes) VALUES('mixed-row','Mixed Row','technology-ai','tier-2',1,50,50,50,'[]','x','authorized-provider-discovery','2026-09-30','x')").run();expect(repo.resolveCompanyTrust({companyId:"mixed-row"})).toMatchObject({state:"unverified",identityVerified:false});}finally{repo.close();}});
});
