import {describe,expect,it} from "vitest";
import {migrateTestDatabase} from "./test-migrations";
import {SqliteSimulationRepository} from "./database";
import {importCandidateBatch} from "@/application/ingestion";
import {reviewCompanyTrust} from "@/application/company-trust";
import {planRecruiterCandidates} from "@/domain/recruiters";
import type {CandidateSourceRecord} from "@/domain/candidates";
import {seedTargetCompanyRegistry} from "./seed";
import {approveForGmailDraft,type ApprovedEmailDraftSnapshot} from "@/application/email-drafts";

const at=new Date("2026-09-30T12:00:00.000Z");
const source=(id:string,name:string,identity:{domain?:string;providerId?:string},title="Technical Recruiter"):CandidateSourceRecord=>({sourceProviderId:"apollo",providerRecordId:id,datasetClassification:"authorized-provider",person:{firstName:"Fixture",lastName:"Recruiter"},currentTitle:title,currentOrganization:{name,...identity},location:"United States",industrySignals:["Software"],experienceEvidence:[{kind:"exact",years:7,sourceField:"fixture"}],email:{address:`${id}@example.invalid`,verificationStatus:"verified"},sourceTimestamps:{retrievedAt:at.toISOString()},fieldProvenance:{},consent:{suppressed:false,optedOut:false},sourceFingerprint:`company-trust-${id}-fingerprint`,providerMetadata:{adapterVersion:"fixture",responseMappingVersion:"fixture",requestContractVersion:"fixture",importArchitectureVersion:"fixture",matchConfidence:"high"}});
const repository=()=>{const value=new SqliteSimulationRepository(":memory:");migrateTestDatabase(value);return value;};
const add=(repo:SqliteSimulationRepository,record:CandidateSourceRecord,domains:Record<string,string>={})=>{importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:`trust-batch-${record.providerRecordId}`,adapterId:"apollo",adapterVersion:"fixture",datasetClassification:"authorized-provider",sourceFingerprint:`trust-batch-${record.providerRecordId}-fingerprint`,records:[record],strategyCompanyDomains:domains,authorizedProviderAccess:{enabled:true,providerId:"apollo"}},at);return repo.findImportedCandidate("apollo",record.providerRecordId)!;};
const review=(repo:SqliteSimulationRepository,companyId:string,resultingTrustState:"unverified"|"trusted-operating"|"disallowed-recruiting-service",expectedVersion:number,commandId:string)=>reviewCompanyTrust(repo,{commandId,companyId,expectedVersion,resultingTrustState,reason:`Reviewed ${resultingTrustState}`,reviewerActor:"local-operator",sourceReference:"operator://company-review/fixture",at:new Date(at.getTime()+expectedVersion*1000)});

describe("audited company trust persistence",()=>{
  it("keeps provider-only recruiters review-required until exact-company human trust exists",()=>{const repo=repository();try{const first=add(repo,source("provider-one","Ordinary Software",{domain:"ordinary.example",providerId:"org-one"}));expect(first).toMatchObject({state:"review-required",employerTrust:{state:"unverified",sourceKind:"provider-discovery-default"},recruiterClassification:{accepted:false},gateFailures:expect.arrayContaining(["company-trust-unverified"])});expect(planRecruiterCandidates(repo.listImportedCandidates(),new Set(),new Set())).toHaveLength(0);const companyId=first.strategyCompanyMatch!.companyId;review(repo,companyId,"trusted-operating",0,"trust-command-one");const projected=repo.findImportedCandidate("apollo","provider-one")!;expect(projected).toMatchObject({state:"eligible",employerTrust:{state:"trusted-operating",sourceKind:"audited-human-review",version:1},recruiterClassification:{accepted:true,internalStatus:"internal"}});expect(planRecruiterCandidates(repo.listImportedCandidates(),new Set(),new Set())).toHaveLength(1);const stored=JSON.parse((repo.native.prepare("SELECT normalized_snapshot_json value FROM imported_candidates WHERE id=?").get(projected.id) as {value:string}).value) as typeof projected;expect(stored.employerTrust?.state).toBe("unverified");}finally{repo.close();}});

  it("reuses trust for the same stable identity but not similar names, different domains, or different provider IDs",()=>{const repo=repository();try{const first=add(repo,source("identity-one","Acme Systems",{domain:"acme.example",providerId:"org-acme"})),companyId=first.strategyCompanyMatch!.companyId;review(repo,companyId,"trusted-operating",0,"identity-trust-one");expect(add(repo,source("identity-two","Acme Systems",{domain:"acme.example",providerId:"org-other"}))).toMatchObject({state:"eligible",employerTrust:{state:"trusted-operating"}});expect(add(repo,source("identity-three","Acme Systems",{domain:"other.example",providerId:"org-acme"}))).toMatchObject({state:"review-required",employerTrust:{state:"unverified"}});expect(add(repo,source("identity-four","Acme System",{providerId:"org-other"}))).toMatchObject({state:"review-required",employerTrust:{state:"unverified"}});expect(add(repo,source("identity-five","Acme Systems",{providerId:"org-different"}))).toMatchObject({state:"review-required",employerTrust:{state:"unverified",identityVerified:false}});}finally{repo.close();}});

  it("supports disallow and later corrections while preserving every audit event",()=>{const repo=repository();try{const candidate=add(repo,source("correction-one","Correction Software",{domain:"correction.example"})),companyId=candidate.strategyCompanyMatch!.companyId;review(repo,companyId,"trusted-operating",0,"correction-command-one");review(repo,companyId,"disallowed-recruiting-service",1,"correction-command-two");expect(repo.findImportedCandidate("apollo","correction-one")).toMatchObject({state:"rejected",employerTrust:{state:"disallowed-recruiting-service"},gateFailures:expect.arrayContaining(["company-trust-disallowed"])});review(repo,companyId,"trusted-operating",2,"correction-command-three");expect(repo.findImportedCandidate("apollo","correction-one")).toMatchObject({state:"eligible",employerTrust:{state:"trusted-operating",version:3}});const history=repo.native.prepare("SELECT previous_trust_state previous,resulting_trust_state result,resulting_version version FROM company_trust_audit WHERE company_id=? ORDER BY resulting_version").all(companyId);expect(history).toEqual([{previous:"unverified",result:"trusted-operating",version:1},{previous:"trusted-operating",result:"disallowed-recruiting-service",version:2},{previous:"disallowed-recruiting-service",result:"trusted-operating",version:3}]);expect(()=>repo.native.prepare("UPDATE company_trust_audit SET reason='rewritten'").run()).toThrow("company-trust-audit-append-only");expect(()=>repo.native.prepare("DELETE FROM company_trust_audit").run()).toThrow("company-trust-audit-append-only");}finally{repo.close();}});

  it("is idempotent by command identity and rejects conflicting replay and stale versions",()=>{const repo=repository();try{const companyId=add(repo,source("replay-one","Replay Software",{domain:"replay.example"})).strategyCompanyMatch!.companyId;const result=review(repo,companyId,"trusted-operating",0,"replay-command-one"),replay=review(repo,companyId,"trusted-operating",0,"replay-command-one");expect(result.replayed).toBe(false);expect(replay).toMatchObject({replayed:true,event:{id:result.event.id,resultingVersion:1}});expect(repo.native.prepare("SELECT COUNT(*) count FROM company_trust_audit").get()).toEqual({count:1});expect(()=>reviewCompanyTrust(repo,{commandId:"replay-command-one",companyId,expectedVersion:0,resultingTrustState:"disallowed-recruiting-service",reason:"Different payload",reviewerActor:"local-operator",sourceReference:"operator://company-review/fixture",at})).toThrow("company-trust-command-conflict");expect(()=>review(repo,companyId,"disallowed-recruiting-service",0,"stale-command-one")).toThrow("company-trust-stale-version");}finally{repo.close();}});

  it("does not rewrite candidate imports, Gmail snapshots, or outreach history",()=>{const repo=repository();try{const candidate=add(repo,source("history-one","History Software",{domain:"history.example"})),companyId=candidate.strategyCompanyMatch!.companyId,snapshot:ApprovedEmailDraftSnapshot={snapshotId:"history-approved-snapshot",recipientProfessionalEmail:"history@example.invalid",recipientDisplayName:"Fixture Recruiter",subject:"Historical subject",body:"Historical approved body",planningSnapshotId:`daily-command-center:${candidate.id}`,templateCatalogVersion:"historical-fixture",evidenceIds:[],approvedAt:at.toISOString(),outreachTrack:"recruiter",candidateId:candidate.id,companyId,companyDisplayName:"History Software",professionalTitle:"Technical Recruiter"};const operation=approveForGmailDraft(repo,snapshot,"fixture");repo.createManualOutreach({id:"history-outreach",draftSnapshotId:snapshot.snapshotId,gmailOperationId:operation.operationId,candidateId:candidate.id,companyId,identitySource:"imported-candidate",confirmationSource:"operator",confirmedAt:at.toISOString(),effectiveSentAt:at.toISOString(),outcome:"awaiting-response",operationVersion:"fixture",createdAt:at.toISOString(),updatedAt:at.toISOString(),outreachTrack:"recruiter"});const before=JSON.stringify({candidate:repo.native.prepare("SELECT * FROM imported_candidates WHERE id=?").get(candidate.id),gmail:repo.native.prepare("SELECT * FROM gmail_draft_operations WHERE operation_id=?").get(operation.operationId),outreach:repo.native.prepare("SELECT * FROM manual_outreach_records WHERE id='history-outreach'").get(),audit:repo.native.prepare("SELECT * FROM manual_outreach_audit WHERE manual_outreach_id='history-outreach'").all()});review(repo,companyId,"trusted-operating",0,"history-trust-one");const after=JSON.stringify({candidate:repo.native.prepare("SELECT * FROM imported_candidates WHERE id=?").get(candidate.id),gmail:repo.native.prepare("SELECT * FROM gmail_draft_operations WHERE operation_id=?").get(operation.operationId),outreach:repo.native.prepare("SELECT * FROM manual_outreach_records WHERE id='history-outreach'").get(),audit:repo.native.prepare("SELECT * FROM manual_outreach_audit WHERE manual_outreach_id='history-outreach'").all()});expect(after).toBe(before);expect(repo.findImportedCandidate("apollo","history-one")).toMatchObject({state:"eligible",employerTrust:{state:"trusted-operating"}});}finally{repo.close();}});

  it("accepts the exact curated registry identity but not a mixed target row or exact display name alone",()=>{const repo=repository();try{seedTargetCompanyRegistry(repo);expect(add(repo,source("curated-domain","Microsoft",{domain:"microsoft.com",providerId:"apollo-microsoft"}),{microsoft:"microsoft.com"})).toMatchObject({state:"eligible",strategyCompanyMatch:{companyId:"microsoft",method:"domain"},employerTrust:{state:"trusted-operating",sourceKind:"authoritative-curated-registry"}});expect(add(repo,source("curated-name","Microsoft",{providerId:"unverified-microsoft"}))).toMatchObject({state:"review-required",strategyCompanyMatch:{companyId:"microsoft",method:"exact-name"},employerTrust:{state:"unverified",identityVerified:false}});const disallow=review(repo,"microsoft","disallowed-recruiting-service",0,"curated-disallow-one");expect(disallow.event.previousTrustState).toBe("trusted-operating");expect(repo.resolveCompanyTrust({companyId:"microsoft",employerDomain:"microsoft.com"})).toMatchObject({state:"disallowed-recruiting-service",sourceKind:"audited-human-review"});repo.native.prepare("INSERT INTO target_companies(id,canonical_name,industry_id,company_tier,enabled,recognition_score,career_upside_score,technical_interest_score,geographic_relevance_json,rationale,provenance,last_reviewed_date,operator_notes) VALUES('mixed-row','Mixed Row','technology-ai','tier-2',1,50,50,50,'[]','x','Headquarters-approved Milestone 3 starting registry','2026-09-30','x')").run();expect(repo.resolveCompanyTrust({companyId:"mixed-row"})).toMatchObject({state:"unverified",identityVerified:false});}finally{repo.close();}});

  it.each(["neutralrpopeople.example","jobs.staffing.example"])("keeps provider-only domain evidence %s supporting-only",(domain)=>{const repo=repository();try{const candidate=add(repo,source(`domain-${domain.replaceAll(".","-")}`,"Neutral Technology",{domain,providerId:`org-${domain}`}));expect(candidate.state).not.toBe("eligible");expect(candidate.employerTrust?.state).toBe("unverified");}finally{repo.close();}});
});
