import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {SqliteSimulationRepository} from "./database";
import {recordDraftDisposition,SqliteDailyRefreshRepository} from "./daily-refresh";
import type {DailyRefreshResult} from "@/application/daily-refresh";
import {SqliteCandidateRefreshRepository} from "./candidate-refresh";

const dirs:string[]=[];
afterEach(()=>{for(const dir of dirs.splice(0))rmSync(dir,{recursive:true,force:true});});
describe("SQLite daily refresh persistence",()=>{
  it("persists generations and returns the latest campaign-day result",()=>{const dir=mkdtempSync(join(tmpdir(),"np-refresh-"));dirs.push(dir);const repository=new SqliteSimulationRepository(join(dir,"test.sqlite"));try{repository.migrate();const store=new SqliteDailyRefreshRepository(repository.native),base:DailyRefreshResult={id:"2026-09-15:1",campaignDate:"2026-09-15",generation:1,createdAt:"2026-09-15T12:00:00Z",candidateIds:["a"],professionalCount:1,recruiterCount:0,target:15,shortfall:14,reserveCount:1,providerUsed:false,enrichmentAttempts:0,creditBefore:null,creditAfter:null,warning:null};store.save(base);store.save({...base,id:"2026-09-15:2",generation:2,candidateIds:["b"]});expect(store.findLatest("2026-09-15")?.candidateIds).toEqual(["b"]);}finally{repository.close();}});
  it("persists completion-pass refresh accounting through migration 0016",()=>{const dir=mkdtempSync(join(tmpdir(),"np-candidate-refresh-"));dirs.push(dir);const repository=new SqliteSimulationRepository(join(dir,"test.sqlite"));try{repository.migrate();new SqliteCandidateRefreshRepository(repository.native).saveCandidateRefresh({id:"candidate-refresh:fixture",createdAt:"2026-09-18T12:00:00Z",usableBefore:20,target:40,deficit:20,providerCap:20,maximumProviderUsage:20,providerRequired:true,searchCalls:4,enrichmentCreditsUsed:9,candidatesAdded:9,qualifiedCandidatesAdded:5,professionalCandidatesAdded:3,recruiterCandidatesAdded:2,companiesAdded:5,usableAfter:25});expect(repository.native.prepare("SELECT professional_candidates_added,recruiter_candidates_added,companies_added FROM candidate_refresh_events").get()).toEqual({professional_candidates_added:3,recruiter_candidates_added:2,companies_added:5});}finally{repository.close();}});
  it("records skip without contact or cooldown and permanent exclusion as candidate-only suppression",()=>{const dir=mkdtempSync(join(tmpdir(),"np-disposition-")),path=join(dir,"test.sqlite"),prior=process.env.NETWORKPILOT_MANUAL_OUTREACH_DATABASE_PATH;dirs.push(dir);process.env.NETWORKPILOT_MANUAL_OUTREACH_DATABASE_PATH=path;const repository=new SqliteSimulationRepository(path);try{repository.migrate();new SqliteDailyRefreshRepository(repository.native).save({id:"2026-09-18:1",campaignDate:"2026-09-18",generation:1,createdAt:"2026-09-18T11:00:00Z",candidateIds:["candidate-skip","candidate-never"],professionalCount:2,recruiterCount:0,target:2,shortfall:0,reserveCount:2,providerUsed:false,enrichmentAttempts:0,creditBefore:null,creditAfter:null,warning:null});recordDraftDisposition({candidateId:"candidate-skip",permanent:false,now:()=>new Date("2026-09-18T12:00:00Z")});recordDraftDisposition({candidateId:"candidate-never",permanent:true,now:()=>new Date("2026-09-18T12:01:00Z")});expect(repository.native.prepare("SELECT candidate_id,disposition FROM draft_dispositions ORDER BY candidate_id").all()).toEqual([{candidate_id:"candidate-never",disposition:"permanently-excluded"},{candidate_id:"candidate-skip",disposition:"skipped"}]);expect(repository.native.prepare("SELECT candidate_id,reason FROM candidate_suppression_entries").all()).toEqual([{candidate_id:"candidate-never",reason:"operator-do-not-show-again"}]);expect(repository.native.prepare("SELECT COUNT(*) count FROM manual_outreach_records").get()).toEqual({count:0});expect(repository.listOutreachEvents()).toEqual([]);}finally{repository.close();if(prior===undefined)delete process.env.NETWORKPILOT_MANUAL_OUTREACH_DATABASE_PATH;else process.env.NETWORKPILOT_MANUAL_OUTREACH_DATABASE_PATH=prior;}});
  it("refuses a disposition for a candidate outside the active campaign",()=>{const dir=mkdtempSync(join(tmpdir(),"np-disposition-invalid-")),path=join(dir,"test.sqlite"),prior=process.env.NETWORKPILOT_MANUAL_OUTREACH_DATABASE_PATH;dirs.push(dir);process.env.NETWORKPILOT_MANUAL_OUTREACH_DATABASE_PATH=path;const repository=new SqliteSimulationRepository(path);try{repository.migrate();expect(()=>recordDraftDisposition({candidateId:"not-active",permanent:false,now:()=>new Date("2026-09-18T12:00:00Z")})).toThrow("draft-disposition-candidate-unavailable");expect(repository.native.prepare("SELECT COUNT(*) count FROM draft_dispositions").get()).toEqual({count:0});}finally{repository.close();if(prior===undefined)delete process.env.NETWORKPILOT_MANUAL_OUTREACH_DATABASE_PATH;else process.env.NETWORKPILOT_MANUAL_OUTREACH_DATABASE_PATH=prior;}});
});
