import {readQueueCandidates,readDraftGenerations,draftIsDismissed} from "./draft-queue";
import {localCampaignDate} from "@/application/daily-refresh";
import Database from "better-sqlite3";
import {existsSync} from "node:fs";
import {resolve} from "node:path";
import {buildDailyCommandCenter,type DailyCommandCenterState,type ReserveCandidate} from "@/application/daily-command-center";
import type {ImportedCandidateSnapshot} from "@/application/ingestion";
import {listManualDraftOperatorEntries,resolveManualOutreachDatabaseSelection} from "./manual-outreach-operator";
import {readApolloConfig} from "@/infrastructure/providers/apollo/config";
import {renderRecruiterDraft} from "@/domain/recruiters";
import {prepareControlledRealCampaign} from "@/application/providers/prepare-controlled-real-campaign";

const redact=(first:string,last:string)=>`${first[0]??"?"}***${last?` ${last[0]}.`:""}`;
export const RECRUITER_OPERATIONAL_DATABASE="data/apollo-recruiter-enrichment.sqlite" as const;
export function loadDailyCommandCenter(at=new Date()):DailyCommandCenterState{
  let selected;try{selected=resolveManualOutreachDatabaseSelection();}catch{const fallback=resolve(/*turbopackIgnore: true*/ process.cwd(),process.env.NETWORKPILOT_DATABASE_PATH??"data/networkpilot.sqlite");if(!existsSync(/*turbopackIgnore: true*/ fallback))return buildDailyCommandCenter({drafts:[],reserve:[],gmailState:"not-configured",apolloEnabled:false,apolloExposure:0,apolloObserved:null,cooldownCompanies:0});selected={path:fallback};}
  const drafts=listManualDraftOperatorEntries(selected.path),db=new Database(selected.path,{readonly:true,fileMustExist:true});
  try{
    const now=at.getTime(),cooldownCutoff=new Date(now-7*86400000).toISOString(),today=at.toLocaleDateString("en-CA",{timeZone:"America/New_York"});
    const contacted=new Set((db.prepare("SELECT candidate_id FROM manual_outreach_records").all() as {candidate_id:string}[]).map((r)=>r.candidate_id));
    const cooldown=new Set((db.prepare("SELECT company_id,outcome,effective_sent_at_utc FROM manual_outreach_records WHERE effective_sent_at_utc>=?").all(cooldownCutoff) as {company_id:string;outcome:string;effective_sent_at_utc:string}[]).filter(r=>r.outcome!=="hard-bounce"||new Date(r.effective_sent_at_utc).toLocaleDateString("en-CA",{timeZone:"America/New_York"})===today).map(r=>r.company_id));
    const suppressed=new Set((db.prepare("SELECT candidate_id FROM candidate_suppression_entries").all() as {candidate_id:string}[]).map((r)=>r.candidate_id));
    const rows=readQueueCandidates(db).map(c=>({normalized_snapshot_json:JSON.stringify(c),lifecycle_state:c.state})),planned=new Set(readDraftGenerations(db).flatMap(g=>[...g.candidateIds,...(g.carriedDraftReviews??[]).map(r=>r.candidateId)].filter(id=>g.campaignDate===localCampaignDate(at)||!draftIsDismissed(db,id,g.campaignDate)))),operationPeople=new Set((db.prepare("SELECT approved_snapshot_json FROM gmail_draft_operations WHERE send_state!='sent'").all() as {approved_snapshot_json:string}[]).map(row=>(JSON.parse(row.approved_snapshot_json) as {candidateId:string}).candidateId));
    const mapped:ReserveCandidate[]=rows.map((row)=>{const c=JSON.parse(row.normalized_snapshot_json) as ImportedCandidateSnapshot,track=c.outreachTrack??"professional",companyId=c.strategyCompanyMatch?.companyId??"",companyKind=c.strategyCompanyMatch?.method==="discovered-provider"?"discovered" as const:"preferred" as const,recruiterDraft=track==="recruiter"&&c.recruiterClassification?.accepted?renderRecruiterDraft({firstName:c.source.person.firstName,company:c.source.currentOrganization.name,title:c.source.currentTitle,classification:c.recruiterClassification}):null,planningReady=track==="recruiter"?Boolean(recruiterDraft):prepareControlledRealCampaign([c],{target:1}).drafts.length===1;let stage:ReserveCandidate["stage"]=c.state==="eligible"&&!c.source.consent.optedOut&&c.source.email.verificationStatus==="verified"&&c.gateFailures.length===0&&planningReady?"qualified-available":row.lifecycle_state==="eligible"?"enriched-unqualified":"search-only";if(planned.has(c.id)||operationPeople.has(c.id)||draftIsDismissed(db,c.id,localCampaignDate(at)))stage="in-draft-queue";if(contacted.has(c.id))stage="already-contacted";else if(suppressed.has(c.id)||c.source.consent.suppressed||c.source.consent.optedOut)stage="suppressed";else if(cooldown.has(companyId))stage="cooldown";return{id:c.id,recipient:redact(c.source.person.firstName,c.source.person.lastName),company:c.source.currentOrganization.name,companyId,companyKind,title:c.source.currentTitle,industry:c.source.industrySignals[0]??"Unclassified",geography:c.source.location,functionName:track==="recruiter"?c.recruiterClassification?.recruitingDomain??"recruiting":c.recipientFunction.primaryFunction,persona:c.personaId??"unclassified",score:track==="recruiter"?c.recruiterClassification?.score??0:c.dataQualityScore,stage,planningReady,track,recruiterType:c.recruiterClassification?.recruiterType,recruitingDomain:c.recruiterClassification?.recruitingDomain,technicalRecruiting:c.recruiterClassification?.technicalRelevance,earlyCareerRecruiting:c.recruiterClassification?.earlyCareerRelevance,whySelected:track==="recruiter"?c.recruiterClassification?.earlyCareerRelevance&&c.recruiterClassification.technicalRelevance?"Internal early-career technology recruiter at a reviewed target company.":c.recruiterClassification?.technicalRelevance?"Internal technical recruiter at a reviewed target company.":c.recruiterClassification?.earlyCareerRelevance?"Internal early-career recruiter at a reviewed target company.":"Internal recruiter at a reviewed target company.":undefined,draftSubject:recruiterDraft?.subject,draftBody:recruiterDraft?.body,draftWordCount:recruiterDraft?.wordCount};}),byPerson=new Map<string,ReserveCandidate>();for(const candidate of mapped){const prior=byPerson.get(candidate.id);if(!prior||candidate.track==="recruiter")byPerson.set(candidate.id,candidate);}const reserve=[...byPerson.values()];
    const gmail=db.prepare("SELECT connection_state FROM gmail_connection_metadata WHERE provider='gmail'").get() as {connection_state:string}|undefined;
    const budget=db.prepare("SELECT estimated_max_exposure,observed_consumption FROM provider_daily_budgets WHERE provider_id='apollo' AND local_date=?").get(today) as {estimated_max_exposure:number;observed_consumption:number|null}|undefined,apollo=readApolloConfig(process.env);
    return buildDailyCommandCenter({drafts,reserve,gmailState:gmail?.connection_state??"not-configured",apolloEnabled:apollo.enabled,apolloReady:apollo.enabled&&Boolean(apollo.apiKey?.trim()),apolloExposure:budget?.estimated_max_exposure??0,apolloObserved:budget?.observed_consumption??null,cooldownCompanies:cooldown.size});
  }finally{db.close();}
}
