import{mkdtempSync,rmSync,readFileSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import{afterEach,describe,expect,it}from"vitest";
import{generateDraftsForRun}from"@/application/drafts";import{runDailySimulation}from"@/application/simulation/run-daily-simulation";import{TARGET_COMPANIES}from"@/domain/targeting";import{SqliteSimulationRepository}from"./database";import{seedFictionalData}from"./seed";
const dirs:string[]=[];function setup(){const dir=mkdtempSync(join(tmpdir(),"networkpilot-drafts-"));dirs.push(dir);const repo=new SqliteSimulationRepository(join(dir,"test.sqlite"));repo.migrate();seedFictionalData(repo);const run=runDailySimulation(repo,{instant:new Date("2026-09-07T15:00:00Z"),random:()=>0});return{repo,run};}afterEach(()=>{while(dirs.length)rmSync(dirs.pop()!,{recursive:true,force:true});});
describe("draft persistence",()=>{
 it("creates the draft schema and separate public company registry",()=>{const{repo}=setup();const tables=(repo.native.prepare("SELECT name FROM sqlite_master WHERE type='table'").all()as Array<{name:string}>).map((r)=>r.name);expect(tables).toEqual(expect.arrayContaining(["drafts","personalization_evidence","target_companies"]));expect(repo.listTargetCompanies()).toHaveLength(TARGET_COMPANIES.length);const columns=(repo.native.prepare("PRAGMA table_info(target_companies)").all()as Array<{name:string}>).map((r)=>r.name);expect(columns.some((name)=>/person|email|contact/i.test(name))).toBe(false);repo.close();});
 it("generates idempotent versioned drafts with historical score and template snapshots",()=>{const{repo,run}=setup();const first=generateDraftsForRun(repo,run.id,()=>new Date("2026-09-07T16:00:00Z"));const second=generateDraftsForRun(repo,run.id,()=>new Date("2026-09-08T16:00:00Z"));expect(first).toHaveLength(15);expect(second.map((d)=>d.id)).toEqual(first.map((d)=>d.id));expect(repo.listDrafts()).toHaveLength(15);expect(second[0]).toMatchObject({templateVersion:"1.0.0",scoreVersion:"targeting-v1",score:first[0].score,createdAt:"2026-09-07T16:00:00.000Z"});repo.close();});
 it("persists approval and rejection as simulation-only lifecycle states",()=>{const{repo,run}=setup();const drafts=generateDraftsForRun(repo,run.id,()=>new Date());repo.updateDraftStatus(drafts[0].id,"approved-for-simulation",new Date("2026-09-08T00:00:00Z"));repo.updateDraftStatus(drafts[1].id,"rejected",new Date("2026-09-08T00:00:00Z"));expect(repo.listDrafts({status:"approved-for-simulation"})).toHaveLength(1);expect(repo.listDrafts({status:"rejected"})).toHaveLength(1);expect(()=>repo.native.prepare("UPDATE drafts SET status='sent' WHERE id=?").run(drafts[0].id)).toThrow();repo.close();});
 it("rejects missing or non-completed run contexts",()=>{const{repo}=setup();expect(()=>generateDraftsForRun(repo,"missing-run",()=>new Date())).toThrow("Completed fictional simulation run not found");expect(repo.listDrafts()).toEqual([]);repo.close();});
 it("retains evidence IDs only for verified fictional evidence",()=>{const{repo,run}=setup();const drafts=generateDraftsForRun(repo,run.id,()=>new Date());for(const draft of drafts){const evidence=repo.listEvidence(draft.prospectId).filter((e)=>e.verificationStatus==="verified");expect(draft.evidenceIds).toEqual(evidence.slice(0,1).map((e)=>e.id));}repo.close();});
 it("keeps drafts attached only to fictional prospects and never public registry employers",()=>{const{repo,run}=setup();generateDraftsForRun(repo,run.id,()=>new Date());const invalid=(repo.native.prepare("SELECT COUNT(*) count FROM drafts d JOIN prospects p ON p.id=d.prospect_id WHERE p.fictional<>1").get()as{count:number}).count;expect(invalid).toBe(0);const fictionalEmployers=new Set(repo.listProspects().map((p)=>p.companyName));expect(repo.listTargetCompanies().some((company)=>fictionalEmployers.has(company.canonicalName))).toBe(false);repo.close();});
 it("contains no delivery schema or implementation",()=>{const migration=readFileSync(join(process.cwd(),"migrations/0002_targeting_and_drafts.sql"),"utf8").toLowerCase();expect(migration).not.toContain("sent status");expect(migration).not.toContain("email delivery");expect(migration).not.toContain("provider");});
});
