import { afterEach, describe, expect, it } from "vitest";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { importCandidateBatch } from "@/application/ingestion";
import { adaptFlatFixture, FLAT_FIXTURES } from "@/infrastructure/fixtures/provider-fixtures";
import { SqliteSimulationRepository } from "./database";
import { seedFictionalData } from "./seed";

const dirs:string[]=[];
const repository=()=>{const dir=mkdtempSync(join(tmpdir(),"networkpilot-import-"));dirs.push(dir);const repo=new SqliteSimulationRepository(join(dir,"test.sqlite"));repo.migrate();return repo;};
afterEach(()=>{for(const dir of dirs.splice(0))rmSync(dir,{recursive:true,force:true});});

describe("provider-independent import and review",()=>{
  it("persists both fixture batches idempotently",()=>{const repo=repository();seedFictionalData(repo);expect(repo.listImportedCandidates()).toHaveLength(6);const before=(repo.native.prepare("SELECT COUNT(*) count FROM import_batches").get() as {count:number}).count;seedFictionalData(repo);expect((repo.native.prepare("SELECT COUNT(*) count FROM import_batches").get() as {count:number}).count).toBe(before);repo.close();});
  it("fails conflicting identities and malformed records without partial writes",()=>{const repo=repository();seedFictionalData(repo);const base=adaptFlatFixture(FLAT_FIXTURES[0]);expect(()=>importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:"conflict-batch",adapterId:"fictional-flat",adapterVersion:"1",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"conflict-batch-fingerprint",records:[base,{...base,sourceFingerprint:"different-fingerprint"}]})).toThrow("source-record-conflict");expect(repo.findImportBatchByFingerprint("conflict-batch-fingerprint")).toBeNull();expect(()=>importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:"bad",adapterId:"fictional-flat",adapterVersion:"1",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"bad",records:[]})).toThrow("import-identity-invalid");repo.close();});
  it("audits corrections, materializes eligibility, and refuses hard-gate overrides",()=>{const repo=repository();seedFictionalData(repo);const blocked=repo.listImportedCandidates().find((item)=>item.source.providerRecordId==="flat-002")!;expect(()=>repo.reviewCandidate(blocked.id,"correct","try override","data-analyst",new Date())).toThrow("hard-gate-not-overridable");const pendingSource={...adaptFlatFixture(FLAT_FIXTURES[0]),providerRecordId:"flat-review",currentTitle:"Analyst",email:{address:"flat.review@example.test",verificationStatus:"verified" as const},sourceFingerprint:"flat-review-fingerprint"};importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:"review-batch",adapterId:"fictional-flat",adapterVersion:"1",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"review-batch-fingerprint",records:[pendingSource]});const pending=repo.findImportedCandidate("fictional-flat","flat-review")!;expect(pending.state).toBe("review-required");repo.reviewCandidate(pending.id,"correct","operator resolved exact supplied title","data-analyst",new Date("2026-09-08T14:00:00Z"));expect(repo.findImportedCandidate("fictional-flat","flat-review")).toMatchObject({state:"eligible",reviewState:"corrected",classification:{specificRoleId:"data-analyst",roleFamilyId:"data-analytics"}});expect(repo.listCandidateSourceRecords().some((item)=>item.input.internalId===pending.id)).toBe(true);expect(repo.listReviewAudit(pending.id)[0]).toMatchObject({action:"correct",reason:"operator resolved exact supplied title"});repo.close();});
  it("keeps automatically eligible fixture records in the existing planning source",()=>{const repo=repository();seedFictionalData(repo);const imported=repo.listCandidateSourceRecords().find((item)=>item.input.internalId.includes("fictional-flat:flat-001"));expect(imported).toMatchObject({input:{professionalTitle:"Data Engineer",emailVerificationStatus:"verified"},suppliedClassification:{desiredRoleId:"data-engineer"}});repo.close();});
});
