import { afterEach, describe, expect, it } from "vitest";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { importCandidateBatch } from "@/application/ingestion";
import { adaptFlatFixture, FLAT_FIXTURES } from "@/infrastructure/fixtures/provider-fixtures";
import { SqliteSimulationRepository } from "./database";
import { seedFictionalData } from "./seed";

const dirs:string[]=[];
const repository=()=>{const dir=mkdtempSync(join(tmpdir(),"networkpilot-import-"));dirs.push(dir);const repo=new SqliteSimulationRepository(join(dir,"test.sqlite"));repo.migrate();return repo;};
afterEach(()=>{for(const dir of dirs.splice(0))rmSync(dir,{recursive:true,force:true});});

describe("provider-independent import and review",()=>{
  it("persists both fixture batches idempotently",()=>{const repo=repository();seedFictionalData(repo);expect(repo.listImportedCandidates()).toHaveLength(6);const before=(repo.native.prepare("SELECT COUNT(*) count FROM import_batches").get() as {count:number}).count;seedFictionalData(repo);expect((repo.native.prepare("SELECT COUNT(*) count FROM import_batches").get() as {count:number}).count).toBe(before);repo.close();});
  it("fails conflicting identities and malformed records without partial candidate writes",()=>{const repo=repository();seedFictionalData(repo);const base=adaptFlatFixture(FLAT_FIXTURES[0]);expect(()=>importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:"conflict-batch",adapterId:"fictional-flat",adapterVersion:"1",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"conflict-batch-fingerprint",records:[base,{...base,sourceFingerprint:"different-fingerprint"}]})).toThrow("source-record-conflict");expect(repo.findImportBatchByFingerprint("conflict-batch-fingerprint")).toMatchObject({state:"failed",acceptedCount:0,failureReasonCodes:["source-record-conflict:fictional-flat:flat-001"]});expect(repo.listImportedCandidates().filter((item)=>item.batchId==="conflict-batch")).toHaveLength(0);expect(()=>importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:"bad",adapterId:"fictional-flat",adapterVersion:"1",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"bad",records:[]})).toThrow("import-identity-invalid");repo.close();});
  it("audits corrections, materializes eligibility, and refuses hard-gate overrides",()=>{const repo=repository();seedFictionalData(repo);const blocked=repo.listImportedCandidates().find((item)=>item.source.providerRecordId==="flat-002")!;expect(()=>repo.reviewCandidate(blocked.id,"correct","try override","data-analyst",new Date())).toThrow("hard-gate-not-overridable");const pendingSource={...adaptFlatFixture(FLAT_FIXTURES[0]),providerRecordId:"flat-review",currentTitle:"Analyst",email:{address:"flat.review@example.test",verificationStatus:"verified" as const},sourceFingerprint:"flat-review-fingerprint"};importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:"review-batch",adapterId:"fictional-flat",adapterVersion:"1",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"review-batch-fingerprint",records:[pendingSource]});const pending=repo.findImportedCandidate("fictional-flat","flat-review")!;expect(pending.state).toBe("review-required");const functionEvidence=structuredClone({classification:pending.recipientFunction,affinities:pending.targetRoleAffinities});repo.reviewCandidate(pending.id,"correct","operator resolved exact supplied title","data-analyst",new Date("2026-09-08T14:00:00Z"));const corrected=repo.findImportedCandidate("fictional-flat","flat-review")!;expect(corrected).toMatchObject({state:"eligible",reviewState:"corrected",classification:{specificRoleId:"data-analyst",roleFamilyId:"data-analytics"}});expect({classification:corrected.recipientFunction,affinities:corrected.targetRoleAffinities}).toEqual(functionEvidence);expect(corrected.recipientFunction.primaryFunction).toBe("unknown");expect(corrected.recipientRelevance.explanationCodes).toContain("primary-function-relevance:0");expect(repo.listCandidateSourceRecords().some((item)=>item.input.internalId===pending.id)).toBe(true);expect(repo.listReviewAudit(pending.id)[0]).toMatchObject({action:"correct",reason:"operator resolved exact supplied title"});repo.close();});
  it("keeps automatically eligible fixture records in the existing planning source",()=>{const repo=repository();seedFictionalData(repo);const imported=repo.listCandidateSourceRecords().find((item)=>item.input.internalId.includes("fictional-flat:flat-001"));expect(imported).toMatchObject({input:{professionalTitle:"Data Engineer",emailVerificationStatus:"verified"},suppliedClassification:{desiredRoleId:"data-engineer"}});repo.close();});
  it("persists safe aggregate provider-record rejection diagnostics without malformed raw data",()=>{const repo=repository();seedFictionalData(repo);const record=adaptFlatFixture(FLAT_FIXTURES[0]),batch=importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:"partial-provider-batch",adapterId:"fictional-flat",adapterVersion:"1",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"partial-provider-fingerprint",records:[record],providerRecordRejections:[{recordIndex:24,reason:"apollo-required-field-missing:person.last_name_obfuscated"}]});expect(batch).toMatchObject({recordCount:2,rejectedCount:1,validationOutcomes:expect.arrayContaining(["provider-record-rejections:1"]),failureReasonCodes:["apollo-required-field-missing:person.last_name_obfuscated"]});expect(batch.safeSourceSnapshot).not.toContain("last_name_obfuscated");repo.close();});
  it("corrects an exact target-role analogue without replacing independent recipient-function evidence",()=>{const repo=repository();seedFictionalData(repo);const source={...adaptFlatFixture(FLAT_FIXTURES[0]),providerRecordId:"function-review",currentTitle:"Analytics Program Manager",email:{address:"function.review@example.test",verificationStatus:"verified" as const},sourceFingerprint:"function-review-fingerprint"};importCandidateBatch(repo,repo.listTargetCompanies(),{batchId:"function-review-batch",adapterId:"fictional-flat",adapterVersion:"1",datasetClassification:"provider-shaped-fixture",sourceFingerprint:"function-review-batch-fingerprint",records:[source]});const before=repo.findImportedCandidate("fictional-flat","function-review")!;expect(before).toMatchObject({classification:{specificRoleId:null},recipientFunction:{primaryFunction:"project-program",secondaryFunctions:expect.arrayContaining(["data-analytics"]),confidence:"high"}});const evidence=structuredClone({recipientFunction:before.recipientFunction,targetRoleAffinities:before.targetRoleAffinities});repo.reviewCandidate(before.id,"correct","operator supplied independent exact-role analogue","project-manager",new Date("2026-09-08T15:00:00Z"));const after=repo.findImportedCandidate("fictional-flat","function-review")!;expect(after.classification).toMatchObject({specificRoleId:"project-manager",roleFamilyId:"business-delivery"});expect({recipientFunction:after.recipientFunction,targetRoleAffinities:after.targetRoleAffinities}).toEqual(evidence);expect(after.recipientRelevance.explanationCodes).toContain("precise-target-role-bonus");expect(repo.listReviewAudit(before.id)).toHaveLength(1);repo.close();});
});
