import Link from "next/link";
import {sentOutreach} from "@/application/product-workflow";
import {loadDailyCommandCenter} from "@/infrastructure/sqlite/daily-command-center";
import {ProductNav} from "@/app/product-nav";
import {recordOutcome} from "@/app/today/actions";
export const dynamic="force-dynamic";
const label=(value:string)=>({"awaiting-response":"Awaiting reply","replied":"Replied","meeting-scheduled":"Meeting","declined":"Declined","hard-bounce":"Bounced","opt-out":"Opt-out","no-response":"No response"}[value]??value.replaceAll("-"," "));
const elapsed=(sent:string|null)=>sent?`${Math.max(0,Math.floor((Date.now()-new Date(sent).getTime())/86400000))} days`:`—`;
const filters=["awaiting-response","replied","meeting-scheduled","declined","hard-bounce","opt-out"];
export default async function SentPage({searchParams}:{searchParams:Promise<{outcome?:string}>}){const params=await searchParams,all=sentOutreach(loadDailyCommandCenter().drafts),rows=params.outcome?all.filter((row)=>row.outcome===params.outcome):all;return <main><ProductNav current="sent"/><header className="product-header compact-header"><div><h1>Sent</h1><p>Contacted recipients and their latest outcome.</p></div><strong>{all.length} contacted</strong></header><section className="product-section"><nav className="crm-filters" aria-label="Outcome filters"><Link aria-current={!params.outcome?"page":undefined} href="/sent">All</Link>{filters.map((filter)=><Link aria-current={params.outcome===filter?"page":undefined} key={filter} href={`/sent?outcome=${filter}`}>{label(filter)}</Link>)}</nav>{rows.length===0?<div className="empty"><strong>No outreach sent yet.</strong><p>Sent messages will appear here automatically.</p></div>:<div className="table-wrap"><table><thead><tr><th>Person</th><th>Track</th><th>Sent</th><th>Outcome</th><th>Elapsed</th><th>Details</th></tr></thead><tbody>{rows.map((row)=><tr key={row.operatorId}><td>{row.redactedRecipient}<small>{row.title} · {row.company}</small></td><td>{row.outreachTrack??"professional"}</td><td>{row.effectiveSentAt?new Date(row.effectiveSentAt).toLocaleDateString():"—"}</td><td><span className="outcome-label">{label(row.outcome??"awaiting-response")}</span>{row.suppressed?<small>Suppressed</small>:null}</td><td>{elapsed(row.effectiveSentAt)}</td><td><details className="sent-details"><summary>View</summary><div><p><strong>Subject</strong><br/>{row.subject}</p><p><strong>Sent through</strong><br/>{row.confirmationSource==="networkpilot-gmail-send"?"NetworkPilot Gmail":"Manual confirmation"}</p>{row.outcome==="hard-bounce"?<p>Delivery failed. This address is suppressed.</p>:<form action={recordOutcome} className="compact-action"><input type="hidden" name="id" value={row.operatorId}/><label>Outcome<select name="outcome" defaultValue={row.outcome??"awaiting-response"}><option value="awaiting-response">Awaiting reply</option><option value="replied">Replied</option><option value="meeting-scheduled">Meeting</option><option value="declined">Declined</option><option value="opt-out">Opt-out</option><option value="no-response">No response</option></select></label><button>Update</button></form>}</div></details></td></tr>)}</tbody></table></div>}</section></main>}
