import Link from "next/link";
import {sentOutreach} from "@/application/product-workflow";
import {loadDailyCommandCenter} from "@/infrastructure/sqlite/daily-command-center";
import {ProductNav} from "@/app/product-nav";
import {recordOutcome} from "@/app/today/actions";
export const dynamic="force-dynamic";
const label=(value:string)=>value.replaceAll("-"," ");
const elapsed=(sent:string|null)=>sent?`${Math.max(0,Math.floor((Date.now()-new Date(sent).getTime())/86400000))} days`:`—`;
const filters=["awaiting-response","replied","meeting-scheduled","declined","hard-bounce","opt-out"];
export default async function SentPage({searchParams}:{searchParams:Promise<{outcome?:string}>}){const params=await searchParams,all=sentOutreach(loadDailyCommandCenter().drafts),rows=params.outcome?all.filter((row)=>row.outcome===params.outcome):all;return <main><ProductNav current="sent"/><header className="product-header"><div><h1>Sent</h1><p>Authoritative outreach history and human-reported outcomes.</p></div><strong>{rows.length} of {all.length} contacted</strong></header><section className="product-section"><nav className="crm-filters" aria-label="Outcome filters"><Link href="/sent">All</Link>{filters.map((filter)=><Link key={filter} href={`/sent?outcome=${filter}`}>{label(filter)}</Link>)}</nav><div className="table-wrap"><table><thead><tr><th>Recipient</th><th>Track</th><th>Sent</th><th>Provenance</th><th>Outcome</th><th>Elapsed</th><th>Update</th></tr></thead><tbody>{rows.map((row)=><tr key={row.operatorId}><td>{row.redactedRecipient}<small>{row.title} · {row.company}</small></td><td>{row.outreachTrack??"professional"}</td><td>{row.effectiveSentAt?new Date(row.effectiveSentAt).toLocaleString():"—"}</td><td>{row.confirmationSource==="networkpilot-gmail-send"?"NetworkPilot Gmail send":"Manual send confirmation"}</td><td>{label(row.outcome??"awaiting-response")}{row.suppressed?<small>Suppressed</small>:null}</td><td>{elapsed(row.effectiveSentAt)}</td><td>{row.outcome==="hard-bounce"?<span>Delivery failed</span>:<form action={recordOutcome} className="compact-action"><input type="hidden" name="id" value={row.operatorId}/><select name="outcome" defaultValue={row.outcome??"awaiting-response"}><option value="awaiting-response">Awaiting reply</option><option value="replied">Replied</option><option value="meeting-scheduled">Meeting</option><option value="declined">Declined</option><option value="opt-out">Opt-out</option><option value="no-response">No response</option></select><button>Update</button></form>}</td></tr>)}</tbody></table></div></section></main>}
