import {readFileSync} from "node:fs";
import {join} from "node:path";
import {renderToStaticMarkup} from "react-dom/server";
import {beforeEach,describe,expect,it,vi} from "vitest";
import type {RelationshipWorkspaceEntry} from "@/infrastructure/sqlite/relationship-workspace";
import SentPage from "./page";
const fixtures=vi.hoisted(()=>({rows:[] as RelationshipWorkspaceEntry[]}));
vi.mock("@/infrastructure/sqlite/relationship-workspace",()=>({loadRelationshipWorkspace:()=>fixtures.rows}));
vi.mock("@/app/today/actions",()=>({recordOutcome:vi.fn()}));
const entry:RelationshipWorkspaceEntry={operatorId:"npms-fictional",snapshotId:"fixture-snapshot",operationId:"fictional",redactedRecipient:"F*** P.",company:"Fictional company",title:"Product Analyst",subject:"Product work",body:"A privacy-safe fictional message.",gmailDraftCreated:true,gmailDraftCreatedAt:"2026-09-01T11:00:00Z",approvedAt:"2026-09-01T10:00:00Z",manualSendConfirmed:true,effectiveSentAt:"2026-09-01T12:00:00Z",outcome:"awaiting-response",suppressed:false,responseState:"awaiting-response",outreachTrack:"professional",confirmationSource:"operator",timeline:[{label:"Draft approved",at:"2026-09-01T10:00:00Z"},{label:"Sent",at:"2026-09-01T12:00:00Z"}]};
const render=async(outcome?:string)=>renderToStaticMarkup(await SentPage({searchParams:Promise.resolve({outcome})}));
const workspace=()=>readFileSync(join(process.cwd(),"src/app/sent/relationship-workspace.tsx"),"utf8");
describe("Network Command relationship memory",()=>{
  beforeEach(()=>{fixtures.rows=[{...entry}];});
  it("renders identity-first relationships and plain-language outcome filters",async()=>{const html=await render();for(const text of ["Relationship memory","F*** P.","Fictional company","Product Analyst","Awaiting reply","Bounced","Opt-out"])expect(html).toContain(text);expect(html).not.toContain("provider-confirmed");});
  it("distinguishes an empty filter from empty outreach history",async()=>{expect(await render("replied")).toContain("No relationships match this view.");fixtures.rows=[];expect(await render()).toContain("No outreach sent yet.");});
  it("keeps unconfirmed Gmail drafts out of Sent",async()=>{fixtures.rows=[{...entry,manualSendConfirmed:false}];expect(await render()).not.toContain("F*** P.");});
  it("provides a truthful message, timeline, suppression, provenance, and outcome inspector",()=>{const source=workspace(),projection=readFileSync(join(process.cwd(),"src/infrastructure/sqlite/relationship-workspace.ts"),"utf8");for(const text of ["Message sent","Timeline","Delivery failed. This address remains suppressed.","Operator-confirmed manual send","Current outcome","Update outcome"])expect(source).toContain(text);expect(projection).toContain("Draft approved");expect(source).not.toContain("provider-confirmed");});
  it("shows only attachment labels and never provider or storage identifiers",()=>{const source=workspace();expect(source).toContain("selected.resumeLabel");expect(source).not.toContain("storageKey");expect(source).not.toContain("gmailDraftId");expect(source).not.toContain("operationId");});
  it("retains all six outcome filters with accessible current selection",async()=>{const html=await render("replied");for(const outcome of ["awaiting-response","replied","meeting-scheduled","declined","hard-bounce","opt-out"])expect(html).toContain(`/sent?outcome=${outcome}`);expect(html).toContain('aria-current="page" href="/sent?outcome=replied"');});
  it("offers every outcome in a compact mobile control with the active filter visible",async()=>{const html=await render("hard-bounce");expect(html).toContain('aria-label="Filter relationships by outcome"');for(const label of ["All relationships","Awaiting reply","Replied","Meeting","Declined","Bounced","Opt-out"])expect(html).toContain(label);expect(html).toContain('<option value="hard-bounce" selected="">Bounced</option>');});
});
