import {GMAIL_COMPOSE_SCOPE,type GmailDraftCreator} from "@/application/email-drafts";
import {assertGmailEnabled,type GmailConfig} from "./config";
import type {GmailHttpTransport,GmailTokenProvider} from "./types";

export const GMAIL_ADAPTER_VERSION="gmail-draft-adapter-v1";
export type GmailErrorCategory="gmail-authentication-failed"|"gmail-authorization-failed"|"gmail-request-invalid"|"gmail-draft-not-found"|"gmail-rate-limited"|"gmail-provider-transient"|"gmail-timeout"|"gmail-response-malformed"|"gmail-transport-failure"|"gmail-account-ambiguous"|"gmail-scope-invalid";
export class GmailProviderError extends Error{constructor(readonly category:GmailErrorCategory,readonly outcomeUnknown=false){super(category);}}
const category=(status:number):GmailErrorCategory=>status===400?"gmail-request-invalid":status===401?"gmail-authentication-failed":status===403?"gmail-authorization-failed":status===404?"gmail-draft-not-found":status===429?"gmail-rate-limited":status>=500?"gmail-provider-transient":"gmail-response-malformed";
const object=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new GmailProviderError("gmail-response-malformed");return value as Record<string,unknown>;};

export class GmailDraftAdapter implements GmailDraftCreator{
  constructor(private readonly config:GmailConfig,private readonly transport:GmailHttpTransport,private readonly tokens:GmailTokenProvider){}
  private async authorization(requireIdentity=true){assertGmailEnabled(this.config);const token=await this.tokens.getAccessToken();if(token.grantedScopes.length!==1||token.grantedScopes[0]!==GMAIL_COMPOSE_SCOPE)throw new GmailProviderError("gmail-scope-invalid");if(requireIdentity&&!token.accountEmail)throw new GmailProviderError("gmail-account-ambiguous");return token;}
  async connectedAccount():Promise<string>{const token=await this.authorization(false),response=await this.transport.request({method:"GET",path:"/gmail/v1/users/me/profile",accessToken:token.accessToken,timeoutMs:this.config.timeoutMs,maxResponseBytes:this.config.maxResponseBytes});if(response.status<200||response.status>=300)throw new GmailProviderError(category(response.status));try{const emailAddress=object(JSON.parse(response.body)).emailAddress;if(typeof emailAddress!=="string"||token.accountEmail&&emailAddress.toLowerCase()!==token.accountEmail.toLowerCase())throw new GmailProviderError("gmail-account-ambiguous");if(!token.accountEmail)await this.tokens.setAccountEmail(emailAddress);return emailAddress;}catch(error){if(error instanceof GmailProviderError)throw error;throw new GmailProviderError("gmail-response-malformed");}}
  async createDraft(rawMessage:string):Promise<{draftId:string;messageId:string}>{const token=await this.authorization();let response;try{response=await this.transport.request({method:"POST",path:"/gmail/v1/users/me/drafts",body:{message:{raw:rawMessage}},accessToken:token.accessToken,timeoutMs:this.config.timeoutMs,maxResponseBytes:this.config.maxResponseBytes});}catch(error){if(error instanceof Error&&error.message==="gmail-request-timeout")throw new GmailProviderError("gmail-timeout",true);throw new GmailProviderError("gmail-transport-failure",true);}if(response.status<200||response.status>=300)throw new GmailProviderError(category(response.status),response.status>=500||response.status===429);try{const payload=object(JSON.parse(response.body)),message=object(payload.message);if(typeof payload.id!=="string"||typeof message.id!=="string")throw new Error();return{draftId:payload.id,messageId:message.id};}catch{throw new GmailProviderError("gmail-response-malformed",true);}}
}
