import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it,vi} from "vitest";
import {approveForGmailDraft,createApprovedGmailDraft,GMAIL_COMPOSE_SCOPE,type ApprovedEmailDraftSnapshot} from "@/application/email-drafts";
import {GmailDraftAdapter,GMAIL_ADAPTER_VERSION,GmailProviderError} from "./adapter";
import {DeterministicPlainTextMimeBuilder} from "./mime";
import type {GmailHttpTransport,GmailTokenProvider} from "./types";
import {SqliteSimulationRepository} from "@/infrastructure/sqlite/database";
import {seedFictionalData} from "@/infrastructure/sqlite/seed";
import {runDailySimulation} from "@/application/simulation/run-daily-simulation";
import {generateDraftsForRun} from "@/application/drafts";

const directories:string[]=[];
const setup=()=>{const directory=mkdtempSync(join(tmpdir(),"networkpilot-gmail-"));directories.push(directory);const repository=new SqliteSimulationRepository(join(directory,"test.sqlite"));repository.migrate();return repository;};
afterEach(()=>{while(directories.length)rmSync(directories.pop()!,{recursive:true,force:true});});
const snapshot=():ApprovedEmailDraftSnapshot=>({snapshotId:"fictional-draft-snapshot-001",recipientProfessionalEmail:"recipient@example.invalid",recipientDisplayName:"Fictional Résumé",subject:"A thoughtful question — data work",body:"Hello Fictional,\n\nCould I ask for 15 minutes?\n\nThank you,\nDylan",planningSnapshotId:"fictional-plan-001",templateCatalogVersion:"catalog-v3",evidenceIds:["fictional-evidence-001"],approvedAt:"2026-09-10T12:00:00.000Z"});
const config={enabled:true,clientId:"fixture-client",redirectUri:"http://127.0.0.1:9876/oauth/google/callback",scope:GMAIL_COMPOSE_SCOPE,timeoutMs:1000,maxResponseBytes:10000} as const;
const tokens=():GmailTokenProvider=>({getAccessToken:vi.fn(async()=>({accessToken:"fixture-access-token",expiresAt:"2099-01-01T00:00:00.000Z",grantedScopes:[GMAIL_COMPOSE_SCOPE],accountEmail:"operator@example.invalid"})),setAccountEmail:vi.fn(async()=>{})});

describe("Gmail draft-only production path",()=>{
  it("persists only non-secret connection metadata",()=>{const repository=setup(),metadata={accountEmail:"operator@example.invalid",grantedScopes:[GMAIL_COMPOSE_SCOPE],state:"connected" as const,updatedAt:"2026-09-10T12:00:00.000Z"};repository.saveGmailConnectionMetadata(metadata);expect(repository.getGmailConnectionMetadata()).toEqual(metadata);const columns=(repository.native.prepare("PRAGMA table_info(gmail_connection_metadata)").all() as Array<{name:string}>).map((item)=>item.name);expect(columns.some((name)=>/token|secret|client_id/i.test(name))).toBe(false);repository.close();});
  it("flows from qualification and immutable planning through deterministic drafting to the mocked Gmail boundary",async()=>{const repository=setup();seedFictionalData(repository);const run=runDailySimulation(repository,{instant:new Date("2026-09-07T15:00:00.000Z"),random:()=>0}),draft=generateDraftsForRun(repository,run.id,()=>new Date("2026-09-07T16:00:00.000Z"))[0]!,prospect=repository.listProspects().find((item)=>item.id===draft.prospectId)!,eventCount=repository.listOutreachEvents().length;const approved:ApprovedEmailDraftSnapshot={snapshotId:draft.id,recipientProfessionalEmail:prospect.email,recipientDisplayName:draft.prospectName,subject:draft.subject,body:draft.body,planningSnapshotId:run.id,templateCatalogVersion:draft.templateCatalogVersion,evidenceIds:draft.evidenceIds,approvedAt:"2026-09-07T17:00:00.000Z"},operation=approveForGmailDraft(repository,approved,GMAIL_ADAPTER_VERSION),request=vi.fn(async()=>({status:200,headers:{},body:JSON.stringify({id:"fixture-gmail-draft-id",message:{id:"fixture-gmail-message-id"}})})),created=await createApprovedGmailDraft({snapshotId:operation.snapshot.snapshotId,repository,creator:new GmailDraftAdapter(config,{request},tokens()),mime:new DeterministicPlainTextMimeBuilder(),now:()=>new Date("2026-09-07T17:01:00.000Z")});expect(run.selectedCount).toBe(15);expect(draft.templateCatalogVersion).toBe("catalog-v3");expect(created.state).toBe("gmail-draft-created");expect(request).toHaveBeenCalledTimes(1);expect(repository.listOutreachEvents()).toHaveLength(eventCount);repository.close();});
  it("creates one external draft from an approved immutable snapshot and is idempotent",async()=>{const repository=setup(),original=snapshot(),operation=approveForGmailDraft(repository,original,GMAIL_ADAPTER_VERSION),requests:Parameters<GmailHttpTransport["request"]>[0][]=[],transport:GmailHttpTransport={request:vi.fn(async(input)=>{requests.push(input);return{status:200,headers:{},body:JSON.stringify({id:"fixture-gmail-draft-id",message:{id:"fixture-gmail-message-id"}})};})},adapter=new GmailDraftAdapter(config,transport,tokens()),mime=new DeterministicPlainTextMimeBuilder();original.subject="Mutated current subject";original.body="Mutated current body";const first=await createApprovedGmailDraft({snapshotId:operation.snapshot.snapshotId,repository,creator:adapter,mime,now:()=>new Date("2026-09-10T12:01:00.000Z")}),second=await createApprovedGmailDraft({snapshotId:operation.snapshot.snapshotId,repository,creator:adapter,mime,now:()=>new Date("2026-09-10T12:02:00.000Z")});expect(first).toMatchObject({state:"gmail-draft-created",gmailDraftId:"fixture-gmail-draft-id",gmailMessageId:"fixture-gmail-message-id"});expect(second).toEqual(first);expect(requests).toHaveLength(1);expect(requests[0]).toMatchObject({method:"POST",path:"/gmail/v1/users/me/drafts",body:{message:{raw:expect.any(String)}}});const decoded=Buffer.from((requests[0].body as {message:{raw:string}}).message.raw,"base64url").toString();expect(decoded).toContain("Hello Fictional");expect(decoded).not.toContain("Mutated current");repository.close();});
  it("marks an uncertain POST timeout for reconciliation and blocks automatic retry",async()=>{const repository=setup(),operation=approveForGmailDraft(repository,snapshot(),GMAIL_ADAPTER_VERSION),request=vi.fn(async()=>{throw new Error("gmail-request-timeout");}),adapter=new GmailDraftAdapter(config,{request},tokens()),input={snapshotId:operation.snapshot.snapshotId,repository,creator:adapter,mime:new DeterministicPlainTextMimeBuilder(),now:()=>new Date("2026-09-10T12:01:00.000Z")};await expect(createApprovedGmailDraft(input)).rejects.toMatchObject({category:"gmail-timeout",outcomeUnknown:true});expect(repository.findGmailDraftOperation(operation.snapshot.snapshotId)?.state).toBe("reconciliation-required");await expect(createApprovedGmailDraft(input)).rejects.toThrow("gmail-draft-reconciliation-required");expect(request).toHaveBeenCalledTimes(1);repository.close();});
  it("fails closed before token or transport activity when disabled",async()=>{const tokenProvider=tokens(),request=vi.fn(),adapter=new GmailDraftAdapter({...config,enabled:false},{request},tokenProvider);await expect(adapter.createDraft("fixture")).rejects.toThrow("gmail-feature-disabled");expect(tokenProvider.getAccessToken).not.toHaveBeenCalled();expect(request).not.toHaveBeenCalled();});
  it("discovers and pins identity through the minimal profile endpoint",async()=>{const tokenProvider=tokens();vi.mocked(tokenProvider.getAccessToken).mockResolvedValue({...await tokenProvider.getAccessToken(),accountEmail:null});const request=vi.fn(async()=>({status:200,headers:{},body:JSON.stringify({emailAddress:"operator@example.invalid"})})),adapter=new GmailDraftAdapter(config,{request},tokenProvider);await expect(adapter.connectedAccount()).resolves.toBe("operator@example.invalid");expect(request).toHaveBeenCalledWith(expect.objectContaining({method:"GET",path:"/gmail/v1/users/me/profile"}));expect(tokenProvider.setAccountEmail).toHaveBeenCalledWith("operator@example.invalid");});
  it("rejects broader scopes and ambiguous accounts",async()=>{const tokenProvider=tokens();vi.mocked(tokenProvider.getAccessToken).mockResolvedValue({...await tokenProvider.getAccessToken(),grantedScopes:[GMAIL_COMPOSE_SCOPE,"https://www.googleapis.com/auth/gmail.modify"]});await expect(new GmailDraftAdapter(config,{request:vi.fn()},tokenProvider).createDraft("fixture")).rejects.toBeInstanceOf(GmailProviderError);});
  it.each([[400,"gmail-request-invalid",false],[401,"gmail-authentication-failed",false],[403,"gmail-authorization-failed",false],[404,"gmail-draft-not-found",false],[429,"gmail-rate-limited",true],[500,"gmail-provider-transient",true]])("classifies HTTP %s without retrying",async(status,category,outcomeUnknown)=>{const request=vi.fn(async()=>({status,headers:{},body:"{}"})),adapter=new GmailDraftAdapter(config,{request},tokens());await expect(adapter.createDraft("fixture")).rejects.toMatchObject({category,outcomeUnknown});expect(request).toHaveBeenCalledTimes(1);});
  it.each(["not-json",JSON.stringify({id:"draft-without-message"}),JSON.stringify({id:"draft",message:{}})])("treats malformed successful responses as uncertain",async(body)=>{const adapter=new GmailDraftAdapter(config,{request:vi.fn(async()=>({status:200,headers:{},body}))},tokens());await expect(adapter.createDraft("fixture")).rejects.toMatchObject({category:"gmail-response-malformed",outcomeUnknown:true});});
});

describe("deterministic plain-text MIME",()=>{
  it("uses CRLF, RFC 2047 for Unicode headers, base64URL, and no From/CC/BCC",()=>{const raw=new DeterministicPlainTextMimeBuilder().build(snapshot()),decoded=Buffer.from(raw,"base64url").toString();expect(decoded).toContain("To: =?UTF-8?B?");expect(decoded).toContain("Subject: =?UTF-8?B?");expect(decoded).toContain("MIME-Version: 1.0\r\nContent-Type: text/plain");expect(decoded).not.toMatch(/\n(From|Cc|Bcc):/i);expect(raw).not.toMatch(/[+/=]/);});
  it.each([{...snapshot(),subject:"Safe\r\nBcc: attacker@example.invalid"},{...snapshot(),recipientProfessionalEmail:"safe@example.invalid\nCc: attacker@example.invalid"},{...snapshot(),recipientDisplayName:"Safe\nBcc"}])("rejects header injection",(input)=>expect(()=>new DeterministicPlainTextMimeBuilder().build(input)).toThrow("header-injection"));
  it.each(["invalid","a@@example.invalid","a@example","a b@example.invalid"])("rejects recipient %s",(recipientProfessionalEmail)=>expect(()=>new DeterministicPlainTextMimeBuilder().build({...snapshot(),recipientProfessionalEmail})).toThrow("recipient-invalid"));
});
