import {describe,expect,it,vi} from "vitest";
import {GMAIL_COMPOSE_SCOPE} from "@/application/email-drafts";
import {GoogleOAuthSession,type GoogleOAuthTransport,type GoogleTokenSecretStore,type StoredGoogleTokens} from "./oauth";
import {readGmailConfig,redactGmailError} from "./config";

const config=readGmailConfig({NETWORKPILOT_GMAIL_ENABLED:"true",GOOGLE_OAUTH_CLIENT_ID:"fixture-client",GOOGLE_OAUTH_CLIENT_SECRET:"fixture-secret",GOOGLE_OAUTH_REDIRECT_URI:"http://127.0.0.1:8765/oauth/google/callback"});
const tokens:StoredGoogleTokens={accessToken:"fixture-access",refreshToken:"fixture-refresh",expiresAt:"2099-01-01T00:00:00.000Z",grantedScopes:[GMAIL_COMPOSE_SCOPE],accountEmail:null};
const store=(initial:StoredGoogleTokens|null=null)=>{let value=initial;return{load:vi.fn(async()=>value),save:vi.fn(async(next:StoredGoogleTokens)=>{value=next;}),delete:vi.fn(async()=>{value=null;})} satisfies GoogleTokenSecretStore;};
const transport=():GoogleOAuthTransport=>({exchange:vi.fn(async()=>tokens),refresh:vi.fn(async()=>({...tokens,refreshToken:undefined} as never)),revoke:vi.fn(async()=>{})});

describe("local desktop Google OAuth boundary",()=>{
  it("uses loopback, PKCE, state, offline access, and only gmail.compose",async()=>{const secretStore=store(),provider=transport(),session=new GoogleOAuthSession(config,provider,secretStore,()=>new Date("2026-09-10T12:00:00Z")),request=session.createAuthorizationUrl(),url=new URL(request.url);expect(url.origin).toBe("https://accounts.google.com");expect(url.searchParams.get("scope")).toBe(GMAIL_COMPOSE_SCOPE);expect(url.searchParams.get("redirect_uri")).toBe("http://127.0.0.1:8765/oauth/google/callback");expect(url.searchParams.get("code_challenge_method")).toBe("S256");expect(url.searchParams.get("access_type")).toBe("offline");await session.completeAuthorization("fixture-code",request.state);expect(provider.exchange).toHaveBeenCalledWith(expect.objectContaining({codeVerifier:expect.any(String)}));expect(secretStore.save).toHaveBeenCalledWith(tokens);});
  it("rejects invalid state and any broader granted scope",async()=>{const session=new GoogleOAuthSession(config,{...transport(),exchange:vi.fn(async()=>({...tokens,grantedScopes:[GMAIL_COMPOSE_SCOPE,"broader"]}))},store());await expect(session.completeAuthorization("code","wrong-state")).rejects.toThrow("state-invalid");const request=session.createAuthorizationUrl();await expect(session.completeAuthorization("code",request.state)).rejects.toThrow("scope-invalid");});
  it("refreshes expiration without broadening scope and deletes invalid grants",async()=>{const expired={...tokens,expiresAt:"2020-01-01T00:00:00Z",accountEmail:"operator@example.invalid"},secretStore=store(expired),provider=transport();vi.mocked(provider.refresh).mockResolvedValue({accessToken:"fresh",expiresAt:"2099-01-01T00:00:00Z",grantedScopes:[GMAIL_COMPOSE_SCOPE],accountEmail:null});const session=new GoogleOAuthSession(config,provider,secretStore,()=>new Date("2026-09-10T12:00:00Z"));await expect(session.getAccessToken()).resolves.toMatchObject({accessToken:"fresh",refreshToken:"fixture-refresh",accountEmail:"operator@example.invalid"});vi.mocked(provider.refresh).mockRejectedValue(new Error("invalid_grant"));await secretStore.save(expired);await expect(session.getAccessToken()).rejects.toThrow("invalid_grant");expect(secretStore.delete).toHaveBeenCalled();});
  it("disconnects by revoking and deleting local state",async()=>{const secretStore=store(tokens),provider=transport();await new GoogleOAuthSession(config,provider,secretStore).disconnect();expect(provider.revoke).toHaveBeenCalledWith("fixture-access");expect(secretStore.delete).toHaveBeenCalled();});
  it("defaults disabled, restricts redirect URIs, and redacts secrets",()=>{expect(readGmailConfig({}).enabled).toBe(false);expect(()=>readGmailConfig({GOOGLE_OAUTH_REDIRECT_URI:"https://example.test/callback"})).toThrow("redirect-uri");expect(redactGmailError(new Error("bad fixture-secret and fixture-access"),["fixture-secret","fixture-access"])).toBe("bad [REDACTED] and [REDACTED]");});
});
