import {createHash,randomBytes} from "node:crypto";
import {GMAIL_COMPOSE_SCOPE} from "@/application/email-drafts";
import type {GmailConnectionMetadataRepository} from "@/application/email-drafts";
import {assertGmailEnabled,type GmailConfig} from "./config";

export interface StoredGoogleTokens {accessToken:string;refreshToken:string;expiresAt:string;grantedScopes:readonly string[];accountEmail:string|null;}
export interface GoogleTokenSecretStore {load():Promise<StoredGoogleTokens|null>;save(tokens:StoredGoogleTokens):Promise<void>;delete():Promise<void>;}
export interface GoogleOAuthTransport {exchange(input:{clientId:string;clientSecret?:string;code:string;codeVerifier:string;redirectUri:string}):Promise<StoredGoogleTokens>;refresh(input:{clientId:string;clientSecret?:string;refreshToken:string}):Promise<Omit<StoredGoogleTokens,"refreshToken" >>;revoke(accessToken:string):Promise<void>;}

export class GoogleOAuthSession{
  private pending=new Map<string,{verifier:string;createdAt:number}>();
  constructor(private readonly config:GmailConfig,private readonly transport:GoogleOAuthTransport,private readonly store:GoogleTokenSecretStore,private readonly now:()=>Date=()=>new Date(),private readonly metadata?:GmailConnectionMetadataRepository){}
  createAuthorizationUrl():{url:string;state:string}{const {clientId,redirectUri}=assertGmailEnabled(this.config),state=randomBytes(32).toString("base64url"),verifier=randomBytes(48).toString("base64url"),challenge=createHash("sha256").update(verifier).digest("base64url");this.pending.set(state,{verifier,createdAt:this.now().getTime()});const query=new URLSearchParams({client_id:clientId,redirect_uri:redirectUri,response_type:"code",scope:GMAIL_COMPOSE_SCOPE,access_type:"offline",prompt:"consent",state,code_challenge:challenge,code_challenge_method:"S256"});return{url:`https://accounts.google.com/o/oauth2/v2/auth?${query}`,state};}
  async completeAuthorization(code:string,state:string):Promise<StoredGoogleTokens>{const pending=this.pending.get(state);this.pending.delete(state);if(!pending||this.now().getTime()-pending.createdAt>10*60*1000)throw new Error("gmail-oauth-state-invalid");const {clientId,redirectUri}=assertGmailEnabled(this.config),tokens=await this.transport.exchange({clientId,...this.config.clientSecret?{clientSecret:this.config.clientSecret}:{},code,codeVerifier:pending.verifier,redirectUri});this.assertScopes(tokens.grantedScopes);await this.store.save(tokens);this.metadata?.saveGmailConnectionMetadata({accountEmail:tokens.accountEmail,grantedScopes:tokens.grantedScopes,state:"connected",updatedAt:this.now().toISOString()});return tokens;}
  async getAccessToken():Promise<StoredGoogleTokens>{assertGmailEnabled(this.config);const tokens=await this.store.load();if(!tokens)throw new Error("gmail-oauth-disconnected");this.assertScopes(tokens.grantedScopes);if(new Date(tokens.expiresAt).getTime()>this.now().getTime()+60_000)return tokens;try{const {clientId}=assertGmailEnabled(this.config),refreshed=await this.transport.refresh({clientId,...this.config.clientSecret?{clientSecret:this.config.clientSecret}:{},refreshToken:tokens.refreshToken}),grantedScopes=refreshed.grantedScopes.length?refreshed.grantedScopes:tokens.grantedScopes;this.assertScopes(grantedScopes);const updated={...refreshed,grantedScopes,accountEmail:tokens.accountEmail,refreshToken:tokens.refreshToken};await this.store.save(updated);return updated;}catch(error){if(error instanceof Error&&error.message.includes("invalid_grant")){await this.store.delete();this.metadata?.saveGmailConnectionMetadata({accountEmail:tokens.accountEmail,grantedScopes:tokens.grantedScopes,state:"reauthorization-required",updatedAt:this.now().toISOString()});}throw error;}}
  async setAccountEmail(email:string):Promise<void>{const tokens=await this.store.load();if(!tokens)throw new Error("gmail-oauth-disconnected");await this.store.save({...tokens,accountEmail:email});this.metadata?.saveGmailConnectionMetadata({accountEmail:email,grantedScopes:tokens.grantedScopes,state:"connected",updatedAt:this.now().toISOString()});}
  async disconnect():Promise<void>{const tokens=await this.store.load();if(tokens)try{await this.transport.revoke(tokens.accessToken);}finally{await this.store.delete();}else await this.store.delete();this.metadata?.saveGmailConnectionMetadata({accountEmail:null,grantedScopes:[],state:"disconnected",updatedAt:this.now().toISOString()});}
  private assertScopes(scopes:readonly string[]):void{if(scopes.length!==1||scopes[0]!==GMAIL_COMPOSE_SCOPE)throw new Error("gmail-oauth-scope-invalid");}
}
