import type {GoogleOAuthTransport,StoredGoogleTokens} from "./oauth";

const TOKEN_ENDPOINT="https://oauth2.googleapis.com/token",REVOKE_ENDPOINT="https://oauth2.googleapis.com/revoke";
const parse=(status:number,body:string)=>{if(status<200||status>=300)throw new Error(body.includes("invalid_grant")?"gmail-oauth-invalid_grant":`gmail-oauth-http-${status}`);try{return JSON.parse(body) as Record<string,unknown>;}catch{throw new Error("gmail-oauth-response-malformed");}};
const scopes=(value:unknown)=>typeof value==="string"?value.split(/\s+/).filter(Boolean):[];
const tokenFields=(payload:Record<string,unknown>)=>{if(typeof payload.access_token!=="string"||typeof payload.expires_in!=="number")throw new Error("gmail-oauth-response-malformed");return{accessToken:payload.access_token,expiresAt:new Date(Date.now()+payload.expires_in*1000).toISOString(),grantedScopes:scopes(payload.scope),accountEmail:null};};

export class FetchGoogleOAuthTransport implements GoogleOAuthTransport{
  constructor(private readonly fetcher:typeof fetch=fetch,private readonly timeoutMs=10000,private readonly maxResponseBytes=262144){}
  private async post(url:string,body:URLSearchParams):Promise<{status:number;body:string}>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{const response=await this.fetcher(url,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,redirect:"error",signal:controller.signal}),declared=Number(response.headers.get("content-length"));if(Number.isFinite(declared)&&declared>this.maxResponseBytes)throw new Error("gmail-oauth-response-too-large");const text=await response.text();if(Buffer.byteLength(text)>this.maxResponseBytes)throw new Error("gmail-oauth-response-too-large");return{status:response.status,body:text};}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new Error("gmail-oauth-request-timeout");throw error;}finally{clearTimeout(timer);}}
  async exchange(input:Parameters<GoogleOAuthTransport["exchange"]>[0]):Promise<StoredGoogleTokens>{const body=new URLSearchParams({client_id:input.clientId,...input.clientSecret?{client_secret:input.clientSecret}:{},code:input.code,code_verifier:input.codeVerifier,redirect_uri:input.redirectUri,grant_type:"authorization_code"}),response=await this.post(TOKEN_ENDPOINT,body),payload=parse(response.status,response.body);if(typeof payload.refresh_token!=="string")throw new Error("gmail-oauth-refresh-token-missing");return{...tokenFields(payload),refreshToken:payload.refresh_token};}
  async refresh(input:Parameters<GoogleOAuthTransport["refresh"]>[0]){const body=new URLSearchParams({client_id:input.clientId,...input.clientSecret?{client_secret:input.clientSecret}:{},refresh_token:input.refreshToken,grant_type:"refresh_token"}),response=await this.post(TOKEN_ENDPOINT,body);return tokenFields(parse(response.status,response.body));}
  async revoke(accessToken:string):Promise<void>{const response=await this.post(REVOKE_ENDPOINT,new URLSearchParams({token:accessToken}));if(response.status<200||response.status>=300)throw new Error(`gmail-oauth-revoke-${response.status}`);}
}
