import {createServer,type Server} from "node:http";
import type {GmailConnectionMetadataRepository} from "@/application/email-drafts";
import {GmailDraftAdapter} from "./adapter";
import type {GmailConfig} from "./config";
import {FetchGmailTransport} from "./http";
import {MacOsKeychainGoogleTokenStore} from "./keychain";
import {GoogleOAuthSession,type GoogleTokenSecretStore,type StoredGoogleTokens} from "./oauth";
import {FetchGoogleOAuthTransport} from "./oauth-http";

class StagedTokenStore implements GoogleTokenSecretStore{tokens:StoredGoogleTokens|null=null;async load(){return this.tokens;}async save(tokens:StoredGoogleTokens){this.tokens=tokens;}async delete(){this.tokens=null;}}
export async function commitSameAccountReauthorization(input:{tokens:StoredGoogleTokens;authorizedAccount:string;expectedAccount:string;store:GoogleTokenSecretStore;metadata:GmailConnectionMetadataRepository;now:Date}){if(input.authorizedAccount.toLowerCase()!==input.expectedAccount.toLowerCase())throw new Error("gmail-reauthorization-account-mismatch");const tokens={...input.tokens,accountEmail:input.authorizedAccount};await input.store.save(tokens);input.metadata.saveGmailConnectionMetadata({accountEmail:input.expectedAccount,grantedScopes:tokens.grantedScopes,state:"connected",updatedAt:input.now.toISOString()});return tokens;}

let active:Server|null=null;
export async function beginLocalGmailReauthorization(input:{config:GmailConfig;expectedAccount:string;metadata:GmailConnectionMetadataRepository;returnOrigin:string}):Promise<string>{if(active)throw new Error("gmail-reauthorization-already-active");if(!input.config.redirectUri)throw new Error("gmail-oauth-configuration-missing");const callback=new URL(input.config.redirectUri);if(callback.protocol!=="http:"||callback.hostname!=="127.0.0.1"||!callback.port)throw new Error("gmail-config-invalid:redirect-uri");const staged=new StagedTokenStore(),session=new GoogleOAuthSession(input.config,new FetchGoogleOAuthTransport(),staged),authorization=session.createAuthorizationUrl(),realStore=new MacOsKeychainGoogleTokenStore();
  const server=createServer(async(request,response)=>{const url=new URL(request.url??"/",callback.origin);if(url.pathname!==callback.pathname){response.writeHead(404).end();return;}try{const code=url.searchParams.get("code"),state=url.searchParams.get("state");if(!code||!state)throw new Error("gmail-oauth-callback-invalid");await session.completeAuthorization(code,state);const adapter=new GmailDraftAdapter(input.config,new FetchGmailTransport(),session),account=await adapter.connectedAccount(),stagedTokens=await staged.load();if(!stagedTokens)throw new Error("gmail-reauthorization-staged-credential-missing");await commitSameAccountReauthorization({tokens:stagedTokens,authorizedAccount:account,expectedAccount:input.expectedAccount,store:realStore,metadata:input.metadata,now:new Date()});response.writeHead(302,{location:`${input.returnOrigin}/today`}).end();}catch{response.writeHead(302,{location:`${input.returnOrigin}/today?sendError=gmail-reauthorization-failed`}).end();}finally{clearTimeout(timer);server.close();active=null;}}),timer=setTimeout(()=>{server.close();active=null;},10*60*1000);await new Promise<void>((resolve,reject)=>{server.once("error",error=>{clearTimeout(timer);active=null;reject(error);});server.listen(Number(callback.port),"127.0.0.1",()=>resolve());});active=server;return authorization.url;}
