import { describe,expect,it } from "vitest";
import { CONTACT_PERSONAS, INDUSTRY_PREFERENCES, TARGET_ROLES, type TargetCompany } from "@/domain/targeting";
import type { Industry, Prospect } from "@/domain/outreach";
import type { PlanningCandidate } from ".";
import { planDailyCampaign } from ".";
import { CLASSIFICATION_VERSION } from "@/domain/candidates";

const industryDisplay:Record<string,Industry>={"technology-ai":"Technology",consulting:"Consulting","financial-services":"Finance","commodities-energy":"Commodities","defense-aerospace":"Defense"};
function candidate(id:number,options:{industry?:string;family?:string;company?:string;score?:number;legacy?:number;tier?:"tier-1"|"tier-2"|"tier-3";upside?:number;suppressed?:boolean;registry?:boolean}={}):PlanningCandidate{
 const industryId=options.industry??"technology-ai",family=options.family??"data-analytics",role=TARGET_ROLES.find((item)=>item.familyId===family)!,persona=CONTACT_PERSONAS[0],companyId=options.company??`fictional-company-${id}`,tier=options.tier??"tier-2",value=options.score??80;
 const company:TargetCompany={id:`registry-${id}`,canonicalName:`Registry Strategy ${id}`,industryId,tier,enabled:true,recognitionScore:80,careerUpsideScore:80,technicalInterestScore:80,geographicRelevance:["boston-ma"],rationale:"test",provenance:"test",lastReviewedDate:"2026-09-08",operatorNotes:"test"};
 const prospect:Prospect={id:`person-${id}`,firstName:"Fictional",lastName:String(id),companyId,companyName:`Imaginary ${id}`,industry:industryDisplay[industryId],email:`person-${id}@example.test`,emailVerified:true,yearsExperience:10,suppressed:options.suppressed??false,optedOut:false,relevanceScore:options.legacy??50};
 const normalized={internalId:`candidate-${id}`,externalSourceReference:`fixture:${id}`,sourceType:"fictional-fixture" as const,retrievedAt:"2026-09-08T00:00:00.000Z",firstName:"Fictional",lastName:String(id),professionalTitle:"Data Engineer",employerName:prospect.companyName,industry:industryId,geography:"boston-ma",yearsExperience:10,professionalEmail:prospect.email,emailVerificationStatus:"verified" as const,roleSignals:[family],sharedSignals:[],dataQualityIndicators:[],publicCompanyRegistryMatch:{companyId:company.id,matchedBy:"simulation-alias" as const,reviewed:true},rawRecordFingerprint:`fingerprint-${id}`};
 const companyMatch=options.registry===false?null:{registryCompanyId:company.id,canonicalName:company.canonicalName,tier,method:"simulation-alias" as const,provenance:"fictional test",fictionalScenario:true as const};
 return{prospect,professionalTitle:"Data Engineer",roleFamilyId:family,desiredRoleId:role.id,personaId:persona.id,industryId,geographyId:"boston-ma",targetingProfileVersion:"profile-v1",companyProfileVersion:"company-v1",companyMatch,normalized,normalizedRecord:{source:normalized,fictionalEmployer:{id:companyId,name:prospect.companyName,industryId},stableFingerprint:normalized.rawRecordFingerprint,normalizedTitle:"data engineer",yearsExperience:10,roleFamilyId:family,desiredRoleId:role.id,recipientPersonaId:persona.id,industryId,geographyId:"boston-ma",companyMatch:options.registry===false?null:{companyId:company.id,canonicalName:company.canonicalName,tier,enabled:true,industryId,recognitionScore:80,careerUpsideScore:80,technicalInterestScore:80,reviewStatus:"reviewed",method:"simulation-alias",provenance:"fictional test"},dataQualityScore:value,sharedSignal:value,roleAlignment:value,functionalRelevance:value,roleSpecificUpside:options.upside??value,explanationCodes:[],reviewCode:null,rejectionCode:options.registry===false?"company-unknown":null,classificationVersion:CLASSIFICATION_VERSION,targetingProfileVersion:"profile-v1",companyProfileVersion:"company-v1"},target:{id:prospect.id,company,role,persona,industry:INDUSTRY_PREFERENCES.find((item)=>item.id===industryId)!,geographyScore:100,roleAlignment:value,functionalRelevance:value,yearsExperience:10,sharedSignal:value,dataQuality:value,roleSpecificUpside:options.upside??value}};
}
describe("targeting-first campaign planning",()=>{
 it("uses targeting score and deterministic candidate IDs, never legacy relevance",()=>{const low=candidate(1,{score:60,legacy:100}),high=candidate(2,{score:95,legacy:1});expect(planDailyCampaign([low,high],[],1,new Date("2026-09-08T12:00:00Z"),7).selected[0].prospectId).toBe("person-2");const tied=planDailyCampaign([candidate(4),candidate(3)],[],1,new Date(),7);expect(tied.selected[0].candidateId).toBe("candidate-3");});
 it("applies hard gates before scoring",()=>{const item=candidate(1,{suppressed:true});item.target!.role=undefined as never;expect(planDailyCampaign([item],[],1,new Date(),7).decisions[0].selectionReason).toBe("suppressed");});
 it("rejects unknown companies and Tier 3 without exceptional fit",()=>{expect(planDailyCampaign([candidate(1,{registry:false})],[],1,new Date(),7).decisions[0].hardGateRejectionCode).toBe("company-unknown");expect(planDailyCampaign([candidate(2,{tier:"tier-3",upside:84})],[],1,new Date(),7).decisions[0].hardGateRejectionCode).toBe("tier-3-needs-exceptional-fit");expect(planDailyCampaign([candidate(3,{tier:"tier-3",upside:95,score:95})],[],1,new Date(),7).selected).toHaveLength(1);});
 it("keeps company uniqueness and cooldown hard",()=>{const result=planDailyCampaign([candidate(1,{company:"same"}),candidate(2,{company:"same"})],[],2,new Date("2026-09-08T12:00:00Z"),7);expect(result.selected).toHaveLength(1);const history=[{prospectId:"old",companyId:"same",type:"selected" as const,occurredAt:new Date("2026-09-07T12:00:00Z")}];expect(planDailyCampaign([candidate(3,{company:"same"})],history,1,new Date("2026-09-08T12:00:00Z"),7).selected).toHaveLength(0);});
 it("diversifies softly and records deterministic relaxation",()=>{const pool=Array.from({length:7},(_,i)=>candidate(i+1,{industry:i<5?"technology-ai":"consulting",family:i<5?"data-analytics":"technical-product",score:95-i}));const result=planDailyCampaign(pool,[],6,new Date(),7,{industrySoftCap:2,roleFamilySoftCap:3,minimumScore:0});expect(new Set(result.selected.map((item)=>item.industry)).size).toBe(2);expect(result.quotaRelaxations.length).toBeGreaterThan(0);expect(planDailyCampaign(pool,[],6,new Date(),7,{industrySoftCap:2,roleFamilySoftCap:3,minimumScore:0})).toEqual(result);});
 it("permits a target shortfall without selecting ineligible candidates",()=>{const result=planDailyCampaign([candidate(1),candidate(2,{registry:false})],[],5,new Date(),7);expect(result.selected).toHaveLength(1);expect(result.target-result.selected.length).toBe(4);});
});
