import { scoreTarget } from "@/domain/targeting";
import { CONTACT_IMPACTING_EVENT_TYPES, type OutreachEvent } from "@/domain/outreach";
import { CAMPAIGN_PLAN_VERSION, type DailyPlanResult, type DiversificationConfig, type PlanningCandidate, type QuotaRelaxation, type TargetingPlanSnapshot } from "./types";

export const DEFAULT_DIVERSIFICATION_CONFIG:Readonly<DiversificationConfig>={industrySoftCap:6,roleFamilySoftCap:8,minimumScore:55};
const DAY=86_400_000;
const baseSnapshot=(item:PlanningCandidate):Omit<TargetingPlanSnapshot,"totalScore"|"components"|"explanationCodes"|"hardGateRejectionCode"|"rankBeforeDiversification"|"selected"|"selectionReason">=>({planVersion:CAMPAIGN_PLAN_VERSION,targetingVersion:"targeting-v1",candidateId:item.normalized.internalId,externalSourceReference:item.normalized.externalSourceReference,sourceType:item.normalized.sourceType,retrievedAt:item.normalized.retrievedAt,rawRecordFingerprint:item.normalized.rawRecordFingerprint,prospectId:item.prospect.id,prospectName:`${item.prospect.firstName} ${item.prospect.lastName}`,professionalTitle:item.professionalTitle,companyId:item.prospect.companyId,companyName:item.prospect.companyName,companyMatch:item.companyMatch,desiredRoleFamily:item.roleFamilyId,desiredRoleId:item.desiredRoleId,recipientPersona:item.personaId,industry:item.industryId,geography:item.geographyId,yearsExperience:item.prospect.yearsExperience,companyTier:item.target.company?.tier??null,companyRecognition:item.target.company?.recognitionScore??0,companyCareerUpside:item.target.company?.careerUpsideScore??0,companyTechnicalInterest:item.target.company?.technicalInterestScore??0,roleAlignment:item.target.roleAlignment,functionalRelevance:item.target.functionalRelevance,roleSpecificUpside:item.target.roleSpecificUpside,dataQuality:item.target.dataQuality,sharedSignal:item.target.sharedSignal,targetingProfileVersion:item.targetingProfileVersion,companyProfileVersion:item.companyProfileVersion});

export function planDailyCampaign(candidates:readonly PlanningCandidate[],history:readonly OutreachEvent[],target:number,now:Date,cooldownDays:number,config:Partial<DiversificationConfig>={}):DailyPlanResult{
  const rules={...DEFAULT_DIVERSIFICATION_CONFIG,...config};
  if(!Number.isInteger(target)||target<0||!Number.isInteger(cooldownDays)||cooldownDays<0||!Number.isInteger(rules.industrySoftCap)||rules.industrySoftCap<1||!Number.isInteger(rules.roleFamilySoftCap)||rules.roleFamilySoftCap<1)throw new RangeError("Invalid campaign planning configuration");
  const impacting=history.filter((event)=>CONTACT_IMPACTING_EVENT_TYPES.has(event.type)||event.type==="selected");
  const contacted=new Set(impacting.map((event)=>event.prospectId));
  const cooldownStart=now.getTime()-cooldownDays*DAY;
  const cooling=new Set(impacting.filter((event)=>event.occurredAt.getTime()>cooldownStart&&event.occurredAt.getTime()<=now.getTime()).map((event)=>event.companyId));
  const evaluated=candidates.map((item)=>{
    let rejection:string|undefined;
    if(item.prospect.suppressed)rejection="suppressed";else if(item.prospect.optedOut)rejection="opted-out";else if(!item.prospect.emailVerified)rejection="email-unverified";else if(item.prospect.yearsExperience<5)rejection="insufficient-experience";else if(contacted.has(item.prospect.id))rejection="previously-contacted";else if(cooling.has(item.prospect.companyId))rejection="company-in-cooldown";else if(item.normalized.emailVerificationStatus!=="verified")rejection="email-unverified";else if(!item.companyMatch?.registryCompanyId)rejection="company-unknown";else if(!item.target.role||!item.target.persona||!item.target.industry)rejection="classification-ambiguous";
    const score=rejection?{eligible:false,total:0,version:"targeting-v1",components:[],explanationCodes:[rejection],rejectionCode:rejection}:scoreTarget(item.target);
    if(!rejection&&!score.eligible)rejection=score.rejectionCode;
    if(!rejection&&score.total<rules.minimumScore)rejection="targeting-score-below-threshold";
    return {item,score,rejection};
  });
  const eligible=evaluated.filter((entry)=>!entry.rejection).sort((a,b)=>b.score.total-a.score.total||a.item.normalized.internalId.localeCompare(b.item.normalized.internalId));
  const rank=new Map(eligible.map((entry,index)=>[entry.item.prospect.id,index+1]));
  const selectedIds=new Set<string>(),companies=new Set<string>(),industryCounts=new Map<string,number>(),roleCounts=new Map<string,number>(),relaxations:QuotaRelaxation[]=[];
  const choose=(relax:boolean)=>{for(const entry of eligible){if(selectedIds.size>=target)break;const {item}=entry;if(selectedIds.has(item.prospect.id)||companies.has(item.prospect.companyId))continue;const industryCount=industryCounts.get(item.industryId)??0,roleCount=roleCounts.get(item.roleFamilyId)??0;const blocksIndustry=industryCount>=rules.industrySoftCap,blocksRole=roleCount>=rules.roleFamilySoftCap;if(!relax&&(blocksIndustry||blocksRole))continue;if(relax&&blocksIndustry)relaxations.push({code:"industry-soft-cap-relaxed",candidateId:item.normalized.internalId,reason:"Qualified pool could not reach the daily target within the industry soft cap."});if(relax&&blocksRole)relaxations.push({code:"role-family-soft-cap-relaxed",candidateId:item.normalized.internalId,reason:"Qualified pool could not reach the daily target within the role-family soft cap."});selectedIds.add(item.prospect.id);companies.add(item.prospect.companyId);industryCounts.set(item.industryId,industryCount+1);roleCounts.set(item.roleFamilyId,roleCount+1);}};
  choose(false);if(selectedIds.size<target)choose(true);
  const decisions=evaluated.map(({item,score,rejection}):TargetingPlanSnapshot=>{const selected=selectedIds.has(item.prospect.id);let reason=rejection??(selected?"selected-by-targeting-rank":"eligible-below-targeting-cutoff");if(!rejection&&!selected&&companies.has(item.prospect.companyId))reason="duplicate-company-in-plan";return{...baseSnapshot(item),targetingVersion:score.version,totalScore:score.total,components:score.components,explanationCodes:score.explanationCodes,hardGateRejectionCode:rejection==="targeting-score-below-threshold"?null:rejection??null,rankBeforeDiversification:rank.get(item.prospect.id)??null,selected,selectionReason:reason};});
  return{target,decisions,selected:decisions.filter((item)=>item.selected).sort((a,b)=>(a.rankBeforeDiversification??Infinity)-(b.rankBeforeDiversification??Infinity)),quotaRelaxations:relaxations,qualifiedPopulation:eligible.length};
}
