import Link from "next/link";
import {QueueContinuity} from "./queue-continuity";
import {DraftAdditionFeedback} from "./addition-feedback";
import {activeDrafts} from "@/application/product-workflow";
import {gmailSendBlockReason,humanSendError} from "@/application/command-center-drafts";
import {loadCommandCenterDraftReviews} from "@/infrastructure/sqlite/command-center-drafts";
import {loadDailyCommandCenter} from "@/infrastructure/sqlite/daily-command-center";
import {ProductNav} from "@/app/product-nav";
import {confirmAlreadySent,createGmailDraft,generateMoreDrafts,permanentlyExcludeDraft,reconcileGmailSendStatus,replaceSkippedDraft,sendGmailDraft,skipDraft} from "@/app/today/actions";
import {GmailDraftControl} from "@/app/today/gmail-draft-control";
import {GmailSendControl} from "@/app/today/gmail-send-control";
import {GmailReconciliationControl} from "@/app/today/gmail-reconciliation-control";
import {AddDraftsControl} from "./add-drafts-control";
import {GmailReadinessPanel} from "@/app/today/gmail-readiness-panel";

export const dynamic="force-dynamic";
const stateLabel={ready:"Ready to review",approved:"Approved", "gmail-draft-created":"Gmail draft created","needs-send-verification":"Check send status"} as const;
export default async function DraftsPage({searchParams}:{searchParams:Promise<{sendError?:string;sendStatus?:string;generationStatus?:string;skipStatus?:string;replacementStatus?:string;added?:string;requested?:string;reserveRemaining?:string}>}){
  const workflow=await loadCommandCenterDraftReviews(),commandCenter=loadDailyCommandCenter(),outreach=commandCenter.drafts,rows=activeDrafts(workflow.items,outreach),params=await searchParams,hasReserve=commandCenter.reserve.some((candidate)=>candidate.stage==="qualified-available");
  return <main className="product-shell drafts-page"><QueueContinuity completionKey={JSON.stringify([params,rows.map(row=>row.review.snapshotId)])}/><ProductNav current="drafts"/><header id="workspace-content" tabIndex={-1} className="product-header compact-header queue-header"><div><h1>Drafts</h1><p>Review and send messages. Contacted recipients move to Sent.</p></div><div className="draft-header-actions"><strong>{rows.length} active {rows.length===1?"draft":"drafts"}</strong>{hasReserve?<AddDraftsControl action={generateMoreDrafts}/>:<Link href="/candidates">Refresh Candidates</Link>}</div></header>
    {params.added!==undefined?<DraftAdditionFeedback added={Number(params.added)||0} requested={Number(params.requested)||0} remaining={Number(params.reserveRemaining)||0}/>:null}{params.sendError?<p role="alert" className="block-message send-result">{humanSendError(params.sendError)}</p>:params.sendStatus==="sent"?<p role="status" className="refresh-result"><strong>Sent.</strong> Continue with the next draft.</p>:params.generationStatus==="ready"?<p role="status" className="refresh-result"><strong>Drafts added.</strong> Review the expanded queue below.</p>:params.skipStatus==="skipped"?<div role="status" className="refresh-result drafts-feedback"><strong>Skipped.</strong><form action={replaceSkippedDraft}><button className="link-button">Replace with another candidate</button></form></div>:params.skipStatus==="excluded"?<p role="status" className="refresh-result"><strong>Person removed.</strong> They will not appear again.</p>:params.replacementStatus==="ready"?<p role="status" className="refresh-result"><strong>Replacement added.</strong></p>:params.replacementStatus==="empty"?<p role="status" className="refresh-result"><strong>No replacement candidates are available.</strong><Link href="/candidates">Refresh Candidates</Link></p>:null}<GmailReadinessPanel connectionState={workflow.gmail.connectionState} readiness={workflow.gmail.readiness}/>
    <section className="product-section"><div className="draft-table" role="table" aria-label="Unsent drafts"><div className="draft-table-head" role="row"><span role="columnheader">Person</span><span role="columnheader">Track</span><span role="columnheader">Role</span><span role="columnheader">State</span><span role="columnheader">Next step</span></div>{rows.length===0?<div className="empty"><strong>No drafts waiting for review.</strong>{hasReserve?<><p>Create another batch from your available candidates.</p><form action={generateMoreDrafts}><button className="primary-action">Add Drafts</button></form></>:<><p>Find more people to contact.</p><Link className="primary-action" href="/candidates">Refresh Candidates</Link></>}</div>:rows.map(({review,state})=>{const sendBlock=gmailSendBlockReason(review,workflow.gmail.readiness),manual=outreach.find((entry)=>entry.snapshotId===review.snapshotId&&!entry.manualSendConfirmed);return <article className="draft-table-row" role="row" key={review.snapshotId} id={`draft-${review.candidateId}`}>
      <div role="cell" className="draft-person"><strong>{state==="ready"?<Link className="row-detail-link" href={`/drafts/review?candidate=${encodeURIComponent(review.candidateId)}`}>{review.recipient}</Link>:review.recipient}</strong><span>{review.company}</span></div><span role="cell" className="track-label">{review.outreachTrack}</span><span role="cell">{review.title}</span><span role="cell" className="state-label">{stateLabel[state]}</span>
      <div role="cell" className="row-action">{state==="ready"?<Link className="primary-action" href={`/drafts/review?candidate=${encodeURIComponent(review.candidateId)}`}>Review</Link>:state==="approved"?<GmailDraftControl snapshotId={review.snapshotId} readiness={workflow.gmail.readiness} action={createGmailDraft}/>:state==="gmail-draft-created"?(sendBlock?<p className="block-message">{humanSendError(sendBlock)}</p>:<><GmailSendControl snapshotId={review.snapshotId} recipient={review.recipient} company={review.company} subject={review.subject} track={review.outreachTrack} action={sendGmailDraft}/>{manual?<details className="manual-fallback"><summary>Sent outside NetworkPilot?</summary><form action={confirmAlreadySent}><input type="hidden" name="id" value={manual.operatorId}/><label>Sent time<input type="datetime-local" name="sentAt" required/></label><button name="confirmation" value="confirmed">Record manual send</button></form></details>:null}</>):<GmailReconciliationControl snapshotId={review.snapshotId} action={reconcileGmailSendStatus}/>}{state!=="needs-send-verification"?<div className="draft-secondary"><form action={skipDraft}><input type="hidden" name="candidateId" value={review.candidateId}/><button>Skip</button></form><details><summary>More</summary><form action={permanentlyExcludeDraft}><input type="hidden" name="candidateId" value={review.candidateId}/><p>Remove this person from all future outreach?</p><button name="confirmation" value="do-not-show-again">Don&apos;t show this person again</button></form></details></div>:null}</div>
    </article>;})}</div></section>
  </main>;
}
