import {describe,expect,it,vi} from "vitest";
import {DAILY_REFRESH_ENRICHMENT_CAP,localCampaignDate,planTrackAwareCandidates,refreshDailyPipeline,type DailyRefreshRepository,type DailyRefreshResult,type RefreshCandidate} from ".";
const candidates=(professional=10,recruiter=5):RefreshCandidate[]=>[...Array.from({length:professional},(_,i)=>({id:`p${i}`,company:`pc${i}`,track:"professional" as const,score:100-i,available:true})),...Array.from({length:recruiter},(_,i)=>({id:`r${i}`,company:`rc${i}`,track:"recruiter" as const,score:90-i,available:true}))];
const repository=():DailyRefreshRepository&{rows:DailyRefreshResult[]}=>({rows:[],findLatest(date){return this.rows.filter((row)=>row.campaignDate===date).at(-1)??null;},save(row){this.rows.push(row);}});
describe("daily refresh",()=>{
 it("plans a deterministic 10 Professional / 5 Recruiter target without cross-track company or person collisions",()=>{const rows=candidates();rows[10]={...rows[10],company:"pc0"};rows.push({...rows[0],company:"duplicate-person-company"});const plan=planTrackAwareCandidates(rows);expect(plan).toHaveLength(15);expect(plan.filter((c)=>c.track==="professional")).toHaveLength(10);expect(new Set(plan.map((c)=>c.company)).size).toBe(plan.length);expect(new Set(plan.map((c)=>c.id)).size).toBe(plan.length);});
 it("uses reserve first and reuses the same-day result without provider calls",async()=>{const repo=repository(),replenish=vi.fn();const input={repository:repo,candidates:candidates(),now:()=>new Date("2026-09-15T14:00:00Z"),replenisher:{replenish},allowProvider:true};const first=await refreshDailyPipeline(input),second=await refreshDailyPipeline(input);expect(first).toEqual(second);expect(replenish).not.toHaveBeenCalled();expect(repo.rows).toHaveLength(1);});
 it("caps optional replenishment at twenty and preserves hard gates",async()=>{const repo=repository(),replenish=vi.fn(async(maximum:number)=>({candidates:[{id:"blocked",company:"x",track:"professional" as const,score:999,available:false},...candidates(Math.min(maximum,10),5)],attempts:20,creditBefore:10,creditAfter:30}));const result=await refreshDailyPipeline({repository:repo,candidates:[],now:()=>new Date("2026-09-15T14:00:00Z"),replenisher:{replenish},allowProvider:true});expect(replenish).toHaveBeenCalledWith(DAILY_REFRESH_ENRICHMENT_CAP);expect(result.candidateIds).not.toContain("blocked");expect(result.shortfall).toBe(0);});
 it("does not replenish without explicit live-provider confirmation",async()=>{const replenish=vi.fn();const result=await refreshDailyPipeline({repository:repository(),candidates:candidates(2,1),now:()=>new Date("2026-09-15T14:00:00Z"),replenisher:{replenish},allowProvider:false});expect(result.shortfall).toBe(12);expect(replenish).not.toHaveBeenCalled();});
 it("reports unexpected credit consumption and rejects a replenisher that exceeds the hard cap",async()=>{const warning=await refreshDailyPipeline({repository:repository(),candidates:[],now:()=>new Date("2026-09-15T14:00:00Z"),allowProvider:true,replenisher:{replenish:async()=>({candidates:[],attempts:2,creditBefore:4,creditAfter:7})}});expect(warning.warning).toContain("credit use differed");await expect(refreshDailyPipeline({repository:repository(),candidates:[],now:()=>new Date("2026-09-16T14:00:00Z"),allowProvider:true,replenisher:{replenish:async()=>({candidates:[],attempts:21,creditBefore:0,creditAfter:21})}})).rejects.toThrow("daily-refresh-enrichment-cap-exceeded");});
 it("requires explicit confirmation for refresh again",async()=>{const repo=repository(),base={repository:repo,candidates:candidates(),now:()=>new Date("2026-09-15T14:00:00Z"),allowProvider:false};await refreshDailyPipeline(base);await expect(refreshDailyPipeline({...base,force:true})).rejects.toThrow("refresh-again-explicit-confirmation-required");});
 it("prepares the next weekday on weekends",()=>{expect(localCampaignDate(new Date("2026-09-19T16:00:00Z"))).toBe("2026-09-21");expect(localCampaignDate(new Date("2026-09-20T16:00:00Z"))).toBe("2026-09-21");});
});
