import {describe,expect,it} from "vitest";
import {planNextDraftBatch,type RefreshCandidate} from ".";

const row=(id:string,track:"professional"|"recruiter",companyKind:"preferred"|"discovered",score:number):RefreshCandidate=>({id,track,companyKind,company:`company-${id}`,score,available:true});

describe("next draft batch",()=>{
  it("targets three professionals, two recruiters, and at least three discovered employers",()=>{const selected=planNextDraftBatch([row("p1","professional","discovered",90),row("p2","professional","discovered",89),row("p3","professional","discovered",88),row("r1","recruiter","discovered",80),row("r2","recruiter","preferred",79),row("preferred-high","professional","preferred",100)]);expect(selected).toHaveLength(5);expect(selected.filter((item)=>item.track==="professional")).toHaveLength(3);expect(selected.filter((item)=>item.track==="recruiter")).toHaveLength(2);expect(selected.filter((item)=>item.companyKind==="discovered").length).toBeGreaterThanOrEqual(3);expect(selected.filter((item)=>item.companyKind==="preferred").length).toBeLessThanOrEqual(2);});
  it("falls back to the best qualified supply",()=>{const selected=planNextDraftBatch(Array.from({length:5},(_,index)=>row(`p${index}`,"professional","preferred",100-index)));expect(selected).toHaveLength(5);});
  it("keeps one person per company",()=>{const duplicate={...row("duplicate","professional","discovered",99),company:"company-p1"};const selected=planNextDraftBatch([row("p1","professional","discovered",100),duplicate,row("p2","professional","discovered",98),row("p3","professional","discovered",97),row("r1","recruiter","discovered",96),row("r2","recruiter","preferred",95)]);expect(new Set(selected.map((item)=>item.company)).size).toBe(selected.length);});
  it.each([[1,1,0],[5,3,2],[10,6,4],[20,12,8]])("supports a %i draft request with a sixty-forty target",(target,professionals,recruiters)=>{const supply=[...Array.from({length:20},(_,index)=>row(`p${index}`,"professional","discovered",100-index)),...Array.from({length:20},(_,index)=>row(`r${index}`,"recruiter","discovered",80-index))],selected=planNextDraftBatch(supply,target);expect(selected).toHaveLength(target);expect(selected.filter((item)=>item.track==="professional")).toHaveLength(professionals);expect(selected.filter((item)=>item.track==="recruiter")).toHaveLength(recruiters);});
  it("limits preferred companies to forty percent when discovered supply exists",()=>{const supply=[...Array.from({length:10},(_,index)=>row(`d${index}`,index<4?"recruiter":"professional","discovered",70-index)),...Array.from({length:10},(_,index)=>row(`x${index}`,index<4?"recruiter":"professional","preferred",100-index))],selected=planNextDraftBatch(supply,10);expect(selected.filter((item)=>item.companyKind==="preferred").length).toBeLessThanOrEqual(4);});
  it("rejects custom sizes outside one through twenty",()=>{expect(()=>planNextDraftBatch([],0)).toThrow("draft-batch-size-invalid");expect(()=>planNextDraftBatch([],21)).toThrow("draft-batch-size-invalid");});
  it("simulates skip, replacement, permanent exclusion, and adding ten without duplicates or provider input",()=>{const supply=[...Array.from({length:18},(_,index)=>row(`p${index}`,"professional",index<12?"discovered":"preferred",100-index)),...Array.from({length:12},(_,index)=>row(`r${index}`,"recruiter",index<8?"discovered":"preferred",80-index))],first=planNextDraftBatch(supply,5),skipped=first[1]!,permanent=first[3]!,used=new Set(first.map((item)=>item.id)),companies=new Set(first.map((item)=>item.company)),replacement=planNextDraftBatch(supply.map((item)=>({...item,available:!used.has(item.id)&&!companies.has(item.company)})),1),blocked=new Set([...used,permanent.id,...replacement.map((item)=>item.id)]),activeCompanies=new Set([...companies,...replacement.map((item)=>item.company)]),added=planNextDraftBatch(supply.map((item)=>({...item,available:!blocked.has(item.id)&&!activeCompanies.has(item.company)})),10),all=[...first.filter((item)=>item.id!==skipped.id&&item.id!==permanent.id),...replacement,...added];expect(replacement).toHaveLength(1);expect(all.some((item)=>item.id===skipped.id)).toBe(false);expect(all.some((item)=>item.id===permanent.id)).toBe(false);expect(new Set(all.map((item)=>item.id)).size).toBe(all.length);expect(new Set(all.map((item)=>item.company)).size).toBe(all.length);expect(added.filter((item)=>item.track==="recruiter")).toHaveLength(4);expect(added.filter((item)=>item.companyKind==="preferred").length).toBeLessThanOrEqual(4);});
});
