import {describe,expect,it} from "vitest";
import {classifyDiscoveredCompany,classifyInternalRecruiterCompany} from "./discovered-company";
describe("broader company discovery",()=>{it("allows a legitimate company outside the preferred registry with provider-backed identity and industry",()=>expect(classifyDiscoveredCompany({name:"Regional Data Works",domain:"regionaldata.example",industrySignal:"Information Technology and Services"})).toMatchObject({eligible:true,kind:"discovered",company:{tier:"tier-2",industryId:"technology-ai"}}));it.each(["Example Staffing","Fast Talent Solutions","Shell Company Returns"])("fails closed for unsafe employer %s",(name)=>expect(classifyDiscoveredCompany({name,domain:"unsafe.example",industrySignal:"Software"}).eligible).toBe(false));it("requires verifiable identity",()=>expect(classifyDiscoveredCompany({name:"Unknown"})).toMatchObject({eligible:false,reason:"company-identity-unverifiable"}));it("fails closed without a supported provider industry",()=>expect(classifyDiscoveredCompany({name:"Opaque Ventures",domain:"opaque.example",industrySignal:"Unknown"})).toMatchObject({eligible:false,reason:"company-industry-unsupported"}));it("keeps the discovered-company profile useful without claiming preferred-company prestige",()=>{const discovered=classifyDiscoveredCompany({name:"Regional Bank",domain:"regionalbank.example",industrySignal:"Banking"}).company!;expect(discovered).toMatchObject({industryId:"financial-services",recognitionScore:65,careerUpsideScore:70});expect(discovered.recognitionScore).toBeLessThan(78);});});

describe("recruiter discovered-company domain safety",()=>{
  it.each(["northwindstaffing.com","northwindrecruit.com","northwind_staffing.com","garbage"])("blocks unsafe recruiter domain %s before company discovery",(domain)=>expect(classifyDiscoveredCompany({name:"Northwind Technology",domain,industrySignal:"Software",recruiterTitleRelevant:true})).toMatchObject({eligible:false}));
  it("does not apply recruiter-only lexical policy to a professional company discovery",()=>expect(classifyDiscoveredCompany({name:"Replacement Software",domain:"replacement.com",industrySignal:"Software",recruiterTitleRelevant:false})).toMatchObject({eligible:true,kind:"discovered"}));
  it("allows a neutral recruiter domain with operating-employer evidence",()=>expect(classifyDiscoveredCompany({name:"Northwind Technology",domain:"northwindcloud.com",industrySignal:"Software",recruiterTitleRelevant:true})).toMatchObject({eligible:true,kind:"discovered"}));
  it("distinguishes missing domain from malformed domain when provider identity exists",()=>{
    expect(classifyInternalRecruiterCompany({name:"Northwind Technology",providerEmployerId:"org-northwind",recruiterTitleRelevant:true})).toMatchObject({eligible:true,kind:"discovered"});
    expect(classifyInternalRecruiterCompany({name:"Northwind Technology",domain:"northwind_staffing.com",providerEmployerId:"org-northwind",recruiterTitleRelevant:true})).toMatchObject({eligible:false,reason:"recruiter-company-domain-ambiguous"});
  });
});
