import { describe,expect,it } from "vitest";
import { CLASSIFICATION_VERSION, type SimulationCandidateSourceRecord as CandidateSourceRecord } from "@/domain/candidates";
import { planDailyCampaign } from "@/domain/planning";
import type { TargetCompany } from "@/domain/targeting";
import { DEFAULT_CANDIDATE_PIPELINE_CONFIG, normalizeCandidateSources } from ".";

const company=(id:string,tier:TargetCompany["tier"]="tier-2",overrides:Partial<TargetCompany>={}):TargetCompany=>({id,canonicalName:id==="strategy-two"?"Strategy Two":"Strategy One",industryId:"technology-ai",tier,enabled:true,recognitionScore:tier==="tier-1"?98:75,careerUpsideScore:tier==="tier-1"?96:82,technicalInterestScore:80,geographicRelevance:["boston-ma"],rationale:"test",provenance:`reviewed:${id}`,lastReviewedDate:"2026-09-08",operatorNotes:"test",...overrides});
const source=(id:string,overrides:Partial<CandidateSourceRecord>={}):CandidateSourceRecord=>({input:{internalId:id,externalSourceReference:`fixture:${id}`,sourceType:"fictional-fixture",retrievedAt:"2026-09-08T12:00:00.000Z",firstName:"Fictional",lastName:id,professionalTitle:"Senior Data Engineer",employerName:`Imaginary ${id}`,industry:"technology-ai",geography:"boston-ma",yearsExperience:10,professionalEmail:`${id}@example.test`,emailVerificationStatus:"verified",roleSignals:["data"],sharedSignals:[],dataQualityIndicators:["complete"],publicCompanyRegistryMatch:{companyId:"strategy-one",matchedBy:"simulation-alias",reviewed:true},rawRecordFingerprint:`fingerprint-${id}`},fictionalEmployer:{id:`employer-${id}`,name:`Imaginary ${id}`,industryId:"technology-ai"},suppliedClassification:{roleFamilyId:"data-analytics",desiredRoleId:"data-engineer",personaId:"senior-ic",industryId:"technology-ai",geographyId:"boston-ma"},scoringSignals:{roleAlignment:90,functionalRelevance:90,sharedSignal:60,roleSpecificUpside:90},controls:{suppressed:false,optedOut:false},targetingProfileVersion:"fixture-v1",companyProfileVersion:"company-fixture-v1",...overrides});
const registry=[company("strategy-one","tier-1"),company("strategy-two","tier-2")];

describe("provider-neutral normalization pipeline",()=>{
 it("derives the authoritative intermediate before constructing a targeting candidate",()=>{const result=normalizeCandidateSources([source("one")],registry)[0];expect(result.normalizedRecord).toMatchObject({classificationVersion:CLASSIFICATION_VERSION,normalizedTitle:"senior data engineer",roleFamilyId:"data-analytics",desiredRoleId:"data-engineer",recipientPersonaId:"senior-ic",industryId:"technology-ai",geographyId:"boston-ma",rejectionCode:null});expect(result.target?.company).toMatchObject({id:"strategy-one",tier:"tier-1",recognitionScore:98,careerUpsideScore:96,technicalInterestScore:80});});
 it("fails conflicting supplied classifications closed",()=>{const item=source("conflict",{suppliedClassification:{roleFamilyId:"technical-product",desiredRoleId:"technical-1",personaId:"team-manager",industryId:"technology-ai",geographyId:"boston-ma"}});expect(normalizeCandidateSources([item],registry)[0].normalizedRecord.rejectionCode).toBe("classification-conflict");});
 it("uses registry values instead of fictional company substitutes",()=>{const result=normalizeCandidateSources([source("one")],registry)[0];expect(result.target?.company?.tier).toBe("tier-1");expect(result.target?.company?.recognitionScore).toBe(98);expect(result.normalizedRecord.companyMatch?.provenance).toBe("reviewed:strategy-one");});
 it("allows a relevant Tier 2 specialist to outrank an unrelated Tier 1 candidate",()=>{const strong=source("strong",{input:{...source("strong").input,publicCompanyRegistryMatch:{companyId:"strategy-two",matchedBy:"simulation-alias",reviewed:true}},scoringSignals:{roleAlignment:98,functionalRelevance:99,sharedSignal:90,roleSpecificUpside:98}});const irrelevant=source("irrelevant",{scoringSignals:{roleAlignment:10,functionalRelevance:5,sharedSignal:90,roleSpecificUpside:90}});const plan=planDailyCampaign(normalizeCandidateSources([irrelevant,strong],registry),[],1,new Date("2026-09-08T12:00:00Z"),7);expect(plan.selected[0].prospectId).toBe("strong");expect(plan.decisions.find((item)=>item.prospectId==="irrelevant")?.hardGateRejectionCode).toBe("recipient-function-unrelated");});
 it("snapshots exact-name, domain, and simulation-alias methods",()=>{const exact=source("exact",{input:{...source("exact").input,employerName:"Strategy One",publicCompanyRegistryMatch:undefined}});const domain=source("domain",{input:{...source("domain").input,employerName:"Unrelated label",employerDomain:"strategy.test",publicCompanyRegistryMatch:undefined}});const alias=source("alias");const config={...DEFAULT_CANDIDATE_PIPELINE_CONFIG,companyDomains:{"strategy-one":"strategy.test"}};expect(normalizeCandidateSources([exact,domain,alias],registry,config).map((item)=>item.normalizedRecord.companyMatch?.method)).toEqual(["simulation-alias","domain","exact-name"]);});
 it("fails domain and industry conflicts closed",()=>{const domain=source("domain",{input:{...source("domain").input,employerName:"Strategy One",employerDomain:"two.test",publicCompanyRegistryMatch:undefined}});const industry=source("industry",{fictionalEmployer:{id:"employer-industry",name:"Imaginary",industryId:"consulting"}});const config={...DEFAULT_CANDIDATE_PIPELINE_CONFIG,companyDomains:{"strategy-one":"one.test","strategy-two":"two.test"}};const results=normalizeCandidateSources([domain,industry],registry,config);expect(results.find((item)=>item.prospect.id==="domain")?.normalizedRecord.rejectionCode).toBe("company-domain-conflict");expect(results.find((item)=>item.prospect.id==="industry")?.normalizedRecord.rejectionCode).toBe("industry-conflict");});
 it.each([company("disabled","tier-2",{enabled:false}),company("unreviewed","unreviewed"),company("excluded","excluded")])("fails prohibited registry record $id closed",(prohibited)=>{const item=source(prohibited.id,{input:{...source(prohibited.id).input,publicCompanyRegistryMatch:{companyId:prohibited.id,matchedBy:"simulation-alias",reviewed:true}}});expect(normalizeCandidateSources([item],[prohibited])[0].normalizedRecord.rejectionCode).toBe("company-prohibited");});
  it("deduplicates idempotent re-ingestion and rejects duplicate fingerprints and people",()=>{const original=source("one");const duplicateFingerprint=source("two",{input:{...source("two").input,rawRecordFingerprint:original.input.rawRecordFingerprint}});const duplicatePerson=source("three",{input:{...source("three").input,firstName:original.input.firstName,lastName:original.input.lastName},fictionalEmployer:original.fictionalEmployer});const results=normalizeCandidateSources([original,structuredClone(original),duplicateFingerprint,duplicatePerson],registry);expect(results).toHaveLength(3);expect(results.find((item)=>item.prospect.id==="two")?.normalizedRecord.rejectionCode).toBe("duplicate-fingerprint");expect(results.find((item)=>item.prospect.id==="three")?.normalizedRecord.rejectionCode).toBe("duplicate-person");});
  it("rejects malformed fingerprints and conflicting source identities deterministically",()=>{const malformed=source("malformed",{input:{...source("malformed").input,rawRecordFingerprint:"bad"}});expect(normalizeCandidateSources([malformed],registry)[0].normalizedRecord.rejectionCode).toBe("fingerprint-invalid");const conflicting=source("one",{input:{...source("one").input,rawRecordFingerprint:"fingerprint-different"}});expect(()=>normalizeCandidateSources([source("one"),conflicting],registry)).toThrow("Conflicting source records");});
  it("rejects invalid score inputs and classification versions",()=>{const invalid=source("invalid",{scoringSignals:{roleAlignment:Number.NaN,functionalRelevance:90,sharedSignal:50,roleSpecificUpside:90}});expect(normalizeCandidateSources([invalid],registry)[0].normalizedRecord.rejectionCode).toBe("candidate-input-invalid");expect(()=>normalizeCandidateSources([source("one")],registry,{...DEFAULT_CANDIDATE_PIPELINE_CONFIG,classificationVersion:"unknown"})).toThrow("Unsupported classification version");});
 it.each([Number.NaN,-1,101])("rejects invalid minimum score %s before normalization",(minimumScore)=>expect(()=>normalizeCandidateSources([source("one")],registry,{...DEFAULT_CANDIDATE_PIPELINE_CONFIG,minimumScore})).toThrow("minimumScore"));
});
