"use server";
import {revalidatePath} from "next/cache";
import {SqliteSimulationRepository} from "@/infrastructure/sqlite/database";
import {listManualDraftOperatorEntries,resolveManualOutreachDatabaseSelection} from "@/infrastructure/sqlite/manual-outreach-operator";
import {confirmManualSendByOperatorId,recordOperatorReportedHardBounce,reportManualOutreachOutcome,resolveManualSendOperatorEntry,MANUAL_OUTREACH_OUTCOMES,type ManualOutreachOutcome} from "@/application/manual-outreach";
import {approveCommandCenterDraft,createCommandCenterGmailDraft} from "@/infrastructure/sqlite/command-center-drafts";
import {runDailyRefreshFromToday} from "@/infrastructure/sqlite/daily-refresh";
import {redirect} from "next/navigation";

function context(){const selection=resolveManualOutreachDatabaseSelection(),entries=listManualDraftOperatorEntries(selection.path),repository=new SqliteSimulationRepository(selection.path);repository.migrate();return{entries,repository};}
export async function confirmAlreadySent(formData:FormData){if(formData.get("confirmation")!=="confirmed")throw new Error("manual-send-explicit-confirmation-required");const id=String(formData.get("id")??""),sentAt=new Date(String(formData.get("sentAt")??"")),{entries,repository}=context();try{confirmManualSendByOperatorId({entries,operatorId:id,effectiveSentAt:sentAt,now:()=>new Date(),repository});}finally{repository.close();}revalidatePath("/today");}
export async function recordOutcome(formData:FormData){const id=String(formData.get("id")??""),outcome=String(formData.get("outcome")??"") as ManualOutreachOutcome;if(!MANUAL_OUTREACH_OUTCOMES.includes(outcome)||outcome==="hard-bounce")throw new Error("manual-outcome-invalid");const{entries,repository}=context();try{const entry=resolveManualSendOperatorEntry(entries,id);reportManualOutreachOutcome({snapshotId:entry.snapshotId,outcome,now:()=>new Date(),repository});}finally{repository.close();}revalidatePath("/today");}
export async function reportDeliveryFailure(formData:FormData){if(formData.get("confirmation")!=="address-not-found")throw new Error("manual-hard-bounce-explicit-confirmation-required");const id=String(formData.get("id")??""),sentAt=new Date(String(formData.get("sentAt")??"")),{entries,repository}=context();try{const entry=resolveManualSendOperatorEntry(entries,id);recordOperatorReportedHardBounce({snapshotId:entry.snapshotId,effectiveSentAt:sentAt,now:()=>new Date(),repository});}finally{repository.close();}revalidatePath("/today");}
export async function approveDraft(formData:FormData){await approveCommandCenterDraft(String(formData.get("snapshotId")??""));revalidatePath("/today");}
export async function createGmailDraft(formData:FormData){await createCommandCenterGmailDraft(String(formData.get("snapshotId")??""));revalidatePath("/today");}
export async function refreshToday(formData:FormData){const allowProvider=formData.get("providerConfirmation")==="confirmed",force=formData.get("force")==="true";if(force&&!allowProvider)redirect("/today?refreshError=confirmation-required");try{await runDailyRefreshFromToday({allowProvider,force});}catch(error){const code=error instanceof Error?error.message:"";if(code==="apollo-feature-disabled"||code==="apollo-api-key-missing")redirect("/today?refreshError=apollo-unavailable");if(code.includes("budget-exhausted"))redirect("/today?refreshError=budget-exhausted");if(code.includes("credit-model"))redirect("/today?refreshError=credit-warning");throw error;}revalidatePath("/today");}
