"use server";
import {draftAdditionDestination} from "@/application/daily-refresh/addition-feedback";
import {revalidatePath} from "next/cache";
import {SqliteSimulationRepository} from "@/infrastructure/sqlite/database";
import {listManualDraftOperatorEntries,resolveManualOutreachDatabaseSelection} from "@/infrastructure/sqlite/manual-outreach-operator";
import {confirmManualSendByOperatorId,recordOperatorReportedHardBounce,reportManualOutreachOutcome,resolveManualSendOperatorEntry,MANUAL_OUTREACH_OUTCOMES,type ManualOutreachOutcome} from "@/application/manual-outreach";
import {approveCommandCenterDraft,approveEditedCommandCenterDraft,createCommandCenterGmailDraft,reconcileCommandCenterGmailSend,sendCommandCenterGmailDraft} from "@/infrastructure/sqlite/command-center-drafts";
import {recordDraftDisposition,replaceBucketDraftFromReserve,resolveBucketDraftCorrection,runDailyRefreshFromToday,runNextDraftBatchFromReserve} from "@/infrastructure/sqlite/daily-refresh";
import {parseBucketScope,type BucketScope} from "@/domain/recipient-buckets";
import {redirect} from "next/navigation";

function refreshProductPages(){for(const path of ["/today","/drafts","/sent","/candidates"])revalidatePath(path);}
function context(){const selection=resolveManualOutreachDatabaseSelection(),entries=listManualDraftOperatorEntries(selection.path),repository=new SqliteSimulationRepository(selection.path);repository.migrate();return{entries,repository};}
export async function confirmAlreadySent(formData:FormData){if(formData.get("confirmation")!=="confirmed")throw new Error("manual-send-explicit-confirmation-required");const id=String(formData.get("id")??""),sentAt=new Date(String(formData.get("sentAt")??"")),{entries,repository}=context();try{confirmManualSendByOperatorId({entries,operatorId:id,effectiveSentAt:sentAt,now:()=>new Date(),repository});}finally{repository.close();}refreshProductPages();}
export async function recordOutcome(formData:FormData){const id=String(formData.get("id")??""),outcome=String(formData.get("outcome")??"") as ManualOutreachOutcome;if(!MANUAL_OUTREACH_OUTCOMES.includes(outcome)||outcome==="hard-bounce")throw new Error("manual-outcome-invalid");const{entries,repository}=context();try{const entry=resolveManualSendOperatorEntry(entries,id);reportManualOutreachOutcome({snapshotId:entry.snapshotId,outcome,now:()=>new Date(),repository});}finally{repository.close();}revalidatePath("/today");}
export async function reportDeliveryFailure(formData:FormData){if(formData.get("confirmation")!=="address-not-found")throw new Error("manual-hard-bounce-explicit-confirmation-required");const id=String(formData.get("id")??""),sentAt=new Date(String(formData.get("sentAt")??"")),{entries,repository}=context();try{const entry=resolveManualSendOperatorEntry(entries,id);recordOperatorReportedHardBounce({snapshotId:entry.snapshotId,effectiveSentAt:sentAt,now:()=>new Date(),repository});}finally{repository.close();}revalidatePath("/today");}
export async function approveDraft(formData:FormData){const resumeId=String(formData.get("resumeId")??"")||undefined,resumeDecision=String(formData.get("resumeDecision")??"")||undefined;await approveCommandCenterDraft(String(formData.get("snapshotId")??""),resumeId,resumeDecision);refreshProductPages();}
const editErrors=new Set(["dylan-voice-em-dash-prohibited","dylan-voice-generic-phrase-prohibited","dylan-voice-subject-invalid","dylan-voice-word-count-invalid","dylan-voice-cta-count-invalid","recipient-bucket-review-required","recruiter-resume-decision-required","resume-copy-mismatch","draft-placeholder-unresolved","draft-unsupported-claim","draft-recipient-invalid"]);
export async function approveEditedDraft(formData:FormData){const snapshotId=String(formData.get("snapshotId")??""),candidateId=String(formData.get("candidateId")??""),resumeId=String(formData.get("resumeId")??""),resumeDecision=String(formData.get("resumeDecision")??"");try{await approveEditedCommandCenterDraft({snapshotId,candidateId,subject:String(formData.get("subject")??""),body:String(formData.get("body")??""),...resumeId?{resumeId}:{},...resumeDecision?{resumeDecision}:{}});}catch(error){const code=error instanceof Error?error.message:"";if(editErrors.has(code))redirect(`/drafts/review?candidate=${encodeURIComponent(candidateId)}&error=${encodeURIComponent(code)}`);throw error;}refreshProductPages();redirect(`/drafts?candidate=${encodeURIComponent(candidateId)}`);}
export async function createGmailDraft(formData:FormData){await createCommandCenterGmailDraft(String(formData.get("snapshotId")??""));refreshProductPages();}
const operatorSafeSendErrors=new Set(["gmail-send-draft-unavailable","gmail-send-reconciliation-required","suppressed","opted-out","previous-contact","company-cooldown","gmail-feature-disabled","gmail-connection-invalid","gmail-scope-invalid","gmail-oauth-configuration-missing","gmail-credential-unavailable","gmail-credential-scope-invalid","gmail-account-unpinned","gmail-authentication-failed","gmail-authorization-failed","gmail-request-invalid","gmail-draft-not-found","gmail-rate-limited","gmail-provider-transient","gmail-timeout","gmail-response-malformed","gmail-transport-failure","gmail-account-ambiguous"]);
export async function sendGmailDraft(formData:FormData){if(formData.get("confirmation")!=="send-approved-draft-now")throw new Error("gmail-send-explicit-confirmation-required");const nextCandidateId=String(formData.get("nextCandidateId")??"");try{await sendCommandCenterGmailDraft(String(formData.get("snapshotId")??""));}catch(error){const code=error instanceof Error?error.message:"";if(operatorSafeSendErrors.has(code))redirect(`/drafts?sendError=${encodeURIComponent(code)}`);throw error;}refreshProductPages();redirect(`/drafts?sendStatus=sent${nextCandidateId?`&candidate=${encodeURIComponent(nextCandidateId)}`:""}`);}
const scopeFromForm=(formData?:FormData):BucketScope|undefined=>parseBucketScope({bucket:formData?.get("bucket"),earlyCareerOnly:formData?.get("earlyCareerOnly")});
const scopeQuery=(scope?:BucketScope)=>scope?`&bucket=${encodeURIComponent(scope.bucket)}${scope.earlyCareerOnly?"&earlyCareerOnly=true":""}`:"";
export async function generateMoreDrafts(formData?:FormData){const raw=formData?.get("additionalDraftCount")??formData?.get("count"),additionalDraftCount=raw===null||raw===undefined||raw===""?5:Number(raw),candidateId=String(formData?.get("candidateId")??""),scope=scopeFromForm(formData),requestId=String(formData?.get("requestId")??"")||undefined;const result=scope?runNextDraftBatchFromReserve(additionalDraftCount,()=>new Date(),scope,requestId):runNextDraftBatchFromReserve(additionalDraftCount),destination=draftAdditionDestination(result.addition!);refreshProductPages();redirect(`${destination}${candidateId?`&candidate=${encodeURIComponent(candidateId)}`:""}${scopeQuery(scope)}`);}
export async function skipDraft(formData:FormData){const nextCandidateId=String(formData.get("nextCandidateId")??"");recordDraftDisposition({candidateId:String(formData.get("candidateId")??""),permanent:false});refreshProductPages();redirect(`/drafts?skipStatus=skipped${nextCandidateId?`&candidate=${encodeURIComponent(nextCandidateId)}`:""}`);}
export async function permanentlyExcludeDraft(formData:FormData){if(formData.get("confirmation")!=="do-not-show-again")throw new Error("permanent-exclusion-confirmation-required");const nextCandidateId=String(formData.get("nextCandidateId")??"");recordDraftDisposition({candidateId:String(formData.get("candidateId")??""),permanent:true});refreshProductPages();redirect(`/drafts?skipStatus=excluded${nextCandidateId?`&candidate=${encodeURIComponent(nextCandidateId)}`:""}`);}
export async function replaceSkippedDraft(){const result=runNextDraftBatchFromReserve(1);refreshProductPages();redirect(draftAdditionDestination(result.addition!));}
export async function replaceDraft(formData:FormData){const candidateId=String(formData.get("candidateId")??""),nextCandidateId=String(formData.get("nextCandidateId")??""),scope=scopeFromForm(formData);if(scope){const result=replaceBucketDraftFromReserve({candidateId,scope}),replacementId=result.replacement?.replacementCandidateId??candidateId;refreshProductPages();redirect(`/drafts?replacementStatus=${result.addition?.addedCount?"ready":"empty"}&candidate=${encodeURIComponent(replacementId)}${scopeQuery(scope)}`);}recordDraftDisposition({candidateId,permanent:false});const result=runNextDraftBatchFromReserve(1),replacementId=result.candidateIds[0]??nextCandidateId;refreshProductPages();redirect(`/drafts?replacementStatus=${result.addition?.addedCount?"ready":"empty"}${replacementId?`&candidate=${encodeURIComponent(replacementId)}`:""}`);}
export async function resolveBucketCorrection(formData:FormData){const candidateId=String(formData.get("candidateId")??""),snapshotId=String(formData.get("snapshotId")??""),decision=String(formData.get("decision")??"");if(decision!=="keep-edits"&&decision!=="regenerate")throw new Error("bucket-copy-decision-invalid");resolveBucketDraftCorrection({candidateId,snapshotId,decision,subject:String(formData.get("subject")??"")||undefined,body:String(formData.get("body")??"")||undefined});refreshProductPages();redirect(`/drafts?candidate=${encodeURIComponent(candidateId)}&bucketCorrection=${encodeURIComponent(decision)}`);}
export async function reconcileGmailSendStatus(formData:FormData){if(formData.get("confirmation")!=="confirmed")throw new Error("gmail-reconciliation-explicit-confirmation-required");const outcome=String(formData.get("outcome")??"") as "sent"|"not-sent"|"still-uncertain";if(!["sent","not-sent","still-uncertain"].includes(outcome))throw new Error("gmail-reconciliation-outcome-invalid");const value=String(formData.get("sentAt")??""),effectiveSentAt=value?new Date(value):undefined;reconcileCommandCenterGmailSend({snapshotId:String(formData.get("snapshotId")??""),outcome,...effectiveSentAt?{effectiveSentAt}:{}});const candidateId=String(formData.get(outcome==="sent"?"nextCandidateId":"candidateId")??"");refreshProductPages();redirect(`/drafts?reconciliationStatus=recorded${candidateId?`&candidate=${encodeURIComponent(candidateId)}`:""}`);}
export async function refreshToday(formData:FormData){const allowProvider=formData.get("providerConfirmation")==="confirmed",force=formData.get("force")==="true";if(force&&!allowProvider)redirect("/today?refreshError=confirmation-required");try{await runDailyRefreshFromToday({allowProvider,force});}catch(error){const code=error instanceof Error?error.message:"";if(code==="apollo-feature-disabled"||code==="apollo-api-key-missing")redirect("/today?refreshError=apollo-unavailable");if(code.includes("budget-exhausted"))redirect("/today?refreshError=budget-exhausted");if(code.includes("credit-model"))redirect("/today?refreshError=credit-warning");throw error;}revalidatePath("/today");}
