"use server";
import {revalidatePath} from "next/cache";
import {SqliteSimulationRepository} from "@/infrastructure/sqlite/database";
import {listManualDraftOperatorEntries,resolveManualOutreachDatabaseSelection} from "@/infrastructure/sqlite/manual-outreach-operator";
import {confirmManualSendByOperatorId,recordOperatorReportedHardBounce,reportManualOutreachOutcome,resolveManualSendOperatorEntry,MANUAL_OUTREACH_OUTCOMES,type ManualOutreachOutcome} from "@/application/manual-outreach";
import {approveCommandCenterDraft,createCommandCenterGmailDraft,reconcileCommandCenterGmailSend,sendCommandCenterGmailDraft} from "@/infrastructure/sqlite/command-center-drafts";
import {runDailyRefreshFromToday} from "@/infrastructure/sqlite/daily-refresh";
import {redirect} from "next/navigation";

function context(){const selection=resolveManualOutreachDatabaseSelection(),entries=listManualDraftOperatorEntries(selection.path),repository=new SqliteSimulationRepository(selection.path);repository.migrate();return{entries,repository};}
export async function confirmAlreadySent(formData:FormData){if(formData.get("confirmation")!=="confirmed")throw new Error("manual-send-explicit-confirmation-required");const id=String(formData.get("id")??""),sentAt=new Date(String(formData.get("sentAt")??"")),{entries,repository}=context();try{confirmManualSendByOperatorId({entries,operatorId:id,effectiveSentAt:sentAt,now:()=>new Date(),repository});}finally{repository.close();}revalidatePath("/today");}
export async function recordOutcome(formData:FormData){const id=String(formData.get("id")??""),outcome=String(formData.get("outcome")??"") as ManualOutreachOutcome;if(!MANUAL_OUTREACH_OUTCOMES.includes(outcome)||outcome==="hard-bounce")throw new Error("manual-outcome-invalid");const{entries,repository}=context();try{const entry=resolveManualSendOperatorEntry(entries,id);reportManualOutreachOutcome({snapshotId:entry.snapshotId,outcome,now:()=>new Date(),repository});}finally{repository.close();}revalidatePath("/today");}
export async function reportDeliveryFailure(formData:FormData){if(formData.get("confirmation")!=="address-not-found")throw new Error("manual-hard-bounce-explicit-confirmation-required");const id=String(formData.get("id")??""),sentAt=new Date(String(formData.get("sentAt")??"")),{entries,repository}=context();try{const entry=resolveManualSendOperatorEntry(entries,id);recordOperatorReportedHardBounce({snapshotId:entry.snapshotId,effectiveSentAt:sentAt,now:()=>new Date(),repository});}finally{repository.close();}revalidatePath("/today");}
export async function approveDraft(formData:FormData){await approveCommandCenterDraft(String(formData.get("snapshotId")??""));revalidatePath("/today");}
export async function createGmailDraft(formData:FormData){await createCommandCenterGmailDraft(String(formData.get("snapshotId")??""));revalidatePath("/today");}
const operatorSafeSendErrors=new Set(["gmail-send-draft-unavailable","gmail-send-reconciliation-required","suppressed","opted-out","previous-contact","company-cooldown","gmail-feature-disabled","gmail-connection-invalid","gmail-scope-invalid","gmail-oauth-configuration-missing","gmail-credential-unavailable","gmail-credential-scope-invalid","gmail-account-unpinned","gmail-authentication-failed","gmail-authorization-failed","gmail-request-invalid","gmail-draft-not-found","gmail-rate-limited","gmail-provider-transient","gmail-timeout","gmail-response-malformed","gmail-transport-failure","gmail-account-ambiguous"]);
export async function sendGmailDraft(formData:FormData){if(formData.get("confirmation")!=="send-approved-draft-now")throw new Error("gmail-send-explicit-confirmation-required");try{await sendCommandCenterGmailDraft(String(formData.get("snapshotId")??""));}catch(error){const code=error instanceof Error?error.message:"";if(operatorSafeSendErrors.has(code))redirect(`/today?sendError=${encodeURIComponent(code)}#next-outreach`);throw error;}revalidatePath("/today");redirect("/today?sendStatus=sent#next-outreach");}
export async function reconcileGmailSendStatus(formData:FormData){if(formData.get("confirmation")!=="confirmed")throw new Error("gmail-reconciliation-explicit-confirmation-required");const outcome=String(formData.get("outcome")??"") as "sent"|"not-sent"|"still-uncertain";if(!["sent","not-sent","still-uncertain"].includes(outcome))throw new Error("gmail-reconciliation-outcome-invalid");const value=String(formData.get("sentAt")??""),effectiveSentAt=value?new Date(value):undefined;reconcileCommandCenterGmailSend({snapshotId:String(formData.get("snapshotId")??""),outcome,...effectiveSentAt?{effectiveSentAt}:{}});revalidatePath("/today");redirect("/today?reconciliationStatus=recorded#next-outreach");}
export async function refreshToday(formData:FormData){const allowProvider=formData.get("providerConfirmation")==="confirmed",force=formData.get("force")==="true";if(force&&!allowProvider)redirect("/today?refreshError=confirmation-required");try{await runDailyRefreshFromToday({allowProvider,force});}catch(error){const code=error instanceof Error?error.message:"";if(code==="apollo-feature-disabled"||code==="apollo-api-key-missing")redirect("/today?refreshError=apollo-unavailable");if(code.includes("budget-exhausted"))redirect("/today?refreshError=budget-exhausted");if(code.includes("credit-model"))redirect("/today?refreshError=credit-warning");throw error;}revalidatePath("/today");}
