import {loadDailyCommandCenter} from "@/infrastructure/sqlite/daily-command-center";
import {confirmAlreadySent,recordOutcome,reportDeliveryFailure,approveDraft,createGmailDraft,sendGmailDraft,refreshToday} from "./actions";
import Link from "next/link";
import {loadCommandCenterDraftReviews} from "@/infrastructure/sqlite/command-center-drafts";
import {gmailSendBlockReason,humanDraftError,humanSendError} from "@/application/command-center-drafts";
import {ConfirmSubmitButton} from "./confirm-submit-button";
import {GmailDraftControl} from "./gmail-draft-control";
import {GmailSendControl} from "./gmail-send-control";
import {OutreachTrackSummary,RecruiterRecommendations,TrackAwareReserve} from "./recruiter-track";
import {loadLatestDailyRefresh} from "@/infrastructure/sqlite/daily-refresh";
import {RefreshControl} from "./refresh-control";
import {localCampaignDate,planTrackAwareCandidates} from "@/application/daily-refresh";
import {isDemoMode} from "@/demo/mode";
import {DemoToday} from "./demo-today";
export const dynamic="force-dynamic";
const label=(value:string)=>value.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("-"," ");
const elapsed=(sent:string|null)=>sent?`${Math.max(0,Math.floor((Date.now()-new Date(sent).getTime())/86400000))}d elapsed`:"Not sent";
export default async function TodayPage(props:{searchParams:Promise<{track?:string;refreshError?:string}>}){if(isDemoMode())return <DemoToday/>;return ProductionTodayPage(props);}
async function ProductionTodayPage({searchParams}:{searchParams:Promise<{track?:string;refreshError?:string}>}){const data=loadDailyCommandCenter(),latestRefresh=loadLatestDailyRefresh(),currentRefresh=latestRefresh?.campaignDate===localCampaignDate(new Date())?latestRefresh:null,workflow=await loadCommandCenterDraftReviews(),professionalDrafts=workflow.items.filter((item)=>item.outreachTrack==="professional"),recruiterDrafts=workflow.items.filter((item)=>item.outreachTrack==="recruiter"),o=data.outreach.outcomes,params=await searchParams,requested=params.track,track=requested==="professional"||requested==="recruiter"?requested:"all",refreshErrors:Record<string,string>={"confirmation-required":"Confirm the displayed Apollo credit boundary before refreshing.","apollo-unavailable":"Reserve is insufficient and Apollo is not configured. Existing safe candidates were not weakened.","budget-exhausted":"The 20-credit daily refresh budget is exhausted. No additional enrichment was attempted.","credit-warning":"Apollo credit telemetry did not match the expected model, so further enrichment stopped."};return <main>
 <nav className="nav"><Link className="brand" href="/today"><span className="brand-mark"><i/><i/><i/></span>Network<span>Pilot</span></Link><div className="nav-meta"><Link href="/today" aria-current="page">Today</Link><a href="#candidate-reserve">Candidate reserve</a><a href="#next-outreach">Draft review</a>{isDemoMode()?<span className="mode-pill"><b/>Demo Mode</span>:<span className="mode-pill"><b/>Human reviewed</span>}</div></nav>
 <section className="today-hero"><div><span className="kicker">Daily command center</span><h1>Today’s outreach</h1><p>Review recommendations, approve exact messages, and decide when a prepared Gmail draft should be sent.</p></div><aside><strong>Human-controlled sending</strong><span>Nothing is sent without a separate, explicit confirmation.</span></aside></section>
 <OutreachTrackSummary professional={professionalDrafts.length} recruiter={recruiterDrafts.length} analytics={data.trackAnalytics}/>
 {params.refreshError?<p role="alert" className="block-message">{refreshErrors[params.refreshError]??"The refresh could not be completed safely. No email was sent."}</p>:null}
 <RefreshControl latest={latestRefresh} current={Boolean(currentRefresh)} providerMayBeNeeded={Boolean(currentRefresh)||planTrackAwareCandidates(data.reserve.map((candidate)=>({id:candidate.id,company:candidate.companyId||candidate.company,track:candidate.track??"professional",score:candidate.score,available:candidate.stage==="qualified-available"}))).length<15} action={refreshToday}/>
 <section className="content-section"><div className="section-heading"><div><span className="kicker">Current outreach</span><h2>{data.outreach.replyEligible} contacts can still reply</h2></div><p>{data.outreach.attempted} attempted · {o["hard-bounce"]} hard bounced · {(data.outreach.bounceRate*100).toFixed(1)}% bounce rate. Small cohort; directional only.</p></div><div className="metric-row">{[["Awaiting",o["awaiting-response"]],["Replied",o.replied],["Meetings",o["meeting-scheduled"]],["Declined",o.declined],["Hard bounce",o["hard-bounce"]],["Opt-out",o["opt-out"]]].map(([l,v])=><article key={l}><span>{l}</span><strong>{v}</strong></article>)}</div></section>
 <section className="content-section soft"><div className="section-heading"><div><span className="kicker">Today’s pipeline</span><h2>From source to human send</h2></div><p>Every number comes from persisted local state.</p></div><div className="stage-row">{Object.entries(data.pipeline).map(([k,v])=><div key={k}><strong>{v}</strong><span>{label(k)}</span></div>)}</div></section>
 <section className="content-section"><div className="section-heading"><div><span className="kicker">Active outreach</span><h2>Sent outreach and saved drafts</h2></div><p>{data.drafts.filter(d=>d.manualSendConfirmed).length} sent attempts recorded · {data.drafts.filter(d=>!d.manualSendConfirmed).length} unsent Gmail drafts. Gmail-confirmed NetworkPilot sends and operator-confirmed external sends retain distinct provenance.</p></div><div className="table-wrap"><table><thead><tr><th>Contact</th><th>Status</th><th>Timing</th><th>Outcome</th><th>Human action</th></tr></thead><tbody>{data.drafts.map(d=><tr className={d.manualSendConfirmed?"sent-outreach":"unsent-draft"} key={d.operatorId}><td>{d.redactedRecipient}<small>{d.title} · {d.company}</small></td><td>Gmail draft created<small>Send recorded: {d.manualSendConfirmed?"yes":"no"}{d.confirmationSource?` · ${d.confirmationSource==="networkpilot-gmail-send"?"Gmail-confirmed NetworkPilot send":"Operator-confirmed external send"}`:""} · Suppressed: {d.suppressed?"yes":"no"}</small></td><td>{d.effectiveSentAt?new Date(d.effectiveSentAt).toLocaleString():"—"}<small>{elapsed(d.effectiveSentAt)}</small></td><td>{d.outcome?label(d.outcome):"—"}<small>{d.responseState?label(d.responseState):"No external outcome recorded"}</small></td><td>{!d.manualSendConfirmed?<><form action={confirmAlreadySent} className="inline-action"><input type="hidden" name="id" value={d.operatorId}/><input name="sentAt" type="datetime-local" required/><ConfirmSubmitButton name="confirmation" value="confirmed" message="This does not send email. Confirm only if you already pressed Send in Gmail.">Confirm I already sent this in Gmail</ConfirmSubmitButton></form><form action={reportDeliveryFailure} className="inline-action danger"><input type="hidden" name="id" value={d.operatorId}/><input name="sentAt" type="datetime-local" required/><ConfirmSubmitButton name="confirmation" value="address-not-found" message="Record a failed attempted delivery and permanently suppress this recipient? This does not verify anything through Gmail.">Report a Send That Bounced</ConfirmSubmitButton></form></>:d.outcome!=="hard-bounce"?<form action={recordOutcome} className="inline-action"><input type="hidden" name="id" value={d.operatorId}/><select name="outcome" defaultValue="awaiting-response"><option value="awaiting-response">Awaiting response</option><option value="replied">Record reply</option><option value="meeting-scheduled">Record meeting scheduled</option><option value="declined">Record decline</option><option value="opt-out">Record opt-out</option><option value="no-response">Record no response</option></select><button>Record human-reported outcome</button></form>:<span>Delivery failure recorded</span>}</td></tr>)}</tbody></table></div></section>
 <RecruiterRecommendations items={recruiterDrafts} readiness={workflow.gmail.readiness} approveAction={approveDraft} createAction={createGmailDraft} sendAction={sendGmailDraft}/>
 <section className="content-section" id="next-outreach"><div className="section-heading"><div><span className="kicker">Next outreach</span><h2>{professionalDrafts.length} messages ready to review</h2></div><p>{new Set(professionalDrafts.map(i=>i.company)).size} companies · individual approval only · never automatically sent.</p></div><div className="review-grid">{professionalDrafts.map(item=>{const sendBlock=gmailSendBlockReason(item,workflow.gmail.readiness);return <article className="message-review" key={item.snapshotId}><header><div><span>Strong match · fit score {item.score}</span><h3>{item.recipient} · {item.company}</h3><p>{item.title} · {label(item.primaryFunction)}{item.secondaryFunctions.length?` (+ ${item.secondaryFunctions.join(", ")})`:""}</p></div><b>{item.operation?.sendState==="sent"?"Sent":item.operation?.state==="gmail-draft-created"?"Gmail Draft Created":item.operation?.state==="approved-for-gmail-draft"?"Approved for Gmail Draft":"Ready for review"}</b></header><dl><div><dt>Experience</dt><dd>{item.experience.toFixed(1)} years supported</dd></div><div><dt>Context</dt><dd>{label(item.industry)} · {label(item.location)} · {label(item.persona)}</dd></div><div><dt>Message</dt><dd>{label(item.lane)} · {label(item.templateVariant)} · {item.wordCount} words</dd></div></dl><details><summary>Review message</summary><div className="draft-preview"><p><strong>To:</strong> {item.recipientEmail}</p><p><strong>Subject:</strong> {item.subject}</p><pre>{item.body}</pre></div></details><details><summary>Why this message?</summary><p>{item.whySelected}</p><small>Message facts: {item.factIds.join(", ")} · template version {item.catalogVersion}</small></details>{item.operation?.sendState==="sent"?<p role="status">Sent</p>:item.operation?.state==="gmail-draft-created"?(sendBlock?<p role="status" className="block-message">{humanSendError(sendBlock)}</p>:<GmailSendControl snapshotId={item.snapshotId} recipient={item.recipient} company={item.company} subject={item.subject} track={item.outreachTrack} action={sendGmailDraft}/>):item.blockedReason?<p role="status" className="block-message">{humanDraftError(item.blockedReason)}</p>:item.operation?.state==="approved-for-gmail-draft"?<GmailDraftControl snapshotId={item.snapshotId} readiness={workflow.gmail.readiness} action={createGmailDraft}/>:<form action={approveDraft}><input type="hidden" name="snapshotId" value={item.snapshotId}/><button className="simulate-button">Approve Draft</button><small>Freezes this exact message inside NetworkPilot. It does not contact Gmail.</small></form>}</article>;})}</div></section>
 <div id="candidate-reserve"><TrackAwareReserve items={data.reserve} track={track}/></div>
 <section className="content-section safety"><div className="section-heading"><div><span className="kicker">Safety and providers</span><h2>Human control remains the boundary</h2></div></div><div className="metric-row"><article><span>Operational datastore</span><strong>available</strong><small>Local and private</small></article><article><span>Send boundary</span><strong>explicit only</strong><small>Approved drafts require confirmation</small></article><article><span>Companies on cooldown</span><strong>{data.safety.cooldownCompanies}</strong></article><article><span>Suppressed</span><strong>{data.safety.suppressed}</strong></article><article><span>Gmail</span><strong>{workflow.gmail.readiness.available?"draft and send ready":workflow.gmail.connected?"needs attention":"not connected"}</strong><small>{workflow.gmail.account} · {workflow.gmail.scopeValid?"compose scope valid":"scope unavailable"}</small></article><article><span>Apollo</span><strong>{data.safety.apolloReady?"ready":data.safety.apolloEnabled?"credential unavailable":"disabled"}</strong></article><article><span>Credit exposure today</span><strong>{data.safety.apolloExposure}</strong></article></div></section>
 </main>}
