import {loadDailyCommandCenter} from "@/infrastructure/sqlite/daily-command-center";
import {confirmAlreadySent,recordOutcome,reportDeliveryFailure,approveDraft,createGmailDraft} from "./actions";
import Link from "next/link";
import {loadCommandCenterDraftReviews} from "@/infrastructure/sqlite/command-center-drafts";
import {humanDraftError} from "@/application/command-center-drafts";
import {ConfirmSubmitButton} from "./confirm-submit-button";
export const dynamic="force-dynamic";
const label=(value:string)=>value.replaceAll("-"," ");
const elapsed=(sent:string|null)=>sent?`${Math.max(0,Math.floor((Date.now()-new Date(sent).getTime())/86400000))}d elapsed`:"Not sent";
export default function TodayPage(){const data=loadDailyCommandCenter(),workflow=loadCommandCenterDraftReviews(),o=data.outreach.outcomes;return <main>
 <nav className="nav"><Link className="brand" href="/"><span className="brand-mark"><i/><i/><i/></span>Network<span>Pilot</span></Link><div className="nav-meta"><Link href="/candidate-review">Candidate reserve</Link><Link href="/draft-studio">Draft studio</Link><span className="mode-pill"><b/>Human reviewed</span></div></nav>
 <section className="today-hero"><div><span className="kicker">Daily command center</span><h1>Good evening.<br/><em>Here’s the outreach picture.</em></h1><p>Review the reserve, prepare thoughtfully, and record only what already happened outside NetworkPilot.</p></div><aside><strong>No email sending</strong><span>Draft creation and manual-send confirmation are separate states.</span></aside></section>
 <section className="content-section"><div className="section-heading"><div><span className="kicker">Current outreach</span><h2>{data.outreach.replyEligible} contacts can still reply</h2></div><p>{data.outreach.attempted} attempted · {o["hard-bounce"]} hard bounced · {(data.outreach.bounceRate*100).toFixed(1)}% bounce rate. Small cohort; directional only.</p></div><div className="metric-row">{[["Awaiting",o["awaiting-response"]],["Replied",o.replied],["Meetings",o["meeting-scheduled"]],["Declined",o.declined],["Hard bounce",o["hard-bounce"]],["Opt-out",o["opt-out"]]].map(([l,v])=><article key={l}><span>{l}</span><strong>{v}</strong></article>)}</div></section>
 <section className="content-section soft"><div className="section-heading"><div><span className="kicker">Today’s pipeline</span><h2>From source to human send</h2></div><p>Every number comes from persisted local state.</p></div><div className="stage-row">{Object.entries(data.pipeline).map(([k,v])=><div key={k}><strong>{v}</strong><span>{label(k)}</span></div>)}</div></section>
 <section className="content-section"><div className="section-heading"><div><span className="kicker">Active cohort</span><h2>Drafts and outcomes</h2></div><p>“Manual send” means Dylan confirmed pressing Send in Gmail. It is not provider-confirmed delivery.</p></div><div className="table-wrap"><table><thead><tr><th>Contact</th><th>Status</th><th>Timing</th><th>Outcome</th><th>Human action</th></tr></thead><tbody>{data.drafts.map(d=><tr key={d.operatorId}><td>{d.redactedRecipient}<small>{d.title} · {d.company}</small></td><td>Gmail draft created<small>Manual send: {d.manualSendConfirmed?"yes":"no"} · Suppressed: {d.suppressed?"yes":"no"}</small></td><td>{d.effectiveSentAt?new Date(d.effectiveSentAt).toLocaleString():"—"}<small>{elapsed(d.effectiveSentAt)}</small></td><td>{d.outcome?label(d.outcome):"—"}<small>{d.responseState?label(d.responseState):"No external outcome recorded"}</small></td><td>{!d.manualSendConfirmed?<><form action={confirmAlreadySent} className="inline-action"><input type="hidden" name="id" value={d.operatorId}/><input name="sentAt" type="datetime-local" required/><ConfirmSubmitButton name="confirmation" value="confirmed" message="This does not send email. Confirm only if you already pressed Send in Gmail.">Confirm I already sent this in Gmail</ConfirmSubmitButton></form><form action={reportDeliveryFailure} className="inline-action danger"><input type="hidden" name="id" value={d.operatorId}/><input name="sentAt" type="datetime-local" required/><ConfirmSubmitButton name="confirmation" value="address-not-found" message="Record a failed attempted delivery and permanently suppress this recipient? This does not verify anything through Gmail.">Report Delivery Failure</ConfirmSubmitButton></form></>:d.outcome!=="hard-bounce"?<form action={recordOutcome} className="inline-action"><input type="hidden" name="id" value={d.operatorId}/><select name="outcome" defaultValue="awaiting-response"><option value="awaiting-response">Awaiting response</option><option value="replied">Record reply</option><option value="meeting-scheduled">Record meeting scheduled</option><option value="declined">Record decline</option><option value="opt-out">Record opt-out</option><option value="no-response">Record no response</option></select><button>Record human-reported outcome</button></form>:<span>Delivery failure recorded</span>}</td></tr>)}</tbody></table></div></section>
 <section className="content-section soft"><div className="section-heading"><div><span className="kicker">Candidate reserve</span><h2>{data.pipeline.available} qualified and available</h2></div><p>Promising candidates remain available even when not chosen today.</p></div><div className="reserve-grid">{data.reserve.slice(0,30).map(c=><article key={c.id}><span>{label(c.stage)}</span><h3>{c.recipient} · {c.company}</h3><p>{c.title}</p><small>{c.functionName} · {c.industry} · {c.persona}</small></article>)}</div></section>
 <section className="content-section"><div className="section-heading"><div><span className="kicker">Next outreach</span><h2>{workflow.items.length} messages ready to review</h2></div><p>{new Set(workflow.items.map(i=>i.company)).size} companies · individual approval only · never automatically sent.</p></div><div className="review-grid">{workflow.items.map(item=><article className="message-review" key={item.snapshotId}><header><div><span>{item.qualification} · score {item.score}</span><h3>{item.recipient} · {item.company}</h3><p>{item.title} · {item.primaryFunction}{item.secondaryFunctions.length?` (+ ${item.secondaryFunctions.join(", ")})`:""}</p></div><b>{item.operation?.state.replaceAll("-"," ")??"local generated"}</b></header><dl><div><dt>Experience</dt><dd>{item.experience.toFixed(1)} years supported</dd></div><div><dt>Context</dt><dd>{item.industry} · {item.location} · {item.persona}</dd></div><div><dt>Message</dt><dd>{item.lane} · {item.templateVariant} · {item.wordCount} words</dd></div></dl><div className="draft-preview"><p><strong>To:</strong> {item.recipientEmail}</p><p><strong>Subject:</strong> {item.subject}</p><pre>{item.body}</pre></div><details><summary>Why this message?</summary><p>{item.whySelected}</p><small>Facts used: {item.factIds.join(", ")} · catalog {item.catalogVersion}</small></details>{item.blockedReason?<p role="status" className="block-message">{humanDraftError(item.blockedReason)}</p>:item.operation?.state==="gmail-draft-created"?<p role="status">Gmail Draft Created</p>:item.operation?.state==="approved-for-gmail-draft"?<form action={createGmailDraft}><input type="hidden" name="snapshotId" value={item.snapshotId}/><button className="simulate-button" disabled={!workflow.gmail.connected||!workflow.gmail.scopeValid||!workflow.gmail.featureEnabled} title={!workflow.gmail.connected?"Connect Gmail first":!workflow.gmail.scopeValid?"Compose scope required":!workflow.gmail.featureEnabled?"Gmail draft feature disabled":"Create approved draft"}>Create Gmail Draft</button></form>:<form action={approveDraft}><input type="hidden" name="snapshotId" value={item.snapshotId}/><button className="simulate-button">Approve Draft</button><small>Approves this exact content; it does not contact Gmail.</small></form>}</article>)}</div></section>
 <section className="content-section safety"><div className="section-heading"><div><span className="kicker">Safety and providers</span><h2>Human control remains the boundary</h2></div></div><div className="metric-row"><article><span>Companies on cooldown</span><strong>{data.safety.cooldownCompanies}</strong></article><article><span>Suppressed</span><strong>{data.safety.suppressed}</strong></article><article><span>Gmail</span><strong>{workflow.gmail.connected?"connected":"not connected"}</strong><small>{workflow.gmail.account} · {workflow.gmail.scopeValid?"compose scope valid":"scope unavailable"}</small></article><article><span>Apollo</span><strong>{data.safety.apolloEnabled?"enabled":"disabled"}</strong></article><article><span>Credit exposure today</span><strong>{data.safety.apolloExposure}</strong></article></div></section>
 </main>}
