import {renderToStaticMarkup} from "react-dom/server";
import {describe,expect,it} from "vitest";
import {OutreachTrackSummary,RecruiterRecommendations,TrackAwareReserve} from "./recruiter-track";
import type {ReserveCandidate} from "@/application/daily-command-center";
import type {CommandCenterDraftReview,GmailDraftReadiness} from "@/application/command-center-drafts";

const candidate=(track:"professional"|"recruiter"):ReserveCandidate=>({id:track,recipient:"A*** R.",company:"Datadog",companyId:"datadog",title:track==="recruiter"?"Technical Recruiter":"Senior Engineer",industry:"Technology",functionName:"technical",persona:"senior",score:90,stage:"qualified-available",track,recruiterType:"technical-recruiter",recruitingDomain:"technical-data-ai",technicalRecruiting:true,earlyCareerRecruiting:false,whySelected:"Internal technical recruiter at a reviewed target company.",draftSubject:"Data engineering and analytics at Datadog",draftBody:"Local preview",draftWordCount:80});
const review=(state:"ready"|"approved"|"created"="ready",blockedReason:string|null=null):CommandCenterDraftReview=>({outreachTrack:"recruiter",candidateId:"recruiter",recipient:"A*** R.",recipientEmail:"fixture@example.invalid",company:"Datadog",companyId:"datadog",title:"Technical Recruiter",primaryFunction:"recruiting",secondaryFunctions:[],persona:"technical-recruiter",experience:8,industry:"Technology",location:"New York",score:90,lane:"recruiter",templateVariant:"technical-recruiting-alignment",qualification:"qualified",whySelected:"Internal technical recruiter at a reviewed target company.",subject:"Data engineering and analytics at Datadog",body:"Local preview",wordCount:80,factIds:["recruiter-technical-title"],catalogVersion:"recruiter-catalog-v1",snapshotId:"command-center:recruiter",operation:state==="ready"?null:{operationId:"gmail-draft:recruiter",snapshot:{} as never,provider:"gmail",state:state==="approved"?"approved-for-gmail-draft":"gmail-draft-created",gmailDraftId:state==="created"?"fixture":null,gmailMessageId:null,attemptStartedAt:null,completedAt:null,errorCategory:null,adapterVersion:"fixture",outreachTrack:"recruiter"},blockedReason,recruiterType:"technical-recruiter",recruitingDomain:"technical-data-ai",technicalRecruiting:true,earlyCareerRecruiting:false});
const ready:GmailDraftReadiness={available:true,reason:null};

describe("Today recruiter track",()=>{
  it("renders the explicit approval, draft creation, and confirmed-send lifecycle",()=>{const approve=()=>{},create=()=>{};const reviewHtml=renderToStaticMarkup(<RecruiterRecommendations items={[review()]} readiness={ready} approveAction={approve} createAction={create} sendAction={create}/>),approvedHtml=renderToStaticMarkup(<RecruiterRecommendations items={[review("approved")]} readiness={ready} approveAction={approve} createAction={create} sendAction={create}/>),createdHtml=renderToStaticMarkup(<RecruiterRecommendations items={[review("created")]} readiness={ready} approveAction={approve} createAction={create} sendAction={create}/>);expect(reviewHtml).toContain("Approve Draft");expect(reviewHtml).toContain("does not contact Gmail");expect(approvedHtml).toContain("Create Gmail Draft");expect(approvedHtml).toContain("never sends email");expect(createdHtml).toContain("Gmail Draft Created");expect(createdHtml).toContain("Send Email");expect(createdHtml).toContain("contacts the recipient immediately");});
  it.each([["suppressed","suppressed"],["previous-contact","already contacted"],["company-cooldown","Someone at this company was contacted recently"]])("shows the %s safety reason instead of an externalization action",(reason,message)=>{const html=renderToStaticMarkup(<RecruiterRecommendations items={[review("approved",reason)]} readiness={ready} approveAction={()=>{}} createAction={()=>{}} sendAction={()=>{}}/>);expect(html).toContain(message);expect(html).not.toContain("Create Gmail Draft");});
  it.each([["gmail-connection-invalid","Gmail is not connected"],["gmail-scope-invalid","required compose scope"]])("disables recruiter Gmail creation for %s",(reason,message)=>{const html=renderToStaticMarkup(<RecruiterRecommendations items={[review("approved")]} readiness={{available:false,reason}} approveAction={()=>{}} createAction={()=>{}} sendAction={()=>{}}/>);expect(html).toContain("disabled");expect(html).toContain(message);});
  it.each([["suppressed","suppressed"],["opted-out","opted out"],["previous-contact","already contacted"],["company-cooldown","contacted recently"]])("hides Send Email when the mutable %s gate fails",(reason,message)=>{const html=renderToStaticMarkup(<RecruiterRecommendations items={[review("created",reason)]} readiness={ready} approveAction={()=>{}} createAction={()=>{}} sendAction={()=>{}}/>);expect(html).not.toContain("Send this email now?");expect(html).toContain(message);});
  it("hides Send Email when runtime Gmail readiness fails",()=>{const html=renderToStaticMarkup(<RecruiterRecommendations items={[review("created")]} readiness={{available:false,reason:"gmail-account-unpinned"}} approveAction={()=>{}} createAction={()=>{}} sendAction={()=>{}}/>);expect(html).not.toContain("Send this email now?");expect(html).toContain("approved Gmail account is not pinned");});
  it("shows track counts and recruiter-specific evidence without classifier jargon",()=>{const html=renderToStaticMarkup(<><OutreachTrackSummary professional={3} recruiter={2}/><RecruiterRecommendations items={[review()]} readiness={ready} approveAction={()=>{}} createAction={()=>{}} sendAction={()=>{}}/></>);expect(html).toContain("3 Professional");expect(html).toContain("2 Recruiter");expect(html).toContain("Technical Recruiter");expect(html).toContain("Technical, data, and AI recruiting");expect(html).not.toContain("recruiter-qualified");});
  it("filters the shared reserve by track",()=>{const html=renderToStaticMarkup(<TrackAwareReserve items={[candidate("professional"),candidate("recruiter")]} track="recruiter"/>);expect(html).toContain("Technical Recruiter");expect(html).not.toContain("Senior Engineer");expect(html).toContain("Professional");expect(html).toContain("Recruiter");});
});
