import Link from "next/link";
import type {ReserveCandidate} from "@/application/daily-command-center";
import {gmailSendBlockReason,humanDraftError,humanSendError,type CommandCenterDraftReview,type GmailDraftReadiness} from "@/application/command-center-drafts";
import {GmailDraftControl} from "./gmail-draft-control";
import {GmailSendControl} from "./gmail-send-control";

const label=(value:string)=>value.replaceAll("-"," ");
const recruitingDomainLabel=(value:ReserveCandidate["recruitingDomain"])=>(value==="technical-data-ai"?"Technical, data, and AI recruiting":value==="early-career"?"Early-career recruiting":"General internal recruiting");
export function OutreachTrackSummary({professional,recruiter,analytics}:{professional:number;recruiter:number;analytics?:import("@/application/daily-command-center").DailyCommandCenterState["trackAnalytics"]}){const detail=(value:NonNullable<typeof analytics>["professional"])=>`${value.replyEligible} reply-eligible · ${value.replies} replies · ${value.meetings} meetings · ${value.declines} declines · ${value.optOuts} opt-outs · ${value.hardBounces} hard bounces`;return <section className="content-section"><div className="section-heading"><div><span className="kicker">Recommended next outreach</span><h2>{professional+recruiter} recommendations across two strategies</h2></div><p><strong>{professional} Professional</strong> · <strong>{recruiter} Recruiter</strong></p></div>{analytics?<div className="metric-row"><article><span>Professional attempts</span><strong>{analytics.professional.attempts}</strong><small>{detail(analytics.professional)}</small></article><article><span>Recruiter attempts</span><strong>{analytics.recruiter.attempts}</strong><small>{detail(analytics.recruiter)}</small></article></div>:null}</section>;}
export function RecruiterRecommendations({items,readiness,approveAction,createAction,sendAction}:{items:readonly CommandCenterDraftReview[];readiness:GmailDraftReadiness;approveAction:(formData:FormData)=>void|Promise<void>;createAction:(formData:FormData)=>void|Promise<void>;sendAction:(formData:FormData)=>void|Promise<void>}){if(!items.length)return null;return <section className="content-section soft"><div className="section-heading"><div><span className="kicker">Recruiter Track</span><h2>{items.length} recruiter introductions ready for review</h2></div><p>Direct, role-aware introductions. Each approval and send requires Dylan’s explicit action.</p></div><div className="review-grid">{items.map((item)=>{const sendBlock=gmailSendBlockReason(item,readiness);return <article className="message-review" key={item.snapshotId}><header><div><span>Recruiter Track</span><h3>{item.recipient} · {item.company}</h3><p>{item.title}</p></div><b>{item.operation?.sendState==="sent"?"Sent":item.operation?.state==="gmail-draft-created"?"Gmail Draft Created":item.operation?.state==="approved-for-gmail-draft"?"Approved for Gmail Draft":"Ready for review"}</b></header><dl><div><dt>Recruiter type</dt><dd>{label(item.recruiterType??"internal recruiter")}</dd></div><div><dt>Recruiting domain</dt><dd>{recruitingDomainLabel(item.recruitingDomain)}</dd></div><div><dt>Evidence</dt><dd>{[item.technicalRecruiting?"Technical recruiting":null,item.earlyCareerRecruiting?"Early-career recruiting":null].filter(Boolean).join(" · ")||"Internal recruiting"}</dd></div><div><dt>Track</dt><dd>Recruiter</dd></div></dl><p>{item.whySelected}</p><details><summary>Review message</summary><div className="draft-preview"><p><strong>Subject:</strong> {item.subject}</p><pre>{item.body}</pre></div></details><small>{item.wordCount} words · recruiter catalog {item.catalogVersion}</small>{item.operation?.sendState==="sent"?<p role="status">Sent</p>:item.operation?.state==="gmail-draft-created"?(sendBlock?<p role="status" className="block-message">{humanSendError(sendBlock)}</p>:<GmailSendControl snapshotId={item.snapshotId} recipient={item.recipient} company={item.company} subject={item.subject} track="recruiter" action={sendAction}/>):item.blockedReason?<p role="status" className="block-message">{humanDraftError(item.blockedReason)}</p>:item.operation?.state==="approved-for-gmail-draft"?<GmailDraftControl snapshotId={item.snapshotId} readiness={readiness} action={createAction}/>:<form action={approveAction}><input type="hidden" name="snapshotId" value={item.snapshotId}/><button className="simulate-button">Approve Draft</button><small>Freezes this exact message inside NetworkPilot. It does not contact Gmail.</small></form>}</article>;})}</div></section>;}
export function TrackAwareReserve({items,track}:{items:readonly ReserveCandidate[];track:"all"|"professional"|"recruiter"}){const shown=track==="all"?items:items.filter((item)=>(item.track??"professional")===track);return <section className="content-section soft"><div className="section-heading"><div><span className="kicker">Candidate reserve</span><h2>{shown.filter((item)=>item.stage==="qualified-available").length} contactable in this view</h2></div><nav aria-label="Filter candidate reserve by outreach track"><Link href="/today?track=all" aria-current={track==="all"?"page":undefined}>All</Link> · <Link href="/today?track=professional" aria-current={track==="professional"?"page":undefined}>Professional</Link> · <Link href="/today?track=recruiter" aria-current={track==="recruiter"?"page":undefined}>Recruiter</Link></nav></div><div className="reserve-grid">{shown.map((item)=><article key={item.id}><span>{item.track==="recruiter"?"Recruiter":"Professional"} · {label(item.stage)}</span><h3>{item.recipient} · {item.company}</h3><p>{item.title}</p><small>{label(item.functionName)} · {label(item.industry)} · {label(item.persona)}</small></article>)}</div></section>;}
