import {renderToStaticMarkup} from "react-dom/server";
import {describe,expect,it} from "vitest";
import {RefreshControl} from "./refresh-control";
describe("Refresh Today control",()=>{
 it("explains provider exposure and no-draft/no-send boundaries",()=>{const html=renderToStaticMarkup(<RefreshControl latest={null} current={false} providerMayBeNeeded action={()=>{}}/>);expect(html).toContain("Refresh Today’s Pipeline");expect(html).toContain("20 Apollo enrichment credits");expect(html).toContain("never creates Gmail drafts automatically");expect(html).toContain("never sends email");expect(html).toContain("required");});
 it("makes a repeated refresh explicit and reports shortfall",()=>{const html=renderToStaticMarkup(<RefreshControl action={()=>{}} current providerMayBeNeeded latest={{id:"x",campaignDate:"2026-09-15",generation:1,createdAt:"2026-09-15T12:00:00Z",candidateIds:[],professionalCount:2,recruiterCount:1,target:15,shortfall:12,reserveCount:3,providerUsed:false,enrichmentAttempts:0,creditBefore:null,creditAfter:null,warning:null}}/>);expect(html).toContain("Refresh Again");expect(html).toContain("12 below the 15-person target");expect(html).toContain("may incur additional provider usage");});
 it("makes reserve-only refresh zero-provider without a paid-use confirmation",()=>{const html=renderToStaticMarkup(<RefreshControl latest={null} current={false} providerMayBeNeeded={false} action={()=>{}}/>);expect(html).toContain("will not contact Apollo");expect(html).not.toContain('name="providerConfirmation"');});
 it("labels a stale plan and offers a normal current-day refresh",()=>{const html=renderToStaticMarkup(<RefreshControl action={()=>{}} current={false} providerMayBeNeeded={false} latest={{id:"x",campaignDate:"2026-09-14",generation:1,createdAt:"2026-09-14T12:00:00Z",candidateIds:[],professionalCount:10,recruiterCount:5,target:15,shortfall:0,reserveCount:20,providerUsed:false,enrichmentAttempts:0,creditBefore:null,creditAfter:null,warning:null}}/>);expect(html).toContain("saved recommendations are from 2026-09-14");expect(html).toContain("Refresh Today’s Pipeline");expect(html).not.toContain("Refresh Again");});
});
