import {describe,expect,it,vi} from "vitest";
import {planCandidateRefresh,refreshCandidateReserve} from ".";
describe("candidate reserve refresh",()=>{
  it("uses reserve first and targets forty",()=>{expect(planCandidateRefresh(42)).toMatchObject({target:40,providerRequired:false,maximumProviderUsage:0});});
  it("bounds provider usage by the deficit and cap",()=>{expect(planCandidateRefresh(10,40,12).maximumProviderUsage).toBe(12);expect(planCandidateRefresh(35,40,20).maximumProviderUsage).toBe(5);});
  it("persists logical accounting and does not call a provider when reserve is full",async()=>{const saveCandidateRefresh=vi.fn(),replenish=vi.fn();await refreshCandidateReserve({usableBefore:40,repository:{saveCandidateRefresh},provider:{replenish},allowProvider:true,now:()=>new Date("2026-09-17T12:00:00Z")});expect(replenish).not.toHaveBeenCalled();expect(saveCandidateRefresh).toHaveBeenCalledWith(expect.objectContaining({usableAfter:40,enrichmentCreditsUsed:0,searchCalls:0}));});
  it("reports qualified track, company, search, and credit accounting",async()=>{const saveCandidateRefresh=vi.fn();const result=await refreshCandidateReserve({usableBefore:20,repository:{saveCandidateRefresh},provider:{replenish:async()=>({attempts:4,searchCalls:4,candidates:[{available:true,track:"professional",company:"one"},{available:true,track:"recruiter",company:"two"},{available:false,track:"professional",company:"three"}]})},allowProvider:true,now:()=>new Date("2026-09-17T12:00:00Z")});expect(result).toMatchObject({qualifiedCandidatesAdded:2,professionalCandidatesAdded:1,recruiterCandidatesAdded:1,companiesAdded:2,searchCalls:4,enrichmentCreditsUsed:4,usableAfter:22});expect(saveCandidateRefresh).toHaveBeenCalledWith(result);});
  it("records each explicit repeat as a logical refresh event",async()=>{const saved:unknown[]=[];const repository={saveCandidateRefresh:(event:unknown)=>saved.push(event)};await refreshCandidateReserve({usableBefore:40,repository,allowProvider:false,now:()=>new Date("2026-09-17T12:00:00Z")});await refreshCandidateReserve({usableBefore:40,repository,allowProvider:false,now:()=>new Date("2026-09-17T12:01:00Z")});expect(saved).toHaveLength(2);});
});
