import type {RefreshDiagnostics} from "./diagnostics";
export const DEFAULT_RESERVE_TARGET=40;
export const DEFAULT_REFRESH_PROVIDER_CAP=20;
export interface CandidateRefreshPlan {usableBefore:number;target:number;deficit:number;providerCap:number;maximumProviderUsage:number;providerRequired:boolean;}
export interface CandidateRefreshResult extends CandidateRefreshPlan {diagnostics?:RefreshDiagnostics;id:string;createdAt:string;searchCalls:number;enrichmentCreditsUsed:number;preferredEnrichmentAttempts?:number;discoveredEnrichmentAttempts?:number;recruiterEnrichmentAttempts?:number;candidatesAdded:number;qualifiedCandidatesAdded:number;professionalCandidatesAdded:number;recruiterCandidatesAdded:number;companiesAdded:number;usableAfter:number;}
export interface CandidateRefreshRepository {saveCandidateRefresh(result:CandidateRefreshResult):void;}
export interface CandidateRefreshProvider {replenish(maximum:number):Promise<{diagnostics?:RefreshDiagnostics;candidates:Array<{available:boolean;track?:"professional"|"recruiter";company?:string}>;attempts:number;searchCalls?:number;preferredAttempts?:number;discoveredAttempts?:number;recruiterAttempts?:number}>;}

export function planCandidateRefresh(usableBefore:number,target=DEFAULT_RESERVE_TARGET,providerCap=DEFAULT_REFRESH_PROVIDER_CAP):CandidateRefreshPlan{
  if(!Number.isInteger(usableBefore)||usableBefore<0||!Number.isInteger(target)||target<1||!Number.isInteger(providerCap)||providerCap<0)throw new Error("candidate-refresh-configuration-invalid");
  const deficit=Math.max(0,target-usableBefore);return{usableBefore,target,deficit,providerCap,maximumProviderUsage:Math.min(deficit,providerCap),providerRequired:deficit>0};
}
export async function refreshCandidateReserve(input:{usableBefore:number;repository:CandidateRefreshRepository;provider?:CandidateRefreshProvider;allowProvider:boolean;now:()=>Date;target?:number;providerCap?:number}):Promise<CandidateRefreshResult>{
  let diagnostics:RefreshDiagnostics|undefined;const plan=planCandidateRefresh(input.usableBefore,input.target,input.providerCap),id=`candidate-refresh:${input.now().toISOString()}`;let attempts=0,searchCalls=0,preferredEnrichmentAttempts=0,discoveredEnrichmentAttempts=0,recruiterEnrichmentAttempts=0,candidatesAdded=0,qualifiedCandidatesAdded=0,professionalCandidatesAdded=0,recruiterCandidatesAdded=0,companiesAdded=0;
  if(plan.providerRequired&&input.allowProvider&&input.provider&&plan.maximumProviderUsage>0){const supplied=await input.provider.replenish(plan.maximumProviderUsage);if(supplied.attempts>plan.maximumProviderUsage)throw new Error("candidate-refresh-provider-cap-exceeded");diagnostics=supplied.diagnostics;attempts=supplied.attempts;searchCalls=supplied.searchCalls??0;preferredEnrichmentAttempts=supplied.preferredAttempts??0;discoveredEnrichmentAttempts=supplied.discoveredAttempts??0;recruiterEnrichmentAttempts=supplied.recruiterAttempts??0;candidatesAdded=supplied.candidates.length;const qualified=supplied.candidates.filter((candidate)=>candidate.available);qualifiedCandidatesAdded=qualified.length;professionalCandidatesAdded=qualified.filter((candidate)=>candidate.track!=="recruiter").length;recruiterCandidatesAdded=qualified.filter((candidate)=>candidate.track==="recruiter").length;companiesAdded=new Set(qualified.map((candidate)=>candidate.company).filter(Boolean)).size;}
  const result={...plan,...diagnostics?{diagnostics}:{},id,createdAt:input.now().toISOString(),searchCalls,enrichmentCreditsUsed:attempts,preferredEnrichmentAttempts,discoveredEnrichmentAttempts,recruiterEnrichmentAttempts,candidatesAdded,qualifiedCandidatesAdded,professionalCandidatesAdded,recruiterCandidatesAdded,companiesAdded,usableAfter:input.usableBefore+qualifiedCandidatesAdded};input.repository.saveCandidateRefresh(result);return result;
}
