import {DEFAULT_RESERVE_TARGET,planCandidateRefresh} from "@/application/candidate-refresh";
import {humanScopedDiscoveryReadiness,type ScopedDiscoveryReadiness} from "@/application/candidate-refresh/scoped-readiness";
import {refreshCandidates} from "./actions";
const labels={recruiters:"recruiters",peers:"peers",managers:"managers",executives:"executives",ceos:"CEOs and presidents"} as const;
export function CandidateRefreshControl({available,totalReserve=available,exposure=0,maximumPerBatch=20,maximumPerDay=20,fiveBucketEnabled=false,bucket,earlyCareerOnly=false,legacyView=false,requestId,readiness}:{available:number;totalReserve?:number;exposure?:number;maximumPerBatch?:number;maximumPerDay?:number;fiveBucketEnabled?:boolean;bucket?:keyof typeof labels;earlyCareerOnly?:boolean;legacyView?:boolean;requestId?:string;readiness?:ScopedDiscoveryReadiness}){
  const remaining=Math.max(0,maximumPerDay-exposure),plan=planCandidateRefresh(available,DEFAULT_RESERVE_TARGET,Math.min(maximumPerBatch,remaining)),label=fiveBucketEnabled&&bucket?labels[bucket]:"candidates",title=fiveBucketEnabled?`Find more ${label}`:"Refresh Candidates";
  if(legacyView)return <p className="budget-message" role="status">Legacy / unclassified candidates are not actionable. Review bucket evidence before finding more in a bucket.</p>;
  if(fiveBucketEnabled&&!bucket)return <p className="budget-message" role="status">Choose a recipient bucket to find more within that scope. The provider allowance is shared across all buckets.</p>;
  if(fiveBucketEnabled&&readiness&&!readiness.ready)return <div className="budget-message" role="status"><strong>Find More is blocked</strong><small>{humanScopedDiscoveryReadiness(readiness)}</small></div>;
  if(remaining===0)return <p className="budget-message" role="status">Candidate refresh is available again tomorrow.<small>Your drafts and outreach are still available. The shared provider allowance is exhausted across all buckets.</small></p>;
  return <details className="refresh-candidates"><summary>{title}</summary><div><h3>{fiveBucketEnabled&&bucket?`Find more ${label}?`:"Find more candidates?"}</h3><dl><div><dt>{fiveBucketEnabled&&bucket?`Total ${label} in reserve`:"Total reserve"}</dt><dd>{totalReserve}</dd></div><div><dt>Available for new drafts</dt><dd>{available}</dd></div><div><dt>Target reserve</dt><dd>{DEFAULT_RESERVE_TARGET}</dd></div><div><dt>Maximum credits</dt><dd>{Math.min(plan.maximumProviderUsage,remaining)}</dd></div></dl><p>{earlyCareerOnly?"Scope: Early-career peers only. ":""}{plan.providerRequired?`This search is scoped to ${label} and uses the shared allowance. NetworkPilot will use existing reserve first, then request only additional candidates needed.`:"This bucket reserve already meets the target. No search is needed."}</p><form action={refreshCandidates}><input type="hidden" name="confirmation" value="confirmed"/><input type="hidden" name="allowProvider" value="yes"/><input type="hidden" name="requested" value={plan.maximumProviderUsage}/>{bucket?<input type="hidden" name="bucket" value={bucket}/>:null}{earlyCareerOnly?<input type="hidden" name="earlyCareerOnly" value="true"/>:null}{requestId?<input type="hidden" name="requestId" value={requestId}/>:null}<button disabled={!plan.providerRequired}>Find more {fiveBucketEnabled&&bucket?label:"candidates"}</button></form></div></details>;
}
