import { getDashboardData } from "@/application/simulation/dashboard";
import { DECISION_REASON_CODES, INDUSTRIES } from "@/domain/outreach";
import { getSimulationRepository } from "@/infrastructure/sqlite/runtime";
import { runTodaySimulation } from "./actions";
import { ReadySimulationControl, SimulationUnavailableControl } from "./simulation-control";
import {readApolloConfig,APOLLO_ADAPTER_VERSION} from "@/infrastructure/providers/apollo";
export const dynamic = "force-dynamic";
const labels: Record<(typeof DECISION_REASON_CODES)[number], string> = { "suppressed": "Suppressed", "opted-out": "Opted out", "email-unverified": "Email unverified", "insufficient-experience": "Insufficient experience", "previously-contacted": "Previously contacted", "company-in-cooldown": "Company in cooldown", "duplicate-company-in-run": "Duplicate company", "eligible-below-cutoff": "Below daily cutoff", "selected": "Selected" };
export default function Home() {
  const repository=getSimulationRepository(),data = getDashboardData(repository, new Date()),apollo=readApolloConfig(process.env),apolloStatus=repository.getApolloProviderStatus(data.today);
  const totals = Object.fromEntries(DECISION_REASON_CODES.map((code) => [code, data.latestRun?.decisions.filter((d) => d.reasonCode === code).length ?? 0]));
  return <main>
    <nav className="nav"><a className="brand" href="#top"><span className="brand-mark"><i/><i/><i/></span>Network<span>Pilot</span></a><div className="nav-meta"><a href="/today">Today</a><a href="#campaign-plan">Campaign Plan</a><a href="/candidate-review">Candidate Review</a><a href="/draft-studio">Draft Studio</a><span className="private-label">Fictional data only</span><span className="mode-pill"><b/> Simulation mode</span></div></nav>
    <section className="hero dashboard-hero" id="top"><div className="eyebrow"><span>Campaign workspace</span>{data.isWeekday ? "Sending day" : "Weekend pause"}</div><h1>Today’s fictional<br/><em>campaign simulation.</em></h1><p className="hero-copy">Campaign date <strong>{data.today}</strong> in <strong>{data.timezone}</strong>. Every record is fabricated and every delivery is simulated.</p><div className="notice"><span className="notice-icon">S</span><div><strong>Live sending is disabled</strong><small>Contact sourcing, external research, drafting providers, and email delivery remain disconnected.</small></div><span className="secure">Isolated</span></div>{data.simulationReady ? <ReadySimulationControl action={runTodaySimulation} existing={Boolean(data.latestRun)}/> : <SimulationUnavailableControl/>}</section>
    <section className="content-section" id="campaign-plan"><div className="section-heading"><div><span className="kicker">Targeting-first plan</span><h2>{data.latestPlan ? "Persisted campaign plan" : "No plan yet"}</h2></div><p>{data.latestPlan ? `${data.latestPlan.planVersion} · ${data.latestPlan.targetingVersion} · ${data.latestPlan.status}` : "Run the simulation to normalize, gate, score, diversify, and persist a fictional plan."}</p></div><div className="rule-grid four">{[["Daily target",data.latestRun?.target ?? "—","randomized once, 15–20"],["Qualified",data.latestPlan?.decisions.filter((d)=>!d.hardGateRejectionCode).length ?? "—","passed hard gates and score floor"],["Selected",data.latestPlan?.selected.length ?? "—","plan reservations; no delivery"],["Relaxations",data.latestPlan?.quotaRelaxations.length ?? "—","persisted soft-cap decisions"]].map(([label,value,detail])=><article className="rule-card" key={label}><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>)}</div></section>
    <section className="industry-section decision-section"><div><span className="kicker">Explainable qualification</span><h2>Every decision has a reason</h2><p>Stable reason codes preserve an auditable snapshot even when a fictional prospect changes later.</p></div><ul>{DECISION_REASON_CODES.map((code,i)=><li key={code}><span>{String(i+1).padStart(2,"0")}</span>{labels[code]}<b>{totals[code]}</b></li>)}</ul></section>
    <section className="content-section"><div className="section-heading"><div><span className="kicker">Ranked decisions</span><h2>Fictional candidate plan</h2></div><p>A simulation alias exercises a public-company strategy record. It is not an employment claim, and the fictional employer remains separately labeled.</p></div>{data.latestPlan?.decisions.length ? <div className="table-wrap"><table><thead><tr><th>Rank / candidate</th><th>Fictional employer / strategy</th><th>Normalized classification</th><th>Registry inputs</th><th>Score</th><th>Decision</th></tr></thead><tbody>{data.latestPlan.decisions.map((d)=><tr key={d.prospectId}><td>{d.rankBeforeDiversification ?? "—"} · {d.prospectName}<small>Normalized: {d.normalizedTitle} · {d.classificationVersion}</small></td><td>{d.fictionalEmployer.name}<small>Strategy: {d.strategyCompanyMatch?.canonicalName ?? "No approved match"} · {d.matchMethod ?? "unmatched"}</small></td><td>{d.desiredRoleFamily}<small>{d.desiredRoleId} · recipient {d.recipientPersona} · {d.classificationExplanationCodes.join(", ")}{d.classificationReviewCode?` · review: ${d.classificationReviewCode}`:""}</small></td><td>{d.companyTier ?? "—"}<small>Recognition {d.companyRecognition} · Upside {d.companyCareerUpside} · Technical {d.companyTechnicalInterest}</small></td><td>{d.totalScore}<small>{d.components.map((c)=>`${c.id} ${c.weighted.toFixed(1)}`).join(" · ")}</small></td><td>{d.selected?"Selected":"Excluded"}<small>{d.selectionReason}</small></td></tr>)}</tbody></table></div>:<div className="empty">{data.prospectCount ? "No fictional plan has been created today." : "No fictional dataset found. Run npm run db:seed to begin."}</div>}</section>
    <section className="content-section pipeline-section"><div className="section-heading"><div><span className="kicker">Run history</span><h2>Recent simulations</h2></div><p>{data.prospectCount} fictional prospects across {INDUSTRIES.length} target industries.</p></div>{data.recentRuns.length?<div className="pipeline">{data.recentRuns.map((run)=><article key={run.id}><span className="pipeline-number">{run.campaignDate}</span><div><h3>{run.status === "completed" ? "Weekday simulation" : "Weekend — no send"}</h3><p>Target {run.target} · Selected {run.selectedCount} · Shortfall {run.shortfall}</p></div><span className="offline"><b/>Stored</span></article>)}</div>:<div className="empty">No simulation history yet.</div>}</section>
    <section className="content-section"><div className="section-heading"><div><span className="kicker">Provider boundary</span><h2>Apollo read-only adapter</h2></div><p>{APOLLO_ADAPTER_VERSION} · {apollo.enabled?"feature enabled":"feature disabled"} · no live access validated</p></div><div className="rule-grid four">{[["Enrichment attempts",apolloStatus.attempted,"today"],["Authorized exposure",apolloStatus.estimatedExposure,`daily cap ${apollo.maxEnrichmentsPerDay}`],["Observed credits",apolloStatus.observedConsumption??"unknown","never inferred"],["Provider failures",apolloStatus.failed,apollo.enabled?"guarded":"network incapable"]].map(([label,value,detail])=><article className="rule-card" key={label}><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>)}</div><p>Search is staged before deliberate enrichment. The API key is server-only and is never displayed. No provider action is available in this interface.</p></section>
    <footer><span>NetworkPilot</span><p>Persistent fictional campaign · SQLite local only</p><span>Live sending disabled</span></footer>
  </main>;
}
