import {readFileSync} from "node:fs";
import {join} from "node:path";
import {describe,expect,it} from "vitest";

const source=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");
describe("v1 daily workflow UX",()=>{
  it("keeps responsive metadata, keyboard landmarks and persistent queue selection",()=>{
    const css=source("src/app/product.css"),workspace=source("src/app/drafts/drafts-workspace.tsx"),workspaceCss=source("src/app/drafts/drafts-workspace.module.css");
    expect(source("src/app/product-nav.tsx")).toContain("Skip to content");
    for(const page of ["today","sent","candidates"])expect(source(`src/app/${page}/page.tsx`)).toContain('id="workspace-content"');
    expect(workspace).toContain('id="workspace-content"');
    expect(css).toContain(":focus-visible");expect(css).toContain("content:attr(data-label)");
    expect(workspaceCss).toContain(":focus-visible");expect(workspaceCss).toContain("@media(max-width:860px)");
    expect(workspace).toContain("setSelectedId");expect(workspace).toContain("window.history.replaceState");expect(workspace).toContain('key==="j"||key==="k"');
  });
  it("keeps dialogs keyboard-contained and implements only the four approved motion families",()=>{const workspace=source("src/app/drafts/drafts-workspace.tsx"),css=source("src/app/drafts/drafts-workspace.module.css");expect(workspace).toContain('input:not([type="hidden"]):not(:disabled)');expect(workspace).toContain('event.key!=="Tab"');expect(workspace).toContain("returnFocus");expect(css.match(/@keyframes/g)).toHaveLength(4);for(const motion of ["selectionTracking","queueReflow","commandResponse","lifecycleTransfer"])expect(css).toContain(`@keyframes ${motion}`);expect(css).toContain("prefers-reduced-motion:reduce");});
  it("keeps the four primary destinations and a secondary system destination",()=>{const nav=source("src/app/product-nav.tsx");for(const value of ["Today","Drafts","Sent","Candidates"])expect(nav).toContain(value);expect(nav).toContain('className="secondary-nav"');expect(nav).toContain("aria-current");});
  it("keeps sent work out of Drafts and maps one primary action per draft state",()=>{const workflow=source("src/application/product-workflow/index.ts"),ui=source("src/app/drafts/drafts-workspace.tsx");expect(workflow).toContain("manualSendConfirmed");expect(workflow).toContain('sendState!=="sent"');for(const action of ["Approve draft","Create Gmail Draft","Send email","Resolve send status"])expect(ui).toContain(action);});
  it("supports pre-approval editing and immutable approval",()=>{const review=source("src/app/drafts/drafts-workspace.tsx"),projection=source("src/app/drafts/workspace-data.ts"),infra=source("src/infrastructure/sqlite/command-center-drafts.ts");expect(review).toContain('name="subject"');expect(review).toContain('name="body"');expect(review).toContain("Approve draft");expect(projection).toContain('state!=="ready"?review.operation?.snapshot:null');expect(infra).toContain("prepareEditedDraft");expect(infra).toContain("approveForGmailDraft");});
  it("offers explicit single-resume selection with a None default and private management surface",()=>{const review=source("src/app/drafts/drafts-workspace.tsx"),resumes=source("src/app/resumes/page.tsx");expect(review).toContain('name="resumeId" defaultValue=""');expect(review).toContain('<option value="">None</option>');expect(review).toContain('selected.state==="ready"');for(const text of ["Upload a resume","PDF only, up to 10 MB","Deactivate","Kept for historical attachment evidence"])expect(resumes).toContain(text);});
  it("uses stable candidate lookup and the newest immutable operation after a failed attempt",()=>{const screen=source("src/app/drafts/drafts-screen.tsx"),projection=source("src/app/drafts/workspace-data.ts"),infra=source("src/infrastructure/sqlite/draft-queue.ts");expect(screen).toContain("row.review.candidateId===candidateId");expect(projection).toContain("review.operation?.snapshot");expect(infra).toContain("ORDER BY updated_at_utc,operation_id");});
  it("shows Product and reserve refresh confirmation in product language",()=>{const candidates=source("src/app/candidates/page.tsx"),refresh=source("src/app/candidates/refresh-control.tsx");expect(candidates).toContain('"Product"');expect(candidates).toContain("Role family");for(const text of ["Usable now","Target reserve","Maximum credits","Refresh"])expect(refresh).toContain(text);});
  it("covers reconnect, uncertain send, empty states, filters, and cross-page refresh",()=>{const workspace=source("src/app/drafts/drafts-workspace.tsx"),actions=source("src/app/today/actions.ts");expect(source("src/app/today/gmail-readiness-panel.tsx")).toContain("Reconnect Gmail");expect(workspace).toContain("could not confirm whether Gmail sent");expect(workspace).toContain("No drafts waiting for review");expect(workspace).toContain("Add drafts");expect(workspace).toContain("Refresh Candidates");expect(actions).toContain("sendStatus=sent");expect(actions).not.toContain("/sent?sendStatus=sent");expect(source("src/app/sent/page.tsx")).toContain("No outreach sent yet");expect(source("src/app/candidates/page.tsx")).toContain("No available candidates.");expect(source("src/app/sent/page.tsx")).toContain('aria-current={params.outcome===filter');for(const page of ["/today","/drafts","/sent","/candidates"])expect(actions).toContain(`"${page}"`);});
  it("exposes bounded draft controls and keeps System secondary",()=>{const drafts=source("src/app/drafts/drafts-workspace.tsx"),today=source("src/app/today/page.tsx"),nav=source("src/app/product-nav.tsx");expect(drafts).toContain("Add drafts");expect(drafts).toContain("Add 5");expect(drafts).toContain("Add 10");expect(drafts).toContain('min="1" max="20"');expect(drafts).toContain("Skip");expect(drafts).toContain("Don&apos;t show this person again");expect(drafts).toContain("Replace");expect(today).toContain("AddDraftsControl");expect(nav).toContain('className="secondary-nav"');});
});
