import {readFileSync} from "node:fs";
import {join} from "node:path";
import {describe,expect,it} from "vitest";

const source=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");
describe("v1 daily workflow UX",()=>{
  it("keeps the four primary destinations and a secondary system destination",()=>{const nav=source("src/app/product-nav.tsx");for(const value of ["Today","Drafts","Sent","Candidates"])expect(nav).toContain(value);expect(nav).toContain('className="secondary-nav"');expect(nav).toContain("aria-current");});
  it("keeps sent work out of Drafts and maps one primary action per draft state",()=>{const workflow=source("src/application/product-workflow/index.ts"),ui=["src/app/drafts/page.tsx","src/app/today/gmail-draft-control.tsx","src/app/today/gmail-send-control.tsx","src/app/today/gmail-reconciliation-control.tsx"].map(source).join("\n");expect(workflow).toContain("manualSendConfirmed");expect(workflow).toContain('sendState!=="sent"');for(const action of ["Review","Create Gmail Draft","Send Email","Verify Send"])expect(ui).toContain(action);});
  it("supports pre-approval editing and immutable approval",()=>{const review=source("src/app/drafts/review/page.tsx"),infra=source("src/infrastructure/sqlite/command-center-drafts.ts");expect(review).toContain('name="subject"');expect(review).toContain('name="body"');expect(review).toContain("Approve message");expect(infra).toContain("prepareEditedDraft");expect(infra).toContain("approveForGmailDraft");});
  it("uses stable candidate lookup and the newest immutable operation after a failed attempt",()=>{const drafts=source("src/app/drafts/page.tsx"),review=source("src/app/drafts/review/page.tsx"),infra=source("src/infrastructure/sqlite/command-center-drafts.ts");expect(drafts).toContain("review.candidateId");expect(review).toContain("item.candidateId===candidateId");expect(infra).toContain("ORDER BY updated_at_utc DESC,operation_id DESC");});
  it("shows Product and reserve refresh confirmation in product language",()=>{const candidates=source("src/app/candidates/page.tsx"),refresh=source("src/app/candidates/refresh-control.tsx");expect(candidates).toContain('"Product"');expect(candidates).toContain("Role family");for(const text of ["Usable now","Target reserve","Maximum credits","Refresh"])expect(refresh).toContain(text);});
  it("covers reconnect, uncertain send, empty states, filters, and cross-page refresh",()=>{expect(source("src/app/today/gmail-readiness-panel.tsx")).toContain("Reconnect Gmail");expect(source("src/app/today/gmail-reconciliation-control.tsx")).toContain("could not confirm whether Gmail sent");expect(source("src/app/drafts/page.tsx")).toContain("You&apos;re caught up.");expect(source("src/app/drafts/page.tsx")).toContain("Generate More Drafts");expect(source("src/app/drafts/page.tsx")).toContain("Refresh Candidates");expect(source("src/app/today/actions.ts")).toContain("redirect(\"/drafts?sendStatus=sent\")");expect(source("src/app/today/actions.ts")).not.toContain("redirect(\"/sent?sendStatus=sent\")");expect(source("src/app/sent/page.tsx")).toContain("No outreach sent yet");expect(source("src/app/candidates/page.tsx")).toContain("No available candidates match");expect(source("src/app/sent/page.tsx")).toContain('aria-current={params.outcome===filter');for(const page of ["/today","/drafts","/sent","/candidates"])expect(source("src/app/today/actions.ts")).toContain(`"${page}"`);});
  it("exposes bounded draft controls and keeps System secondary",()=>{const drafts=source("src/app/drafts/page.tsx"),today=source("src/app/today/page.tsx"),nav=source("src/app/product-nav.tsx");expect(drafts).toContain("Add Drafts");expect(drafts).toContain("Add 5");expect(drafts).toContain("Add 10");expect(drafts).toContain('min="1" max="20"');expect(drafts).toContain("Skip");expect(drafts).toContain("Don&apos;t show this person again");expect(drafts).toContain("Replace with another candidate");expect(today).toContain("Add Drafts");expect(nav).toContain('className="secondary-nav"');});
});
