import {createHash} from "node:crypto";
import type {ImportedCandidateSnapshot} from "@/application/ingestion";
import type {CandidateInput,NormalizedCandidateRecord} from "@/domain/candidates";
import {draftWordCount,PROHIBITED_DRAFT_PHRASES,renderDraft,selectTemplateWithReason,type RenderedDraft} from "@/domain/drafting";
import type {Prospect} from "@/domain/outreach";
import {planDailyCampaign,type DailyPlanResult,type PlanningCandidate,type TargetingPlanSnapshot} from "@/domain/planning";
import {CONTACT_PERSONAS,GEOGRAPHY_PREFERENCES,INDUSTRY_PREFERENCES,TARGET_COMPANIES,TARGET_ROLES,type TargetCompany} from "@/domain/targeting";

export interface ControlledDraftPreview {candidateReference:string;redactedName:string;company:string;sourceTitle:string;recipientFunction:string|null;persona:string;yearsExperience:number;geography:string;emailVerified:boolean;targetingScore:number;whySelected:string;lane:string;laneReason:string;templateVariant:string;draft:RenderedDraft;wordCount:number;constraintFailures:string[];snapshot:TargetingPlanSnapshot;}
export interface ControlledPlanningCapacity {desiredVolume:number;qualifiedCandidates:number;uniqueQualifiedCompanies:number;companyUniquenessCapacity:number;actualPlanned:number;qualificationShortfall:number;companyCapacityShortfall:number;}
export interface ControlledCampaignPreview {plan:DailyPlanResult;capacity:ControlledPlanningCapacity;drafts:ControlledDraftPreview[];}
const safeReference=(id:string)=>`candidate-${createHash("sha256").update(id).digest("hex").slice(0,12)}`;
const industryName=(id:string)=>({consulting:"Consulting","financial-services":"Finance","commodities-energy":"Commodities","technology-ai":"Technology","defense-aerospace":"Defense"}[id]??"Technology") as Prospect["industry"];

function planningCandidate(candidate:ImportedCandidateSnapshot,registry:readonly TargetCompany[]):PlanningCandidate|null{
  const company=registry.find((item)=>item.id===candidate.strategyCompanyMatch?.companyId),roleId=candidate.classification.specificRoleId??candidate.targetRoleAffinities[0]?.targetRoleId,role=TARGET_ROLES.find((item)=>item.id===roleId),persona=CONTACT_PERSONAS.find((item)=>item.id===candidate.personaId),industry=INDUSTRY_PREFERENCES.find((item)=>item.id===company?.industryId),geography=GEOGRAPHY_PREFERENCES.find((item)=>item.id===candidate.geographyId),years=candidate.experience.minimumSupportedYears;
  if(candidate.state!=="eligible"||!company||!role||!persona||!industry||!geography||years===null)return null;
  const id=`authorized:${candidate.source.providerRecordId}`,normalized:CandidateInput={internalId:id,externalSourceReference:candidate.source.providerRecordId,sourceType:"authorized-adapter",retrievedAt:candidate.source.sourceTimestamps.retrievedAt,firstName:candidate.source.person.firstName,lastName:candidate.source.person.lastName,professionalTitle:candidate.source.currentTitle,employerName:company.canonicalName,...candidate.source.currentOrganization.domain?{employerDomain:candidate.source.currentOrganization.domain}:{},industry:company.industryId,geography:geography.id,yearsExperience:years,professionalEmail:candidate.source.email.address,emailVerificationStatus:candidate.source.email.verificationStatus,roleSignals:[],sharedSignals:[],dataQualityIndicators:[],publicCompanyRegistryMatch:{companyId:company.id,matchedBy:"domain",reviewed:true},rawRecordFingerprint:candidate.source.sourceFingerprint};
  const companyMatch={companyId:company.id,canonicalName:company.canonicalName,tier:company.tier,enabled:company.enabled,industryId:company.industryId,recognitionScore:company.recognitionScore,careerUpsideScore:company.careerUpsideScore,technicalInterestScore:company.technicalInterestScore,reviewStatus:"reviewed" as const,method:candidate.strategyCompanyMatch!.method,provenance:company.provenance},affinity=candidate.targetRoleAffinities.find((item)=>item.targetRoleId===role.id)?.score??candidate.recipientRelevance.score,normalizedRecord:NormalizedCandidateRecord={source:normalized,fictionalEmployer:{id:company.id,name:company.canonicalName,industryId:company.industryId},stableFingerprint:candidate.source.sourceFingerprint,normalizedTitle:candidate.classification.normalizedTitle,yearsExperience:years,roleFamilyId:role.familyId,desiredRoleId:role.id,preciseTargetRoleId:candidate.classification.specificRoleId,recipientFunction:candidate.recipientFunction,targetRoleAffinities:candidate.targetRoleAffinities,recipientRelevance:candidate.recipientRelevance,recipientPersonaId:persona.id,industryId:industry.id,geographyId:geography.id,companyMatch,dataQualityScore:candidate.dataQualityScore,sharedSignal:0,roleAlignment:affinity,functionalRelevance:candidate.recipientRelevance.score,roleSpecificUpside:affinity,explanationCodes:[...candidate.classification.matchedSignals,...candidate.recipientFunction.explanationCodes,...candidate.recipientRelevance.explanationCodes,"authorized-provider-production-normalization"],reviewCode:null,rejectionCode:null,classificationVersion:"classification-v1",targetingProfileVersion:"controlled-real-targeting-v2",companyProfileVersion:"headquarters-reviewed-registry"};
  const prospect:Prospect={id,firstName:candidate.source.person.firstName,lastName:candidate.source.person.lastName,companyId:company.id,companyName:company.canonicalName,industry:industryName(company.industryId),email:candidate.source.email.address,emailVerified:candidate.source.email.verificationStatus==="verified",yearsExperience:years,suppressed:candidate.source.consent.suppressed,optedOut:candidate.source.consent.optedOut,relevanceScore:0};
  return{prospect,normalized,normalizedRecord,target:{id,company,role,preciseRoleId:candidate.classification.specificRoleId,recipientRelevance:{score:candidate.recipientRelevance.score,version:candidate.recipientRelevance.version},persona,industry,geographyScore:geography.score,roleAlignment:affinity,functionalRelevance:candidate.recipientRelevance.score,yearsExperience:years,sharedSignal:0,dataQuality:candidate.dataQualityScore,roleSpecificUpside:affinity},professionalTitle:candidate.source.currentTitle,roleFamilyId:role.familyId,desiredRoleId:role.id,personaId:persona.id,industryId:industry.id,geographyId:geography.id,targetingProfileVersion:normalizedRecord.targetingProfileVersion,companyProfileVersion:normalizedRecord.companyProfileVersion,companyMatch:{registryCompanyId:company.id,canonicalName:company.canonicalName,tier:company.tier,method:candidate.strategyCompanyMatch!.method,provenance:company.provenance,fictionalScenario:true}};
}

export function prepareControlledRealCampaign(candidates:readonly ImportedCandidateSnapshot[],input:{registry?:readonly TargetCompany[];now?:Date;target?:number}={}):ControlledCampaignPreview{
  const registry=input.registry??TARGET_COMPANIES,now=input.now??new Date(),normalized=candidates.map((candidate)=>planningCandidate(candidate,registry)).filter((candidate):candidate is PlanningCandidate=>candidate!==null),byId=new Map(candidates.map((candidate)=>[`authorized:${candidate.source.providerRecordId}`,candidate])),plan=planDailyCampaign(normalized,[],input.target??15,now,7);
  const drafts=plan.selected.map((snapshot):ControlledDraftPreview=>{
    const source=byId.get(snapshot.prospectId)!;
    const recipient={id:snapshot.prospectId,firstName:source.source.person.firstName,companyName:snapshot.companyName,roleFamilyId:snapshot.desiredRoleFamily,industryId:snapshot.industry,personaId:snapshot.recipientPersona,professionalTitle:snapshot.professionalTitle,primaryRecipientFunction:snapshot.primaryRecipientFunction};
    const selection=selectTemplateWithReason(recipient,{runId:`controlled-real-${now.toISOString().slice(0,10)}`}),draft=renderDraft(recipient,[],()=>now,selection.template),wordCount=draftWordCount(draft.body),lower=draft.body.toLowerCase();
    const constraintFailures=[...(wordCount<70||wordCount>130?["word-count-outside-70-130"]:[]),...PROHIBITED_DRAFT_PHRASES.filter((phrase)=>lower.includes(phrase)).map((phrase)=>`prohibited-phrase:${phrase}`),...lower.includes("15 minute")||lower.includes("15-minute")?[]:["missing-modest-time-request"],.../long-term.{0,20}long-term/i.test(draft.body)?["duplicated-long-term-language"]:[],...draft.usedEvidence&&draft.body.includes(snapshot.companyName)?[]:["missing-recipient-evidence-connection"]];
    return{candidateReference:safeReference(source.source.providerRecordId),redactedName:`${source.source.person.firstName} ${source.source.person.lastName.slice(0,1)}.`,company:snapshot.companyName,sourceTitle:source.source.currentTitle,recipientFunction:source.recipientFunction.primaryFunction,persona:snapshot.recipientPersona,yearsExperience:snapshot.yearsExperience,geography:snapshot.geography,emailVerified:source.source.email.verificationStatus==="verified",targetingScore:snapshot.totalScore,whySelected:snapshot.selectionReason,lane:selection.template.laneId,laneReason:selection.reason,templateVariant:selection.template.variantId,draft,wordCount,constraintFailures,snapshot:structuredClone(snapshot)};
  });
  const desiredVolume=plan.target,qualifiedCandidates=plan.qualifiedPopulation,uniqueQualifiedCompanies=new Set(plan.decisions.filter((item)=>!item.hardGateRejectionCode).map((item)=>item.companyId)).size,companyUniquenessCapacity=Math.min(qualifiedCandidates,uniqueQualifiedCompanies),qualificationShortfall=Math.max(0,desiredVolume-qualifiedCandidates),companyCapacityShortfall=Math.max(0,Math.min(desiredVolume,qualifiedCandidates)-companyUniquenessCapacity),capacity={desiredVolume,qualifiedCandidates,uniqueQualifiedCompanies,companyUniquenessCapacity,actualPlanned:plan.selected.length,qualificationShortfall,companyCapacityShortfall};
  return{plan,capacity,drafts};
}
