import {createHash} from "node:crypto";
import {importCandidateBatch,type ImportedCandidateSnapshot,type IngestionRepository} from "@/application/ingestion";
import {planRecruiterCandidates,renderRecruiterDraft} from "@/domain/recruiters";
import {TARGET_COMPANIES,type TargetCompany} from "@/domain/targeting";
import type {CandidateSourceRecord} from "@/domain/candidates";
import type {ApolloCreditUsage,ApolloEnrichmentOptions,ApolloHttpResponse,ApolloHttpTransport,ApolloSearchOptions,ApolloSearchResult} from "@/infrastructure/providers/apollo";
import {OPERATIONAL_COMPANIES} from "./run-operational-scale-batch";

export const RECRUITER_MAX_SEARCH_REQUESTS=46,RECRUITER_MAX_RAW_RECORDS=1150,RECRUITER_MAX_ENRICHMENTS=20,RECRUITER_MAX_RECOMMENDATIONS=5;
export const RECRUITER_SEARCH_TITLES=["technical recruiter","talent acquisition partner","recruiter","talent partner","university recruiter","campus recruiter","early careers recruiter","engineering recruiter"] as const;
const domains=Object.fromEntries(OPERATIONAL_COMPANIES),digest=(value:string)=>createHash("sha256").update(value).digest("hex");
interface RecruiterAdapter {search(options:ApolloSearchOptions):Promise<ApolloSearchResult>;enrich(options:ApolloEnrichmentOptions):Promise<CandidateSourceRecord[]>;creditUsage():Promise<ApolloCreditUsage>;}
export class RecruiterDiscoveryTransport implements ApolloHttpTransport {readonly counts={search:0,enrichment:0,usage:0};constructor(private readonly delegate:ApolloHttpTransport){}async request(input:Parameters<ApolloHttpTransport["request"]>[0]):Promise<ApolloHttpResponse>{const kind=input.path==="/api/v1/mixed_people/api_search"?"search":input.path==="/api/v1/people/match"?"enrichment":input.path==="/api/v1/usage_stats/credit_usage_stats"?"usage":null;if(!kind)throw new Error("recruiter-endpoint-not-authorized");const cap=kind==="search"?RECRUITER_MAX_SEARCH_REQUESTS:kind==="enrichment"?RECRUITER_MAX_ENRICHMENTS:2;if(this.counts[kind]>=cap)throw new Error(`recruiter-${kind}-cap-exceeded`);this.counts[kind]++;return this.delegate.request(input);}}
export interface RecruiterDiscoveryOutcome {companiesSearched:number;searchRequests:number;rawRecords:number;validRecruiterCandidates:number;internalRecruiters:number;agencyOrAmbiguousRejects:number;shortlist:ImportedCandidateSnapshot[];enriched:ImportedCandidateSnapshot[];qualified:ImportedCandidateSnapshot[];recommendations:Array<{candidate:ImportedCandidateSnapshot;draft:ReturnType<typeof renderRecruiterDraft>}>;usageBefore:ApolloCreditUsage|null;usageAfter:ApolloCreditUsage|null;creditDelta:number|null;failures:Array<{stage:string;companyId?:string;reason:string}>;}
export async function runRecruiterDiscovery(input:{adapter:RecruiterAdapter;searchRepository:IngestionRepository;enrichmentRepository:IngestionRepository;registry?:readonly TargetCompany[];now?:()=>Date;usePersistedSearch?:boolean}):Promise<RecruiterDiscoveryOutcome>{
 const registry=input.registry??TARGET_COMPANIES,now=input.now??(()=>new Date()),failures:RecruiterDiscoveryOutcome["failures"]=[],unique=new Map<string,ImportedCandidateSnapshot>();let usageBefore:null|ApolloCreditUsage=null,usageAfter:null|ApolloCreditUsage=null,rawRecords=0,searchRequests=0,agencyOrAmbiguousRejects=0;
 try{usageBefore=await input.adapter.creditUsage();}catch(error){failures.push({stage:"usage-before",reason:error instanceof Error?error.message:"usage-failed"});}
 if(input.usePersistedSearch){for(const candidate of input.searchRepository.listImportedCandidates())if(candidate.outreachTrack==="recruiter"&&candidate.recruiterClassification?.internalStatus==="internal")unique.set(candidate.id,candidate);rawRecords=input.searchRepository.listImportedCandidates().length;}else for(const [companyId,domain] of OPERATIONAL_COMPANIES){if(searchRequests>=RECRUITER_MAX_SEARCH_REQUESTS||rawRecords>=RECRUITER_MAX_RAW_RECORDS)break;const company=registry.find((item)=>item.id===companyId&&item.enabled&&item.tier!=="excluded"&&item.tier!=="unreviewed");if(!company)continue;const at=now(),options:ApolloSearchOptions={batchId:`recruiter-search-${companyId}`,companyDomains:[domain],specificTitles:[...RECRUITER_SEARCH_TITLES],seniorities:[],personLocations:["Boston","Massachusetts","New York","New Jersey","United States"],includeSimilarTitles:false,controlledDiagnosticAuthorization:"milestone-12",page:1,perPage:25};try{searchRequests++;const result=await input.adapter.search(options),processed=result.records.length+(result.recordRejections?.length??0);if(processed>25||rawRecords+processed>RECRUITER_MAX_RAW_RECORDS)throw new Error("recruiter-raw-cap-exceeded");rawRecords+=processed;importCandidateBatch(input.searchRepository,registry,{batchId:`recruiter-search-${companyId}-${at.toISOString().replace(/\D/g,"").slice(0,14)}`,adapterId:"apollo",adapterVersion:result.requestVersion,datasetClassification:"authorized-provider",sourceFingerprint:`recruiter-search:${digest(JSON.stringify(options)+result.records.map((record)=>record.sourceFingerprint).sort().join("|"))}`,records:result.records,providerRecordRejections:result.recordRejections,authorizedProviderAccess:{enabled:true,providerId:"apollo"},strategyCompanyDomains:domains},at);for(const record of result.records){const candidate=input.searchRepository.findImportedCandidate("apollo",record.providerRecordId);if(!candidate)continue;if(candidate.outreachTrack==="recruiter"&&candidate.recruiterClassification?.internalStatus==="internal")unique.set(candidate.id,candidate);else agencyOrAmbiguousRejects++;}}catch(error){failures.push({stage:"search",companyId,reason:error instanceof Error?error.message:"search-failed"});}}
 const preEnrichmentEligible=(candidate:ImportedCandidateSnapshot)=>candidate.outreachTrack==="recruiter"&&candidate.recruiterClassification?.internalStatus==="internal"&&candidate.recruiterClassification.explanationCodes.every((code)=>code==="recruiter-experience-unsupported"||code==="recruiter-qualified"||code.startsWith("target-company-opportunity:")),shortlist=[...unique.values()].filter(preEnrichmentEligible).sort((a,b)=>(b.recruiterClassification?.score??0)-(a.recruiterClassification?.score??0)||a.id.localeCompare(b.id)).filter((candidate,index,all)=>index===all.findIndex((other)=>other.strategyCompanyMatch?.companyId===candidate.strategyCompanyMatch?.companyId)).slice(0,RECRUITER_MAX_ENRICHMENTS),enriched:ImportedCandidateSnapshot[]=[];
 for(const [index,candidate] of shortlist.entries()){const id=candidate.source.providerRecordId,at=now(),batchId=`recruiter-enrichment-${index+1}-${at.toISOString().replace(/\D/g,"").slice(0,14)}`;try{const records=await input.adapter.enrich({batchId,personIds:[id],persistedSearchPersonIds:[id],creditCostPolicy:"disabled-phone-v1"});if(records.length!==1||records[0]?.providerRecordId!==id)throw new Error("recruiter-enrichment-identity-invalid");importCandidateBatch(input.enrichmentRepository,registry,{batchId,adapterId:"apollo",adapterVersion:records[0].providerMetadata?.adapterVersion??"apollo-adapter-v1",datasetClassification:"authorized-provider",sourceFingerprint:`recruiter-enrichment:${digest(records[0].sourceFingerprint)}`,records,authorizedProviderAccess:{enabled:true,providerId:"apollo"},strategyCompanyDomains:domains},at);const imported=input.enrichmentRepository.findImportedCandidate("apollo",id);if(imported)enriched.push(imported);}catch(error){failures.push({stage:"enrichment",reason:error instanceof Error?error.message:"enrichment-failed"});}}
 try{usageAfter=await input.adapter.creditUsage();}catch(error){failures.push({stage:"usage-after",reason:error instanceof Error?error.message:"usage-failed"});}
 const qualified=planRecruiterCandidates(enriched,new Set(),new Set(),RECRUITER_MAX_ENRICHMENTS),recommendations=planRecruiterCandidates(qualified,new Set(),new Set(),RECRUITER_MAX_RECOMMENDATIONS).map((candidate)=>({candidate,draft:renderRecruiterDraft({firstName:candidate.source.person.firstName,company:candidate.source.currentOrganization.name,title:candidate.source.currentTitle,classification:candidate.recruiterClassification!})}));
 return{companiesSearched:input.usePersistedSearch?new Set([...unique.values()].map((candidate)=>candidate.strategyCompanyMatch?.companyId).filter(Boolean)).size:searchRequests,searchRequests,rawRecords,validRecruiterCandidates:unique.size,internalRecruiters:[...unique.values()].filter((candidate)=>candidate.recruiterClassification?.internalStatus==="internal").length,agencyOrAmbiguousRejects,shortlist,enriched,qualified,recommendations,usageBefore,usageAfter,creditDelta:usageBefore?.leadCreditsConsumed!=null&&usageAfter?.leadCreditsConsumed!=null?usageAfter.leadCreditsConsumed-usageBefore.leadCreditsConsumed:null,failures};
}
