import {createHash} from "node:crypto";
import {importCandidateBatch,type ImportedCandidateSnapshot,type IngestionRepository} from "@/application/ingestion";
import type {CandidateSourceRecord} from "@/domain/candidates";
import {chooseDailyTarget,DEFAULT_SELECTION_CONFIG} from "@/domain/outreach";
import {TARGET_COMPANIES,type TargetCompany} from "@/domain/targeting";
import type {ApolloCreditUsage,ApolloEnrichmentOptions,ApolloHttpResponse,ApolloHttpTransport,ApolloSearchOptions,ApolloSearchResult} from "@/infrastructure/providers/apollo";
import {selectControlledEnrichmentShortlistDetailed,type ControlledProviderFailure,type ShortlistDiversification} from "./run-controlled-real-batch";

export const OPERATIONAL_MAX_SEARCH_REQUESTS=46,OPERATIONAL_MAX_RAW_RECORDS=1150,OPERATIONAL_MAX_ENRICHMENTS=30,OPERATIONAL_MAX_PER_COMPANY=2,OPERATIONAL_FUNCTION_SOFT_CAP=6;
export const OPERATIONAL_COMPANIES=[
  ["microsoft","microsoft.com"],["google","google.com"],["amazon","amazon.com"],["apple","apple.com"],["nvidia","nvidia.com"],["palantir","palantir.com"],
  ["jpmorganchase","jpmorganchase.com"],["goldman-sachs","goldmansachs.com"],["morgan-stanley","morganstanley.com"],["blackrock","blackrock.com"],["bloomberg","bloomberg.com"],
  ["mckinsey-and-company","mckinsey.com"],["boston-consulting-group","bcg.com"],["bain-and-company","bain.com"],["accenture","accenture.com"],["deloitte","deloitte.com"],
  ["rtx","rtx.com"],["lockheed-martin","lockheedmartin.com"],["northrop-grumman","northropgrumman.com"],["anduril","anduril.com"],
  ["vitol","vitol.com"],["trafigura","trafigura.com"],["mercuria","mercuria.com"],["glencore","glencore.com"],["cargill","cargill.com"],["shell","shell.com"],["bp","bp.com"],["chevron","chevron.com"],
  ["pwc","pwc.com"],["ey","ey.com"],["kpmg","kpmg.com"],["oliver-wyman","oliverwyman.com"],
  ["citi","citi.com"],["bank-of-america","bankofamerica.com"],["fidelity-investments","fidelity.com"],["state-street","statestreet.com"],["capital-one","capitalone.com"],
  ["datadog","datadoghq.com"],["snowflake","snowflake.com"],["servicenow","servicenow.com"],["ibm","ibm.com"],
  ["shield-ai","shield.ai"],["general-dynamics","gd.com"],["l3harris-technologies","l3harris.com"],["bae-systems","baesystems.com"],["boeing","boeing.com"],
] as const;
const TITLES=["data","analytics","software engineer","AI","security","product manager","program manager","operations"];
const digest=(value:string)=>createHash("sha256").update(value).digest("hex"),domains=Object.fromEntries(OPERATIONAL_COMPANIES);
const message=(error:unknown)=>error instanceof Error?error.message:"provider-operation-failed";
const safeReason=(error:unknown)=>message(error).startsWith("source-record-conflict:")?"provider-import-conflict":message(error);
const searchFailureStage=(error:unknown):ControlledProviderFailure["stage"]=>{const reason=message(error);if(reason.startsWith("source-record-")||reason.startsWith("import-"))return"import-conflict";if(reason.includes("response-malformed")||reason.includes("required-field"))return"search-response-schema";return"search";};

interface OperationalAdapter {search(options:ApolloSearchOptions):Promise<ApolloSearchResult>;enrich(options:ApolloEnrichmentOptions):Promise<CandidateSourceRecord[]>;creditUsage():Promise<ApolloCreditUsage>;}
export class OperationalScaleTransport implements ApolloHttpTransport{
  readonly counts={search:0,enrichment:0,usage:0};
  constructor(private readonly delegate:ApolloHttpTransport){}
  async request(input:Parameters<ApolloHttpTransport["request"]>[0]):Promise<ApolloHttpResponse>{const kind=input.path==="/api/v1/mixed_people/api_search"?"search":input.path==="/api/v1/people/match"?"enrichment":input.path==="/api/v1/usage_stats/credit_usage_stats"?"usage":null;if(!kind)throw new Error("operational-endpoint-not-authorized");const maximum=kind==="search"?OPERATIONAL_MAX_SEARCH_REQUESTS:kind==="enrichment"?OPERATIONAL_MAX_ENRICHMENTS:2;if(this.counts[kind]>=maximum)throw new Error(`operational-${kind}-http-cap-exceeded`);this.counts[kind]++;return this.delegate.request(input);}
}
export interface OperationalScaleOutcome {companies:Array<{id:string;domain:string;tier:string;industryId:string}>;desiredTarget:number;searchRequests:number;rawRecords:number;validSearchRecords:number;providerRecordRejections:Array<{companyId:string;recordIndex:number;reason:string}>;uniqueSearchCandidates:number;shortlist:ImportedCandidateSnapshot[];diversification:Omit<ShortlistDiversification,"selected">;enriched:ImportedCandidateSnapshot[];failures:ControlledProviderFailure[];usageBefore:ApolloCreditUsage|null;usageAfter:ApolloCreditUsage|null;leadCreditDelta:number|null;creditModelExceeded:boolean;}

export async function runOperationalScaleBatch(input:{adapter:OperationalAdapter;searchRepository:IngestionRepository;enrichmentRepository:IngestionRepository;random:()=>number;registry?:readonly TargetCompany[];now?:()=>Date}):Promise<OperationalScaleOutcome>{
  const registry=input.registry??TARGET_COMPANIES,now=input.now??(()=>new Date()),companies=OPERATIONAL_COMPANIES.map(([id,domain])=>{const company=registry.find((item)=>item.id===id&&item.enabled&&(item.tier==="tier-1"||item.tier==="tier-2"));if(!company)throw new Error(`operational-company-unavailable:${id}`);return{company,domain};}),desiredTarget=chooseDailyTarget(DEFAULT_SELECTION_CONFIG,input.random),failures:ControlledProviderFailure[]=[],providerRecordRejections:OperationalScaleOutcome["providerRecordRejections"]=[],unique=new Map<string,ImportedCandidateSnapshot>();let usageBefore:ApolloCreditUsage|null=null,usageAfter:ApolloCreditUsage|null=null,searchRequests=0,rawRecords=0,validSearchRecords=0,creditModelExceeded=false;
  try{usageBefore=await input.adapter.creditUsage();}catch(error){failures.push({stage:"usage-before",reason:safeReason(error)});}
  for(const {company,domain} of companies){if(searchRequests>=OPERATIONAL_MAX_SEARCH_REQUESTS||rawRecords>=OPERATIONAL_MAX_RAW_RECORDS)break;const at=now(),options:ApolloSearchOptions={batchId:`operational-search-${company.id}`,companyDomains:[domain],seniorities:["manager","director","senior"],personLocations:["Boston","Massachusetts","New York","New Jersey","United States"],specificTitles:TITLES,includeSimilarTitles:true,controlledDiagnosticAuthorization:"milestone-6.3",page:1,perPage:25};try{searchRequests++;const result=await input.adapter.search(options),rejections=result.recordRejections??[],processed=result.records.length+rejections.length;if(processed>25||rawRecords+processed>OPERATIONAL_MAX_RAW_RECORDS)throw new Error("operational-search-result-cap-exceeded");rawRecords+=processed;validSearchRecords+=result.records.length;providerRecordRejections.push(...rejections.map((item)=>({companyId:company.id,...item})));importCandidateBatch(input.searchRepository,registry,{batchId:`operational-search-${company.id}-${at.toISOString().replace(/\D/g,"").slice(0,14)}`,adapterId:"apollo",adapterVersion:result.requestVersion,datasetClassification:"authorized-provider",sourceFingerprint:`operational-search:${digest(JSON.stringify(options)+result.records.map((record)=>record.sourceFingerprint).sort().join("|")+JSON.stringify(rejections))}`,records:result.records,providerRecordRejections:rejections,authorizedProviderAccess:{enabled:true,providerId:"apollo"},strategyCompanyDomains:domains},at);for(const record of result.records){const candidate=input.searchRepository.findImportedCandidate("apollo",record.providerRecordId);if(candidate&&!unique.has(record.providerRecordId))unique.set(record.providerRecordId,candidate);}}catch(error){failures.push({stage:searchFailureStage(error),companyId:company.id,reason:safeReason(error)});}}
  const selection=selectControlledEnrichmentShortlistDetailed([...unique.values()],registry,OPERATIONAL_MAX_ENRICHMENTS,{maximumPerCompany:OPERATIONAL_MAX_PER_COMPANY,functionSoftCap:OPERATIONAL_FUNCTION_SOFT_CAP,companyOrder:companies.map(({company})=>company.id)}),enriched:ImportedCandidateSnapshot[]=[];
  for(const [index,candidate] of selection.selected.entries()){const id=candidate.source.providerRecordId,at=now(),batchId=`operational-enrichment-${index+1}-${at.toISOString().replace(/\D/g,"").slice(0,14)}`;try{const records=await input.adapter.enrich({batchId,personIds:[id],persistedSearchPersonIds:[id],creditCostPolicy:"disabled-phone-v1"});if(records.length!==1||records[0].providerRecordId!==id)throw new Error("operational-enrichment-identity-invalid");importCandidateBatch(input.enrichmentRepository,registry,{batchId,adapterId:"apollo",adapterVersion:records[0].providerMetadata?.adapterVersion??"apollo-adapter-v1",datasetClassification:"authorized-provider",sourceFingerprint:`operational-enrichment:${digest(records[0].sourceFingerprint)}`,records,authorizedProviderAccess:{enabled:true,providerId:"apollo"},strategyCompanyDomains:domains},at);const imported=input.enrichmentRepository.findImportedCandidate("apollo",id);if(!imported)throw new Error("operational-enrichment-import-missing");enriched.push(imported);}catch(error){const reason=safeReason(error);failures.push({stage:"enrichment",candidateReference:digest(id).slice(0,12),reason});if(reason.includes("provider-credit-model-exceeded")){creditModelExceeded=true;break;}}}
  try{usageAfter=await input.adapter.creditUsage();}catch(error){failures.push({stage:"usage-after",reason:safeReason(error)});}
  const leadCreditDelta=usageBefore?.leadCreditsConsumed!=null&&usageAfter?.leadCreditsConsumed!=null?usageAfter.leadCreditsConsumed-usageBefore.leadCreditsConsumed:null;
  return{companies:companies.map(({company,domain})=>({id:company.id,domain,tier:company.tier,industryId:company.industryId})),desiredTarget,searchRequests,rawRecords,validSearchRecords,providerRecordRejections,uniqueSearchCandidates:unique.size,shortlist:selection.selected,diversification:{functionCapRelaxations:selection.functionCapRelaxations,diversificationShortfalls:selection.diversificationShortfalls,excludedSolelyByFunctionCap:selection.excludedSolelyByFunctionCap},enriched,failures,usageBefore,usageAfter,leadCreditDelta,creditModelExceeded};
}
