import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it,vi} from "vitest";
import type {CandidateSourceRecord} from "@/domain/candidates";
import {TARGET_COMPANIES} from "@/domain/targeting";
import type {ApolloHttpTransport} from "@/infrastructure/providers/apollo";
import {SqliteSimulationRepository} from "@/infrastructure/sqlite/database";
import {seedTargetCompanyRegistry} from "@/infrastructure/sqlite/seed";
import {OPERATIONAL_COMPANIES,OPERATIONAL_MAX_ENRICHMENTS,OperationalScaleTransport,runOperationalScaleBatch} from "./run-operational-scale-batch";

const directories:string[]=[];
const repository=()=>{const directory=mkdtempSync(join(tmpdir(),"networkpilot-operational-"));directories.push(directory);const repo=new SqliteSimulationRepository(join(directory,"test.sqlite"));repo.migrate();return repo;};
afterEach(()=>directories.splice(0).forEach((directory)=>rmSync(directory,{recursive:true,force:true})));
const titles=["Senior Data Engineer","Senior Software Engineer","Analytics Manager","Technical Program Manager"];
const record=(companyId:string,domain:string,index:number,stage:"search"|"enrichment"):CandidateSourceRecord=>{const company=TARGET_COMPANIES.find((item)=>item.id===companyId)!;return{sourceProviderId:"apollo",providerRecordId:`${companyId}-fixture-${index}`,datasetClassification:"authorized-provider",person:{firstName:"Fictional",lastName:stage==="search"?"P***n":"Person"},currentTitle:titles[index%titles.length]!,currentOrganization:{name:company.canonicalName,domain},location:"Boston, Massachusetts, United States",industrySignals:[company.industryId],experienceEvidence:stage==="search"?[{kind:"unknown",sourceField:"fixture"}]:[{kind:"exact",years:9,sourceField:"fixture"}],email:{address:stage==="search"?"":`fictional-${companyId}-${index}@example.invalid`,verificationStatus:stage==="search"?"unknown":"verified"},sourceTimestamps:{retrievedAt:"2026-09-10T12:00:00.000Z"},fieldProvenance:{},consent:{suppressed:false,optedOut:false},sourceFingerprint:`fixture-${stage}-${companyId}-${index}-fingerprint`,providerMetadata:{adapterVersion:"fixture",responseMappingVersion:"fixture",requestContractVersion:"fixture",importArchitectureVersion:"fixture",providerSeniority:"senior",identityEvidenceBasis:"provider-native-id-exact",providerNativeRequestId:`${companyId}-fixture-${index}`,providerNativeReturnedId:`${companyId}-fixture-${index}`,matchConfidence:"high"}};};

describe("operational-scale controlled batch",()=>{
  it("keeps the 46-company run within search, shortlist, per-company, function, and exact-ID bounds",async()=>{const searchRepository=repository(),enrichmentRepository=repository();seedTargetCompanyRegistry(enrichmentRepository);const searched:string[]=[],enriched:string[]=[];const adapter={creditUsage:vi.fn().mockResolvedValue({cycleStart:"2026-09-01",cycleEnd:"2026-10-01",leadCreditsLimit:100,leadCreditsConsumed:10,leadCreditsRemaining:90,observedAt:"2026-09-10",adapterVersion:"apollo-adapter-v1"}),search:vi.fn(async(options:{companyDomains?:string[]})=>{const domain=options.companyDomains![0]!,company=OPERATIONAL_COMPANIES.find((item)=>item[1]===domain)!;searched.push(domain);return{records:[record(company[0],domain,0,"search"),record(company[0],domain,1,"search")],recordRejections:[],totalAvailable:2,requestVersion:"fixture"};}),enrich:vi.fn(async(options:{personIds:string[];persistedSearchPersonIds?:string[];creditCostPolicy?:string})=>{expect(options.personIds).toEqual(options.persistedSearchPersonIds);expect(options.creditCostPolicy).toBe("disabled-phone-v1");const id=options.personIds[0]!,company=OPERATIONAL_COMPANIES.find((item)=>id.startsWith(`${item[0]}-fixture`))!;enriched.push(id);return[record(company[0],company[1],Number(id.at(-1)),"enrichment")];})};const result=await runOperationalScaleBatch({adapter,searchRepository,enrichmentRepository,random:()=>0.999,now:()=>new Date("2026-09-10T12:00:00.000Z")});expect(result.desiredTarget).toBe(20);expect(result.searchRequests).toBe(46);expect(result.rawRecords).toBe(92);expect(result.shortlist).toHaveLength(OPERATIONAL_MAX_ENRICHMENTS);expect(result.enriched).toHaveLength(30);expect(searched).toHaveLength(46);expect(new Set(enriched).size).toBe(30);expect(Math.max(...OPERATIONAL_COMPANIES.map(([id])=>result.shortlist.filter((item)=>item.strategyCompanyMatch?.companyId===id).length))).toBeLessThanOrEqual(2);searchRepository.close();enrichmentRepository.close();});
  it("hard-caps HTTP endpoints independently",async()=>{const delegate={request:vi.fn(async()=>({status:200,headers:{},body:"{}"}))} satisfies ApolloHttpTransport,transport=new OperationalScaleTransport(delegate),request={path:"/api/v1/usage_stats/credit_usage_stats" as const,body:{},apiKey:"fixture",timeoutMs:1,maxResponseBytes:1};await transport.request(request);await transport.request(request);await expect(transport.request(request)).rejects.toThrow("operational-usage-http-cap-exceeded");expect(transport.counts.usage).toBe(2);});
  it("stops remaining enrichments when the provider contradicts the authorized credit model",async()=>{const searchRepository=repository(),enrichmentRepository=repository();seedTargetCompanyRegistry(enrichmentRepository);const usage={cycleStart:"2026-09-01",cycleEnd:"2026-10-01",leadCreditsLimit:100,leadCreditsConsumed:10,leadCreditsRemaining:90,observedAt:"2026-09-10T12:00:00.000Z",adapterVersion:"fixture"},enrich=vi.fn(async()=>{throw new Error("provider-credit-model-exceeded");}),adapter={creditUsage:vi.fn().mockResolvedValue(usage),search:vi.fn(async(options:{companyDomains?:string[]})=>{const domain=options.companyDomains![0]!,company=OPERATIONAL_COMPANIES.find((item)=>item[1]===domain)!;return{records:[record(company[0],domain,0,"search")],recordRejections:[],totalAvailable:1,requestVersion:"fixture"};}),enrich};const result=await runOperationalScaleBatch({adapter,searchRepository,enrichmentRepository,random:()=>0,now:()=>new Date("2026-09-10T12:00:00.000Z")});expect(result.creditModelExceeded).toBe(true);expect(enrich).toHaveBeenCalledTimes(1);searchRepository.close();enrichmentRepository.close();});
});
