import { getDraftStudioData, ENABLED_ROLE_FAMILIES } from "@/application/drafts";
import type { DraftStatus } from "@/application/drafts";
import { DRAFT_TEMPLATES } from "@/domain/drafting";
import { DEFAULT_TARGETING_WEIGHTS, INDUSTRY_PREFERENCES } from "@/domain/targeting";
import { getSimulationRepository } from "@/infrastructure/sqlite/runtime";
import { changeDraftStatus, generateRunDrafts } from "./actions";
import Link from "next/link";
import { DraftSafetyNotice } from "./draft-safety-notice";
export const dynamic="force-dynamic";
export default async function DraftStudio({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const query=await searchParams;const repo=getSimulationRepository();const base=getDraftStudioData(repo);
  const value=(key:string)=>typeof query[key]==="string"?query[key] as string:"";
  const drafts=repo.listDrafts({runId:value("run")||undefined,industry:value("industry")||undefined,roleFamilyId:value("family")||undefined,templateId:value("template")||undefined,status:(value("status")||undefined) as DraftStatus|undefined});
  return <main><nav className="nav"><Link className="brand" href="/"><span className="brand-mark"><i/><i/><i/></span>Network<span>Pilot</span></Link><div className="nav-meta"><Link href="/">Campaign dashboard</Link><span className="mode-pill"><b/>Draft-only simulation</span></div></nav>
  <section className="studio-hero"><DraftSafetyNotice/></section>
  <section className="content-section studio-config"><div><span className="kicker">Current-role strategy</span><h2>Enabled role families</h2><ul className="chip-list">{ENABLED_ROLE_FAMILIES.map((f)=><li key={f.id}>{f.displayName}<small>{f.priorityTier}</small></li>)}</ul></div><div><span className="kicker">Targeting v1</span><h2>Scoring weights</h2><dl className="weights">{Object.entries(DEFAULT_TARGETING_WEIGHTS).map(([key,weight])=><div key={key}><dt>{key.replace(/([A-Z])/g," $1")}</dt><dd>{weight}%</dd></div>)}</dl></div></section>
  <section className="content-section pipeline-section"><div className="section-heading"><div><span className="kicker">Generation</span><h2>Create drafts for a completed run</h2></div><p>Generation is idempotent for each fictional prospect, run, template, and template version.</p></div>{base.runs.length?<form action={generateRunDrafts} className="studio-form"><label>Completed fictional simulation<select name="runId" required>{base.runs.map((r)=><option value={r.id} key={r.id}>{r.campaignDate} · {r.selectedCount} selected</option>)}</select></label><button className="simulate-button">Generate deterministic drafts</button></form>:<div className="empty">No completed fictional simulation runs. Run a weekday simulation first.</div>}</section>
  <section className="content-section"><div className="section-heading"><div><span className="kicker">Draft queue</span><h2>Simulation review</h2></div><p>{drafts.length} drafts shown · generated content never leaves this application.</p></div><form className="filter-grid"><select name="run" defaultValue={value("run")}><option value="">All runs</option>{base.runs.map((r)=><option key={r.id} value={r.id}>{r.campaignDate}</option>)}</select><select name="industry" defaultValue={value("industry")}><option value="">All industries</option>{["Consulting","Finance","Commodities","Technology","Defense"].map((x)=><option key={x}>{x}</option>)}</select><select name="family" defaultValue={value("family")}><option value="">All role families</option>{ENABLED_ROLE_FAMILIES.map((f)=><option key={f.id} value={f.id}>{f.displayName}</option>)}</select><select name="template" defaultValue={value("template")}><option value="">All templates</option>{DRAFT_TEMPLATES.map((t)=><option key={t.id} value={t.id}>{t.displayName}</option>)}</select><select name="status" defaultValue={value("status")}><option value="">All statuses</option>{["generated","needs-review","approved-for-simulation","rejected","superseded"].map((x)=><option key={x}>{x}</option>)}</select><button>Apply filters</button></form>
  {drafts.length?<div className="draft-grid">{drafts.map((draft)=><article className="draft-card" key={draft.id}><header><div><span>{draft.industry} · {draft.companyName}</span><h3>{draft.prospectName}</h3></div><b>{draft.status}</b></header><div className="draft-score"><strong>{draft.score}</strong><span>{draft.scoreVersion}<br/>{draft.scoreComponents.map((c)=>`${c.id} [${c.explanationCode}]: ${c.weighted.toFixed(1)}`).join(" · ")}</span></div><h4>{draft.subject}</h4><pre>{draft.body}</pre><footer><div><span>Template</span>{draft.templateId} · {draft.templateVersion}</div><div><span>Facts</span>{draft.factIds.join(", ")}</div><div><span>Evidence</span>{draft.evidence.length?draft.evidence.map((e)=>`${e.id}: ${e.claim}`).join(" · "):"Verified evidence unavailable — clean fallback used"}</div></footer><div className="draft-actions"><form action={changeDraftStatus}><input type="hidden" name="draftId" value={draft.id}/><input type="hidden" name="status" value="approved-for-simulation"/><button>Approve for simulation</button></form><form action={changeDraftStatus}><input type="hidden" name="draftId" value={draft.id}/><input type="hidden" name="status" value="rejected"/><button className="reject">Reject draft</button></form><small>Neither action sends email.</small></div></article>)}</div>:<div className="empty">No drafts match these filters. Generate drafts from a completed fictional run.</div>}</section>
  <section className="industry-section registry"><div><span className="kicker">Public metadata only</span><h2>Target-company registry</h2><p>Editable strategic starting points—not hiring claims. Fictional prospects are never represented as employees of these companies.</p></div><div><form className="registry-filter"><label>Industry<select name="companyIndustry" defaultValue={value("companyIndustry")}><option value="">All industries</option>{INDUSTRY_PREFERENCES.map((i)=><option key={i.id} value={i.id}>{i.displayName}</option>)}</select></label><button>Filter registry</button></form><ul>{base.companies.filter((c)=>!value("companyIndustry")||c.industryId===value("companyIndustry")).map((c)=><li key={c.id}><span>{c.tier}</span>{c.canonicalName}<b>{c.recognitionScore}</b></li>)}</ul></div></section>
  <footer><span>NetworkPilot</span><p>Deterministic draft studio · fictional recipients only</p><span>No email delivery</span></footer></main>;
}
