import {createHash} from "node:crypto";
import {readFileSync,realpathSync} from "node:fs";
import {relative,resolve} from "node:path";
import {approveForGmailDraft,createApprovedGmailDraft,GMAIL_COMPOSE_SCOPE,type ApprovedEmailDraftSnapshot} from "../src/application/email-drafts";
import {prepareControlledRealCampaign,type ControlledDraftPreview} from "../src/application/providers/prepare-controlled-real-campaign";
import {CONTACT_IMPACTING_EVENT_TYPES} from "../src/domain/outreach";
import {DeterministicPlainTextMimeBuilder,FetchGmailTransport,FetchGoogleOAuthTransport,GmailDraftAdapter,GMAIL_ADAPTER_VERSION,GoogleOAuthSession,MacOsKeychainGoogleTokenStore,readGmailConfig,type GmailHttpResponse,type GmailHttpTransport,type GoogleOAuthTransport} from "../src/infrastructure/providers/gmail";
import {SqliteSimulationRepository} from "../src/infrastructure/sqlite/database";

const DATABASE=resolve(process.cwd(),"data/apollo-operational-scale-enrichment.sqlite"),MAX_DRAFTS=8,hash=(value:string)=>createHash("sha256").update(value).digest("hex"),redactEmail=(email:string)=>`${email[0]}***@${email.split("@")[1]}`;
interface DesktopCredentials {installed?:{client_id?:string;client_secret?:string};}
class PilotGmailTransport implements GmailHttpTransport{readonly counts={profile:0,draftCreate:0};constructor(private readonly delegate:GmailHttpTransport){}async request(input:Parameters<GmailHttpTransport["request"]>[0]):Promise<GmailHttpResponse>{if(input.method==="GET"&&input.path==="/gmail/v1/users/me/profile"){if(this.counts.profile>=1)throw new Error("gmail-pilot-profile-cap-exceeded");this.counts.profile++;return this.delegate.request(input);}if(input.method==="POST"&&input.path==="/gmail/v1/users/me/drafts"){if(this.counts.draftCreate>=MAX_DRAFTS)throw new Error("gmail-pilot-draft-cap-exceeded");this.counts.draftCreate++;return this.delegate.request(input);}throw new Error("gmail-pilot-endpoint-not-authorized");}}
class ObservedOAuthTransport implements GoogleOAuthTransport{refreshCount=0;constructor(private readonly delegate:GoogleOAuthTransport){}exchange(input:Parameters<GoogleOAuthTransport["exchange"]>[0]){return this.delegate.exchange(input);}refresh(input:Parameters<GoogleOAuthTransport["refresh"]>[0]){this.refreshCount++;return this.delegate.refresh(input);}revoke(token:string){return this.delegate.revoke(token);}}
const snapshotId=(draft:ControlledDraftPreview)=>`gmail-live:${hash(JSON.stringify({prospectId:draft.snapshot.prospectId,subject:draft.draft.subject,body:draft.draft.body,catalog:draft.draft.templateCatalogVersion}))}`;
const validateMime=(raw:string,email:string,subject:string,body:string)=>{const decoded=Buffer.from(raw,"base64url").toString("utf8");if(!decoded.includes(`<${email}>\r\n`)||!decoded.includes(`Subject: ${subject}\r\n`)||!decoded.includes("\r\nMIME-Version: 1.0\r\n")||!decoded.endsWith(body.replace(/\r?\n/g,"\r\n"))||/\r\n(?:Cc|Bcc|From):/i.test(decoded)||/text\/html|content-disposition:|<img|tracking/i.test(decoded)||/[+/=]/.test(raw))throw new Error("gmail-pilot-mime-validation-failed");};
const counts=(values:readonly string[])=>Object.fromEntries([...new Set(values)].sort().map((value)=>[value,values.filter((item)=>item===value).length]));
const sentenceCounts=(drafts:readonly ControlledDraftPreview[])=>{const sentences=drafts.flatMap((draft)=>draft.draft.body.split(/(?<=[.!?])\s+/).map((value)=>value.replace(/\s+/g," ").trim()).filter((value)=>value.length>=30));return Object.fromEntries([...new Set(sentences)].filter((sentence)=>sentences.filter((item)=>item===sentence).length>1).map((sentence)=>[sentence,sentences.filter((item)=>item===sentence).length]));};
function diversified(candidates:ControlledDraftPreview[],maximum:number):ControlledDraftPreview[]{const selected:ControlledDraftPreview[]=[],companies=new Set<string>(),lanes=new Set<string>(),functions=new Set<string>(),industries=new Set<string>(),personas=new Set<string>();while(selected.length<maximum){const remaining=candidates.filter((draft)=>!selected.includes(draft)&&!companies.has(draft.company));if(!remaining.length)break;remaining.sort((a,b)=>{const novelty=(draft:ControlledDraftPreview)=>(lanes.has(draft.lane)?0:8)+(functions.has(draft.recipientFunction??"unknown")?0:4)+(industries.has(draft.snapshot.industry)?0:2)+(personas.has(draft.persona)?0:1);return novelty(b)-novelty(a)||b.targetingScore-a.targetingScore||a.candidateReference.localeCompare(b.candidateReference);});const chosen=remaining[0]!;selected.push(chosen);companies.add(chosen.company);lanes.add(chosen.lane);functions.add(chosen.recipientFunction??"unknown");industries.add(chosen.snapshot.industry);personas.add(chosen.persona);}return selected;}

async function main():Promise<void>{
  if(process.env.NETWORKPILOT_GMAIL_ENABLED!=="true")throw new Error("gmail-pilot-feature-disabled");const argument=process.argv[2];if(!argument)throw new Error("gmail-pilot-credential-path-required");const credentialPath=realpathSync(resolve(argument));if(!relative(realpathSync(process.cwd()),credentialPath).startsWith(".."))throw new Error("gmail-pilot-credential-must-be-outside-repository");const credentials=JSON.parse(readFileSync(credentialPath,"utf8")) as DesktopCredentials,clientId=credentials.installed?.client_id,clientSecret=credentials.installed?.client_secret;if(!clientId||!clientSecret)throw new Error("gmail-pilot-desktop-credential-invalid");
  const repository=new SqliteSimulationRepository(DATABASE);try{repository.migrate();if(repository.getSetting("operationalScaleBatchCompleted")!=="true")throw new Error("gmail-pilot-source-unavailable");if(repository.getSetting("gmailHumanReviewedPilotStarted")==="true")throw new Error("gmail-pilot-already-started");const metadata=repository.getGmailConnectionMetadata();if(metadata?.state!=="connected"||!metadata.accountEmail||metadata.grantedScopes.length!==1||metadata.grantedScopes[0]!==GMAIL_COMPOSE_SCOPE)throw new Error("gmail-pilot-connection-invalid");
    const config=readGmailConfig({NETWORKPILOT_GMAIL_ENABLED:"true",GOOGLE_OAUTH_CLIENT_ID:clientId,GOOGLE_OAUTH_CLIENT_SECRET:clientSecret,GOOGLE_OAUTH_REDIRECT_URI:"http://127.0.0.1:8765/oauth/google/callback"}),secretStore=new MacOsKeychainGoogleTokenStore(),oauthTransport=new ObservedOAuthTransport(new FetchGoogleOAuthTransport()),session=new GoogleOAuthSession(config,oauthTransport,secretStore,()=>new Date(),repository),token=await session.getAccessToken();if(token.grantedScopes.length!==1||token.grantedScopes[0]!==GMAIL_COMPOSE_SCOPE||token.accountEmail?.toLowerCase()!==metadata.accountEmail.toLowerCase())throw new Error("gmail-pilot-token-identity-invalid");const keychainReload=await new MacOsKeychainGoogleTokenStore().load();if(!keychainReload||keychainReload.accountEmail?.toLowerCase()!==metadata.accountEmail.toLowerCase())throw new Error("gmail-pilot-keychain-readback-failed");
    const imported=repository.listImportedCandidates(),preview=prepareControlledRealCampaign(imported,{target:19,now:new Date("2026-09-09T22:55:14.684Z")}),events=repository.listOutreachEvents(),currentProspects=new Map(repository.listProspects().map((prospect)=>[prospect.id,prospect])),candidateByProspect=new Map(imported.map((candidate)=>[`authorized:${candidate.source.providerRecordId}`,candidate])),candidateById=new Map(imported.map((candidate)=>[candidate.id,candidate])),cooldownStart=Date.now()-7*24*60*60*1000,contacted=new Set(events.filter((event)=>CONTACT_IMPACTING_EVENT_TYPES.has(event.type)).map((event)=>event.prospectId)),cooldownCompanies=new Set(events.filter((event)=>CONTACT_IMPACTING_EVENT_TYPES.has(event.type)&&event.occurredAt.getTime()>=cooldownStart).map((event)=>candidateById.get(event.prospectId)?.strategyCompanyMatch?.companyId).filter((value):value is string=>Boolean(value))),skipped:Array<{candidateReference:string;company:string;reason:string}>=[],eligible:ControlledDraftPreview[]=[];
    for(const draft of preview.drafts){const candidate=candidateByProspect.get(draft.snapshot.prospectId),current=candidate?currentProspects.get(candidate.id):undefined,companyId=candidate?.strategyCompanyMatch?.companyId;if(!candidate||!companyId){skipped.push({candidateReference:draft.candidateReference,company:draft.company,reason:"mutable-source-unavailable"});continue;}const existing=repository.findGmailDraftOperation(snapshotId(draft));if(existing?.state==="gmail-draft-created"){skipped.push({candidateReference:draft.candidateReference,company:draft.company,reason:"already-externalized"});continue;}const reason=candidate.source.consent.suppressed||current?.suppressed?"suppressed":candidate.source.consent.optedOut||current?.optedOut?"opted-out":contacted.has(candidate.id)||contacted.has(draft.snapshot.prospectId)?"previous-contact":cooldownCompanies.has(companyId)?"company-cooldown":null;if(reason)skipped.push({candidateReference:draft.candidateReference,company:draft.company,reason});else eligible.push(draft);}
    const selected=diversified(eligible,MAX_DRAFTS);if(new Set(selected.map((draft)=>draft.company)).size<5)throw new Error("gmail-pilot-qualified-company-pool-insufficient");const mime=new DeterministicPlainTextMimeBuilder();for(const draft of selected){const candidate=candidateByProspect.get(draft.snapshot.prospectId)!;validateMime(mime.build({snapshotId:snapshotId(draft),recipientProfessionalEmail:candidate.source.email.address,recipientDisplayName:draft.redactedName,subject:draft.draft.subject,body:draft.draft.body,planningSnapshotId:`operational-scale:${draft.snapshot.prospectId}`,templateCatalogVersion:draft.draft.templateCatalogVersion,evidenceIds:draft.draft.referencedFactIds,approvedAt:new Date().toISOString()}),candidate.source.email.address,draft.draft.subject,draft.draft.body);}
    repository.setSetting("gmailHumanReviewedPilotStarted","true",new Date());const transport=new PilotGmailTransport(new FetchGmailTransport()),adapter=new GmailDraftAdapter(config,transport,session),account=await adapter.connectedAccount();if(account.toLowerCase()!==metadata.accountEmail.toLowerCase())throw new Error("gmail-pilot-account-mismatch");const results=[];for(const draft of selected){const candidate=candidateByProspect.get(draft.snapshot.prospectId)!,approved:ApprovedEmailDraftSnapshot={snapshotId:snapshotId(draft),recipientProfessionalEmail:candidate.source.email.address,recipientDisplayName:draft.redactedName,subject:draft.draft.subject,body:draft.draft.body,planningSnapshotId:`operational-scale:${draft.snapshot.prospectId}`,templateCatalogVersion:draft.draft.templateCatalogVersion,evidenceIds:draft.draft.referencedFactIds,approvedAt:new Date().toISOString()},operation=approveForGmailDraft(repository,approved,GMAIL_ADAPTER_VERSION),created=await createApprovedGmailDraft({snapshotId:operation.snapshot.snapshotId,repository,creator:adapter,mime,now:()=>new Date()});results.push({candidateReference:draft.candidateReference,redactedName:draft.redactedName,company:draft.company,title:draft.sourceTitle,recipientFunction:draft.recipientFunction,persona:draft.persona,experience:draft.yearsExperience,lane:draft.lane,templateVariant:draft.templateVariant,subject:draft.draft.subject,body:draft.draft.body,wordCount:draft.wordCount,whySelected:draft.whySelected,operationState:created.state,operationHash:hash(created.operationId).slice(0,12)});}
    repository.setSetting("gmailHumanReviewedPilotCompleted","true",new Date());console.log(JSON.stringify({operation:"NetworkPilot human-reviewed Gmail draft pilot — zero sends",connectedAccount:redactEmail(account),grantedScopes:token.grantedScopes,keychainReadback:true,tokenRefreshOccurred:oauthTransport.refreshCount>0,eligiblePool:eligible.length,skipped,selected:selected.length,distribution:{companies:counts(selected.map((draft)=>draft.company)),industries:counts(selected.map((draft)=>draft.snapshot.industry)),functions:counts(selected.map((draft)=>draft.recipientFunction??"unknown")),personas:counts(selected.map((draft)=>draft.persona)),lanes:counts(selected.map((draft)=>draft.lane)),variants:counts(selected.map((draft)=>draft.templateVariant))},http:transport.counts,drafts:results,repetition:{uniqueSubjects:new Set(selected.map((draft)=>draft.draft.subject)).size,repeatedSentences:sentenceCounts(selected),factCombinations:counts(selected.map((draft)=>[...draft.draft.referencedFactIds].sort().join("+"))),asks:counts(selected.map((draft)=>draft.draft.body.split("\n").find((line)=>/15 minutes|15-minute/.test(line))??"unknown")),openings:counts(selected.map((draft)=>draft.draft.body.split("\n").filter(Boolean)[1]??"unknown"))},automatedReview:{ready:selected.filter((draft)=>draft.constraintFailures.length===0).length,editing:selected.filter((draft)=>draft.constraintFailures.length>0).length},reconciliationRequired:results.filter((result)=>result.operationState==="reconciliation-required").length,emailSending:false,apolloActivity:false},null,2));
  }finally{repository.close();}}
main().catch((error)=>{console.error(JSON.stringify({error:error instanceof Error?error.message:"gmail-pilot-failed"}));process.exitCode=1;});
