import {createHash} from "node:crypto";
import {createServer} from "node:http";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import {readFileSync,realpathSync} from "node:fs";
import {relative,resolve} from "node:path";
import {approveForGmailDraft,createApprovedGmailDraft,GMAIL_COMPOSE_SCOPE,type ApprovedEmailDraftSnapshot} from "../src/application/email-drafts";
import {prepareControlledRealCampaign} from "../src/application/providers/prepare-controlled-real-campaign";
import {DeterministicPlainTextMimeBuilder,FetchGmailTransport,FetchGoogleOAuthTransport,GmailDraftAdapter,GMAIL_ADAPTER_VERSION,GoogleOAuthSession,MacOsKeychainGoogleTokenStore,readGmailConfig,type GmailHttpResponse,type GmailHttpTransport} from "../src/infrastructure/providers/gmail";
import {SqliteSimulationRepository} from "../src/infrastructure/sqlite/database";

const execute=promisify(execFile),DATABASE=resolve(process.cwd(),"data/apollo-operational-scale-enrichment.sqlite"),hash=(value:string)=>createHash("sha256").update(value).digest("hex"),redactEmail=(email:string)=>`${email.slice(0,1)}***@${email.split("@")[1]}`;
interface DesktopCredentials {installed?:{client_id?:string;client_secret?:string};}

class ControlledGmailTransport implements GmailHttpTransport{
  readonly counts={profile:0,draftCreate:0};
  constructor(private readonly delegate:GmailHttpTransport){}
  async request(input:Parameters<GmailHttpTransport["request"]>[0]):Promise<GmailHttpResponse>{if(input.path==="/gmail/v1/users/me/profile"&&input.method==="GET"){if(this.counts.profile>=1)throw new Error("gmail-live-profile-cap-exceeded");this.counts.profile++;return this.delegate.request(input);}if(input.path==="/gmail/v1/users/me/drafts"&&input.method==="POST"){if(this.counts.draftCreate>=2)throw new Error("gmail-live-draft-cap-exceeded");this.counts.draftCreate++;return this.delegate.request(input);}throw new Error("gmail-live-endpoint-not-authorized");}
}

const waitForAuthorization=async(session:GoogleOAuthSession,port:number):Promise<void>=>{
  const server=createServer();await new Promise<void>((resolveListen,reject)=>{server.once("error",reject);server.listen(port,"127.0.0.1",()=>resolveListen());});
  const authorization=session.createAuthorizationUrl(),callback=new Promise<{code:string;state:string}>((resolveCallback,reject)=>{const timer=setTimeout(()=>{server.close();reject(new Error("gmail-oauth-callback-timeout"));},5*60*1000);server.on("request",(request,response)=>{const url=new URL(request.url??"/",`http://127.0.0.1:${port}`);if(url.pathname!=="/oauth/google/callback"){response.writeHead(404).end();return;}const code=url.searchParams.get("code"),state=url.searchParams.get("state");response.writeHead(code&&state?200:400,{"content-type":"text/plain; charset=utf-8"});response.end(code&&state?"NetworkPilot authorization received. Return to the terminal.":"NetworkPilot authorization failed.");clearTimeout(timer);server.close();if(code&&state)resolveCallback({code,state});else reject(new Error("gmail-oauth-callback-invalid"));});});
  await execute("open",[authorization.url]);const result=await callback;await session.completeAuthorization(result.code,result.state);
};

const validateMime=(raw:string,expectedEmail:string,expectedSubject:string,expectedBody:string)=>{const decoded=Buffer.from(raw,"base64url").toString("utf8");if(!decoded.startsWith(`To: `)||!decoded.includes(`<${expectedEmail}>\r\n`)||!decoded.includes("\r\nMIME-Version: 1.0\r\n")||!decoded.endsWith(expectedBody.replace(/\r?\n/g,"\r\n"))||/\r\n(?:Cc|Bcc|From):/i.test(decoded)||/content-type:\s*text\/html/i.test(decoded)||/content-disposition:|<img|tracking/i.test(decoded)||!decoded.includes(`Subject: ${expectedSubject}\r\n`))throw new Error("gmail-live-mime-validation-failed");};

async function main():Promise<void>{
  if(process.env.NETWORKPILOT_GMAIL_ENABLED!=="true")throw new Error("gmail-live-feature-disabled");
  const credentialArgument=process.argv[2];if(!credentialArgument)throw new Error("gmail-live-credential-path-required");const credentialPath=realpathSync(resolve(credentialArgument)),insideRepository=!relative(realpathSync(process.cwd()),credentialPath).startsWith("..");if(insideRepository)throw new Error("gmail-live-credential-must-be-outside-repository");
  const parsed=JSON.parse(readFileSync(credentialPath,"utf8")) as DesktopCredentials,clientId=parsed.installed?.client_id,clientSecret=parsed.installed?.client_secret;if(!clientId||!clientSecret)throw new Error("gmail-live-desktop-credential-invalid");
  const repository=new SqliteSimulationRepository(DATABASE);try{
    repository.migrate();if(repository.getSetting("operationalScaleBatchCompleted")!=="true")throw new Error("gmail-live-operational-drafts-unavailable");if(repository.getSetting("gmailControlledLiveStarted")==="true")throw new Error("gmail-live-already-started");
    const server=createServer();await new Promise<void>((resolveListen,reject)=>{server.once("error",reject);server.listen(0,"127.0.0.1",()=>resolveListen());});const address=server.address();if(!address||typeof address==="string")throw new Error("gmail-loopback-address-invalid");const port=address.port;await new Promise<void>((resolveClose)=>server.close(()=>resolveClose()));
    const config=readGmailConfig({NETWORKPILOT_GMAIL_ENABLED:"true",GOOGLE_OAUTH_CLIENT_ID:clientId,GOOGLE_OAUTH_CLIENT_SECRET:clientSecret,GOOGLE_OAUTH_REDIRECT_URI:`http://127.0.0.1:${port}/oauth/google/callback`}),secretStore=new MacOsKeychainGoogleTokenStore(),oauthTransport=new FetchGoogleOAuthTransport(),session=new GoogleOAuthSession(config,oauthTransport,secretStore,()=>new Date(),repository),existing=await secretStore.load();let authorizationPerformed=false;
    if(!existing){authorizationPerformed=true;await waitForAuthorization(session,port);}const granted=await session.getAccessToken();if(granted.grantedScopes.length!==1||granted.grantedScopes[0]!==GMAIL_COMPOSE_SCOPE)throw new Error("gmail-live-scope-invalid");const reloaded=await new MacOsKeychainGoogleTokenStore().load();if(!reloaded||reloaded.refreshToken!==granted.refreshToken)throw new Error("gmail-live-keychain-readback-failed");
    repository.setSetting("gmailControlledLiveStarted","true",new Date());const transport=new ControlledGmailTransport(new FetchGmailTransport()),adapter=new GmailDraftAdapter(config,transport,session),account=await adapter.connectedAccount();if(!account)throw new Error("gmail-live-account-ambiguous");
    const candidates=repository.listImportedCandidates(),preview=prepareControlledRealCampaign(candidates,{target:19,now:new Date("2026-09-09T22:55:14.684Z")}),selected=[preview.drafts.find((draft)=>draft.lane==="engineering-technical"),preview.drafts.find((draft)=>draft.lane!=="engineering-technical")];if(selected.some((draft)=>!draft)||selected[0]!.lane===selected[1]!.lane)throw new Error("gmail-live-distinct-drafts-unavailable");const byProspect=new Map(candidates.map((candidate)=>[`authorized:${candidate.source.providerRecordId}`,candidate])),mime=new DeterministicPlainTextMimeBuilder(),results=[];
    for(const draft of selected){const candidate=byProspect.get(draft!.snapshot.prospectId);if(!candidate||candidate.source.email.verificationStatus!=="verified"||!candidate.source.email.address)throw new Error("gmail-live-recipient-invalid");const approved:ApprovedEmailDraftSnapshot={snapshotId:`gmail-live:${hash(JSON.stringify({prospectId:draft!.snapshot.prospectId,subject:draft!.draft.subject,body:draft!.draft.body,catalog:draft!.draft.templateCatalogVersion}))}`,recipientProfessionalEmail:candidate.source.email.address,recipientDisplayName:draft!.redactedName,subject:draft!.draft.subject,body:draft!.draft.body,planningSnapshotId:`operational-scale:${draft!.snapshot.prospectId}`,templateCatalogVersion:draft!.draft.templateCatalogVersion,evidenceIds:draft!.draft.referencedFactIds,approvedAt:new Date().toISOString()},operation=approveForGmailDraft(repository,approved,GMAIL_ADAPTER_VERSION),raw=mime.build(operation.snapshot);validateMime(raw,candidate.source.email.address,draft!.draft.subject,draft!.draft.body);const created=await createApprovedGmailDraft({snapshotId:operation.snapshot.snapshotId,repository,creator:adapter,mime,now:()=>new Date()});results.push({operationHash:hash(created.operationId).slice(0,12),draftIdHash:hash(created.gmailDraftId!).slice(0,12),messageIdHash:hash(created.gmailMessageId!).slice(0,12),state:created.state,lane:draft!.lane,company:draft!.company,recipient:"redacted",mimeValidated:true});if(results.length===1){const before=transport.counts.draftCreate,repeated=await createApprovedGmailDraft({snapshotId:operation.snapshot.snapshotId,repository,creator:adapter,mime,now:()=>new Date()});if(repeated.gmailDraftId!==created.gmailDraftId||transport.counts.draftCreate!==before)throw new Error("gmail-live-idempotency-failed");}}
    repository.setSetting("gmailControlledLiveCompleted","true",new Date());console.log(JSON.stringify({operation:"NetworkPilot controlled Gmail draft validation — zero sends",authorizationPerformed,requestedScopes:[GMAIL_COMPOSE_SCOPE],grantedScopes:granted.grantedScopes,keychainReadback:true,connectedAccount:redactEmail(account),http:transport.counts,drafts:results,reconciliationRequired:results.some((result)=>result.state==="reconciliation-required"),emailSending:false,apolloActivity:false},null,2));
  }finally{repository.close();}
}
main().catch((error)=>{console.error(JSON.stringify({error:error instanceof Error?error.message:"gmail-live-validation-failed"}));process.exitCode=1;});
