import {mkdtempSync,readFileSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {approveForGmailDraft} from "@/application/email-drafts";
import {SqliteSimulationRepository} from "@/infrastructure/sqlite/database";
import {LocalResumeStore} from "@/infrastructure/resumes/local-store";
import {addResume,attachmentSnapshot,MAX_RESUME_BYTES,sanitizePdfFilename,suggestedResumeId,validateResumePdf} from ".";

const directories:string[]=[];
const setup=()=>{const root=mkdtempSync(join(tmpdir(),"networkpilot-resume-"));directories.push(root);const repository=new SqliteSimulationRepository(join(root,"test.sqlite"));repository.migrate();return{root,repository,store:new LocalResumeStore(join(root,"private-resumes"))};};
const pdf=Buffer.from("%PDF-1.4\n1 0 obj\n<<>>\nendobj\n%%EOF\n");
afterEach(()=>{while(directories.length)rmSync(directories.pop()!,{recursive:true,force:true});});

describe("Resume Library",()=>{
  it("validates, sanitizes, hashes, stores, and classifies an exact PDF version",()=>{const{repository,store}=setup(),record=addResume({repository,store:(key,bytes)=>store.store(key,bytes),filename:"../../Dylan Résumé (Product).PDF",bytes:pdf,displayLabel:"Product Resume",roleLane:"product",now:()=>new Date("2026-09-20T12:00:00Z"),id:"resume-product"});expect(record).toMatchObject({id:"resume-product",originalFilename:"Dylan Resume Product.pdf",displayLabel:"Product Resume",roleLane:"product",sizeBytes:pdf.byteLength,active:true});expect(record.sha256).toMatch(/^[a-f0-9]{64}$/);expect(Buffer.from(store.read(record))).toEqual(pdf);expect(readFileSync(join(store.root,record.storageKey))).toEqual(pdf);repository.close();});
  it("rejects invalid extensions, signatures, empty files, and oversized files",()=>{expect(()=>validateResumePdf({filename:"resume.docx",bytes:pdf})).toThrow("resume-pdf-extension-required");expect(()=>validateResumePdf({filename:"resume.pdf",bytes:Buffer.from("not pdf")})).toThrow("resume-pdf-signature-invalid");expect(()=>validateResumePdf({filename:"resume.pdf",bytes:new Uint8Array()})).toThrow("resume-pdf-empty");expect(()=>validateResumePdf({filename:"resume.pdf",bytes:new Uint8Array(MAX_RESUME_BYTES+1)})).toThrow("resume-pdf-too-large");});
  it("prevents traversal in both display filenames and storage keys",()=>{expect(sanitizePdfFilename("../../private/../resume.pdf")).toBe("resume.pdf");const{store,repository}=setup();expect(()=>store.store("../escape.pdf",pdf)).toThrow("resume-storage-key-invalid");repository.close();});
  it("keeps inactive versions for history and excludes them from attachment snapshots",()=>{const{repository,store}=setup(),record=addResume({repository,store:(key,bytes)=>store.store(key,bytes),filename:"resume.pdf",bytes:pdf,displayLabel:"General Resume",roleLane:"general",now:()=>new Date(),id:"resume-general"});repository.deactivateResume(record.id);expect(repository.findResume(record.id)).toMatchObject({active:false});expect(()=>attachmentSnapshot(repository.findResume(record.id)!)).toThrow("resume-inactive");repository.close();});
  it("suggests by recruiter lane but defaults professional networking to None",()=>{const resumes=[{id:"product",displayLabel:"Product",originalFilename:"p.pdf",storageKey:"a".repeat(64)+".pdf",sizeBytes:1,sha256:"a".repeat(64),uploadedAt:"2026-01-01",roleLane:"product" as const,active:true},{id:"general",displayLabel:"General",originalFilename:"g.pdf",storageKey:"b".repeat(64)+".pdf",sizeBytes:1,sha256:"b".repeat(64),uploadedAt:"2026-01-01",roleLane:"general" as const,active:true}];expect(suggestedResumeId({track:"professional",lane:"product-management",resumes})).toBeNull();expect(suggestedResumeId({track:"recruiter",lane:"product-management",resumes})).toBe("product");expect(suggestedResumeId({track:"recruiter",lane:"other",resumes})).toBe("general");});
  it("freezes attachment metadata in the approved operation despite later library edits",()=>{const{repository,store}=setup(),record=addResume({repository,store:(key,bytes)=>store.store(key,bytes),filename:"product.pdf",bytes:pdf,displayLabel:"Product Resume",roleLane:"product",now:()=>new Date(),id:"resume-product"}),attachment=attachmentSnapshot(record),snapshot={snapshotId:"snapshot-with-resume",recipientProfessionalEmail:"person@example.invalid",recipientDisplayName:"Person",subject:"Product question",body:"Exact reviewed body",planningSnapshotId:"plan",templateCatalogVersion:"catalog",evidenceIds:[],approvedAt:"2026-09-20T12:00:00Z",resumeAttachment:attachment};approveForGmailDraft(repository,snapshot,"fixture");repository.updateResumeMetadata(record.id,{displayLabel:"Renamed Later",roleLane:"general"});repository.deactivateResume(record.id);expect(repository.findGmailDraftOperation(snapshot.snapshotId)?.snapshot.resumeAttachment).toEqual(attachment);repository.close();});
});
