import type {RecruiterClassification,RecruiterDraft} from "./types";
import {assertDylanVoice} from "@/domain/drafting/voice";

const words=(value:string)=>value.trim().split(/\s+/).length;
const hash=(value:string)=>{let result=0x811c9dc5;for(const character of value){result^=character.charCodeAt(0);result=Math.imul(result,0x01000193)>>>0;}return result;};
export function renderRecruiterDraft(input:{firstName:string;company:string;title:string;classification:RecruiterClassification;variationOrdinal?:number}):RecruiterDraft{
  if(!input.classification.accepted)throw new Error("recruiter-not-qualified");
  const variant=input.classification.earlyCareerRelevance?"early-career-alignment":input.classification.technicalRelevance?"technical-recruiting-alignment":input.classification.recruiterType==="general-recruiter"?"general-internal-recruiter":"direct-introduction",index=input.variationOrdinal===undefined?hash(`${input.firstName}|${input.company}|${input.title}|${variant}`)%3:Math.abs(input.variationOrdinal)%3;
  const subjects=input.classification.earlyCareerRelevance?[`Early-career technical roles at ${input.company}`,"Early-career data and product roles","Quick question about early-career hiring"]:input.classification.technicalRelevance?[`Data and product roles at ${input.company}`,"Quick question about technical roles","Technical hiring at "+input.company]:[`Roles at ${input.company}`,"Quick question about your recruiting area","Data and product opportunities"];
  const alignment=input.classification.earlyCareerRelevance?[`I saw you work in early-career recruiting at ${input.company}, so I figured you might be a good person to contact.`,`I saw you work on early-career hiring at ${input.company} and wanted to ask about the roles you cover.`,`I noticed your focus on early-career recruiting at ${input.company} while looking for the right person to contact about technical roles.`][index]:input.classification.technicalRelevance?[`I saw you work in technical recruiting at ${input.company}, so I figured you might be a good person to contact.`,`I saw you recruit for technical roles at ${input.company} and wanted to ask which teams you work with.`,`I noticed your work in technical recruiting at ${input.company} while looking for the right person to contact about data and product roles.`][index]:[`I saw you recruit internally at ${input.company}, so I figured you might be a good person to contact.`,`I’m looking into technical roles at ${input.company} and saw that you work in recruiting there.`,`I noticed you handle recruiting at ${input.company} while looking for the right contact about data and technical roles.`][index];
  const context=["I graduated in May 2026 with a computer science degree and got hands-on BI and data engineering experience using SQL, Python, ETL, and APIs.","My background is in computer science and hands-on BI and data engineering, including automation, APIs, and cross-system integrations that supported real operating needs.","I’m a May 2026 computer science graduate with practical experience connecting BI, data engineering, automation, and business needs."][index];
  const target=input.classification.earlyCareerRelevance?"I’m mainly looking at early-career data, analytics, software, AI/ML, and technical product roles where I can use that experience and keep developing my technical skills.":input.classification.technicalRelevance?"I’m mainly looking at data, analytics, software, AI/ML, and technical product roles where I can use that experience and keep developing my technical skills.":"I’m mainly looking at data, analytics, software, and technical product roles where I can use that experience and keep developing my technical skills.";
  const cta=["If those fall within your area, would you be open to keeping me in mind?","Do those roles fall within your recruiting area?","If someone else handles those roles, would you point me toward the right recruiter?"][index],signoff=index===0?"Best,":index===1?"Thanks,":"Appreciate it,",body=[`Hi ${input.firstName},`,alignment,context,target,cta,signoff,"Dylan"].join("\n\n"),subject=subjects[index]!;
  assertDylanVoice(subject,body);return{track:"recruiter",subject,body,variant,wordCount:words(body),referencedEvidence:["dylan-cs-graduation","dylan-bi-data-experience",...(input.classification.technicalRelevance?["recruiter-technical-title"]:[]),...(input.classification.earlyCareerRelevance?["recruiter-early-career-title"]:[])],catalogVersion:"recruiter-catalog-v5-dylan-outreach-method-v3",subjectVersion:"recruiter-subject-v5"};
}
