import {describe,expect,it} from "vitest";
import {classifyRecruiter,planRecruiterCandidates,renderRecruiterDraft,type RecruiterClassification} from ".";
import type {ImportedCandidateSnapshot} from "@/application/ingestion";

const classify=(title:string,employerName="Datadog",internalCompanyMatch=true,minimumExperience:number|null=3,maximumExperience:number|null=4)=>classifyRecruiter({title,employerName,internalCompanyMatch,minimumExperience,maximumExperience});
describe("Recruiter Track",()=>{
  it("classifies relevant recruiter titles without leaking into the professional track",()=>{for(const title of ["Technical Recruiter","Senior Talent Acquisition Partner","University Recruiter","Engineering Recruiting Manager"]){const result=classify(title);expect(result.track).toBe("recruiter");expect(result.accepted).toBe(true);}});
  it("fails closed for agencies, ambiguous employers, coordinators, HR, and executives",()=>{expect(classify("Technical Recruiter","Example Staffing").internalStatus).toBe("agency");expect(classify("Recruiter","Unknown",false).accepted).toBe(false);expect(classify("Recruiting Coordinator").accepted).toBe(false);expect(classify("HR Business Partner").track).toBe("professional");expect(classify("VP Talent Acquisition").accepted).toBe(false);});
  it("uses recruiter-specific experience and relevance",()=>{expect(classify("Technical Recruiter","Datadog",true,2,3).accepted).toBe(true);expect(classify("Technical Recruiter","Datadog",true,1,1).accepted).toBe(false);expect(classify("Technical Recruiter").technicalRelevance).toBe(true);expect(classify("Early Careers Recruiter").earlyCareerRelevance).toBe(true);expect(classify("Recruiter").score).toBeLessThan(classify("Technical Recruiter").score);});
  it("renders concise recruiter-specific copy in Dylan's voice without unsupported specialization",()=>{const general=classify("Recruiter"),draft=renderRecruiterDraft({firstName:"Avery",company:"Datadog",title:"Recruiter",classification:general});expect(draft.wordCount).toBeGreaterThanOrEqual(75);expect(draft.wordCount).toBeLessThanOrEqual(120);expect(`${draft.subject} ${draft.body}`).not.toMatch(/—|coffee|pick your brain|you recruit for data engineering|I hope this message finds you well|I would love the opportunity/i);expect(draft.body).toContain("hands-on BI and data engineering experience");expect(draft.body).toContain("would you be open to keeping me in mind?");expect(draft.body.match(/\?/g)).toHaveLength(1);expect(draft.subject).toBe("Roles at Datadog");const technical=renderRecruiterDraft({firstName:"Avery",company:"Datadog",title:"Technical Recruiter",classification:classify("Technical Recruiter")});expect(technical.variant).toBe("technical-recruiting-alignment");expect(technical.subject).toMatch(/technical|Data and product/i);expect(technical.body).toMatch(/AI\/ML.*technical product/);});
  it("supports product-recruiter language without claiming Dylan has been a PM",()=>{const classification=classify("Product Recruiter"),draft=renderRecruiterDraft({firstName:"Maya",company:"Fictional Systems",title:"Product Recruiter",classification});expect(classification.technicalRelevance).toBe(true);expect(draft.body).toMatch(/Product as my first full-time role/);expect(draft.body).not.toMatch(/I(?:’m| am| was| have been) (?:a |an )?(?:technical )?product manager/i);expect(draft.body.match(/\?/g)).toHaveLength(1);});
  it("uses a plain fallback subject when an employer name would exceed the voice limit",()=>{const draft=renderRecruiterDraft({firstName:"Avery",company:"The Port Authority of New York & New Jersey",title:"Senior Campus Recruiter",classification:classify("Senior Campus Recruiter")});expect(draft.subject).toBe("Quick question about early-career hiring");expect(draft.subject.length).toBeLessThanOrEqual(64);expect(draft.body).toContain("The Port Authority of New York & New Jersey");});
  it("plans five verified, unsuppressed people from distinct unblocked companies",()=>{const candidate=(id:string,company:string,classification:RecruiterClassification=classify("Technical Recruiter")):ImportedCandidateSnapshot=>({id,batchId:"b",source:{sourceProviderId:"fixture",providerRecordId:id,datasetClassification:"provider-shaped-fixture",person:{firstName:"A",lastName:"B"},currentTitle:"Technical Recruiter",currentOrganization:{name:company},location:"Boston",industrySignals:[],experienceEvidence:[],email:{address:"a@example.invalid",verificationStatus:"verified"},sourceTimestamps:{retrievedAt:"2026-01-01"},fieldProvenance:{},consent:{suppressed:false,optedOut:false},sourceFingerprint:`fingerprint-${id}`},classification:{normalizedTitle:"technical recruiter",specificRoleId:null,roleFamilyId:null,matchedSignals:[],classificationVersion:"role-classification-v2",reviewCode:null},recipientFunction:{primaryFunction:"unrelated",secondaryFunctions:[],evidence:[],confidence:"high",reviewState:"review-required",explanationCodes:[],classifierVersion:"recipient-function-v2"},targetRoleAffinities:[],recipientRelevance:{score:0,version:"recipient-relevance-v2",explanationCodes:[]},experience:{minimumSupportedYears:3,maximumSupportedYears:4,kind:"exact",evidence:[],interpretationVersion:"experience-v1",confidence:"high",reviewState:"accepted",explanationCodes:[]},personaId:"recruiter",geographyId:"boston-ma",strategyCompanyMatch:{companyId:company,canonicalName:company,method:"exact-name"},dataQualityScore:100,gateFailures:[],state:"eligible",reviewState:"pending",outreachTrack:"recruiter",recruiterClassification:classification});const rows=[candidate("1","A"),candidate("2","A"),candidate("3","B"),candidate("4","C"),candidate("5","D"),candidate("6","E"),candidate("7","F")];expect(planRecruiterCandidates(rows,new Set(["B"]),new Set(["7"]))).toHaveLength(4);expect(new Set(planRecruiterCandidates(rows,new Set(),new Set()).map((item)=>item.strategyCompanyMatch?.companyId)).size).toBe(5);const unverified=candidate("8","G"),suppressed=candidate("9","H"),optedOut=candidate("10","I");unverified.source.email.verificationStatus="unknown";suppressed.source.consent.suppressed=true;optedOut.source.consent.optedOut=true;expect(planRecruiterCandidates([unverified,suppressed,optedOut],new Set(),new Set())).toEqual([]);});
});
