import {createHash} from "node:crypto";
import type {CandidateSourceRecord,EmailVerificationStatus,ExperienceEvidence} from "@/domain/candidates";
import {assertApolloEnabled,redactApolloError} from "./config";
import {APOLLO_ADAPTER_VERSION,APOLLO_IMPORT_VERSION,APOLLO_MAPPING_VERSION,type ApolloBudgetRepository,type ApolloConfig,type ApolloEnrichmentOptions,type ApolloHttpResponse,type ApolloHttpTransport,type ApolloSearchOptions,type ApolloSearchResult} from "./types";
type JsonRecord=Record<string,unknown>;
const DEFAULT_SENIORITIES=["manager","director","senior"] as const;
const PROHIBITED=new Set(["intern","entry","owner","founder","c_suite","vp","head","partner"]);
const record=(value:unknown):JsonRecord=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("apollo-response-malformed");return value as JsonRecord;};
const optionalRecord=(value:unknown):JsonRecord|undefined=>value&&typeof value==="object"&&!Array.isArray(value)?value as JsonRecord:undefined;
const optionalString=(value:unknown)=>typeof value==="string"&&value.trim()?value.trim():undefined;
const requiredString=(value:unknown,field:string)=>{const result=optionalString(value);if(!result)throw new Error(`apollo-required-field-missing:${field}`);return result;};
const stringArray=(value:unknown)=>Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"&&Boolean(item.trim())).map((item)=>item.trim()):[];
const fingerprint=(value:unknown)=>`apollo-v1:${createHash("sha256").update(JSON.stringify(value)).digest("hex")}`;
const timestamp=(value:unknown,fallback:string)=>{if(typeof value==="number"&&Number.isFinite(value))return new Date(value*1000).toISOString();if(typeof value==="string"&&!Number.isNaN(new Date(value).getTime()))return new Date(value).toISOString();return fallback;};
export function mapApolloEmailStatus(value:unknown,hasEmail:boolean,stage:"search"|"enrichment"):EmailVerificationStatus{if(stage==="search")return"unknown";if(!hasEmail||value==="unavailable")return"unknown";return value==="verified"?"verified":value==="unverified"?"unverified":"unknown";}
const employmentEvidence=(person:JsonRecord,retrievedAt:string):ExperienceEvidence[]=>{const history=person.employment_history;if(!Array.isArray(history)||history.length===0)return[{kind:"unknown",sourceField:"person.employment_history"}];return[{kind:"employment-history",sourceField:"person.employment_history",referenceDate:retrievedAt.slice(0,10),periods:history.map((entry)=>{const item=optionalRecord(entry)??{};return{startDate:optionalString(item.start_date),endDate:optionalString(item.end_date),current:item.current===true};})}];};
export function mapApolloPerson(value:unknown,input:{stage:"search"|"enrichment";retrievedAt:string;datasetClassification:"provider-shaped-fixture"|"authorized-provider"}):CandidateSourceRecord{
  const person=record(value),organization=optionalRecord(person.organization)??{},id=requiredString(person.id,"person.id"),firstName=requiredString(person.first_name,"person.first_name"),lastName=requiredString(input.stage==="search"?person.last_name_obfuscated??person.last_name:person.last_name,input.stage==="search"?"person.last_name_obfuscated":"person.last_name"),title=requiredString(person.title,"person.title"),organizationName=requiredString(organization.name??person.organization_name,"person.organization.name"),email=input.stage==="search"?"":optionalString(person.email)??"unavailable@example.test",updatedAt=timestamp(person.updated_at??person.last_refreshed_at,input.retrievedAt);
  const source=(field:string)=>({sourceField:`apollo.${field}`,observedAt:updatedAt,confidence:"high" as const});
  return{sourceProviderId:"apollo",providerRecordId:id,datasetClassification:input.datasetClassification,person:{firstName,lastName},currentTitle:title,currentOrganization:{name:organizationName,...optionalString(organization.primary_domain)?{domain:optionalString(organization.primary_domain)!}:{}},location:[optionalString(person.city),optionalString(person.state),optionalString(person.country)].filter(Boolean).join(", ")||"unknown",industrySignals:stringArray(organization.industry?[organization.industry]:organization.industries),experienceEvidence:employmentEvidence(person,input.retrievedAt),email:{address:email,verificationStatus:mapApolloEmailStatus(person.email_status,Boolean(optionalString(person.email)),input.stage)},sourceTimestamps:{retrievedAt:input.retrievedAt,updatedAt},fieldProvenance:{person:source("person.name"),currentTitle:source("person.title"),currentOrganization:source("person.organization"),experienceEvidence:source("person.employment_history"),email:source("person.email_status"),seniority:source("person.seniority")},consent:{suppressed:false,optedOut:false,evidence:"provider-consent-status-unavailable"},sourceFingerprint:fingerprint({adapter:APOLLO_ADAPTER_VERSION,mapping:APOLLO_MAPPING_VERSION,person}),providerMetadata:{adapterVersion:APOLLO_ADAPTER_VERSION,responseMappingVersion:APOLLO_MAPPING_VERSION,requestContractVersion:"apollo-people-v1-assumed",importArchitectureVersion:APOLLO_IMPORT_VERSION,providerSeniority:optionalString(person.seniority)}};
}
export class ApolloProviderError extends Error{constructor(readonly category:string,message=category){super(message);this.name="ApolloProviderError";}}
const withContractMetadata=(source:CandidateSourceRecord):CandidateSourceRecord=>({...source,providerMetadata:{...source.providerMetadata,adapterVersion:APOLLO_ADAPTER_VERSION,responseMappingVersion:APOLLO_MAPPING_VERSION,requestContractVersion:"apollo-people-v1-assumed",importArchitectureVersion:APOLLO_IMPORT_VERSION}});
const errorCategory=(status:number)=>status===401?"provider-authentication-failed":status===403?"provider-authorization-failed":status===429?"provider-rate-limited":status>=500?"provider-transient-failure":"provider-request-rejected";
export class ApolloAdapter{
  constructor(private readonly config:ApolloConfig,private readonly transport:ApolloHttpTransport,private readonly budgets:ApolloBudgetRepository,private readonly dependencies:{now:()=>Date;sleep:(milliseconds:number)=>Promise<void>;datasetClassification:"provider-shaped-fixture"|"authorized-provider";localDate:(date:Date)=>string}){}
  private async call(path:"/api/v1/mixed_people/api_search"|"/api/v1/people/match",body:unknown,operationId?:string):Promise<ApolloHttpResponse>{const apiKey=assertApolloEnabled(this.config);for(let attempt=0;attempt<=this.config.maxRetries;attempt++){if(operationId)this.budgets.recordApolloAttempt(operationId);try{const response=await this.transport.request({path,body,apiKey,timeoutMs:this.config.timeoutMs,maxResponseBytes:this.config.maxResponseBytes});if(response.status>=200&&response.status<300)return response;const category=errorCategory(response.status);if((response.status===429||response.status>=500)&&attempt<this.config.maxRetries){const retryAfter=Number(response.headers["retry-after"]);await this.dependencies.sleep(Number.isFinite(retryAfter)&&retryAfter>=0?retryAfter*1000:250*2**attempt);continue;}throw new ApolloProviderError(category);}catch(error){if(error instanceof ApolloProviderError)throw error;if(attempt<this.config.maxRetries){await this.dependencies.sleep(250*2**attempt);continue;}throw new ApolloProviderError(error instanceof Error&&error.message==="apollo-request-timeout"?"provider-timeout":"provider-transport-failure",redactApolloError(error,apiKey));}}throw new ApolloProviderError("provider-retry-exhausted");}
  async search(options:ApolloSearchOptions):Promise<ApolloSearchResult>{const seniorities=options.seniorities??[...DEFAULT_SENIORITIES],titles=options.specificTitles??[];if(seniorities.some((item)=>PROHIBITED.has(item)))throw new Error("apollo-seniority-prohibited");if(options.includeSimilarTitles===true&&options.controlledDiagnosticAuthorization!=="milestone-6.1b")throw new Error("apollo-similar-titles-require-explicit-authorization");if(options.includeSimilarTitles===true&&!titles.length)throw new Error("apollo-similar-titles-require-titles");const body:JsonRecord={page:options.page??1,per_page:Math.min(options.perPage??25,100)};if(options.companyDomains?.length)body.q_organization_domains_list=options.companyDomains;if(options.organizationIds?.length)body.organization_ids=options.organizationIds;if(titles.length){body.person_titles=titles;body.include_similar_titles=options.includeSimilarTitles??false;}if(seniorities.length)body.person_seniorities=seniorities;if(options.personLocations?.length)body.person_locations=options.personLocations;if(options.organizationLocations?.length)body.organization_locations=options.organizationLocations;if(options.emailStatuses?.length)body.contact_email_status=options.emailStatuses;const retrievedAt=this.dependencies.now().toISOString();const response=await this.call("/api/v1/mixed_people/api_search",body);let payload:JsonRecord;try{payload=record(JSON.parse(response.body));}catch{throw new ApolloProviderError("provider-response-malformed");}if(!Array.isArray(payload.people))throw new ApolloProviderError("provider-response-malformed");if(payload.people.some((person)=>optionalString(record(person).email)))throw new ApolloProviderError("provider-search-email-anomaly");return{records:payload.people.map((person)=>withContractMetadata(mapApolloPerson(person,{stage:"search",retrievedAt,datasetClassification:this.dependencies.datasetClassification}))),totalAvailable:typeof payload.total_entries==="number"?payload.total_entries:null,requestVersion:`${APOLLO_ADAPTER_VERSION}:${APOLLO_MAPPING_VERSION}:${APOLLO_IMPORT_VERSION}`};}
  async enrich(options:ApolloEnrichmentOptions):Promise<CandidateSourceRecord[]>{assertApolloEnabled(this.config);if(!options.personIds.length)return[];const at=this.dependencies.now(),operationId=`apollo-enrich:${fingerprint({batchId:options.batchId,ids:[...options.personIds].sort()})}`;this.budgets.authorizeApolloOperation({operationId,batchId:options.batchId,localDate:this.dependencies.localDate(at),candidateCount:options.personIds.length,estimatedMaxExposure:options.personIds.length,maximumPerBatch:this.config.maxEnrichmentsPerBatch,maximumPerDay:this.config.maxEnrichmentsPerDay,hardStop:this.config.hardStop,at});const records:CandidateSourceRecord[]=[];try{for(const id of options.personIds){const response=await this.call("/api/v1/people/match",{id,reveal_personal_emails:false,reveal_phone_number:false,run_waterfall_email:false,run_waterfall_phone:false},operationId);let payload:JsonRecord;try{payload=record(JSON.parse(response.body));}catch{throw new ApolloProviderError("provider-response-malformed");}records.push(withContractMetadata(mapApolloPerson(payload.person,{stage:"enrichment",retrievedAt:at.toISOString(),datasetClassification:this.dependencies.datasetClassification})));}this.budgets.completeApolloOperation(operationId,null);return records;}catch(error){this.budgets.failApolloOperation(operationId,error instanceof ApolloProviderError?error.category:"provider-enrichment-failed");throw error;}}
}
