import {describe,expect,it,vi} from "vitest";
import {interpretExperience} from "@/domain/candidates";
import {ApolloAdapter,ApolloProviderError,mapApolloEmailStatus} from "./adapter";
import {readApolloConfig,redactApolloError} from "./config";
import {FetchApolloTransport} from "./http";
import {APOLLO_PEOPLE} from "./fixtures";
import type {ApolloBudgetRepository,ApolloConfig,ApolloHttpResponse,ApolloHttpTransport} from "./types";
const config: ApolloConfig={enabled:true,apiKey:"fixture-secret-never-real",maxEnrichmentsPerBatch:5,maxEnrichmentsPerDay:10,hardStop:true,timeoutMs:1000,maxResponseBytes:100000,maxRetries:2};
class Transport implements ApolloHttpTransport{calls:Parameters<ApolloHttpTransport["request"]>[0][]=[];constructor(private responses:Array<ApolloHttpResponse|Error>){}async request(input:Parameters<ApolloHttpTransport["request"]>[0]){this.calls.push(input);const next=this.responses.shift();if(next instanceof Error)throw next;if(!next)throw new Error("fixture-response-missing");return next;}}
class Budgets implements ApolloBudgetRepository{attempts=0;authorized=0;completed=0;failed:string[]=[];authorizeApolloOperation(input:Parameters<ApolloBudgetRepository["authorizeApolloOperation"]>[0]){this.authorized++;if(input.candidateCount>input.maximumPerBatch)throw new Error("apollo-batch-budget-exhausted");return{operationId:input.operationId,estimatedMaxExposure:input.estimatedMaxExposure,remainingDaily:5};}recordApolloAttempt(){this.attempts++;}completeApolloOperation(){this.completed++;}failApolloOperation(_id:string,reason:string){this.failed.push(reason);}}
const response=(status:number,body:unknown,headers:Record<string,string>={}):ApolloHttpResponse=>({status,body:typeof body==="string"?body:JSON.stringify(body),headers});
const adapter=(transport:Transport,budgets=new Budgets(),overrides:Partial<ApolloConfig>={})=>({instance:new ApolloAdapter({...config,...overrides},transport,budgets,{now:()=>new Date("2026-09-08T12:00:00Z"),sleep:vi.fn(async()=>{}),datasetClassification:"provider-shaped-fixture",localDate:()=>"2026-09-08"}),budgets});
describe("Apollo production adapter through mocked transport",()=>{
 it("fails before transport when disabled or missing a key",async()=>{for(const patch of [{enabled:false},{apiKey:undefined}]){const transport=new Transport([]);await expect(adapter(transport,new Budgets(),patch).instance.search({batchId:"batch",specificTitles:["Data Engineer"]})).rejects.toThrow();expect(transport.calls).toHaveLength(0);}});
 it("builds bounded search defaults and never promotes a verified-status search filter",async()=>{const transport=new Transport([response(200,{people:[APOLLO_PEOPLE.manager,APOLLO_PEOPLE.director,APOLLO_PEOPLE.senior],total_entries:3})]);const result=await adapter(transport).instance.search({batchId:"batch",specificTitles:["Data Engineer"],companyDomains:["example.test"],emailStatuses:["verified"]});expect(transport.calls[0]).toMatchObject({path:"/api/v1/mixed_people/api_search",body:{person_titles:["Data Engineer"],person_seniorities:["manager","director","senior"],q_organization_domains_list:["example.test"],contact_email_status:["verified"],include_similar_titles:false}});expect(result.records.every((item)=>item.email.verificationStatus==="unknown")).toBe(true);expect(result.records.every((item)=>item.sourceProviderId==="apollo")).toBe(true);});
 it("maps an identical search page and enriched person deterministically",async()=>{const payload={people:[APOLLO_PEOPLE.senior],total_entries:1},transport=new Transport([response(200,payload),response(200,payload),response(200,{person:APOLLO_PEOPLE.senior}),response(200,{person:APOLLO_PEOPLE.senior})]),subject=adapter(transport).instance,search={batchId:"batch",specificTitles:["Data Engineer"]};expect((await subject.search(search)).records[0].sourceFingerprint).toBe((await subject.search(search)).records[0].sourceFingerprint);expect((await subject.enrich({batchId:"enrich-one",personIds:["senior-001"]}))[0].sourceFingerprint).toBe((await subject.enrich({batchId:"enrich-two",personIds:["senior-001"]}))[0].sourceFingerprint);});
 it("rejects similar-title expansion and prohibited source seniority",async()=>{const subject=adapter(new Transport([])).instance;await expect(subject.search({batchId:"b",specificTitles:["Data Engineer"],includeSimilarTitles:true})).rejects.toThrow("future-approval");await expect(subject.search({batchId:"b",specificTitles:["Data Engineer"],seniorities:["vp" as never]})).rejects.toThrow("seniority-prohibited");});
 it("preauthorizes enrichment and hard-disables personal, phone, and waterfall retrieval",async()=>{const transport=new Transport([response(200,{person:APOLLO_PEOPLE.senior})]),subject=adapter(transport);const records=await subject.instance.enrich({batchId:"batch",personIds:["senior-001"]});expect(subject.budgets.authorized).toBe(1);expect(subject.budgets.attempts).toBe(1);expect(subject.budgets.completed).toBe(1);expect(transport.calls[0]).toMatchObject({path:"/api/v1/people/match",body:{reveal_personal_emails:false,reveal_phone_number:false,run_waterfall_email:false,run_waterfall_phone:false}});expect(records[0].email.verificationStatus).toBe("verified");});
 it.each([["unverified","unverified"],["unavailable","unknown"],["verified","verified"],["guessed","unknown"]])("maps email %s to %s",(provider,expected)=>expect(mapApolloEmailStatus(provider,true,"enrichment")).toBe(expected));
 it("feeds employment evidence to the conservative domain interpreter",async()=>{const records=await adapter(new Transport([response(200,{person:APOLLO_PEOPLE.conflicting})])).instance.enrich({batchId:"batch",personIds:["conflict-001"]});expect(interpretExperience(records[0].experienceEvidence).reviewState).toBe("review-required");});
 it.each([[401,"provider-authentication-failed"],[403,"provider-authorization-failed"],[500,"provider-transient-failure"]])("maps HTTP %s",async(status,category)=>{const transport=new Transport(Array(3).fill(response(status,{})));const {instance,budgets}=adapter(transport);await expect(instance.enrich({batchId:"b",personIds:["x"]})).rejects.toMatchObject({category});expect(budgets.failed).toContain(category);});
 it("honors Retry-After with bounded retry under one authorization",async()=>{const transport=new Transport([response(429,{}, {"retry-after":"2"}),response(200,{person:APOLLO_PEOPLE.senior})]),budgets=new Budgets(),sleep=vi.fn(async()=>{}),instance=new ApolloAdapter(config,transport,budgets,{now:()=>new Date("2026-09-08T12:00:00Z"),sleep,datasetClassification:"provider-shaped-fixture",localDate:()=>"2026-09-08"});await instance.enrich({batchId:"b",personIds:["senior-001"]});expect(sleep).toHaveBeenCalledWith(2000);expect(budgets.authorized).toBe(1);expect(budgets.attempts).toBe(2);});
 it.each([["{", "provider-response-malformed"],[JSON.stringify({person:{id:"missing"}}),"apollo-required-field-missing"]])("fails malformed payloads closed",async(body,message)=>{const subject=adapter(new Transport([response(200,body)])).instance;await expect(subject.enrich({batchId:"b",personIds:["x"]})).rejects.toThrow(message);});
 it("maps timeouts without exposing credentials",async()=>{const subject=adapter(new Transport([new Error("apollo-request-timeout"),new Error("apollo-request-timeout"),new Error("apollo-request-timeout")])).instance;await expect(subject.enrich({batchId:"b",personIds:["x"]})).rejects.toMatchObject({category:"provider-timeout"});expect(redactApolloError(new Error(`bad ${config.apiKey}`),config.apiKey)).toBe("bad [REDACTED]");});
 it("redacts a credential embedded in a transport failure",async()=>{const message=`transport rejected ${config.apiKey}`,subject=adapter(new Transport([new Error(message),new Error(message),new Error(message)])).instance;await expect(subject.enrich({batchId:"redaction",personIds:["x"]})).rejects.not.toThrow(String(config.apiKey));});
 it("enforces response-size bounds in the production HTTP transport",async()=>{const fetcher=vi.fn(async()=>new Response("oversized",{status:200,headers:{"content-length":"9"}}));await expect(new FetchApolloTransport(fetcher).request({path:"/api/v1/people/match",body:{},apiKey:"secret",timeoutMs:100,maxResponseBytes:4})).rejects.toThrow("too-large");});
 it("targets the exact People Search URL and authenticates with a server-supplied API key",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({people:[]})));await new FetchApolloTransport(fetcher).request({path:"/api/v1/mixed_people/api_search",body:{page:1},apiKey:"fixture-secret",timeoutMs:100,maxResponseBytes:1000});expect(fetcher).toHaveBeenCalledWith("https://api.apollo.io/api/v1/mixed_people/api_search",expect.objectContaining({method:"POST",redirect:"error",headers:expect.objectContaining({"x-api-key":"fixture-secret"})}));});
 it("validates configuration without logging secrets",()=>{expect(readApolloConfig({})).toMatchObject({enabled:false,hardStop:true,maxEnrichmentsPerBatch:5});expect(()=>readApolloConfig({NETWORKPILOT_APOLLO_MAX_RETRIES:"NaN"})).toThrow("config-invalid");expect(ApolloProviderError.name).toBe("ApolloProviderError");});
});
