import {describe,expect,it} from "vitest";
import type {ImportedCandidateSnapshot} from "@/application/ingestion";
import {preEnrichmentCompanyKind,selectDailyEnrichmentShortlist} from "./daily-replenisher";

const candidate=(id:string,company:string,track:"professional"|"recruiter",score:number):ImportedCandidateSnapshot=>({id:`zz-import:apollo:${id}`,source:{providerRecordId:id},strategyCompanyMatch:{companyId:company},outreachTrack:track,recipientFunction:{reviewState:"accepted"},recipientRelevance:{score},recruiterClassification:track==="recruiter"?{internalStatus:"internal",score}:null} as ImportedCandidateSnapshot);

describe("daily Apollo replenishment shortlist",()=>{
  it("deduplicates known people, never re-enriches them, and bounds enrichment to two people per company",()=>{const rows=[candidate("known","one","professional",100),candidate("duplicate-company","two","professional",99),candidate("lower-company","two","professional",80),candidate("third-company","two","professional",70),candidate("recruiter","three","recruiter",90),candidate("duplicate-company","four","professional",60)];const selected=selectDailyEnrichmentShortlist(rows,new Set(["known"]),20);expect(selected.map((item)=>item.source.providerRecordId)).toEqual(["recruiter","duplicate-company","lower-company"]);const counts=selected.reduce<Record<string,number>>((all,item)=>({...all,[item.strategyCompanyMatch!.companyId]:(all[item.strategyCompanyMatch!.companyId]??0)+1}),{});expect(Math.max(...Object.values(counts))).toBe(2);});
  it("reserves recruiter representation before filling professional capacity",()=>{const rows=[...Array.from({length:20},(_,index)=>candidate(`p${index}`,`pc${index}`,"professional",100-index)),...Array.from({length:6},(_,index)=>candidate(`r${index}`,`rc${index}`,"recruiter",50-index))];const selected=selectDailyEnrichmentShortlist(rows,new Set(),20);expect(selected).toHaveLength(20);expect(selected.filter((item)=>item.outreachTrack==="recruiter")).toHaveLength(5);expect(selected.filter((item)=>item.outreachTrack==="professional")).toHaveLength(15);});
  it("allocates sixty percent of a full batch to discovered employers when safe supply exists",()=>{const preferred=Array.from({length:20},(_,index)=>candidate(`p${index}`,`pc${index}`,index<5?"recruiter":"professional",100-index)),discovered=Array.from({length:20},(_,index)=>({...candidate(`d${index}`,`dc${index}`,index<5?"recruiter":"professional",60-index),strategyCompanyMatch:{companyId:`dc${index}`,canonicalName:`Discovered ${index}`,method:"discovered-provider" as const}}));const selected=selectDailyEnrichmentShortlist([...preferred,...discovered],new Set(),20);expect(selected.filter((item)=>preEnrichmentCompanyKind(item)==="discovered")).toHaveLength(12);expect(selected.filter((item)=>preEnrichmentCompanyKind(item)==="preferred")).toHaveLength(8);expect(selected.filter((item)=>item.outreachTrack==="recruiter")).toHaveLength(5);});
  it("allows sparse provider search evidence into enrichment but not outreach eligibility",()=>{const base=candidate("sparse","","professional",80),sparse={...base,strategyCompanyMatch:null,source:{...base.source,datasetClassification:"authorized-provider" as const,currentOrganization:{name:"Legitimate Data Systems"},providerRecordId:"sparse"}} as ImportedCandidateSnapshot,ambiguous={...sparse,source:{...sparse.source,currentOrganization:{name:"Unknown"}}};expect(preEnrichmentCompanyKind(sparse)).toBe("discovered");expect(sparse.state).not.toBe("eligible");expect(preEnrichmentCompanyKind(ambiguous)).toBeNull();});
});
