import type { CandidateSourceRecord } from "@/domain/candidates";
import type { TargetCompany } from "@/domain/targeting";
import type { BucketEvidenceKind, RecipientBucket, RecipientBucketEvidence } from ".";
export const FIXTURE_AT = new Date("2026-09-22T14:00:00.000Z");
export function fixtureEvidence(kind: BucketEvidenceKind, value: string = kind): RecipientBucketEvidence { return { id: `fictional-${kind}`, kind, value, sourceReference: `fixture:${kind}`, observedAt: FIXTURE_AT.toISOString(), verified: true, reviewedBy: "Fictional reviewer" }; }
export function bucketFixture(bucket: RecipientBucket, ordinal = 1, early = false): { source: CandidateSourceRecord; company: TargetCompany } {
  const company: TargetCompany = { id: `fictional-company-${ordinal}`, canonicalName: `Fictional Juniper ${ordinal}`, industryId: "technology-ai", tier: "tier-2", enabled: true, recognitionScore: 70, careerUpsideScore: 70, technicalInterestScore: 70, geographicRelevance: ["boston-ma"], rationale: "Fictional test employer", provenance: "fictional fixture", lastReviewedDate: "2026-09-22", operatorNotes: "No real employer" };
  const responsibility: Record<RecipientBucket, BucketEvidenceKind> = { recruiters: "recruiting-function", peers: "individual-contributor", managers: "team-leadership", executives: "functional-leadership", ceos: "company-leadership" };
  const evidence = [fixtureEvidence("professional-identity"), fixtureEvidence("current-employment"), fixtureEvidence("company-identity"), fixtureEvidence("relevant-function", "data and analytics"), fixtureEvidence(responsibility[bucket], bucket === "executives" ? "data platforms" : responsibility[bucket]), fixtureEvidence("outreach-topic", "connecting business systems"), fixtureEvidence("contact-reason", "your fictional community data project")];
  if (bucket === "recruiters") evidence.push(fixtureEvidence("internal-recruiting"), fixtureEvidence("recruiting-domain", "technical-data-ai"));
  if (early) evidence.push(fixtureEvidence("early-career"));
  const source: CandidateSourceRecord = { sourceProviderId: "bucket-fixture", providerRecordId: `person-${ordinal}`, datasetClassification: "provider-shaped-fixture", person: { firstName: `Avery${ordinal}`, lastName: "Fictional" }, currentTitle: { recruiters: "Executive Recruiter", peers: "Data Analyst", managers: "Manager, Business Intelligence", executives: "VP, Data Platforms", ceos: "Chief Executive Officer" }[bucket], currentOrganization: { name: company.canonicalName, domain: `company-${ordinal}.invalid` }, location: "Boston", industrySignals: ["technology-ai"], experienceEvidence: [{ kind: "exact", years: early ? 1 : 8, sourceField: "fictional profile" }], email: { address: `person-${ordinal}@example.invalid`, verificationStatus: "verified" }, sourceTimestamps: { retrievedAt: FIXTURE_AT.toISOString() }, fieldProvenance: {}, consent: { suppressed: false, optedOut: false }, sourceFingerprint: `fictional-person-${ordinal}`, responsibilityEvidence: evidence };
  return { source, company };
}
