import type { DraftTemplate } from "./types";

export const DRAFT_TEMPLATES: DraftTemplate[] = [
  { id:"data-practitioner",version:"1.0.0",displayName:"Data/analytics practitioner",roleFamilyIds:["data-analytics"],industryIds:[],personaIds:["experienced-practitioner","senior-ic"],factIds:["degree","graduation","internship","technical-work"],subject:"A quick question about data work at {{company}}",reason:"I’m exploring early-career data and analytics paths, and your experience is closely connected to the kind of practical work I hope to keep building toward.",question:"Would you be open to a brief 15-minute conversation about what skills matter most on your team?" },
  { id:"engineering-technical",version:"1.0.0",displayName:"Engineering/technical",roleFamilyIds:["technical-product"],industryIds:["technology-ai"],personaIds:[],factIds:["degree","graduation","technical-work","systems-scale"],subject:"Engineering paths at {{company}}",reason:"I’m interested in engineering roles where software, automation, and business systems meet, and I’d value a grounded view from someone doing that work.",question:"Could I ask you for 15 minutes to hear how you would prepare for an early-career role in this area?" },
  { id:"delivery-operations",version:"1.0.0",displayName:"Project/program/operations",roleFamilyIds:["business-delivery"],industryIds:[],personaIds:[],factIds:["degree","graduation","systems-scale","career-interests"],subject:"Technical delivery work at {{company}}",reason:"I’m considering roles that combine technical understanding with project, program, or operations delivery, and your perspective would help me understand that path more realistically.",question:"Would you have 15 minutes for a short conversation about how technical contributors grow into effective delivery roles?" },
  { id:"consulting",version:"1.0.0",displayName:"Consulting outreach",roleFamilyIds:["industry-professional"],industryIds:["consulting"],personaIds:[],factIds:["degree","graduation","internship","systems-scale"],subject:"A question about analytical consulting",reason:"I’m exploring consulting roles that reward analytical depth and practical implementation, and I’m trying to understand how early-career consultants build credibility with clients.",question:"Would you be willing to share 15 minutes on what makes a new analyst or associate useful from the start?" },
  { id:"finance",version:"1.0.0",displayName:"Finance outreach",roleFamilyIds:["industry-professional","data-analytics"],industryIds:["financial-services"],personaIds:[],factIds:["degree","graduation","technical-work"],subject:"Data and analytics in financial services",reason:"I’m interested in how financial organizations use data and technology to support decisions, risk, and operations, and your functional perspective would be useful.",question:"Would you be open to a 15-minute conversation about the strongest entry points for someone with my technical background?" },
  { id:"commodities-energy",version:"1.0.0",displayName:"Commodities/energy outreach",roleFamilyIds:["industry-professional","data-analytics"],industryIds:["commodities-energy","energy-renewables"],personaIds:[],factIds:["degree","graduation","technical-work","career-interests"],subject:"Data work in commodities and energy",reason:"I’m curious about roles where data, market context, and operational decisions come together, especially in commodities and energy environments.",question:"Could I ask for 15 minutes to learn which technical and commercial skills are most useful early in this field?" },
  { id:"defense-technology",version:"1.0.0",displayName:"Defense/technology outreach",roleFamilyIds:["technical-product","data-analytics"],industryIds:["defense-aerospace"],personaIds:[],factIds:["degree","graduation","technical-work","career-interests"],subject:"Technical careers in defense and autonomy",reason:"I’m drawn to technical work tied to consequential products and complex missions, and I’m exploring realistic early-career routes into data and engineering teams.",question:"Would you have 15 minutes to share what preparation is most valuable for contributing in this environment?" },
  { id:"career-path-leader",version:"1.0.0",displayName:"Manager/director career path",roleFamilyIds:[],industryIds:[],personaIds:["team-manager","functional-director","project-leader","cross-functional-leader","select-vp","consulting-principal"],factIds:["degree","graduation","internship","long-term-direction"],subject:"Learning about the path to technical leadership",reason:"I’m focused on earning strong early-career experience now, while learning how capable practitioners eventually take on broader ownership and delivery responsibility.",question:"If you have 15 minutes, I’d appreciate hearing which foundational experiences mattered most before you moved into leadership." },
];
