import {describe,expect,it} from "vitest";
import {classifyRecruiter,renderRecruiterDraft} from "@/domain/recruiters";
import {renderDraft} from "./render-draft";
import {DRAFT_TEMPLATES} from "./templates";
import {assertDylanVoice,BANNED_OUTREACH_PHRASES,DYLAN_VOICE_VERSION} from "./voice";

const recipient={id:"fictional",firstName:"Avery",companyName:"Fictional Systems",roleFamilyId:"data-analytics",industryId:"technology-ai",personaId:"experienced-practitioner"};

describe("Dylan outreach method v3",()=>{
  it("version-controls every professional template without em dashes or generic phrases",()=>{expect(DYLAN_VOICE_VERSION).toBe("dylan-outreach-method-v3");for(const template of DRAFT_TEMPLATES){const draft=renderDraft(recipient,[],()=>new Date("2026-09-15T12:00:00Z"),template),text=`${draft.subject}\n${draft.body}`.toLowerCase();expect(draft.templateCatalogVersion).toContain(DYLAN_VOICE_VERSION);expect(text).not.toContain("—");for(const phrase of BANNED_OUTREACH_PHRASES)expect(text).not.toContain(phrase);}});
  it.each(["Technical Recruiter","Early Careers Recruiter","Recruiter"])("applies the same voice rules to recruiter type %s",(title)=>{const draft=renderRecruiterDraft({firstName:"Avery",company:"Fictional Systems",title,classification:classifyRecruiter({title,employerName:"Fictional Systems",internalCompanyMatch:true,minimumExperience:3,maximumExperience:5})}),text=`${draft.subject}\n${draft.body}`.toLowerCase();expect(draft.catalogVersion).toContain(DYLAN_VOICE_VERSION);expect(text).not.toContain("—");for(const phrase of BANNED_OUTREACH_PHRASES)expect(text).not.toContain(phrase);});
  it("fails closed if a future renderer introduces prohibited style",()=>{expect(()=>assertDylanVoice("A subject — with a dash","Body")).toThrow("dylan-voice-em-dash-prohibited");expect(()=>assertDylanVoice("Subject","I hope this message finds you well")).toThrow("dylan-voice-generic-phrase-prohibited");});
  it("enforces one CTA, natural subjects, and the hard word maximum",()=>{const valid=`Hi Avery,\n\nI saw you work in data at Fictional Systems, so I figured you would be a good person to ask.\n\nI graduated in May with a computer science degree and got practical experience with SQL, Python, ETL, and APIs across several business systems.\n\nI am trying to understand which early experiences matter most when moving from reporting work into deeper data engineering responsibility.\n\nWould you be open to a quick conversation?\n\nBest,\nDylan`;expect(()=>assertDylanVoice("Quick question about data",valid)).not.toThrow();expect(()=>assertDylanVoice("Connecting",valid)).toThrow("dylan-voice-subject-invalid");expect(()=>assertDylanVoice("Quick question 🚀",valid)).toThrow("dylan-voice-subject-invalid");expect(()=>assertDylanVoice("Quick question?",valid)).toThrow("dylan-voice-subject-invalid");expect(()=>assertDylanVoice("Quick question about data",`${valid} ${"padding ".repeat(70)}`)).toThrow("dylan-voice-word-count-invalid");expect(()=>assertDylanVoice("Quick question about data",valid.replace("conversation?","conversation? Could I also send a résumé?"))).toThrow("dylan-voice-cta-count-invalid");});
  it("keeps every catalog draft concise and avoids resume dumping",()=>{for(const template of DRAFT_TEMPLATES){const draft=renderDraft({...recipient,professionalTitle:"Senior Data Engineer"},[],()=>new Date(),template),skills=["SQL","Python","ETL","APIs","Power BI","automation","integrations"].filter((skill)=>draft.body.includes(skill));expect(draft.body.trim().split(/\s+/).length,template.id).toBeLessThanOrEqual(120);expect(skills.length,template.id).toBeLessThanOrEqual(4);expect(draft.body.match(/\?/g),template.id).toHaveLength(1);}});
});
