import {mkdtempSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {afterEach,describe,expect,it,vi} from "vitest";import {approveForGmailDraft} from "./create-approved-gmail-draft";import {reconcileGmailSend} from "./reconcile-gmail-send";import {SqliteSimulationRepository} from "@/infrastructure/sqlite/database";import {seedFictionalData} from "@/infrastructure/sqlite/seed";
const dirs:string[]=[];afterEach(()=>{while(dirs.length)rmSync(dirs.pop()!,{recursive:true,force:true});});
function setup(id:string){const dir=mkdtempSync(join(tmpdir(),"np-reconcile-"));dirs.push(dir);const repository=new SqliteSimulationRepository(join(dir,"test.sqlite"));repository.migrate();seedFictionalData(repository);const prospect=repository.listProspects()[0]!,company=repository.listTargetCompanies()[0]!,operation=approveForGmailDraft(repository,{snapshotId:id,recipientProfessionalEmail:prospect.email,recipientDisplayName:prospect.firstName,subject:"Fixture",body:"Fixture body",planningSnapshotId:`daily-command-center:${prospect.id}`,templateCatalogVersion:"fixture",evidenceIds:[],approvedAt:"2026-09-17T12:00:00Z",candidateId:prospect.id,companyId:company.id,companyDisplayName:company.canonicalName,professionalTitle:"Engineer"},"fixture");repository.beginGmailDraftAttempt(operation.operationId,new Date("2026-09-17T12:01:00Z"));repository.completeGmailDraftOperation(operation.operationId,"draft","message",new Date("2026-09-17T12:02:00Z"));repository.beginGmailSend(operation.operationId,new Date("2026-09-17T12:03:00Z"));return{repository,operation};}
describe("operator Gmail send reconciliation",()=>{
 it("records a sent outcome, awaiting response, actual-time cooldown, and distinct provenance idempotently",()=>{const{repository,operation}=setup("sent"),input={snapshotId:"sent",outcome:"sent" as const,effectiveSentAt:new Date("2026-09-17T12:04:00Z"),now:()=>new Date("2026-09-17T12:05:00Z"),repository};reconcileGmailSend(input);reconcileGmailSend(input);expect(repository.findGmailDraftOperation("sent")).toMatchObject({sendState:"sent",sentAt:"2026-09-17T12:04:00.000Z",gmailSentMessageId:null});expect(repository.findManualOutreach("sent")).toMatchObject({outcome:"awaiting-response",confirmationSource:"operator",effectiveSentAt:"2026-09-17T12:04:00.000Z"});expect(repository.native.prepare("SELECT provenance FROM gmail_send_reconciliation_audit").all()).toEqual([{provenance:"operator-reconciled-sent"}]);expect(repository.native.prepare("SELECT event_type FROM gmail_send_audit").all()).toEqual([{event_type:"explicit-send-started"}]);expect(repository.native.prepare("SELECT count(*) count FROM manual_outreach_records").get()).toEqual({count:1});expect(repository.listOutreachEvents()).toEqual(expect.arrayContaining([expect.objectContaining({occurredAt:new Date("2026-09-17T12:04:00Z")})]));expect(operation.operationId).toBeTruthy();repository.close();});
 it("returns a verified not-sent draft to retryable state without sending or outreach",()=>{const{repository}=setup("not-sent");reconcileGmailSend({snapshotId:"not-sent",outcome:"not-sent",now:()=>new Date(),repository});expect(repository.findGmailDraftOperation("not-sent")?.sendState).toBe("not-sent");expect(repository.findManualOutreach("not-sent")).toBeNull();expect(repository.native.prepare("SELECT provenance FROM gmail_send_reconciliation_audit").get()).toEqual({provenance:"operator-reconciled-not-sent"});repository.close();});
 it("makes still-uncertain a no-op and rejects conflicting reconciliation",()=>{const{repository}=setup("conflict"),before=repository.native.prepare("SELECT count(*) count FROM gmail_send_reconciliation_audit").get();reconcileGmailSend({snapshotId:"conflict",outcome:"still-uncertain",now:()=>new Date(),repository});expect(repository.native.prepare("SELECT count(*) count FROM gmail_send_reconciliation_audit").get()).toEqual(before);reconcileGmailSend({snapshotId:"conflict",outcome:"not-sent",now:()=>new Date(),repository});expect(()=>reconcileGmailSend({snapshotId:"conflict",outcome:"sent",effectiveSentAt:new Date(),now:()=>new Date(),repository})).toThrow("conflict");repository.close();});
 it("contains no provider dependency",()=>{expect(vi.isMockFunction(reconcileGmailSend)).toBe(false);expect(reconcileGmailSend.toString()).not.toMatch(/GmailDraftAdapter|Apollo|sendDraft/);});
});
